### ISSUE TITLE
Headphones doesn´t work with Hydra?

### ISSUE THREAD

**Issue by Hobbabobba** [theotherp/nzbhydra2#103]
When i search for music with Headphones i just get the error message

```

2018-01-31 08:30:59 | ERROR | An unknown error occurred trying to parse the feed: 'length'Traceback (most recent call last):File "/app/headphones/headphones/searcher.py", line 661, in searchNZBsize = int(item.links[1]['length'])File "/app/headphones/lib/feedparser.py", line 317, in __getitem__return UserDict.__getitem__(self, realkey)KeyError: 'length'
```
in Headphones.

In Hydra i can see the search in history and get some results. Hydra is just searching in FLAC, this is normal?
[nzbhydra-debuginfos-2018-01-31-08-33.zip](https://github.com/theotherp/nzbhydra2/files/1680770/nzbhydra-debuginfos-2018-01-31-08-33.zip)

**Comment by theotherp** [comment]
I'll have to test this myself, no reason why it shouldn't work.

Your "Privat" indexer was called using categories 3010 and 3040, which are MP3 and Lossless, respectively.

**Comment by theotherp** [comment]
HeadPhones expects the order of the tags in the returned XML to be a certain way but I'm not 100% sure that the RSS standard actually says anything about that. Anyway, I fixed it on my part.
