### ISSUE TITLE
Unable to check caps on NZB.Su or Dognzb

### ISSUE THREAD

**Issue by regulus0** [theotherp/nzbhydra2#104]
When adding NZB.su and DogNZB to indexers, forcing the caps check always fails. I thought originally it was just DogNZB being DogNZB...but it is happening to NZB.su as well. 

Debug logs:
Message: Error while communicating with Indexer. (See attached)

[Error Log.zip](https://github.com/theotherp/nzbhydra2/files/1686276/Error.Log.zip)

I also get:
Message: Indexer NZB.su does not support searching by any IDs
and
Message: Indexer NZB.su didn't provide a backend type. Will use newznab.

**Comment by theotherp** [comment]
Check your Java Installation. I know of some users who updated from 1.8.161
and had that problem. Currently can't explain why.

Am 01.02.2018 4:28 nachm. schrieb "regulus0" <notifications@github.com>:

When adding NZB.su and DogNZB to indexers, forcing the caps check always
fails. I thought originally it was just DogNZB being DogNZB...but it is
happening to NZB.su as well.

Debug logs:
Message: Error while communicating with Indexer.

Stacktrace:

java.util.concurrent.ExecutionException:
org.nzbhydra.indexers.exceptions.IndexerUnreachableException:
Error while communicating with indexer NZB.su. Server returned:
javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error:
java.security.InvalidAlgorithmParameterException: the trustAnchors
parameter must be non-empty
at java.util.concurrent.FutureTask.report(Unknown Source)
at java.util.concurrent.FutureTask.get(Unknown Source)
at org.nzbhydra.indexers.capscheck.NewznabChecker.
checkCaps(NewznabChecker.java:143)
at org.nzbhydra.indexers.capscheck.NewznabChecker.
checkCaps(NewznabChecker.java:100)
at org.nzbhydra.indexers.capscheck.IndexerWeb.checkCaps(IndexerWeb.java:51)
at org.nzbhydra.indexers.capscheck.IndexerWeb$$FastClassBySpringCGLIB$$
4c12f63e.invoke()
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.
invokeJoinpoint(CglibAopProxy.java:738)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(
ReflectiveMethodInvocation.java:157)
at org.springframework.security.access.intercept.aopalliance.
MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(
ReflectiveMethodInvocation.java:179)
at org.springframework.aop.framework.CglibAopProxy$
DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
at org.nzbhydra.indexers.capscheck.IndexerWeb$$EnhancerBySpringCGLIB$$
943bfcca.checkCaps()
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(
InvocableHandlerMethod.java:205)
at org.springframework.web.method.support.InvocableHandlerMethod.
invokeForRequest(InvocableHandlerMethod.java:133)
at org.springframework.web.servlet.mvc.method.annotation.
ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.
java:97)
at org.springframework.web.servlet.mvc.method.annotation.
RequestMappingHandlerAdapter.invokeHandlerMethod(
RequestMappingHandlerAdapter.java:827)
at org.springframework.web.servlet.mvc.method.annotation.
RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.
java:738)
at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.
handle(AbstractHandlerMethodAdapter.java:85)
at org.springframework.web.servlet.DispatcherServlet.
doDispatch(DispatcherServlet.java:967)
at org.springframework.web.servlet.DispatcherServlet.
doService(DispatcherServlet.java:901)
at org.springframework.web.servlet.FrameworkServlet.processRequest(
FrameworkServlet.java:970)
at org.springframework.web.servlet.FrameworkServlet.
doPost(FrameworkServlet.java:872)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
at org.springframework.web.servlet.FrameworkServlet.
service(FrameworkServlet.java:846)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(
ApplicationFilterChain.java:231)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(
ApplicationFilterChain.java:166)
at org.nzbhydra.auth.HydraAnonymousAuthenticationFilter.doFilter(
HydraAnonymousAuthenticationFilter.java:98)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(
ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(
ApplicationFilterChain.java:166)
at org.springframework.security.web.FilterChainProxy$
VirtualFilterChain.doFilter(FilterChainProxy.java:317)
at org.springframework.security.web.access.intercept.
FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
at org.springframework.security.web.access.intercept.
FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
at org.springframework.security.web.FilterChainProxy$
VirtualFilterChain.doFilter(FilterChainProxy.java:331)
at org.springframework.security.web.access.ExceptionTranslationFilter.
doFilter(ExceptionTranslationFilter.java:114)
at org.springframework.security.web.FilterChainProxy$
VirtualFilterChain.doFilter(FilterChainProxy.java:331)
at org.springframework.security.web.session.SessionManagementFilter.
doFilter(SessionManagementFilter.java:137)
at org.springframework.security.web.FilterChainProxy$
VirtualFilterChain.doFilter(FilterChainProxy.java:331)
at org.springframework.security.web.authentication.
AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.
java:111)
at org.springframework.security.web.FilterChainProxy$
VirtualFilterChain.doFilter(FilterChainProxy.java:331)
at org.springframework.security.web.authentication.rememberme.
RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter
.java:158)
at org.springframework.security.web.FilterChainProxy$
VirtualFilterChain.doFilter(FilterChainProxy.java:331)
at org.springframework.security.web.servletapi.
SecurityContextHolderAwareRequestFilter.doFilter(
SecurityContextHolderAwareRequestFilter.java:170)
at org.springframework.security.web.FilterChainProxy$
VirtualFilterChain.doFilter(FilterChainProxy.java:331)
at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.
doFilter(RequestCacheAwareFilter.java:63)
at org.springframework.security.web.FilterChainProxy$
VirtualFilterChain.doFilter(FilterChainProxy.java:331)
at org.springframework.security.web.authentication.
AbstractAuthenticationProcessingFilter.doFilter(
AbstractAuthenticationProcessingFilter.java:200)
at org.springframework.security.web.FilterChainProxy$
VirtualFilterChain.doFilter(FilterChainProxy.java:331)
at org.springframework.security.web.authentication.logout.
LogoutFilter.doFilter(LogoutFilter.java:116)
at org.springframework.security.web.FilterChainProxy$
VirtualFilterChain.doFilter(FilterChainProxy.java:331)
at org.springframework.security.web.csrf.CsrfFilter.
doFilterInternal(CsrfFilter.java:124)
at org.springframework.web.filter.OncePerRequestFilter.
doFilter(OncePerRequestFilter.java:107)
at org.springframework.security.web.FilterChainProxy$
VirtualFilterChain.doFilter(FilterChainProxy.java:331)
at org.springframework.security.web.header.HeaderWriterFilter.
doFilterInternal(HeaderWriterFilter.java:64)
at org.springframework.web.filter.OncePerRequestFilter.
doFilter(OncePerRequestFilter.java:107)
at org.springframework.security.web.FilterChainProxy$
VirtualFilterChain.doFilter(FilterChainProxy.java:331)
at org.springframework.security.web.context.SecurityContextPersistenceFilt
er.doFilter(SecurityContextPersistenceFilter.java:105)
at org.springframework.security.web.FilterChainProxy$
VirtualFilterChain.doFilter(FilterChainProxy.java:331)
at org.springframework.security.web.context.request.async.
WebAsyncManagerIntegrationFilter.doFilterInternal(
WebAsyncManagerIntegrationFilter.java:56)
at org.springframework.web.filter.OncePerRequestFilter.
doFilter(OncePerRequestFilter.java:107)
at org.springframework.security.web.FilterChainProxy$
VirtualFilterChain.doFilter(FilterChainProxy.java:331)
at org.springframework.security.web.FilterChainProxy.doFilterInternal(
FilterChainProxy.java:214)
at org.springframework.security.web.FilterChainProxy.doFilter(
FilterChainProxy.java:177)
at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(
DelegatingFilterProxy.java:346)
at org.springframework.web.filter.DelegatingFilterProxy.doFilter(
DelegatingFilterProxy.java:262)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(
ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(
ApplicationFilterChain.java:166)
at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(
CharacterEncodingFilter.java:197)
at org.springframework.web.filter.OncePerRequestFilter.
doFilter(OncePerRequestFilter.java:107)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(
ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(
ApplicationFilterChain.java:166)
at org.apache.catalina.core.StandardWrapperValve.invoke(
StandardWrapperValve.java:198)
at org.apache.catalina.core.StandardContextValve.invoke(
StandardContextValve.java:96)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(
AuthenticatorBase.java:478)
at org.nzbhydra.auth.HydraEmbeddedServletContainer$1.invoke(
HydraEmbeddedServletContainer.java:90)
at org.apache.catalina.core.StandardHostValve.invoke(
StandardHostValve.java:140)
at org.apache.catalina.valves.ErrorReportValve.invoke(
ErrorReportValve.java:80)
at org.apache.catalina.core.StandardEngineValve.invoke(
StandardEngineValve.java:87)
at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677)
at org.apache.catalina.connector.CoyoteAdapter.service(
CoyoteAdapter.java:342)
at org.apache.coyote.http11.Http11Processor.service(
Http11Processor.java:799)
at org.apache.coyote.AbstractProcessorLight.process(
AbstractProcessorLight.java:66)
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(
AbstractProtocol.java:868)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.
doRun(NioEndpoint.java:1457)
at org.apache.tomcat.util.net.SocketProcessorBase.run(
SocketProcessorBase.java:49)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(
TaskThread.java:61)
at java.lang.Thread.run(Unknown Source)
Caused by: org.nzbhydra.indexers.exceptions.IndexerUnreachableException:
Error while communicating with indexer NZB.su. Server returned:
javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error:
java.security.InvalidAlgorithmParameterException: the trustAnchors
parameter must be non-empty
at org.nzbhydra.indexers.IndexerWebAccess.get(IndexerWebAccess.java:71)
at org.nzbhydra.indexers.IndexerWebAccess.get(IndexerWebAccess.java:38)
at org.nzbhydra.indexers.capscheck.NewznabChecker.singleCheckCaps(
NewznabChecker.java:293)
at org.nzbhydra.indexers.capscheck.NewznabChecker.lambda$checkCaps$0(
NewznabChecker.java:130)
at java.util.concurrent.FutureTask.run(Unknown Source)
at org.nzbhydra.logging.MdcThreadPoolExecutor$1.run(
MdcThreadPoolExecutor.java:114)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
... 1 common frames omitted
Caused by: javax.net.ssl.SSLException: java.lang.RuntimeException:
Unexpected error: java.security.InvalidAlgorithmParameterException: the
trustAnchors parameter must be non-empty
at sun.security.ssl.Alerts.getSSLException(Unknown Source)
at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
at sun.security.ssl.SSLSocketImpl.handleException(Unknown Source)
at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
at okhttp3.internal.connection.RealConnection.connectTls(
RealConnection.java:281)
at okhttp3.internal.connection.RealConnection.establishProtocol(
RealConnection.java:251)
at okhttp3.internal.connection.RealConnection.connect(
RealConnection.java:151)
at okhttp3.internal.connection.StreamAllocation.findConnection(
StreamAllocation.java:195)
at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(
StreamAllocation.java:121)
at okhttp3.internal.connection.StreamAllocation.newStream(
StreamAllocation.java:100)
at okhttp3.internal.connection.ConnectInterceptor.intercept(
ConnectInterceptor.java:42)
at okhttp3.internal.http.RealInterceptorChain.proceed(
RealInterceptorChain.java:92)
at okhttp3.internal.http.RealInterceptorChain.proceed(
RealInterceptorChain.java:67)
at okhttp3.internal.cache.CacheInterceptor.intercept(
CacheInterceptor.java:93)
at okhttp3.internal.http.RealInterceptorChain.proceed(
RealInterceptorChain.java:92)
at okhttp3.internal.http.RealInterceptorChain.proceed(
RealInterceptorChain.java:67)
at okhttp3.internal.http.BridgeInterceptor.intercept(
BridgeInterceptor.java:93)
at okhttp3.internal.http.RealInterceptorChain.proceed(
RealInterceptorChain.java:92)
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(
RetryAndFollowUpInterceptor.java:120)
at okhttp3.internal.http.RealInterceptorChain.proceed(
RealInterceptorChain.java:92)
at okhttp3.internal.http.RealInterceptorChain.proceed(
RealInterceptorChain.java:67)
at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
at okhttp3.RealCall.execute(RealCall.java:69)
at org.nzbhydra.okhttp.WebAccess.callUrl(WebAccess.java:57)
at org.nzbhydra.indexers.IndexerWebAccess.lambda$get$0(
IndexerWebAccess.java:55)
at java.util.concurrent.FutureTask.run(Unknown Source)
... 3 common frames omitted
Caused by: java.lang.RuntimeException: Unexpected error: java.security.
InvalidAlgorithmParameterException: the trustAnchors parameter must be
non-empty
at sun.security.validator.PKIXValidator.(Unknown Source)
at sun.security.validator.Validator.getInstance(Unknown Source)
at sun.security.ssl.X509TrustManagerImpl.getValidator(Unknown Source)
at sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(Unknown Source)
at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
at sun.security.ssl.Handshaker.processLoop(Unknown Source)
at sun.security.ssl.Handshaker.process_record(Unknown Source)
at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
... 27 common frames omitted
Caused by: java.security.InvalidAlgorithmParameterException: the
trustAnchors parameter must be non-empty
at java.security.cert.PKIXParameters.setTrustAnchors(Unknown Source)
at java.security.cert.PKIXParameters.(Unknown Source)
at java.security.cert.PKIXBuilderParameters.(Unknown Source)
... 39 common frames omitted

I also get:
Message: Indexer NZB.su does not support searching by any IDs
and
Message: Indexer NZB.su didn't provide a backend type. Will use newznab.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/theotherp/nzbhydra2/issues/104>, or mute the thread

**Comment by theotherp** [comment]
See https://github.com/theotherp/nzbhydra2/issues/85

Also please ALWAYS post the debug infos zip file.

**Comment by regulus0** [comment]
My apologies for not zipping.

I rolled back to Java 8u151 to resolve. Thank you.

**Comment by theotherp** [comment]
I meant post the debug infos ZIPyou get from http://127.0.0.1:5076/system/bugreport

**Comment by Metigoth** [comment]
NZBFinder only recognized as IMDB.
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
https://nzbfinder.ws/api?t=caps

**Comment by theotherp** [comment]
@Metigoth Yes, because the results from NZBFinder are too poor. If you want you can enable the other IDs manually but expect loads of wrong results in your searches.

**Comment by theotherp** [comment]
This is fixed, right? If not please comment and I'll reopen.
