### ISSUE TITLE
NZBhydra2 won't open but shows up in task manager.

### ISSUE THREAD

**Issue by digitaldelboy** [theotherp/nzbhydra2#108]
When I try to run NZBHydra2 the url won't show up and the NZBHydra2 icon is missing.  I double click the NZBHydra2.exe and it does nothing. Two NZBhydra2 processes are running in task manager.

It was working fine during the first run to setup configure NZBHydra2 but after I reboot my PC it won't show.

I've tried running as admin but it does nothing.

**Comment by theotherp** [comment]
And you didn't post the fucking debug infos. Is that really so hard...

**Comment by theotherp** [comment]
What does the log say? Check `wrapper.log` and `nzbhydra2.log`. Shutdown the processes and try the console exe.

**Comment by digitaldelboy** [comment]
[wrapper.log](https://github.com/theotherp/nzbhydra2/files/1692120/wrapper.log)
[nzbhydra2.log](https://github.com/theotherp/nzbhydra2/files/1692121/nzbhydra2.log)

**Comment by theotherp** [comment]
And what about the console...

**Comment by digitaldelboy** [comment]
Console opens with this and I just get the "Firefox can’t establish a connection to the server at 192.168.1.80:5076."

`Logging wrapper output to C:\Users\Graeme\Desktop\nzbhydra2-1.2.6-windows\data\logs\wrapper.log
2018-02-03 20:04:45,903  INFO - Starting NZBHydra main process with command line: java -Xmx128M -DfromWrapper -XX:TieredStopAtLevel=1 -noverify -jar C:\Users\Graeme\Desktop\nzbhydra2-1.2.6-windows\lib\core-1.2.6-exec.jar --datafolder C:\Users\Graeme\Desktop\nzbhydra2-1.2.6-windows\data in folder C:\Users\Graeme\Desktop\nzbhydra2-1.2.6-windows
org.yaml.snakeyaml.error.YAMLException: java.nio.charset.MalformedInputException: Input length = 1
        at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:200)
        at org.yaml.snakeyaml.reader.StreamReader.forward(StreamReader.java:118)
        at org.yaml.snakeyaml.reader.StreamReader.forward(StreamReader.java:108)
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:894)
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:360)
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226)
        at org.yaml.snakeyaml.parser.ParserImpl$ParseIndentlessSequenceEntry.produce(ParserImpl.java:531)
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157)
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147)
        at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:198)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:153)
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:246)
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:237)
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:225)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:246)
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:237)
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:225)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
        at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:199)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:153)
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:246)
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:237)
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:225)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
        at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:84)
        at org.yaml.snakeyaml.constructor.BaseConstructor.getData(BaseConstructor.java:104)
        at org.yaml.snakeyaml.Yaml$1.next(Yaml.java:471)
        at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:160)
        at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:138)
        at org.nzbhydra.config.HydraYamlPropertySourceLoader$Processor.process(HydraYamlPropertySourceLoader.java:80)
        at org.nzbhydra.config.HydraYamlPropertySourceLoader.load(HydraYamlPropertySourceLoader.java:36)
        at org.springframework.boot.env.PropertySourcesLoader.load(PropertySourcesLoader.java:127)
        at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.doLoadIntoGroup(ConfigFileApplicationListener.java:490)
        at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.loadIntoGroup(ConfigFileApplicationListener.java:473)
        at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:443)
        at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:382)
        at org.springframework.boot.context.config.ConfigFileApplicationListener.addPropertySources(ConfigFileApplicationListener.java:225)
        at org.springframework.boot.context.config.ConfigFileApplicationListener.postProcessEnvironment(ConfigFileApplicationListener.java:195)
        at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEnvironmentPreparedEvent(ConfigFileApplicationListener.java:182)
        at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEvent(ConfigFileApplicationListener.java:168)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:122)
        at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:74)
        at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
        at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:325)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:296)
        at org.nzbhydra.NzbHydra.main(NzbHydra.java:132)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.nio.charset.MalformedInputException: Input length = 1
        at java.nio.charset.CoderResult.throwException(Unknown Source)
        at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
        at sun.nio.cs.StreamDecoder.read(Unknown Source)
        at java.io.InputStreamReader.read(Unknown Source)
        at org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:123)
        at java.io.Reader.read(Unknown Source)
        at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:184)
        ... 58 more
20:04:46.465 [main] DEBUG org.springframework.boot.logging.ClasspathLoggingApplicationListener - Application failed to start with classpath: [jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/classes!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/mapping-1.2.6.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/jackson-annotations-2.8.9.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/jackson-databind-2.8.9.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/spring-boot-starter-data-jpa-1.5.7.RELEASE.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/spring-boot-starter-aop-1.5.7.RELEASE.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/aspectjweaver-1.8.10.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/hibernate-core-5.0.12.Final.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/jboss-logging-3.3.0.Final.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/hibernate-jpa-2.1-api-1.0.0.Final.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/javassist-3.18.1-GA.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/antlr-2.7.7.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/jandex-2.0.0.Final.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/dom4j-1.6.1.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/xml-apis-1.0.b2.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/hibernate-commons-annotations-5.0.1.Final.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/hibernate-entitymanager-5.0.12.Final.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/javax.transaction-api-1.2.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/spring-data-jpa-1.11.7.RELEASE.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/spring-data-commons-1.13.7.RELEASE.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/spring-orm-4.3.11.RELEASE.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/spring-tx-4.3.11.RELEASE.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/jcl-over-slf4j-1.7.25.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/spring-aspects-4.3.11.RELEASE.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/spring-boot-starter-jdbc-1.5.7.RELEASE.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/tomcat-jdbc-8.5.20.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/tomcat-juli-8.5.20.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/spring-jdbc-4.3.11.RELEASE.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/spring-boot-starter-cache-1.5.7.RELEASE.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/spring-context-4.3.11.RELEASE.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/spring-expression-4.3.11.RELEASE.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/spring-context-support-4.3.11.RELEASE.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/spring-boot-starter-1.5.7.RELEASE.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/spring-boot-1.5.7.RELEASE.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/spring-boot-autoconfigure-1.5.7.RELEASE.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/spring-boot-starter-logging-1.5.7.RELEASE.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/jul-to-slf4j-1.7.25.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/log4j-over-slf4j-1.7.25.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/spring-core-4.3.11.RELEASE.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/snakeyaml-1.17.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/spring-boot-starter-web-1.5.7.RELEASE.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/spring-boot-starter-tomcat-1.5.7.RELEASE.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/tomcat-embed-core-8.5.20.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/tomcat-embed-el-8.5.20.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/tomcat-embed-websocket-8.5.20.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/hibernate-validator-5.3.5.Final.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/validation-api-1.1.0.Final.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/classmate-1.3.1.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/spring-web-4.3.11.RELEASE.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/spring-webmvc-4.3.11.RELEASE.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/spring-boot-starter-security-1.5.7.RELEASE.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/spring-aop-4.3.11.RELEASE.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/spring-security-config-4.2.3.RELEASE.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/spring-security-core-4.2.3.RELEASE.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/spring-security-web-4.2.3.RELEASE.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/spring-oxm-4.3.10.RELEASE.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/spring-beans-4.3.10.RELEASE.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/spring-boot-configuration-processor-1.5.7.RELEASE.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/android-json-0.0.20131108.vaadin1.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/h2-1.4.195.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/threeten-jpa-1.5.1.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/sqlite-jdbc-3.16.1.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/flyway-core-4.2.0.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/jackson-datatype-jdk8-2.8.9.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/jackson-core-2.8.9.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/jackson-dataformat-yaml-2.8.9.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/jackson-datatype-jsr310-2.8.9.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/lombok-1.16.18.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/guava-20.0.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/thymeleaf-spring4-3.0.6.RELEASE.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/thymeleaf-3.0.6.RELEASE.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/attoparser-2.0.4.RELEASE.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/unbescape-1.1.4.RELEASE.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/commons-io-2.5.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/commons-lang3-3.6.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/thymeleaf-layout-dialect-2.2.1.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/tmdb-java-1.6.0.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/retrofit-2.1.0.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/converter-gson-2.1.0.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/gson-2.7.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/jsonrpc4j-1.5.0.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/base64-2.3.9.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/flexmark-0.18.5.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/flexmark-util-0.18.5.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/okhttp-3.8.1.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/okio-1.13.0.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/jopt-simple-4.9.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/jsoup-1.10.2.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/expiringmap-0.5.8.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/URISchemeHandler-1.7.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/logback-classic-1.2.3.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/logback-core-1.2.3.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/logstash-logback-encoder-4.10.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/logback-access-1.2.3.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/slf4j-api-1.7.25.jar!/, jar:file:/C:/Users/Graeme/Desktop/nzbhydra2-1.2.6-windows/lib/core-1.2.6-exec.jar!/BOOT-INF/lib/sockslib-1.0.0.jar!/]`

**Comment by theotherp** [comment]
Your nzbhydra.yml is fucked up for some reason. Restore it from a backup or delete it and start again.

**Comment by digitaldelboy** [comment]
Arrggh thats unfortunate it takes what feels like forever setting up all the providers especially since I use Jackett.

Any I trashed the nzbhydra.yml and it's running so I tried to updated to 1.3.0 but when I start NZBhydra I get a box saying "Failed to execute script nzbhydra2wrapper"

[wrapper.log](https://github.com/theotherp/nzbhydra2/files/1692180/wrapper.log)
[nzbhydra2.log](https://github.com/theotherp/nzbhydra2/files/1692182/nzbhydra2.log)

**Comment by theotherp** [comment]
So for some reason after your first startup and then restart the yml file is rendered unusable.

I faintly remember a similar case. Let me see what I can find.

**Comment by theotherp** [comment]
Ahh...
Put your nzbhydra2 folder somewhere that's not `C:\Program Files`. I recommend using a folder like `c:\programs` where you put all the programs that are not installed by a setup. That folder is handled specially when it comes to read/write rights. 

I'm not sure if that solves the problem but it will prevent others.

**Comment by digitaldelboy** [comment]
I moved 1.3.0 to `C:\Programs`, then I manually downloaded v1.3.1 put it in `C:\Programs\nzbhydra2-1.3.0-windows` replacing the existing files. I then tried to open Hydra and it still won't open.

But like before if I took the files the backup created and put them in  correct locations and now Hydra opens and Firefox opens 192.168.1.80:5076.

Also I noticed that that the  Data Base file and YML file.

Broken YML File - 273 KB (279,946 bytes)
Working YML File - 274 KB (280,616 bytes)

Broken Data Base file - 20.0 KB (20,480 bytes)
Working Data Base file - 36.0 KB (36,864 bytes)


[Workingfiles.zip](https://github.com/theotherp/nzbhydra2/files/1693362/Workingfiles.zip)
[Brokenfiles.zip](https://github.com/theotherp/nzbhydra2/files/1693363/Brokenfiles.zip)

**Comment by theotherp** [comment]
Thanks, I'll analyze the files tonight.

I didn't expect the new version to work with the old broken file but would hope that the new version doesn't break the files anymore in the first place. Although on first glance that broken file does not look like I expected. I'll see what I can find out.

**Comment by theotherp** [comment]
Alright, different problem that I expected. Took a while to get behind it but after I had found it it was actually very obvious...

**Comment by digitaldelboy** [comment]
Thanks so what was the problem and are you able to fix it.

**Comment by theotherp** [comment]
RuTracker (via Jackett) returned some special characters in the list of available categories. I used the wrong encoding when saving the yaml file. From now on it should use the correct one.

Existing yaml files can be fixed by converting them to UTF-8.
