### ISSUE TITLE
Settings Only Migrate Failing

### ISSUE THREAD

**Issue by dmce** [theotherp/nzbhydra2#113]
Expected: Migrate Settings from v1 to v2. No .db Migrate (unchecked the last box)
Setup: Docker containers for v1 and v2 (both from linuxserver). Copied v1 settings.cfg to folder available to v2 container (same location as v2 nzbhydra.yml).
Searched: Looked for NullPointerException in Issues. Couldnt see it.

```
2018-02-05 21:48:35.597  INFO --- [0.0-5076-exec-4] org.nzbhydra.config.ConfigWeb            : [IP: <IP>] Received new config
2018-02-05 21:48:35.608  WARN --- [0.0-5076-exec-4] org.nzbhydra.config.BaseConfig           : [IP: <IP>] Config validation returned warnings:
No indexers configured. You won't get any results
2018-02-05 21:48:35.646  INFO --- [0.0-5076-exec-4] o.n.d.downloaders.DownloaderProvider     : [IP: <IP>] Reloading downloaders
2018-02-05 21:48:35.647  INFO --- [0.0-5076-exec-4] o.n.d.downloaders.DownloaderProvider     : [IP: <IP>] Loading downloaders
2018-02-05 21:48:35.648  INFO --- [0.0-5076-exec-4] o.n.d.downloaders.DownloaderProvider     : [IP: <IP>] No downloaders configured
2018-02-05 21:48:35.651  INFO --- [0.0-5076-exec-4] o.n.searching.SearchModuleProvider       : [IP: <IP>] Loading indexers
2018-02-05 21:48:35.654  WARN --- [0.0-5076-exec-4] o.n.searching.SearchModuleProvider       : [IP: <IP>] No indexers configured
2018-02-05 21:48:35.655  INFO --- [0.0-5076-exec-4] o.n.a.HydraAnonymousAuthenticationFilter : [IP: <IP>] Granting basic user rights to anonymous users
2018-02-05 21:48:35.656  INFO --- [0.0-5076-exec-4] o.n.a.HydraAnonymousAuthenticationFilter : [IP: <IP>] Granting stats rights to anonymous users
2018-02-05 21:48:35.657  INFO --- [0.0-5076-exec-4] o.n.a.HydraAnonymousAuthenticationFilter : [IP: <IP>] Granting admin rights to anonymous users
2018-02-05 21:50:17.683  INFO --- [0.0-5076-exec-2] o.n.debuginfos.DebugInfosProvider        : [IP: <IP>] Creating debug infos
2018-02-05 21:50:17.685  INFO --- [0.0-5076-exec-2] o.n.debuginfos.DebugInfosProvider        : [IP: <IP>] NZBHydra2 version: null
2018-02-05 21:50:17.685  INFO --- [0.0-5076-exec-2] o.n.debuginfos.DebugInfosProvider        : [IP: <IP>] Java command line: <BASEPATH>/lib/core-1.3.2-exec.jar --nobrowser --datafolder /config
2018-02-05 21:50:17.686  INFO --- [0.0-5076-exec-2] o.n.debuginfos.DebugInfosProvider        : [IP: <IP>] Java runtime name: OpenJDK Runtime Environment
2018-02-05 21:50:17.686  INFO --- [0.0-5076-exec-2] o.n.debuginfos.DebugInfosProvider        : [IP: <IP>] Java runtime version: 1.8.0_151-b12
2018-02-05 21:50:17.687  INFO --- [0.0-5076-exec-2] o.n.debuginfos.DebugInfosProvider        : [IP: <IP>] OS name: Linux
2018-02-05 21:50:17.687  INFO --- [0.0-5076-exec-2] o.n.debuginfos.DebugInfosProvider        : [IP: <IP>] OS architecture: amd64
2018-02-05 21:50:17.688  INFO --- [0.0-5076-exec-2] o.n.debuginfos.DebugInfosProvider        : [IP: <IP>] User country: US
2018-02-05 21:50:17.688  INFO --- [0.0-5076-exec-2] o.n.debuginfos.DebugInfosProvider        : [IP: <IP>] File encoding: UTF-8
2018-02-05 21:50:17.689  INFO --- [0.0-5076-exec-2] o.n.debuginfos.DebugInfosProvider        : [IP: <IP>] Apparently run in docker
2018-02-05 21:52:40.240  INFO --- [0.0-5076-exec-2] org.nzbhydra.config.ConfigWeb            : [IP: <IP>] Received new config
2018-02-05 21:52:40.242  WARN --- [0.0-5076-exec-2] org.nzbhydra.config.BaseConfig           : [IP: <IP>] Config validation returned warnings:
No indexers configured. You won't get any results
2018-02-05 21:52:40.253  INFO --- [0.0-5076-exec-2] o.n.d.downloaders.DownloaderProvider     : [IP: <IP>] Reloading downloaders
2018-02-05 21:52:40.254  INFO --- [0.0-5076-exec-2] o.n.d.downloaders.DownloaderProvider     : [IP: <IP>] Loading downloaders
2018-02-05 21:52:40.254  INFO --- [0.0-5076-exec-2] o.n.d.downloaders.DownloaderProvider     : [IP: <IP>] No downloaders configured
2018-02-05 21:52:40.255  INFO --- [0.0-5076-exec-2] o.n.searching.SearchModuleProvider       : [IP: <IP>] Loading indexers
2018-02-05 21:52:40.257  WARN --- [0.0-5076-exec-2] o.n.searching.SearchModuleProvider       : [IP: <IP>] No indexers configured
2018-02-05 21:52:40.258  INFO --- [0.0-5076-exec-2] o.n.a.HydraAnonymousAuthenticationFilter : [IP: <IP>] Granting basic user rights to anonymous users
2018-02-05 21:52:40.259  INFO --- [0.0-5076-exec-2] o.n.a.HydraAnonymousAuthenticationFilter : [IP: <IP>] Granting stats rights to anonymous users
2018-02-05 21:52:40.259  INFO --- [0.0-5076-exec-2] o.n.a.HydraAnonymousAuthenticationFilter : [IP: <IP>] Granting admin rights to anonymous users
2018-02-05 21:53:06.986  INFO --- [0.0-5076-exec-1] o.n.migration.FromPythonMigration        : [IP: <IP>] Received request to migrate from settings file /config/settings.cfg and database file null
2018-02-05 21:53:06.990 ERROR --- [0.0-5076-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : [IP: <IP>] Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause

java.lang.NullPointerException: null
	at java.io.File.<init>(File.java:277)
	at org.nzbhydra.migration.FromPythonMigration.migrateFromFiles(FromPythonMigration.java:54)
	at org.nzbhydra.migration.FromPythonMigration$$FastClassBySpringCGLIB$$25126370.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
	at org.nzbhydra.migration.FromPythonMigration$$EnhancerBySpringCGLIB$$bdac839f.migrateFromFiles(<generated>)
	at org.nzbhydra.migration.MigrationWeb.migrateFromFiles(MigrationWeb.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.nzbhydra.auth.HydraAnonymousAuthenticationFilter.doFilter(HydraAnonymousAuthenticationFilter.java:98)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.nzbhydra.auth.HydraEmbeddedServletContainer$1.invoke(HydraEmbeddedServletContainer.java:90)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

2018-02-05 21:54:27.452  INFO --- [0.0-5076-exec-3] o.n.debuginfos.DebugInfosProvider        : [IP: <IP>] Creating debug infos
2018-02-05 21:54:27.453  INFO --- [0.0-5076-exec-3] o.n.debuginfos.DebugInfosProvider        : [IP: <IP>] NZBHydra2 version: null
2018-02-05 21:54:27.455  INFO --- [0.0-5076-exec-3] o.n.debuginfos.DebugInfosProvider        : [IP: <IP>] Java command line: <BASEPATH>/lib/core-1.3.2-exec.jar --nobrowser --datafolder /config
2018-02-05 21:54:27.457  INFO --- [0.0-5076-exec-3] o.n.debuginfos.DebugInfosProvider        : [IP: <IP>] Java runtime name: OpenJDK Runtime Environment
2018-02-05 21:54:27.457  INFO --- [0.0-5076-exec-3] o.n.debuginfos.DebugInfosProvider        : [IP: <IP>] Java runtime version: 1.8.0_151-b12
2018-02-05 21:54:27.458  INFO --- [0.0-5076-exec-3] o.n.debuginfos.DebugInfosProvider        : [IP: <IP>] OS name: Linux
2018-02-05 21:54:27.458  INFO --- [0.0-5076-exec-3] o.n.debuginfos.DebugInfosProvider        : [IP: <IP>] OS architecture: amd64
2018-02-05 21:54:27.459  INFO --- [0.0-5076-exec-3] o.n.debuginfos.DebugInfosProvider        : [IP: <IP>] User country: US
2018-02-05 21:54:27.460  INFO --- [0.0-5076-exec-3] o.n.debuginfos.DebugInfosProvider        : [IP: <IP>] File encoding: UTF-8
2018-02-05 21:54:27.460  INFO --- [0.0-5076-exec-3] o.n.debuginfos.DebugInfosProvider        : [IP: <IP>] Apparently run in docker
```

**Comment by dmce** [comment]
Although i didnt want the db migration, when i copied the file nzbhydra.db file from v1 to a location accessible from v2 it worked

**Comment by theotherp** [comment]
Oops sorry, I think I fucked that up with one of my latest updates. You can
just delete the new DB file if you want to start with a fresh DB.

Am 05.02.2018 23:06 schrieb "David McElroy" <notifications@github.com>:

**Comment by dmce** [comment]
Hey, its no problem. Feels nice and smooth now its going. Thanks.

**Comment by theotherp** [comment]
Should work now.
