### ISSUE TITLE
DB Migration / SQL Error: INDEXERSTATUS not found

### ISSUE THREAD

**Issue by h45rd** [theotherp/nzbhydra2#127]
Hi,

Thanks for working relentlessly on this great project :)
I think somewhere around this commit: https://github.com/theotherp/nzbhydra2/commit/2681f5e86219d40f5cc053dc5d7536b95a157f46 the db migration process got broken.

Prerequisites: both hydra instances are running in docker containers; does not seem to be resource related, as testing with `-e JAVA_OPTS="-Xmx1024m"` did not help either. All files are fully accessible from within the containers and undamaged, etc.

Trying to migrate my small (20 MB) db from v0.2.231 to v1.4.2 via the files option I run into the following issue:

```
INFO --- [0.0-5076-exec-5] o.n.migration.FromPythonMigration        : Received request to migrate from settings file /config/oldhydra/settings.cfg and database file /config/oldhydra/nzbhydra.db
INFO --- [0.0-5076-exec-5] o.n.migration.FromPythonMigration        : Starting migration
WARN --- [0.0-5076-exec-5] org.nzbhydra.migration.SqliteMigration   : Deleting all indexers, indexer searches, searches, downloads and API accesses from database
WARN --- [0.0-5076-exec-5] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 42102, SQLState: 42S02
ERROR --- [0.0-5076-exec-5] o.h.engine.jdbc.spi.SqlExceptionHelper   : Table "INDEXERSTATUS" not found; SQL statement:
TRUNCATE TABLE indexerstatus [42102-195]
ERROR --- [0.0-5076-exec-5] o.n.migration.FromPythonMigration        : Error while migrating database
[...]
ERROR --- [0.0-5076-exec-5] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.transaction.TransactionSystemException: Could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Transaction marked as rollbackOnly] with root cause

```

More verbose:
```
javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not prepare statement
        at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1692)
        at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1602)
        at org.hibernate.jpa.spi.AbstractEntityManagerImpl.throwPersistenceException(AbstractEntityManagerImpl.java:1700)
        at org.hibernate.jpa.spi.AbstractQueryImpl.executeUpdate(AbstractQueryImpl.java:70)
        at org.nzbhydra.migration.SqliteMigration.migrate(SqliteMigration.java:80)
        at org.nzbhydra.migration.SqliteMigration$$FastClassBySpringCGLIB$$72e2874a.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
        at org.nzbhydra.migration.SqliteMigration$$EnhancerBySpringCGLIB$$186bdc6b.migrate(<generated>)
Caused by: org.hibernate.exception.SQLGrammarException: could not prepare statement
        at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:106)
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:109)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:182)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareStatement(StatementPreparerImpl.java:78)
        at org.hibernate.engine.query.spi.NativeSQLQueryPlan.performExecuteUpdate(NativeSQLQueryPlan.java:188)
        at org.hibernate.internal.SessionImpl.executeNativeUpdate(SessionImpl.java:1373)
        at org.hibernate.internal.SQLQueryImpl.executeUpdate(SQLQueryImpl.java:373)
        at org.hibernate.jpa.internal.QueryImpl.internalExecuteUpdate(QueryImpl.java:405)
        at org.hibernate.jpa.spi.AbstractQueryImpl.executeUpdate(AbstractQueryImpl.java:61)
        at org.nzbhydra.migration.SqliteMigration.migrate(SqliteMigration.java:80)
        at org.nzbhydra.migration.SqliteMigration$$FastClassBySpringCGLIB$$72e2874a.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
Caused by: org.h2.jdbc.JdbcSQLException: Table "INDEXERSTATUS" not found; SQL statement:
TRUNCATE TABLE indexerstatus [42102-195]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
        at org.h2.message.DbException.get(DbException.java:179)
        at org.h2.message.DbException.get(DbException.java:155)
        at org.h2.command.Parser.readTableOrView(Parser.java:5506)
        at org.h2.command.Parser.readTableOrView(Parser.java:5483)
        at org.h2.command.Parser.parseTruncate(Parser.java:1317)
        at org.h2.command.Parser.parsePrepared(Parser.java:464)
        at org.h2.command.Parser.parse(Parser.java:320)
        at org.h2.command.Parser.parse(Parser.java:292)
        at org.h2.command.Parser.prepareCommand(Parser.java:257)
        at org.h2.engine.Session.prepareLocal(Session.java:573)
        at org.h2.engine.Session.prepareCommand(Session.java:514)
        at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
        at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
        at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)

javax.persistence.RollbackException: Transaction marked as rollbackOnly
        at org.hibernate.jpa.internal.TransactionImpl.commit(TransactionImpl.java:58)
        at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:517)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:761)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:730)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:504)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:292)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
        at org.nzbhydra.migration.FromPythonMigration$$EnhancerBySpringCGLIB$$16db389d.migrateFromFiles(<generated>)
        at org.nzbhydra.migration.MigrationWeb.migrateFromFiles(MigrationWeb.java:37)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
```

I verified that INDEXERSTATUS does indeed exist in the old sqlite db.
So not sure what is going wrong exactly.

**Comment by theotherp** [comment]
My bad, will fix tomorrow.

Am 22.02.2018 06:05 schrieb "h45rd" <notifications@github.com>:

**Comment by h45rd** [comment]
Vielen Dank :)
