### ISSUE TITLE
Animetosho support

### ISSUE THREAD

**Issue by M0UL** [theotherp/nzbhydra2#147]
add support for Animetosho indexer

Animetosho is a anime index that  combines  torznab and newznab.

api url: https://animetosho.org/feed/api

**Comment by theotherp** [comment]
Huh, last time I checked they didn't allow any searches.

**Comment by M0UL** [comment]
it does now. 
the url sonarr user to search,  https://animetosho.org/feed/api?t=search&cat=5070&extended=1&offset=0&limit=75&q=Uchuu%20Senkan%20Tiramisu+01.

it gives the result for both torrent and usenet in a single entry.

**Comment by M0UL** [comment]
api url changed to https://feed.animetosho.org/api

**Comment by fryfrog** [comment]
NZBHydra2 does *not* like torznab *and* newznab results coming back from the same endpoint...

```
2018-05-15 13:43:32.503  INFO --- [0.0-5076-exec-3] o.n.searching.IndexerForSearchSelector   : [Search: 448319] Selected 2 out of 28 indexers: Anime Tosho Usenet, Anime Tosho Torrents
2018-05-15 13:43:32.504 DEBUG --- [0.0-5076-exec-3] org.nzbhydra.searching.Searcher          : [Search: 448319] Going to call 2 indexers because 0 of 100 wanted results were loaded yet
2018-05-15 13:43:32.505  INFO --- [ol-278-thread-2] org.nzbhydra.indexers.Torznab            : [Search: 448319] Anime Tosho Torrents: Calling https://feed.animetosho.org/api?t=search&extended=1&q=Naruto&password=<password>&limit=100&offset=0
2018-05-15 13:43:32.505  INFO --- [ol-278-thread-1] org.nzbhydra.indexers.Newznab            : [Search: 448319] Anime Tosho Usenet: Calling https://feed.animetosho.org/api?t=search&extended=1&q=Naruto&password=<password>&limit=100&offset=0
2018-05-15 13:43:33.426 ERROR --- [ol-278-thread-2] org.nzbhydra.indexers.Indexer            : [Search: 448319] Unexpected error while searching

java.lang.NumberFormatException: For input string: "Anime"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.valueOf(Integer.java:766)
        at org.nzbhydra.indexers.Torznab.createSearchResultItem(Torznab.java:33)
        at org.nzbhydra.indexers.Newznab.getSearchResultItems(Newznab.java:327)
        at org.nzbhydra.indexers.Newznab.getSearchResultItems(Newznab.java:43)
        at org.nzbhydra.indexers.Indexer.searchInternal(Indexer.java:149)
        at org.nzbhydra.indexers.Indexer.search(Indexer.java:89)
        at org.nzbhydra.searching.Searcher.lambda$getIndexerCallable$14(Searcher.java:335)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.nzbhydra.logging.MdcThreadPoolExecutor$1.run(MdcThreadPoolExecutor.java:114)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

2018-05-15 13:43:33.426  WARN --- [ol-278-thread-2] org.nzbhydra.indexers.Torznab            : [Search: 448319] Because an error occurred Anime Tosho Torrents will be temporarily disabled until 2018-05-15T20:58:33.426Z. This is error number 1 in a row
2018-05-15 13:43:37.341  INFO --- [ol-278-thread-1] org.nzbhydra.indexers.Newznab            : [Search: 448319] Anime Tosho Usenet: Successfully executed search call in 4831ms with 100 results
2018-05-15 13:43:37.377 DEBUG --- [ol-278-thread-1] org.nzbhydra.indexers.Newznab            : [Search: 448319] Handling of 100 search results took 25ms
2018-05-15 13:43:37.378 ERROR --- [ol-278-thread-1] org.nzbhydra.indexers.Indexer            : [Search: 448319] Unexpected error while searching

java.lang.NullPointerException: null
        at org.nzbhydra.indexers.Newznab.completeIndexerSearchResult(Newznab.java:338)
        at org.nzbhydra.indexers.Newznab.completeIndexerSearchResult(Newznab.java:43)
        at org.nzbhydra.indexers.Indexer.searchInternal(Indexer.java:159)
        at org.nzbhydra.indexers.Indexer.search(Indexer.java:89)
        at org.nzbhydra.searching.Searcher.lambda$getIndexerCallable$14(Searcher.java:335)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.nzbhydra.logging.MdcThreadPoolExecutor$1.run(MdcThreadPoolExecutor.java:114)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

2018-05-15 13:43:37.378  WARN --- [ol-278-thread-1] org.nzbhydra.indexers.Newznab            : [Search: 448319] Because an error occurred Anime Tosho Usenet will be temporarily disabled until 2018-05-15T20:58:37.378Z. This is error number 1 in a row
```

**Comment by drakex90** [comment]
@fryfrog You can directly add into Sonarr https://m.kyaa.sg/TPNU3BF5.png its the last option in Newznzb->preset

**Comment by fryfrog** [comment]
That is actually what I've done, but it should be supported by nzbhydra2 also. :)

**Comment by drakex90** [comment]
paging @animetosho

**Comment by theotherp** [comment]
What do you know, that was easier than I thought...

**Comment by M0UL** [comment]
they are separated, see the build in indexers

**Comment by fryfrog** [comment]
Ah, finally got it started up on the new version and I see now. Awesome. :)

**Comment by animetosho** [comment]
> specific endpoints for newznab and torznab only

There are URLs for clients which barf over two <enclosure> tags being present ([Torrents only](https://feed.animetosho.org/api?only_tor=1) / [NZB only](https://feed.animetosho.org/api?only_nzb=1)), though checking MIME types is ideal.  
Otherwise, the fields for Newznab/Torznab are basically the same, so there's no reason to separate the two. If someone wants both Newznab and Torznab they can always add it twice.

**Comment by drakex90** [comment]
Getting this error while downloading any NZB using Hydra from Sonarr
`Request Failed. POST /api/release: Reference to undeclared entity 'raquo'. Line 4, position 585.`
When am using Animetosho directly from Sonarr am not getting any issues
Full log
`System.Xml.XmlException: Reference to undeclared entity 'raquo'. Line 4, position 585.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.HandleGeneralEntityReference(String name, Boolean isInAttributeValue, Boolean pushFakeEntityIfNullResolver, Int32 entityStartLinePos)
   at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32& charRefEndPos)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at NzbDrone.Core.Download.NzbValidationService.Validate(String filename, Byte[] fileContent) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\NzbValidationService.cs:line 20
   at NzbDrone.Core.Download.UsenetClientBase`1.Download(RemoteEpisode remoteEpisode) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\UsenetClientBase.cs:line 76
   at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteEpisode remoteEpisode) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\DownloadService.cs:line 69
   at NzbDrone.Api.Indexers.ReleaseModule.DownloadRelease(ReleaseResource release) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Api\Indexers\ReleaseModule.cs:line 67
   at NzbDrone.Api.Indexers.ReleaseModule.<.ctor>b__7_0(Object x) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Api\Indexers\ReleaseModule.cs:line 46
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)`

**Comment by theotherp** [comment]
No idea, ask the sonarr devs what could cause that.

**Comment by drakex90** [comment]
@theotherp I raised a ticket they are saying it might be on Hydras side
https://github.com/Sonarr/Sonarr/issues/2600

**Comment by fryfrog** [comment]
I've got Animetosho setup in Sonarr and NZBHydra2, both torznab and newznab and can't say I've seen this error. What in the world is `raquo`, from your error message?
