### ISSUE TITLE
Unexpected error while preparing search

### ISSUE THREAD

**Issue by ajkis** [theotherp/nzbhydra2#151]
Latest public version.
I see quite a few error's 

```
2018-04-11 20:03:58.807 ERROR --- [l-2174-thread-1] org.nzbhydra.mediainfo.InfoProvider      : [Search: 648718, IP: XXX] Error while converting IMDB 6149052

org.nzbhydra.mediainfo.InfoProviderException: TMDB query for IMDB ID 6149052 returned no searchResults
	at org.nzbhydra.mediainfo.TmdbHandler.getMovieByImdbId(TmdbHandler.java:107)
	at org.nzbhydra.mediainfo.TmdbHandler.fromImdb(TmdbHandler.java:47)
	at org.nzbhydra.mediainfo.TmdbHandler.getInfos(TmdbHandler.java:38)
	at org.nzbhydra.mediainfo.InfoProvider.convert(InfoProvider.java:111)
	at org.nzbhydra.mediainfo.InfoProvider$$FastClassBySpringCGLIB$$1ca0fb53.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.cache.interceptor.CacheInterceptor$1.invoke(CacheInterceptor.java:52)
	at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:345)
	at org.springframework.cache.interceptor.CacheAspectSupport$1.call(CacheAspectSupport.java:367)
	at org.springframework.cache.guava.GuavaCache$1.call(GuavaCache.java:103)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4904)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3628)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2336)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2295)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2208)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4053)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4899)
	at org.springframework.cache.guava.GuavaCache.get(GuavaCache.java:100)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:364)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:327)
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
	at org.nzbhydra.mediainfo.InfoProvider$$EnhancerBySpringCGLIB$$153fffd5.convert(<generated>)
	at org.nzbhydra.indexers.Indexer.generateQueryIfApplicable(Indexer.java:361)
	at org.nzbhydra.indexers.Newznab.buildSearchUrl(Newznab.java:105)
	at org.nzbhydra.indexers.Indexer.searchInternal(Indexer.java:136)
	at org.nzbhydra.indexers.Indexer.search(Indexer.java:101)
	at org.nzbhydra.searching.Searcher.lambda$getIndexerCallable$14(Searcher.java:335)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.nzbhydra.logging.MdcThreadPoolExecutor$1.run(MdcThreadPoolExecutor.java:114)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2018-04-11 20:03:58.808  WARN --- [l-2174-thread-1] org.nzbhydra.indexers.Indexer            : [Search: 648718, IP: XXX] Unexpected error while preparing search
```

**Comment by ajkis** [comment]
p.s. Compared to hydra1 this is lighting fast. Great job.

**Comment by theotherp** [comment]
Thanks 😊

**Comment by ajkis** [comment]
Closing down the issue.

p.s. Maybe as suggestion apply a bit more ram after initial update if user wants to import big database. 
My first import failed after around 40 minutes wait, then I raised to 1024 ram ( have tons to spare) and import was done within 5 minutes.

**Comment by theotherp** [comment]
I think the import dialog says that you should use more ram if you have a big database.
