### ISSUE TITLE
Download migration crash

### ISSUE THREAD

**Issue by enilfodne** [theotherp/nzbhydra2#16]
While migrating from v1, i got the following crash every-time during download import.

* Version: v1.0.4
* OS: Linux x64

Log: 
```
INFO  --- [0.0-5076-exec-1] org.nzbhydra.migration.SqliteMigration   : Migrating X downloads from old database
ERROR --- [0.0-5076-exec-1] o.n.migration.FromPythonMigration        : Error while migrating database

java.lang.NullPointerException: null
	at org.nzbhydra.searching.SearchResultIdCalculator.calculateSearchResultId(SearchResultIdCalculator.java:8)
	at org.nzbhydra.searching.SearchResultSequenceGenerator.generate(SearchResultSequenceGenerator.java:14)
	at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:101)
	at org.hibernate.jpa.event.internal.core.JpaPersistEventListener.saveWithGeneratedId(JpaPersistEventListener.java:67)
	at org.hibernate.event.internal.DefaultPersistEventListener.entityIsTransient(DefaultPersistEventListener.java:189)
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:132)
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:58)
	at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:775)
	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:748)
	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:753)
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.persist(AbstractEntityManagerImpl.java:1146)
	at sun.reflect.GeneratedMethodAccessor133.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:298)
	at com.sun.proxy.$Proxy101.persist(Unknown Source)
	at org.springframework.data.jpa.repository.support.SimpleJpaRepository.save(SimpleJpaRepository.java:508)
	at org.springframework.data.jpa.repository.support.SimpleJpaRepository.save(SimpleJpaRepository.java:542)
	at org.springframework.data.jpa.repository.support.SimpleJpaRepository.save(SimpleJpaRepository.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.executeMethodOn(RepositoryFactorySupport.java:504)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:489)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:461)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:56)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:133)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:57)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy113.save(Unknown Source)
	at org.nzbhydra.migration.SqliteMigration.migrateDownloads(SqliteMigration.java:158)
	at org.nzbhydra.migration.SqliteMigration.migrate(SqliteMigration.java:129)
	at org.nzbhydra.migration.SqliteMigration.migrate(SqliteMigration.java:108)
	at org.nzbhydra.migration.SqliteMigration$$FastClassBySpringCGLIB$$72e2874a.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
	at org.nzbhydra.migration.SqliteMigration$$EnhancerBySpringCGLIB$$7dae4580.migrate(<generated>)
	at org.nzbhydra.migration.FromPythonMigration.startMigration(FromPythonMigration.java:105)
	at org.nzbhydra.migration.FromPythonMigration.migrateFromUrl(FromPythonMigration.java:97)
	at org.nzbhydra.migration.FromPythonMigration$$FastClassBySpringCGLIB$$25126370.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
	at org.nzbhydra.migration.FromPythonMigration$$EnhancerBySpringCGLIB$$7c1da1b2.migrateFromUrl(<generated>)
	at org.nzbhydra.migration.MigrationWeb.migrateFromUrl(MigrationWeb.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.nzbhydra.auth.HydraAnonymousAuthenticationFilter.doFilter(HydraAnonymousAuthenticationFilter.java:98)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by theotherp** [comment]
Please try https://github.com/theotherp/nzbhydra2/releases/tag/v1.0.5 I think I fixed that.

**Comment by enilfodne** [comment]
It seems something is broken in `1.0.5` as it started crashing with:

` Invalid maximum heap size: -Xmx128`

Deleteing `nzbhydra.yaml` allows it to start the first time, but the next time it starts - it fails again with the same error.

**Comment by theotherp** [comment]
What does it say in the console when you start it?

**Comment by theotherp** [comment]
Can reproduce. Wait.

**Comment by enilfodne** [comment]
I think its an issue with the commandline generation as this is in my logs:

`
java -Xmx128
M -DfromWrapper -XX:TieredStopAtLevel=1 -noverify -Dspring.output.ansi.enabled=ALWAYS -jar /<path>/lib/core-1.0.5-exec.jar --nobrowser --datafolder /<data> in folder /<path>
`

I think with the removal of `pyYAML` doesn't trim the newline at the end of `Xmx: 128` in `nzbhydra.yml`

**Comment by theotherp** [comment]
Got it.

**Comment by enilfodne** [comment]
`1.0.6` does not throw errors, but nothing `Search` and `Download` history tabs are empty. Some of indexers responded with `429: Too many requests` (to be expected) and this may be cause of error.

**Comment by theotherp** [comment]
Post your debug infos.

**Comment by enilfodne** [comment]
This is one of the big ones (i think the whole batch failed due to schema incompatibility):

```
 WARN --- [0.1-5076-exec-5] o.h.engine.jdbc.spi.SqlExceptionHelper   : [IP: XXX.XXX.XXX.XXX] SQL Error: 22001, SQLState: 22001
ERROR --- [0.1-5076-exec-5] o.h.engine.jdbc.spi.SqlExceptionHelper   : [IP: XXX.XXX.XXX.XXX] Value too long for column "ERROR VARCHAR(255)": "'HTTPConnectionPool(host=''xxx.xx'', port=80): Max retries exceeded with url: /getnzb/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.n... (359)"; SQL statement:
insert into indexernzbdownload (access_source, age, error, external_id, ip, nzb_access_type, search_result_id, status, time, user_agent, username, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [22001-195]
 WARN --- [0.1-5076-exec-5] o.h.engine.jdbc.spi.SqlExceptionHelper   : [IP: XXX.XXX.XXX.XXX] SQL Error: 22001, SQLState: 22001
ERROR --- [0.1-5076-exec-5] o.h.engine.jdbc.spi.SqlExceptionHelper   : [IP: XXX.XXX.XXX.XXX] Value too long for column "ERROR VARCHAR(255)": "'HTTPConnectionPool(host=''xxx.xx'', port=80): Max retries exceeded with url: /getnzb/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.n... (359)"; SQL statement:
insert into indexernzbdownload (access_source, age, error, external_id, ip, nzb_access_type, search_result_id, status, time, user_agent, username, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [22001-195]
 WARN --- [0.1-5076-exec-5] o.h.engine.jdbc.spi.SqlExceptionHelper   : [IP: XXX.XXX.XXX.XXX] SQL Error: 22001, SQLState: 22001
ERROR --- [0.1-5076-exec-5] o.h.engine.jdbc.spi.SqlExceptionHelper   : [IP: XXX.XXX.XXX.XXX] Value too long for column "ERROR VARCHAR(255)": "'HTTPConnectionPool(host=''xxx.xx'', port=80): Max retries exceeded with url: /getnzb/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.n... (359)"; SQL statement:
insert into indexernzbdownload (access_source, age, error, external_id, ip, nzb_access_type, search_result_id, status, time, user_agent, username, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [22001-195]
 WARN --- [0.1-5076-exec-5] o.h.engine.jdbc.spi.SqlExceptionHelper   : [IP: XXX.XXX.XXX.XXX] SQL Error: 22001, SQLState: 22001
ERROR --- [0.1-5076-exec-5] o.h.engine.jdbc.spi.SqlExceptionHelper   : [IP: XXX.XXX.XXX.XXX] Value too long for column "ERROR VARCHAR(255)": "'HTTPConnectionPool(host=''xxx.xx'', port=80): Max retries exceeded with url: /getnzb/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.n... (359)"; SQL statement:
insert into indexernzbdownload (access_source, age, error, external_id, ip, nzb_access_type, search_result_id, status, time, user_agent, username, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [22001-195]
 WARN --- [0.1-5076-exec-5] o.h.engine.jdbc.spi.SqlExceptionHelper   : [IP: XXX.XXX.XXX.XXX] SQL Error: 22001, SQLState: 22001
ERROR --- [0.1-5076-exec-5] o.h.engine.jdbc.spi.SqlExceptionHelper   : [IP: XXX.XXX.XXX.XXX] Value too long for column "ERROR VARCHAR(255)": "'HTTPConnectionPool(host=''xxx.xx'', port=80): Max retries exceeded with url: /getnzb/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.n... (359)"; SQL statement:
insert into indexernzbdownload (access_source, age, error, external_id, ip, nzb_access_type, search_result_id, status, time, user_agent, username, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [22001-195]
 WARN --- [0.1-5076-exec-5] o.h.engine.jdbc.spi.SqlExceptionHelper   : [IP: XXX.XXX.XXX.XXX] SQL Error: 22001, SQLState: 22001
ERROR --- [0.1-5076-exec-5] o.h.engine.jdbc.spi.SqlExceptionHelper   : [IP: XXX.XXX.XXX.XXX] Value too long for column "ERROR VARCHAR(255)": "'HTTPConnectionPool(host=''xxx.xx'', port=80): Max retries exceeded with url: /getnzb/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.n... (359)"; SQL statement:
insert into indexernzbdownload (access_source, age, error, external_id, ip, nzb_access_type, search_result_id, status, time, user_agent, username, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [22001-195]
 WARN --- [0.1-5076-exec-5] o.h.engine.jdbc.spi.SqlExceptionHelper   : [IP: XXX.XXX.XXX.XXX] SQL Error: 22001, SQLState: 22001
ERROR --- [0.1-5076-exec-5] o.h.engine.jdbc.spi.SqlExceptionHelper   : [IP: XXX.XXX.XXX.XXX] Value too long for column "ERROR VARCHAR(255)": "'HTTPConnectionPool(host=''xxx.xx'', port=80): Max retries exceeded with url: /getnzb/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.n... (359)"; SQL statement:
insert into indexernzbdownload (access_source, age, error, external_id, ip, nzb_access_type, search_result_id, status, time, user_agent, username, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [22001-195]
 WARN --- [0.1-5076-exec-5] o.h.engine.jdbc.spi.SqlExceptionHelper   : [IP: XXX.XXX.XXX.XXX] SQL Error: 22001, SQLState: 22001
ERROR --- [0.1-5076-exec-5] o.h.engine.jdbc.spi.SqlExceptionHelper   : [IP: XXX.XXX.XXX.XXX] Value too long for column "ERROR VARCHAR(255)": "'HTTPConnectionPool(host=''xxx.xx'', port=80): Max retries exceeded with url: /getnzb/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.n... (359)"; SQL statement:
insert into indexernzbdownload (access_source, age, error, external_id, ip, nzb_access_type, search_result_id, status, time, user_agent, username, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [22001-195]
 WARN --- [0.1-5076-exec-5] o.h.engine.jdbc.spi.SqlExceptionHelper   : [IP: XXX.XXX.XXX.XXX] SQL Error: 22001, SQLState: 22001
ERROR --- [0.1-5076-exec-5] o.h.engine.jdbc.spi.SqlExceptionHelper   : [IP: XXX.XXX.XXX.XXX] Value too long for column "ERROR VARCHAR(255)": "'HTTPConnectionPool(host=''xxx.xx'', port=80): Max retries exceeded with url: /getnzb/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.n... (359)"; SQL statement:
insert into indexernzbdownload (access_source, age, error, external_id, ip, nzb_access_type, search_result_id, status, time, user_agent, username, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [22001-195]
 WARN --- [0.1-5076-exec-5] o.h.engine.jdbc.spi.SqlExceptionHelper   : [IP: XXX.XXX.XXX.XXX] SQL Error: 22001, SQLState: 22001
ERROR --- [0.1-5076-exec-5] o.h.engine.jdbc.spi.SqlExceptionHelper   : [IP: XXX.XXX.XXX.XXX] Value too long for column "ERROR VARCHAR(255)": "'HTTPConnectionPool(host=''xxx.xx'', port=80): Max retries exceeded with url: /getnzb/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.n... (359)"; SQL statement:
insert into indexernzbdownload (access_source, age, error, external_id, ip, nzb_access_type, search_result_id, status, time, user_agent, username, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [22001-195]
 WARN --- [0.1-5076-exec-5] o.h.engine.jdbc.spi.SqlExceptionHelper   : [IP: XXX.XXX.XXX.XXX] SQL Error: 22001, SQLState: 22001
ERROR --- [0.1-5076-exec-5] o.h.engine.jdbc.spi.SqlExceptionHelper   : [IP: XXX.XXX.XXX.XXX] Value too long for column "ERROR VARCHAR(255)": "'HTTPConnectionPool(host=''xxx.xx'', port=80): Max retries exceeded with url: /getnzb/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.n... (359)"; SQL statement:
insert into indexernzbdownload (access_source, age, error, external_id, ip, nzb_access_type, search_result_id, status, time, user_agent, username, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [22001-195]
 WARN --- [0.1-5076-exec-5] o.h.engine.jdbc.spi.SqlExceptionHelper   : [IP: XXX.XXX.XXX.XXX] SQL Error: 22001, SQLState: 22001
ERROR --- [0.1-5076-exec-5] o.h.engine.jdbc.spi.SqlExceptionHelper   : [IP: XXX.XXX.XXX.XXX] Value too long for column "ERROR VARCHAR(255)": "'HTTPConnectionPool(host=''xxx.xx'', port=80): Max retries exceeded with url: /getnzb/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.n... (359)"; SQL statement:
insert into indexernzbdownload (access_source, age, error, external_id, ip, nzb_access_type, search_result_id, status, time, user_agent, username, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [22001-195]
 WARN --- [0.1-5076-exec-5] o.h.engine.jdbc.spi.SqlExceptionHelper   : [IP: XXX.XXX.XXX.XXX] SQL Error: 22001, SQLState: 22001
ERROR --- [0.1-5076-exec-5] o.h.engine.jdbc.spi.SqlExceptionHelper   : [IP: XXX.XXX.XXX.XXX] Value too long for column "ERROR VARCHAR(255)": "'HTTPConnectionPool(host=''xxx.xx'', port=80): Max retries exceeded with url: /getnzb/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.n... (359)"; SQL statement:
insert into indexernzbdownload (access_source, age, error, external_id, ip, nzb_access_type, search_result_id, status, time, user_agent, username, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [22001-195]
ERROR --- [0.1-5076-exec-5] o.h.e.jdbc.batch.internal.BatchingBatch  : [IP: XXX.XXX.XXX.XXX] HHH000315: Exception executing batch [could not execute batch]
ERROR --- [0.1-5076-exec-5] o.a.c.c.C.[.[.[/v2].[dispatcherServlet]  : [IP: XXX.XXX.XXX.XXX] Servlet.service() for servlet [dispatcherServlet] in context with path [/v2] threw exception [Request processing failed; nested exception is org.springframework.dao.DataIntegrityViolationException: could not execute batch; SQL [insert into indexernzbdownload (access_source, age, error, external_id, ip, nzb_access_type, search_result_id, status, time, user_agent, username, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; nested exception is org.hibernate.exception.DataException: could not execute batch] with root cause

org.h2.jdbc.JdbcBatchUpdateException: Value too long for column "ERROR VARCHAR(255)": "'HTTPConnectionPool(host=''xxx.xx'', port=80): Max retries exceeded with url: /getnzb/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.x... (359)"; SQL statement:
insert into indexernzbdownload (access_source, age, error, external_id, ip, nzb_access_type, search_result_id, status, time, user_agent, username, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [22001-195]
```

and multiple (per-tracker):

```
ERROR --- [pool-3-thread-3] org.nzbhydra.indexers.NewznabChecker     : Error while communicating with indexer

java.util.concurrent.ExecutionException: org.nzbhydra.indexers.exceptions.IndexerUnreachableException: Error while communicating with indexer NZBFinder. Server returned: java.io.IOException: URL call to https://x.x/api?apikey=<APIKEY> returned 429:Too Many Requests
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at org.nzbhydra.indexers.NewznabChecker.checkCaps(NewznabChecker.java:126)
	at org.nzbhydra.migration.JsonConfigMigration.lambda$null$4(JsonConfigMigration.java:530)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.nzbhydra.indexers.exceptions.IndexerUnreachableException: Error while communicating with indexer NZBFinder. Server returned: java.io.IOException: URL call to https://x.x/api?apikey=<APIKEY> returned 429:Too Many Requests
	at org.nzbhydra.indexers.IndexerWebAccess.get(IndexerWebAccess.java:76)
	at org.nzbhydra.indexers.IndexerWebAccess.get(IndexerWebAccess.java:43)
	at org.nzbhydra.indexers.NewznabChecker.singleCheckCaps(NewznabChecker.java:250)
	at org.nzbhydra.indexers.NewznabChecker.lambda$checkCaps$0(NewznabChecker.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.nzbhydra.logging.MdcThreadPoolExecutor$1.run(MdcThreadPoolExecutor.java:93)
	... 3 common frames omitted
Caused by: java.io.IOException: URL call to https://x.x/api?apikey=<APIKEY> returned 429:Too Many Requests
	at org.nzbhydra.okhttp.WebAccess.callUrl(WebAccess.java:66)
	at org.nzbhydra.indexers.IndexerWebAccess.lambda$get$0(IndexerWebAccess.java:60)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 common frames omitted
````

**Comment by theotherp** [comment]
Got the first one. Stupid mistake.

You didn't send the whole debug infos so I have no idea if the second one is caused by the first or an independent issue.

**Comment by theotherp** [comment]
I increased the column width(s) in 1.0.8

**Comment by enilfodne** [comment]
While everything seems to be working, the migration dialog never finishes (even though it says `Completed migration with x message`) and `Download History` is not migrated (`Search`/`Stats` are). But it seems this is past the scope of this issue.

**Comment by theotherp** [comment]
Ok, thanks for the feedback. Considering that migration is something you typically only do once that's a minor issue for me right now.

I'll keep this open for other issues with the migration.

**Comment by theotherp** [comment]
Should work now.
