### ISSUE TITLE
v1 migration - Java heap space error

### ISSUE THREAD

**Issue by piejanssens** [theotherp/nzbhydra2#164]
```
java.lang.OutOfMemoryError: Java heap space

2018-05-03 14:09:31.993 ERROR --- [0.0-5076-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : [IP: 172.17.0.1] Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler processing failed; nested exception is java.lang.OutOfMemoryError: Java heap space] with root cause

java.lang.OutOfMemoryError: Java heap space

2018-05-03 14:09:31.993 ERROR --- [0.0-5076-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : [IP: 172.17.0.1] Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.OutOfMemoryError: Java heap space] with root cause

java.lang.OutOfMemoryError: Java heap space

2018-05-03 14:09:31.996 ERROR --- [     HydraTask5] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.

java.lang.OutOfMemoryError: Java heap space

2018-05-03 14:09:32.048  INFO --- [0.0-5076-exec-4] org.nzbhydra.api.ExternalApi             : [IP: 78.22.81.50] Received external API call: NewznabParameters{t=TVSEARCH, cat=[5030, 5040], tvdbId=248482, season=1, ep=25, offset=0, limit=100, maxage=500, raw=false, extended=false}
2018-05-03 14:09:32.049 ERROR --- [0.0-5076-exec-4] org.nzbhydra.api.ExternalApi             : [IP: 78.22.81.50] Received API call with wrong API key
2018-05-03 14:09:31.993 ERROR --- [0.0-5076-exec-5] org.nzbhydra.api.ExternalApi             : [IP: 78.22.81.50] Unexpected error while handling API request

org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.OutOfMemoryError: Java heap space
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:982)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.nzbhydra.auth.HydraAnonymousAuthenticationFilter.doFilter(HydraAnonymousAuthenticationFilter.java:98)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.nzbhydra.auth.HydraEmbeddedServletContainer$1.invoke(HydraEmbeddedServletContainer.java:90)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at com.fasterxml.jackson.core.util.BufferRecycler.balloc(BufferRecycler.java:155)
	at com.fasterxml.jackson.core.util.BufferRecycler.allocByteBuffer(BufferRecycler.java:96)
	at com.fasterxml.jackson.core.util.BufferRecycler.allocByteBuffer(BufferRecycler.java:86)
	at com.fasterxml.jackson.core.io.IOContext.allocWriteEncodingBuffer(IOContext.java:160)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator.<init>(UTF8JsonGenerator.java:119)
	at com.fasterxml.jackson.core.JsonFactory._createUTF8Generator(JsonFactory.java:1384)
	at com.fasterxml.jackson.core.JsonFactory.createGenerator(JsonFactory.java:1095)
	at net.logstash.logback.composite.CompositeJsonFormatter.createGenerator(CompositeJsonFormatter.java:187)
	at net.logstash.logback.composite.CompositeJsonFormatter.writeEventToOutputStream(CompositeJsonFormatter.java:152)
	at net.logstash.logback.encoder.CompositeJsonEncoder.encode(CompositeJsonEncoder.java:114)
	at net.logstash.logback.encoder.CompositeJsonEncoder.encode(CompositeJsonEncoder.java:32)
	at ch.qos.logback.core.OutputStreamAppender.subAppend(OutputStreamAppender.java:230)
	at ch.qos.logback.core.rolling.RollingFileAppender.subAppend(RollingFileAppender.java:235)
	at ch.qos.logback.core.OutputStreamAppender.append(OutputStreamAppender.java:102)
	at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
	at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
	at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
	at ch.qos.logback.classic.Logger.filterAndLog_2(Logger.java:414)
	at ch.qos.logback.classic.Logger.info(Logger.java:587)
	at org.nzbhydra.api.ExternalApi.api(ExternalApi.java:85)
	at sun.reflect.GeneratedMethodAccessor145.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)

2018-05-03 14:09:32.089 ERROR --- [0.0-5076-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : [IP: 172.17.0.1] Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.OutOfMemoryError: Java heap space] with root cause

java.lang.OutOfMemoryError: Java heap space
```

**Comment by theotherp** [comment]
As the migration modal window says you might need to increase the XMX value in the config for the migration to work.

Also in the future please follow the instructions and post the debug infos ZIP and a description instead of just pasting an excerpt from the log file.

**Comment by piejanssens** [comment]
Debug log link is not accessible after this exception. 
My dockers container in synology has no resource limitation. 8GB Ram. Do I need to explicitly set a limitation and give it like 2GB?

**Comment by theotherp** [comment]
You need to restart the service for it to work again.

The docker doesn't matter, set the XMX value in the config of NZBHydra.

So restart, set higher XMX (e.g. 1024 for the time of migrating, later perhaps 256), try again.

**Comment by piejanssens** [comment]
Whatever I do I can't get it to stick on 1024 after restart.
So I edit nzbyhdra.yml from my config dir and change xmx to 1024.
Click restart and check the config file, it's put back to 128.
Same when I use the UI to click reload config from file and then restart.

**Comment by piejanssens** [comment]
```
2018-05-03 20:47:16.190  INFO --- [0.0-5076-exec-3] o.n.migration.FromPythonMigration        : [IP: 172.17.0.1] Received request to migrate from settings file /config/restore/settings.cfg and database file /config/restore/nzbhydra.db
2018-05-03 20:47:16.193  INFO --- [0.0-5076-exec-3] o.n.migration.FromPythonMigration        : [IP: 172.17.0.1] Starting migration
2018-05-03 20:47:16.377  WARN --- [0.0-5076-exec-3] org.nzbhydra.migration.SqliteMigration   : [IP: 172.17.0.1] Deleting all indexers, indexer searches, searches, downloads and API accesses from database
2018-05-03 20:47:16.414  INFO --- [0.0-5076-exec-3] org.nzbhydra.migration.SqliteMigration   : [IP: 172.17.0.1] Starting database migration
2018-05-03 20:47:16.423  INFO --- [0.0-5076-exec-3] org.nzbhydra.migration.SqliteMigration   : [IP: 172.17.0.1] Migrating 10 indexers from old database
2018-05-03 20:47:16.485  INFO --- [0.0-5076-exec-3] org.nzbhydra.migration.SqliteMigration   : [IP: 172.17.0.1] Successfully migrated indexers from old database
2018-05-03 20:47:16.520  INFO --- [0.0-5076-exec-3] org.nzbhydra.migration.SqliteMigration   : [IP: 172.17.0.1] Migrating 586078 searches from old database
2018-05-03 20:47:43.614  INFO --- [0.0-5076-exec-3] org.nzbhydra.migration.SqliteMigration   : [IP: 172.17.0.1] Saving search entities to database
2018-05-03 20:49:41.400  INFO --- [0.0-5076-exec-3] org.nzbhydra.migration.SqliteMigration   : [IP: 172.17.0.1] Successfully migrated searches from old database
2018-05-03 20:50:02.646  INFO --- [0.0-5076-exec-3] org.nzbhydra.migration.SqliteMigration   : [IP: 172.17.0.1] Migrating 3101928 indexer API accesses from old database
2018-05-03 21:03:47.941 ERROR --- [0.0-5076-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : [IP: 172.17.0.1] Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.OutOfMemoryError: GC overhead limit exceeded] with root cause

java.lang.OutOfMemoryError: GC overhead limit exceeded
```

**Comment by theotherp** [comment]
Well, try 2048...

You can also just choose to not migrate the history to prevent this problem.

**Comment by piejanssens** [comment]
Migration finished with 2048.
Now I'm stuck at the login form. I'm 100% sure about the user/pw combo from v1.

**Comment by theotherp** [comment]
The username and password are stored as plaintext in the .yml file. Just
look it up there and see if it matches. If it still doesn't work you can
change the auth type to "NONE" in the .yml file or change the username and
password if they were not migrated correctly. In both cases shut down the
process before changing the file.

**Comment by theotherp** [comment]
I assume you found a solution?
