### ISSUE TITLE
TMDB find fails

### ISSUE THREAD

**Issue by enilfodne** [theotherp/nzbhydra2#171]
Noticed the following issue in the logs:

```java
ERROR --- [ol-857-thread-1] org.nzbhydra.mediainfo.InfoProvider      : [Search: 25067, IP: X.X.X.X] Error while converting IMDB 0019798

org.nzbhydra.mediainfo.InfoProviderException: TMDB query for IMDB ID 0019798 returned no searchResults
	at org.nzbhydra.mediainfo.TmdbHandler.getMovieByImdbId(TmdbHandler.java:107)
	at org.nzbhydra.mediainfo.TmdbHandler.fromImdb(TmdbHandler.java:47)
	at org.nzbhydra.mediainfo.TmdbHandler.getInfos(TmdbHandler.java:38)
	at org.nzbhydra.mediainfo.InfoProvider.convert(InfoProvider.java:111)
	at org.nzbhydra.mediainfo.InfoProvider$$FastClassBySpringCGLIB$$1ca0fb53.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.cache.interceptor.CacheInterceptor$1.invoke(CacheInterceptor.java:52)
	at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:345)
	at org.springframework.cache.interceptor.CacheAspectSupport$1.call(CacheAspectSupport.java:367)
	at org.springframework.cache.guava.GuavaCache$1.call(GuavaCache.java:103)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4904)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3628)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2336)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2295)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2208)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4053)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4899)
	at org.springframework.cache.guava.GuavaCache.get(GuavaCache.java:100)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:364)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:327)
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
	at org.nzbhydra.mediainfo.InfoProvider$$EnhancerBySpringCGLIB$$122294c4.convert(<generated>)
	at org.nzbhydra.indexers.Indexer.generateQueryIfApplicable(Indexer.java:361)
	at org.nzbhydra.indexers.Newznab.buildSearchUrl(Newznab.java:105)
	at org.nzbhydra.indexers.Indexer.searchInternal(Indexer.java:136)
	at org.nzbhydra.indexers.Indexer.search(Indexer.java:101)
	at org.nzbhydra.searching.Searcher.lambda$getIndexerCallable$14(Searcher.java:335)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.nzbhydra.logging.MdcThreadPoolExecutor$1.run(MdcThreadPoolExecutor.java:114)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

It seems the issue is that `TMDB` expects the format `tt<id>`, but `newzNAB` API sends only `<id>`.

**Comment by theotherp** [comment]
Follow the instructions and post the debug infos ZIP.

**Comment by rigrassm** [comment]
Opened a pull request that I believe should fix this issue. The issue is at [DevEndpoint.java#45](https://github.com/rigrassm/nzbhydra2/blob/master/core/src/main/java/org/nzbhydra/DevEndpoint.java#L45) and is caused by the `InfoProvider.convert()` function using `InfoProvider.IdType.TVDB` as the fromType parameter when it should be `InfoProvider.IdType.TMDB`.
