### ISSUE TITLE
Bad character in 1337x release (via Jackett) throwing "Internal Server Error"

### ISSUE THREAD

**Issue by PearsonFlyer** [theotherp/nzbhydra2#205]
Running NZBHydra2 version 1.5.1 on Windows 10. Searched for a release, and when I try to grab it, it throws the following error screen:

Path | /gettorrent/user/5945552838873637331
-- | --
Query parameters |  
Error | Internal Server Error
Exception | java.lang.IllegalArgumentException
Timestamp | Wed Jun 27 18:02:27 EDT 2018

Here are my logs for this section. The character appears to be between the years instead of a dash.

2018-06-27 18:02:27.607  INFO --- [0.0-5076-exec-3] o.n.d.torrents.TorrentFileHandler        : [Search: 744990, IP: 192.168.1.14] Download request for "Night Court (1984�1992) TV Series All Seasons Complete DVDRip+TVRip {Mixed}" from indexer 1337x Jackett
2018-06-27 18:02:27.607 ERROR --- [0.0-5076-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : [Search: 744990, IP: 192.168.1.14] Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalArgumentException: Illegal character in query at index 763: http://192.168.1.99:9117/dl/1337x/?jackett_apikey=<apikey>&path=N1Y1WjZwZGo2WGxtR2F4blY2TnpGeXE4b1MwSnoxbTFWdW1tY0FuakprYkNoNTJLWFlHSTZoT01RdDZWZmhNSFQrRGl6YkU2eXJOS3NwR2QrMDdURVdIYmQvWVBBOEh5NmRKeWRjM1NuSXVVSFQ0YzZ4eXFlTGw2bHJDR3ZJVC9Kbk05RUJTS3Q4NHArWjllK0M1cnVkYXFmL3FIYkVsUW9TWXFubjVQL3hMUWovN2tzdk9vWEJSem9xby9iN3Z5dytqb3JDRmVBK0RtK1BkTmEwcWNCK3VWR2lIbUZqTzhUR0JPZWc3YWlIZFdyZStBOFBWL2lOYlFKMlpkUjdGazI4ZnlxbXJpRVlqb2w4UFUyWlBrOXg2SnlEdXBOUmpQUktnYWJBYmJuWnpENW1BQU9VOGVzSDRGc084NFZNK1VYRllFbDRHcXlTaWIwMkY4QVR4UFZzZllCUmpNbHhJemlhSGpCOEcxZFNtaEYvTkIxd3o2M3ArMUVENWljam9KVHV0K3U4RElMWW05cmRJbDJtV2RpYmVycWdEbVIrdkZzME9BUmxPVUsxMnpnaHliVlJPSTljdlNnNkRJQTA4NA2&file=Night+Court+(1984�1992)+TV+Series+All+Seasons+Complete+DVDRip%2BTVRip+{Mixed}] with root cause

java.net.URISyntaxException: Illegal character in query at index 763: http://192.168.1.99:9117/dl/1337x/?jackett_apikey=<apikey>&path=N1Y1WjZwZGo2WGxtR2F4blY2TnpGeXE4b1MwSnoxbTFWdW1tY0FuakprYkNoNTJLWFlHSTZoT01RdDZWZmhNSFQrRGl6YkU2eXJOS3NwR2QrMDdURVdIYmQvWVBBOEh5NmRKeWRjM1NuSXVVSFQ0YzZ4eXFlTGw2bHJDR3ZJVC9Kbk05RUJTS3Q4NHArWjllK0M1cnVkYXFmL3FIYkVsUW9TWXFubjVQL3hMUWovN2tzdk9vWEJSem9xby9iN3Z5dytqb3JDRmVBK0RtK1BkTmEwcWNCK3VWR2lIbUZqTzhUR0JPZWc3YWlIZFdyZStBOFBWL2lOYlFKMlpkUjdGazI4ZnlxbXJpRVlqb2w4UFUyWlBrOXg2SnlEdXBOUmpQUktnYWJBYmJuWnpENW1BQU9VOGVzSDRGc084NFZNK1VYRllFbDRHcXlTaWIwMkY4QVR4UFZzZllCUmpNbHhJemlhSGpCOEcxZFNtaEYvTkIxd3o2M3ArMUVENWljam9KVHV0K3U4RElMWW05cmRJbDJtV2RpYmVycWdEbVIrdkZzME9BUmxPVUsxMnpnaHliVlJPSTljdlNnNkRJQTA4NA2&file=Night+Court+(1984�1992)+TV+Series+All+Seasons+Complete+DVDRip%2BTVRip+{Mixed}
	at java.net.URI$Parser.fail(Unknown Source)
	at java.net.URI$Parser.checkChars(Unknown Source)
	at java.net.URI$Parser.parseHierarchical(Unknown Source)
	at java.net.URI$Parser.parse(Unknown Source)
	at java.net.URI.<init>(Unknown Source)
	at java.net.URI.create(Unknown Source)
	at org.nzbhydra.downloading.DownloadResult.getAsResponseEntity(DownloadResult.java:76)
	at org.nzbhydra.downloading.torrents.TorrentHandlingWeb.downloadTorrentForUsers(TorrentHandlingWeb.java:66)
	at sun.reflect.GeneratedMethodAccessor876.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.nzbhydra.auth.HydraAnonymousAuthenticationFilter.doFilter(HydraAnonymousAuthenticationFilter.java:98)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.nzbhydra.auth.HydraEmbeddedServletContainer$1.invoke(HydraEmbeddedServletContainer.java:90)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)

**Comment by theotherp** [comment]
Please post the debug infos ZIP.
