### ISSUE TITLE
All but one indexer searchs works. The one that doesnt work changes all the time

### ISSUE THREAD

**Issue by slamanna212** [theotherp/nzbhydra2#206]
## How to create a bug report

**Set your log file level to debug, repeat the steps that cause the problem and post the debug infos ZIP which can be retrieved in the [System / Bugreport section](http://127.0.0.1:5076/system/bugreport). If other tools are involved post their logs as well.**
[nzbhydra-debuginfos-2018-06-29-02-48.zip](https://github.com/theotherp/nzbhydra2/files/2148066/nzbhydra-debuginfos-2018-06-29-02-48.zip)

* You don't have to follow the next steps by the letter, just think about what you're trying to achieve ;-) 
* What do you expect to happen? What does happen? Expected: I get results from all indexers, what does happen: I get results from all but one indexer. IT doesnt matter how many i select. All but one will work. 
* Have you searched for this problem? You don't have to answer, just make sure. yes
* Can the problem be reproduced? How? Use NzbHydra2 in docker fully updated, try and search with multple indexers select
* Use a proper title. Describe the problem succinctly, don't just copy and paste the error message.

**I will close your issues if I you didn't provide proper information as described as above**

The more information you provide up front the higher the chance that I can help you.

## How to request a new feature
* What do you want to happen?
* If not clear, why do you want it?
* Do you think it's something only you need or something that might be popular?
* If need be explain the use case.

**Comment by slamanna212** [comment]
This also happened: 


2018-06-29 07:10:22.794 ERROR --- [0.0-5076-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception

org.springframework.security.web.authentication.rememberme.CookieTheftException: Invalid remember-me token (Series/token) mismatch. Implies previous cookie theft attack.
        at org.springframework.security.web.authentication.rememberme.PersistentTokenBasedRememberMeServices.processAutoLoginCookie(PersistentTokenBasedRememberMeServices.java:119)
        at org.springframework.security.web.authentication.rememberme.AbstractRememberMeServices.autoLogin(AbstractRememberMeServices.java:130)
        at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:98)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:124)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)

**Comment by slamanna212** [comment]
2018-06-29 07:10:29.354 ERROR --- [0.0-5076-exec-1] org.nzbhydra.update.UpdatesWeb           : [IP: 2601:989:4100:2a9:7cbe:5e6c:6fcf:a7cf] An error occurred while updating or getting update infos: Error while getting latest version: api.github.com: Try again
2018-06-29 07:10:59.545  INFO --- [0.0-5076-exec-2] org.nzbhydra.searching.SearchWeb         : [Search: 702337, IP: 2601:989:4100:2a9:7cbe:5e6c:6fcf:a7cf] New search request: SearchRequest{source=INTERNAL, indexers=[NZBGeek, nzbplanet, Drunken Slug, FastNZB], searchType=SEARCH, category=All, offset=0, limit=100, query=uhd, identifiers={}}
2018-06-29 07:10:59.682  INFO --- [0.0-5076-exec-2] o.n.searching.IndexerForSearchSelector   : [Search: 702337, IP: 2601:989:4100:2a9:7cbe:5e6c:6fcf:a7cf] Selected 4 out of 4 indexers: NZBGeek, nzbplanet, Drunken Slug, FastNZB
2018-06-29 07:10:59.717  INFO --- [pool-3-thread-4] org.nzbhydra.indexers.Newznab            : [Search: 702337, IP: 2601:989:4100:2a9:7cbe:5e6c:6fcf:a7cf] Drunken Slug: Calling https://api.drunkenslug.com/api?apikey=<apikey>&t=search&extended=1&q=uhd&limit=100&offset=0
2018-06-29 07:10:59.717  INFO --- [pool-3-thread-2] org.nzbhydra.indexers.Newznab            : [Search: 702337, IP: 2601:989:4100:2a9:7cbe:5e6c:6fcf:a7cf] NZBGeek: Calling https://api.nzbgeek.info/api?apikey=<apikey>&t=search&extended=1&q=uhd&limit=100&offset=0
2018-06-29 07:10:59.717  INFO --- [pool-3-thread-1] org.nzbhydra.indexers.Newznab            : [Search: 702337, IP: 2601:989:4100:2a9:7cbe:5e6c:6fcf:a7cf] nzbplanet: Calling https://nzbplanet.net/api?apikey=<apikey>&t=search&extended=1&q=uhd&limit=100&offset=0
2018-06-29 07:10:59.717  INFO --- [pool-3-thread-3] org.nzbhydra.indexers.Newznab            : [Search: 702337, IP: 2601:989:4100:2a9:7cbe:5e6c:6fcf:a7cf] FastNZB: Calling https://fastnzb.com/api?apikey=<apikey>&t=search&extended=1&q=uhd&limit=100&offset=0
2018-06-29 07:11:01.291  INFO --- [pool-3-thread-1] org.nzbhydra.indexers.Newznab            : [Search: 702337, IP: 2601:989:4100:2a9:7cbe:5e6c:6fcf:a7cf] nzbplanet: Successfully executed search call in 1537ms with 99 results
2018-06-29 07:11:04.746 ERROR --- [pool-3-thread-3] org.nzbhydra.indexers.Newznab            : [Search: 702337, IP: 2601:989:4100:2a9:7cbe:5e6c:6fcf:a7cf] FastNZB: fastnzb.com: Try again
2018-06-29 07:11:04.746 ERROR --- [pool-3-thread-2] org.nzbhydra.indexers.Newznab            : [Search: 702337, IP: 2601:989:4100:2a9:7cbe:5e6c:6fcf:a7cf] NZBGeek: api.nzbgeek.info: Try again
2018-06-29 07:11:04.746 ERROR --- [pool-3-thread-4] org.nzbhydra.indexers.Newznab            : [Search: 702337, IP: 2601:989:4100:2a9:7cbe:5e6c:6fcf:a7cf] Drunken Slug: api.drunkenslug.com: Try again
2018-06-29 07:11:04.747  WARN --- [pool-3-thread-2] org.nzbhydra.indexers.Newznab            : [Search: 702337, IP: 2601:989:4100:2a9:7cbe:5e6c:6fcf:a7cf] Because an error occurred NZBGeek will be temporarily disabled until 2018-06-29T07:26:04.747Z. This is error number 1 in a row
2018-06-29 07:11:04.747  WARN --- [pool-3-thread-4] org.nzbhydra.indexers.Newznab            : [Search: 702337, IP: 2601:989:4100:2a9:7cbe:5e6c:6fcf:a7cf] Because an error occurred Drunken Slug will be temporarily disabled until 2018-06-29T07:26:04.747Z. This is error number 1 in a row
2018-06-29 07:11:04.747  WARN --- [pool-3-thread-3] org.nzbhydra.indexers.Newznab            : [Search: 702337, IP: 2601:989:4100:2a9:7cbe:5e6c:6fcf:a7cf] Because an error occurred FastNZB will be temporarily disabled until 2018-06-29T07:26:04.747Z. This is error number 1 in a row
2018-06-29 07:11:05.033  INFO --- [pool-8-thread-1] org.nzbhydra.indexers.Newznab            : [Search: 702337, IP: 2601:989:4100:2a9:7cbe:5e6c:6fcf:a7cf] nzbplanet: Calling https://nzbplanet.net/api?apikey=<apikey>&t=search&extended=1&q=uhd&limit=100&offset=100
2018-06-29 07:11:06.365  INFO --- [pool-8-thread-1] org.nzbhydra.indexers.Newznab            : [Search: 702337, IP: 2601:989:4100:2a9:7cbe:5e6c:6fcf:a7cf] nzbplanet: Successfully executed search call in 1311ms with 100 results
2018-06-29 07:11:06.496  INFO --- [0.0-5076-exec-2] org.nzbhydra.searching.Searcher          : [Search: 702337, IP: 2601:989:4100:2a9:7cbe:5e6c:6fcf:a7cf] Returning results 1-199 from 199 results in cache. A total of 805 results is available from indexers of which 0 were already rejected
2018-06-29 07:11:06.531  INFO --- [0.0-5076-exec-2] org.nzbhydra.searching.SearchWeb         : [Search: 702337, IP: 2601:989:4100:2a9:7cbe:5e6c:6fcf:a7cf] Search took 6987ms

**Comment by slamanna212** [comment]
From inside the docker container I can resolve hostnames and ping the servers , so i dont think its a networking issue: 

root@7451ec749687:/$ ping google.com
PING google.com (172.217.6.174): 56 data bytes
64 bytes from 172.217.6.174: seq=0 ttl=54 time=11.051 ms
64 bytes from 172.217.6.174: seq=1 ttl=54 time=11.001 ms
^X^C
--- google.com ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 11.001/11.026/11.051 ms
root@7451ec749687:/$ ping api.drunkenslug.com
PING api.drunkenslug.com (104.24.15.4): 56 data bytes
64 bytes from 104.24.15.4: seq=0 ttl=59 time=0.524 ms
64 bytes from 104.24.15.4: seq=1 ttl=59 time=0.479 ms
64 bytes from 104.24.15.4: seq=2 ttl=59 time=0.468 ms
64 bytes from 104.24.15.4: seq=3 ttl=59 time=0.459 ms
64 bytes from 104.24.15.4: seq=4 ttl=59 time=0.503 ms
^X^C
--- api.drunkenslug.com ping statistics ---
5 packets transmitted, 5 packets received, 0% packet loss
round-trip min/avg/max = 0.459/0.486/0.524 ms
root@7451ec749687:/$

**Comment by theotherp** [comment]
Please try increasing the XMX value in the config. Restart and try again.
