### ISSUE TITLE
hydra2 - docker - java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by gareth-c** [theotherp/nzbhydra2#209]
No special tasks, just automated search's after 3 days cause this. I increased memory to 192MB but doesnt seem to have been the issue. Any recommendations ?

2018-07-02 14:56:19.674 ERROR --- [     HydraTask2] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.

java.lang.OutOfMemoryError: Java heap space

**Comment by theotherp** [comment]
Increasing the xmx value is the only solution. Try 256. I'll likely change
the default value to that anyway.

**Comment by gareth-c** [comment]
I'll make the change and test it out will report back in a few days.

**Comment by DominicMe** [comment]
I am having exact same issue, will see if 256 setting will solve this. There was however another report that even 1024 did not solve the issue.

Is there any reason why this error cannot be caught and the app killed? This would eliminate confusion of the app running but not reachable via web ui. More importantly it should allow systemd to restart automatically making it 99% more reliable. As it stands I cannot use it at all since it fails after an hour or so regardless if it is used or not.

**Comment by DominicMe** [comment]
@theotherp 

I am having exact same issue, will see if 256 setting will solve this. There was however another report that even 1024 did not solve the issue.

Is there any reason why this error cannot be caught and the app killed? This would eliminate confusion of the app running but not reachable via web ui. More importantly it should allow systemd to restart automatically making it 99% more reliable. As it stands I cannot use it at all since it fails after an hour or so regardless if it is used or not.

**Comment by theotherp** [comment]
I'll see if I can find a way.

By the way, I can't think of a scenario where 1024 MB would not be enough.

**Comment by DominicMe** [comment]
@theotherp If there are memory leaks then no amount may be enough. The reason why that might be likely is that it happens without active use. This is unless there is a reason for memory usage to go up to a certain limit (above 128) even without active use.

**Comment by theotherp** [comment]
I've never found any indication for memory leaks. Not saying there are none
but I haven't found any so there's nothing I can do. I have two instances
of hydra running with about a dozen indexers each with 256 MB and no
issues, ever.

Not sure what you consider "no active use". The base memory usage is
unfortunately quite high, especially with a huge database. I've tried
reducing it many times and in almost all cases 256 mb is enough and in the
others 512 suffice.

Not sure where you've seen the report about 1gb not being enough. Without
any hard data, e.g. the debug infos zip I can't really do much.

**Comment by DominicMe** [comment]
@theotherp Hopefully there are none and it's just background tasks using up memory over time up to a finite limit. By active use I just meant no UI or API access, indexers were not disables so maybe it ran checks etc... Also what exactly makes a huge database? Is it the number of indexers, searches or...?

There was another git issue and one user commented that 1024 didn't resolve the issue. Not really much of a report I supposes. Will test 256 for a few of days and report back.

**Comment by brickstool** [comment]
@theotherp I am also getting this issue. I am running Hydra2 in a docker container, using the Linuxserver.io image (Linuxserver.io version:- 82). Not much of a software guy, but I believe this is the relevant part of the log:

	java.lang.OutOfMemoryError: GC overhead limit exceeded


	Dumping heap to /config/logs/java_pid227.hprof ...


	Heap dump file created [160496889 bytes in 1.220 secs]


	Exception in thread "http-nio-0.0.0.0-5076-Acceptor-0" Exception in thread "MVStore background writer nio:/config/database/nzbhydra.mv.db" java.lang.OutOfMemoryError: GC overhead limit exceeded

	at org.h2.value.ValueLong.get(ValueLong.java:213)

	at org.h2.mvstore.db.ValueDataType.readValue(ValueDataType.java:472)

	at org.h2.mvstore.db.ValueDataType.readValue(ValueDataType.java:572)

	at org.h2.mvstore.db.ValueDataType.read(ValueDataType.java:173)

	at org.h2.mvstore.db.ValueDataType.read(ValueDataType.java:160)

	at org.h2.mvstore.Page.read(Page.java:708)

	at org.h2.mvstore.Page.read(Page.java:195)

	at org.h2.mvstore.MVStore.readPage(MVStore.java:1952)

	at org.h2.mvstore.MVMap.readPage(MVMap.java:741)

	at org.h2.mvstore.Page.getChildPage(Page.java:217)

	at org.h2.mvstore.MVMap.rewrite(MVMap.java:828)

	at org.h2.mvstore.MVMap.rewrite(MVMap.java:828)

	at org.h2.mvstore.MVMap.rewrite(MVMap.java:828)

	at org.h2.mvstore.MVMap.rewrite(MVMap.java:828)

	at org.h2.mvstore.MVMap.rewrite(MVMap.java:787)

	at org.h2.mvstore.MVStore.compactRewrite(MVStore.java:1918)

	at org.h2.mvstore.MVStore.compact(MVStore.java:1810)

	at org.h2.mvstore.MVStore.writeInBackground(MVStore.java:2512)

	at org.h2.mvstore.MVStore$BackgroundWriterThread.run(MVStore.java:2720)


	java.lang.OutOfMemoryError: GC overhead limit exceeded

	at java.net.InetAddress.<init>(InetAddress.java:308)

	at java.net.Inet4Address.<init>(Inet4Address.java:102)

	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)

	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)

	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)

	at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:455)

	at java.lang.Thread.run(Thread.java:748)


	2018-08-11 21:07:35.588 ERROR --- [     HydraTask1] o.n.downloading.downloaders.Downloader   : Error while trying to update download statuses


	java.lang.OutOfMemoryError: GC overhead limit exceeded

	at java.lang.String.substring(String.java:1969)

	at sun.security.x509.X509AttributeName.<init>(X509AttributeName.java:53)

	at sun.security.x509.X509CertInfo.get(X509CertInfo.java:535)

	at sun.security.x509.X509CertImpl.getSubjectX500Principal(X509CertImpl.java:909)

	at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:102)

	at sun.security.validator.Validator.getInstance(Validator.java:179)

	at sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:312)

	at sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:171)

	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:184)

	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)

	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1596)

	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)

	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052)

	at sun.security.ssl.Handshaker.process_record(Handshaker.java:987)

	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)`

**Comment by theotherp** [comment]
@brickstool Please post the debug infos zip. Also in your data or log file
should be a big dump file. Zip that and upload it somewhere and post the
link. Also please give some info about your history. How many entries do
you have in your search and download history?

**Comment by DominicMe** [comment]
I can confirm that 256 heap size seems to work so far, no crashes since yesterday.

**Comment by brickstool** [comment]
@theotherp Attached is a zip with log files from two separate days where Hydra2 crashed. Found towards the end of the two text files.

Regarding history, as of right now I have 8,364 searches and and 642 downloads in my history. I use 6 indexers also.

Like @DominicMe I have also set my heap size to 256 as of roughly 7 hours ago and so far haven't had any issues or crashes. 

[hydralogs.zip](https://github.com/theotherp/nzbhydra2/files/2280868/hydralogs.zip)

**Comment by theotherp** [comment]
Considering this fixed. Seems that 256MB is the way to go although 2.0.0 and upwards might need a bit less.

**Comment by kilo-WATT** [comment]
I am having problems with the Heap Space as well...increased my memory all the way up to 1024 and still get an error. Even on a fresh install, I am getting the error. I am running inside docker on OMV.

History stats: 4 indexers; 4000 searches, 1000 downloads unless I am reading the stats page wrong. 

[Debug ZIP](https://github.com/kilo-WATT/nzbhydra/raw/master/nzbhydra-debuginfos-kilowatt.zip)

**Comment by tehniemer** [comment]
I'm having this same issue in Docker on OMV. XMX is set to 512

[nzbhydra-debuginfos-2019-07-13-14-56.zip](https://github.com/theotherp/nzbhydra2/files/3389189/nzbhydra-debuginfos-2019-07-13-14-56.zip)

**Comment by snickers2k** [comment]
same here.. trying xmx 2048 now :D
