### ISSUE TITLE
/torznab API endpoint not working in Radarr

### ISSUE THREAD

**Issue by Igglybuff** [theotherp/nzbhydra2#216]
I've added a number of Jackett indexers correctly in nzbhydra2 and can search them from the web interface with no problems. When I try to add nzbhydra2 as a torznab indexer in Radarr using the `/torznab` endpoint, Radarr throws this error:
```
[Warn] Torznab: Unable to connect to indexer: The 'link' start tag on line 11 position 6 does not match the end tag of 'head'. Line 13, position 3.
```

Additionally, when I `curl` the `/torznab` endpoint I don't hit an API at all, it just dumps the web interface homepage. Same thing when I navigate to `/torznab` in a browser - I just get redirected to the nzbhydra2 search page. I don't see anything in the logs at all, and when I enable debug logs I just see this repeatedly:

```
2018-07-11 10:16:40,489 - NOTICE - nzbhydra - MainThread - Starting web app on 0.0.0.0:5075
2018-07-11 10:16:40,489 - NOTICE - nzbhydra - MainThread - Go to https://[redacted]/ for the frontend
2018-07-11 10:16:40,490 - INFO - web - MainThread - Running threaded server
2018-07-11 10:16:40,493 - ERROR - nzbhydra - MainThread - Fatal error occurred
Traceback (most recent call last):
  File "/app/hydra/nzbhydra.py", line 214, in run
    web.run(host, port, basepath)
  File "/app/hydra/nzbhydra/web.py", line 1730, in run
    app.run(host=host, port=port, debug=config.settings.main.debug, threaded=config.settings.main.runThreaded, use_reloader=config.settings.main.flaskReloader)
  File "/app/hydra/libs/flask/app.py", line 772, in run
    run_simple(host, port, self, **options)
  File "/app/hydra/libs/werkzeug/serving.py", line 625, in run_simple
    inner()
  File "/app/hydra/libs/werkzeug/serving.py", line 603, in inner
    passthrough_errors, ssl_context).serve_forever()
  File "/app/hydra/libs/werkzeug/serving.py", line 506, in make_server
    passthrough_errors, ssl_context)
  File "/app/hydra/libs/werkzeug/serving.py", line 440, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/app/hydra/libs/SocketServer.py", line 420, in __init__
    self.server_bind()
  File "/app/hydra/libs/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/app/hydra/libs/SocketServer.py", line 434, in server_bind
    self.socket.bind(self.server_address)
  File "/app/hydra/libs/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
2018-07-11 10:16:40,495 - INFO - nzbhydra - Dummy-3 - Exit registered. Stopping and closing database
2018-07-11 10:16:40,495 - INFO - nzbhydra - Dummy-3 - Database shut down
```

I'm running nzbhydra2 in docker with the linuxserver/hydra image behind an nginx reverse proxy (https://github.com/jwilder/nginx-proxy with https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion).

I'm able to use the same setup with nzbhydra2 as my newznab indexer in both Sonarr and Radarr with no problems.

nzbhydra2 version: 0.2.233
radarr version: 0.2.0.1120

**Comment by theotherp** [comment]
Please post your debug infos zip.

**Comment by Igglybuff** [comment]
[nzbhydra-debuginfo-2018-07-11-15-44.zip](https://github.com/theotherp/nzbhydra2/files/2184963/nzbhydra-debuginfo-2018-07-11-15-44.zip)

**Comment by Igglybuff** [comment]
Easy fix! Have migrated to NZBHydra2 and everything works. Thanks.

**Comment by PBXg33k** [comment]
Instead of opening a new (duplicate) issue, i thought i'd comment on this one.

I'm having a similar issue where /torznab requests are redirected to /.
My docker container is running from the linuxserver/hydra2 image.

When i check the Updates page in nzbhydra2 i get the following version strings.
```
Current version: 1.5.1 
Latest version: 1.5.1
```

[nzbhydra-debuginfos-2018-07-22-00-53.zip](https://github.com/theotherp/nzbhydra2/files/2216578/nzbhydra-debuginfos-2018-07-22-00-53.zip)

**Comment by theotherp** [comment]
@PBXg33k  Please always open a new ticket if your issue is not exactly the same as described

1) Please increase the "XMX" value in the main config to 256.

2) Are you calling "/api/torznab"? Or just "/torznab"? The former is correct.

**Comment by bdurrow** [comment]
As best I can tell the endpoint should be /torznab/api not /api/torznab.  I only mention this in case someone else finds this ticket.

**Comment by theotherp** [comment]
In the the config on the upper right there's a button that shows all the
information you need to enter hydra into sonarr and co.
