### ISSUE TITLE
Port in use under Docker and changing BaseURL

### ISSUE THREAD

**Issue by CovertDad** [theotherp/nzbhydra2#219]
I have created a container on my docker (macOS) using the linuxserver/hydra2:latest image.  When I initially set it up, it runs beautifully, migration is smooth, and I can search.

However, if I go into config and change the URLBase to "/nzbhydra", I get the following when the container attempts to start:

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 10-adduser: executing... ,
usermod: no changes,
,
-------------------------------------,
          _         (),
         | |  ___   _    __,
         | | / __| | |  /  \ ,
         | | \__ \ | | | () |,
         |_| |___/ |_|  \__/,
,
,
Brought to you by linuxserver.io,
We gratefully accept donations at:,
https://www.linuxserver.io/donations/,
-------------------------------------,
GID/UID,
-------------------------------------,
,
User uid:    911,
User gid:    911,
-------------------------------------,
,
[cont-init.d] 10-adduser: exited 0.,
[cont-init.d] 30-config: executing... ,
[cont-init.d] 30-config: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,
Logging wrapper output to /config/logs/wrapper.log,
2018-07-16 18:40:07,579  INFO - Starting NZBHydra main process with command line: java -Xmx128M -DfromWrapper -XX:TieredStopAtLevel=1 -noverify -Xloggc:/config/logs/gclog-2018-07-16_18-40-07.log -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintTenuringDistribution -XX:+PrintGCCause -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=5M -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/config/logs -Dspring.output.ansi.enabled=ALWAYS -jar /app/hydra2/lib/core-1.5.1-exec.jar --nobrowser --datafolder /config in folder /app/hydra2,
18:40:08.340 [main] DEBUG org.nzbhydra.NzbHydra - Setting property browser.disabled to value true,
.__   __.  ________  .______   __    __  ____    ____  _______  .______          ___          ___
,
|  \ |  | |       /  |   _  \ |  |  |  | \   \  /   / |       \ |   _  \        /   \        |__ \
,
|   \|  | `---/  /   |  |_)  ||  |__|  |  \   \/   /  |  .--.  ||  |_)  |      /  ^  \          ) |
,
|  . `  |    /  /    |   _  < |   __   |   \_    _/   |  |  |  ||      /      /  /_\  \        / /
,
|  |\   |   /  /----.|  |_)  ||  |  |  |     |  |     |  '--'  ||  |\  \----./  _____  \      / /_
,
|__| \__|  /________||______/ |__|  |__|     |__|     |_______/ | _| `._____/__/     \__\    |____|
,
,
2018-07-16 18:40:11.122  INFO --- [           main] org.nzbhydra.NzbHydra                    : Starting NzbHydra on 573c34049f86 with PID 218 (/app/hydra2/lib/core-1.5.1-exec.jar started by abc in /app/hydra2),
2018-07-16 18:40:11.151  INFO --- [           main] org.nzbhydra.NzbHydra                    : The following profiles are active: default,
2018-07-16 18:40:19.711  INFO --- [           main] org.nzbhydra.config.BaseConfig           : Using data folder /config,
2018-07-16 18:40:22.437  INFO --- [ost-startStop-1] o.n.a.HydraAnonymousAuthenticationFilter : Granting basic user rights to anonymous users,
2018-07-16 18:40:22.438  INFO --- [ost-startStop-1] o.n.a.HydraAnonymousAuthenticationFilter : Granting stats rights to anonymous users,
2018-07-16 18:40:22.439  INFO --- [ost-startStop-1] o.n.a.HydraAnonymousAuthenticationFilter : Granting admin rights to anonymous users,
2018-07-16 18:40:26.284  INFO --- [           main] o.f.core.internal.util.VersionPrinter    : Flyway 4.2.0 by Boxfuse,
2018-07-16 18:40:27.045  INFO --- [           main] o.f.c.i.dbsupport.DbSupportFactory       : Database: jdbc:h2:file:/config/database/nzbhydra (H2 1.4),
2018-07-16 18:40:27.299  INFO --- [           main] o.f.core.internal.command.DbValidate     : Successfully validated 14 migrations (execution time 00:00.062s),
2018-07-16 18:40:27.335  INFO --- [           main] o.f.core.internal.command.DbMigrate      : Current version of schema "PUBLIC": 1.13,
2018-07-16 18:40:27.338  INFO --- [           main] o.f.core.internal.command.DbMigrate      : Schema "PUBLIC" is up to date. No migration necessary.,
2018-07-16 18:40:32.553  WARN --- [           main] org.nzbhydra.NzbHydra                    : Overwritten settings will be displayed with their original value in the config section of the GUI,
2018-07-16 18:40:35.692  INFO --- [           main] o.n.searching.SearchModuleProvider       : Loading indexers,
2018-07-16 18:40:35.712  INFO --- [           main] o.n.searching.SearchModuleProvider       : Initializing indexer 6box,
2018-07-16 18:40:35.837  INFO --- [           main] o.n.searching.SearchModuleProvider       : Initializing indexer Binsearch,
2018-07-16 18:40:35.856  INFO --- [           main] o.n.searching.SearchModuleProvider       : Initializing indexer NZBGeek,
2018-07-16 18:40:35.863  INFO --- [           main] o.n.searching.SearchModuleProvider       : Initializing indexer NZBIndex,
2018-07-16 18:40:35.882  INFO --- [           main] o.n.searching.SearchModuleProvider       : Initializing indexer anizb,
2018-07-16 18:40:35.888  INFO --- [           main] o.n.searching.SearchModuleProvider       : Initializing indexer nzb.su,
2018-07-16 18:40:36.570  INFO --- [           main] o.n.d.downloaders.DownloaderProvider     : Loading downloaders,
2018-07-16 18:40:36.571  INFO --- [           main] o.n.d.downloaders.DownloaderProvider     : Initializing downloader SABnzbd,
2018-07-16 18:40:38.050  INFO --- [           main] org.nzbhydra.web.WebConfiguration        : Found folder /static. Will load UI resources from there,
2018-07-16 18:40:41.863  INFO --- [           main] org.nzbhydra.tasks.HydraTaskScheduler    : Scheduling task "Delete short term storage results" to be run every 12 hours,
2018-07-16 18:40:41.871  INFO --- [           main] org.nzbhydra.tasks.HydraTaskScheduler    : Scheduling task "Download queue check" to be run every 10 seconds,
2018-07-16 18:40:41.873  INFO --- [           main] org.nzbhydra.tasks.HydraTaskScheduler    : Scheduling task "Backup" to be run every 1 hour,
2018-07-16 18:40:41.875  INFO --- [           main] org.nzbhydra.tasks.HydraTaskScheduler    : Scheduling task "Clean up indexer statuses" to be run every 1 minute,
2018-07-16 18:40:41.877  INFO --- [           main] org.nzbhydra.tasks.HydraTaskScheduler    : Scheduling task "Download history check" to be run every 10 minutes,
2018-07-16 18:40:41.878  INFO --- [           main] org.nzbhydra.tasks.HydraTaskScheduler    : Scheduling task "Delete old search results" to be run every 1 hour,
2018-07-16 18:40:42.092 ERROR --- [           main] o.a.coyote.http11.Http11NioProtocol      : Failed to start end point associated with ProtocolHandler ["http-nio-192.168.1.101-5076"],
,
java.net.BindException: Address not available,
	at sun.nio.ch.Net.bind0(Native Method),
	at sun.nio.ch.Net.bind(Net.java:433),
	at sun.nio.ch.Net.bind(Net.java:425),
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223),
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74),
	at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:210),
	at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:990),
	at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:635),
	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1022),
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150),
	at org.apache.catalina.core.StandardService.addConnector(StandardService.java:225),
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.addPreviouslyRemovedConnectors(TomcatEmbeddedServletContainer.java:250),
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletContainer.java:193),
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:297),
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:145),
,
2018-07-16 18:40:42.099 ERROR --- [           main] o.apache.catalina.core.StandardService   : Failed to start connector [Connector[HTTP/1.1-5076]],
,
org.apache.catalina.LifecycleException: Failed to start component [Connector[HTTP/1.1-5076]],
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167),
	at org.apache.catalina.core.StandardService.addConnector(StandardService.java:225),
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.addPreviouslyRemovedConnectors(TomcatEmbeddedServletContainer.java:250),
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletContainer.java:193),
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:297),
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:145),
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546),
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122),
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693),
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360),
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303),
	at org.nzbhydra.NzbHydra.startup(NzbHydra.java:145),
	at org.nzbhydra.NzbHydra.main(NzbHydra.java:102),
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method),
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62),
Caused by: org.apache.catalina.LifecycleException: service.getName(): "Tomcat";  Protocol handler start failed,
	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1029),
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150),
	at org.apache.catalina.core.StandardService.addConnector(StandardService.java:225),
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.addPreviouslyRemovedConnectors(TomcatEmbeddedServletContainer.java:250),
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletContainer.java:193),
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:297),
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:145),
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546),
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122),
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693),
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360),
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303),
	at org.nzbhydra.NzbHydra.startup(NzbHydra.java:145),
	at org.nzbhydra.NzbHydra.main(NzbHydra.java:102),
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method),
Caused by: java.net.BindException: Address not available,
	at sun.nio.ch.Net.bind0(Native Method),
	at sun.nio.ch.Net.bind(Net.java:433),
	at sun.nio.ch.Net.bind(Net.java:425),
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223),
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74),
	at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:210),
	at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:990),
	at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:635),
	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1022),
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150),
	at org.apache.catalina.core.StandardService.addConnector(StandardService.java:225),
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.addPreviouslyRemovedConnectors(TomcatEmbeddedServletContainer.java:250),
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletContainer.java:193),
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:297),
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:145),
,
2018-07-16 18:40:42.217 ERROR --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : ,
,
***************************,
APPLICATION FAILED TO START,
***************************,
,
Description:,
,
The Tomcat connector configured to listen on port 5076 failed to start. The port may already be in use or the connector may be misconfigured.,
,
Action:,
,
Verify the connector's configuration, identify and stop any process that's listening on port 5076, or configure this application to listen on another port.,
,
2018-07-16 18:40:42.238  INFO --- [           main] org.nzbhydra.NzbHydra                    : Shutting down,
2018-07-16 18:40:42.804 ERROR --- [           main] org.nzbhydra.NzbHydra                    : The selected port is already in use. Either shut the other application down or select another port,
2018-07-16 18:40:42,874  ERROR - Main process shut down unexpectedly. If the wrapper was started in daemon mode you might not see the error output. Start Hydra manually with the same parameters in the same environment to see it,
Logging wrapper output to /config/logs/wrapper.log,
2018-07-16 18:40:42,997  INFO - Starting NZBHydra main process with command line: java -Xmx128M -DfromWrapper -XX:TieredStopAtLevel=1 -noverify -Xloggc:/config/logs/gclog-2018-07-16_18-40-42.log -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintTenuringDistribution -XX:+PrintGCCause -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=5M -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/config/logs -Dspring.output.ansi.enabled=ALWAYS -jar /app/hydra2/lib/core-1.5.1-exec.jar --nobrowser --datafolder /config in folder /app/hydra2,
18:40:43.893 [main] DEBUG org.nzbhydra.NzbHydra - Setting property browser.disabled to value true,`

I ultimately have to delete the container and create a new one to be able to use hydra again.

**Comment by theotherp** [comment]
Please recreate the container, startup and post the debug infos ZIP.

No idea why that would be happening.

**Comment by CovertDad** [comment]
The debug infos zip from before or after the BaseURL change?

**Comment by CovertDad** [comment]
Here is the debug.zip from the container before making the change.  I can't get the zip from after making the change, because hydra won't load.

[nzbhydra-debuginfos-2018-07-16-15-08.zip](https://github.com/theotherp/nzbhydra2/files/2199008/nzbhydra-debuginfos-2018-07-16-15-08.zip)

**Comment by theotherp** [comment]
Yeah that's why I deleted that comment after I realized you couldn't get
it...

**Comment by theotherp** [comment]
That is the only setting that causes this behavior? When you do any other setting it works fine? Do you use the internal restart mechanism after having changed the URL base? Have you tried saving, not restarting Hydra and instead restarting the container? Perhaps the restart mechanism doesn't work properly inside the container.

**Comment by CovertDad** [comment]
Yes, this is the only change I make.  I have let Hydra restart itself.  I
will try again with skipping that and restarting the container.

**Comment by CovertDad** [comment]
At this point, I think I'm just going to abandon running in Docker.

**Comment by bondesen** [comment]
I found the reason. If anyone else has the same problem here is the cause:
In hydra2 configuration (set by web interface, saved in nzbhydra2.yml) if you, by mistake set "host" parameter to your docker host IP instead of 0.0.0.0 you will get the described error. Set it back to 0.0.0.0 and everything works like a charm.

**Comment by theotherp** [comment]
Thanks for the info. I'll add a feature that warns the user if he changes the host when using docker.
