### ISSUE TITLE
Error while downloading, saving or extracting update ZIP

### ISSUE THREAD

**Issue by DominicMe** [theotherp/nzbhydra2#229]
The auto update from the UI fails for me. I ran it manually from terminal with same user as systemd uses. See log below. I did not see an option to enable debug logging in the UI nor could I find documentation on command line options. Did I miss this info?

Directory used for updates is /var/lib/nzbhydra2/ I did also run chown -R /var/lib/nzbhydra2/

` sudo -u nzbhydra /usr/lib/nzbhydra2/nzbhydra2wrapper.py --nobrowser --datafolder /var/lib/nzbhydra2`

I am not sure what "/internalapi/updates/installUpdate" is all about. I do see nzbhydra2-1.5.2-linux.zip (rw-r--r--) in /var/lib/nzbhydra2/update directory. What could be causing the zip extraction to fail? 

UI error:

```
An error occurred:
500: An error occurred while updating or getting update infos: Error while downloading, saving or extracting update ZIP

Path: /internalapi/updates/installUpdate

Message: An error occurred while updating or getting update infos: Error while downloading, saving or extracting update ZIP
```

Terminal log:
```
2018-08-11 14:23:38.069  INFO --- [           main] org.nzbhydra.NzbHydra                    : You can access NZBHydra 2 in your browser via http://192.168.0.100:5076/
2018-08-11 14:23:38.070  INFO --- [           main] org.nzbhydra.NzbHydra                    : Started NzbHydra in 17.377 seconds (JVM running for 18.236)
2018-08-11 14:24:46.552  INFO --- [0.0-5076-exec-1] org.nzbhydra.update.UpdateManager        : [IP: 192.168.0.49] Starting update process to v1.5.2
2018-08-11 14:26:08.892 ERROR --- [0.0-5076-exec-1] org.nzbhydra.update.UpdateManager        : [IP: 192.168.0.49] Error while download or saving ZIP

java.net.SocketTimeoutException: timeout
        at okio.Okio$4.newTimeoutException(Okio.java:230)
        at okio.AsyncTimeout.exit(AsyncTimeout.java:285)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
        at okio.RealBufferedSource.read(RealBufferedSource.java:46)
        at okhttp3.internal.http1.Http1Codec$FixedLengthSource.read(Http1Codec.java:384)
        at okio.RealBufferedSource.read(RealBufferedSource.java:46)
        at okio.RealBufferedSink.writeAll(RealBufferedSink.java:97)
        at org.nzbhydra.okhttp.WebAccess.downloadToFile(WebAccess.java:92)
        at org.nzbhydra.update.UpdateManager.installUpdate(UpdateManager.java:231)
        at org.nzbhydra.update.UpdatesWeb.installUpdate(UpdatesWeb.java:98)
        at org.nzbhydra.update.UpdatesWeb$$FastClassBySpringCGLIB$$ae0aa0f7.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69)
Caused by: java.net.SocketException: Socket closed
        at java.net.SocketInputStream.read(SocketInputStream.java:204)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
        at sun.security.ssl.InputRecord.readV3Record(InputRecord.java:593)
        at sun.security.ssl.InputRecord.read(InputRecord.java:532)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
        at okio.Okio$2.read(Okio.java:139)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
        at okio.RealBufferedSource.read(RealBufferedSource.java:46)
        at okhttp3.internal.http1.Http1Codec$FixedLengthSource.read(Http1Codec.java:384)
        at okio.RealBufferedSource.read(RealBufferedSource.java:46)
        at okio.RealBufferedSink.writeAll(RealBufferedSink.java:97)
        at org.nzbhydra.okhttp.WebAccess.downloadToFile(WebAccess.java:92)

2018-08-11 14:26:08.899 ERROR --- [0.0-5076-exec-1] org.nzbhydra.update.UpdatesWeb           : [IP: 192.168.0.49] An error occurred while updating or getting update infos: Error while downloading, saving or extracting update ZIP
```

wrapper.log snippet:

```
2018-07-11 20:44:55,630  CRITICAL - Unable to determine base path correctly. Please make sure to run NZBHydra in the folder where its binary is located. Current base path: /usr/lib/nzbhydra2
2018-07-11 20:48:44,537  CRITICAL - Unable to determine base path correctly. Please make sure to run NZBHydra in the folder where its binary is located. Current base path: /usr/lib/nzbhydra2
2018-07-11 20:49:11,799  CRITICAL - Unable to determine base path correctly. Please make sure to run NZBHydra in the folder where its binary is located. Current base path: /usr/lib/nzbhydra2
2018-07-11 20:49:16,979  CRITICAL - Unable to determine base path correctly. Please make sure to run NZBHydra in the folder where its binary is located. Current base path: /usr/lib/nzbhydra2
2018-07-11 20:55:18,168  CRITICAL - Unable to determine base path correctly. Please make sure to run NZBHydra in the folder where its binary is located. Current base path: /usr/lib/nzbhydra2
2018-07-11 20:59:30,987  CRITICAL - Unable to determine base path correctly. Please make sure to run NZBHydra in the folder where its binary is located. Current base path: /usr/lib/nzbhydra2
2018-07-11 21:00:16,089  CRITICAL - Error: Lib folder /usr/lib/nzbhydra2/lib not found. An update might've failed or the installation folder is corrupt
2018-07-11 21:07:05,384  CRITICAL - Error: Lib folder /usr/lib/nzbhydra2/lib not found. An update might've failed or the installation folder is corrupt
2018-07-11 21:09:14,258  CRITICAL - Error: Lib folder /usr/lib/nzbhydra2/lib not found. An update might've failed or the installation folder is corrupt
2018-07-11 21:10:08,144  CRITICAL - Error: Lib folder /usr/lib/nzbhydra2/lib not found. An update might've failed or the installation folder is corrupt
2018-07-11 21:13:05,168  CRITICAL - Error: Lib folder /usr/lib/nzbhydra2/lib not found. An update might've failed or the installation folder is corrupt
2018-07-11 21:13:05,563  CRITICAL - Error: Lib folder /usr/lib/nzbhydra2/lib not found. An update might've failed or the installation folder is corrupt
2018-07-11 21:13:05,823  CRITICAL - Error: Lib folder /usr/lib/nzbhydra2/lib not found. An update might've failed or the installation folder is corrupt
2018-07-11 21:13:06,064  CRITICAL - Error: Lib folder /usr/lib/nzbhydra2/lib not found. An update might've failed or the installation folder is corrupt
2018-07-11 21:13:06,312  CRITICAL - Error: Lib folder /usr/lib/nzbhydra2/lib not found. An update might've failed or the installation folder is corrupt
2018-07-11 21:14:31,386  CRITICAL - Error: Lib folder /usr/lib/nzbhydra2/lib not found. An update might've failed or the installation folder is corrupt
2018-07-11 21:32:59,247  CRITICAL - Error: Lib folder /usr/lib/nzbhydra2/lib not found. An update might've failed or the installation folder is corrupt
2018-07-11 21:40:11,507  CRITICAL - Error: Lib folder /usr/lib/nzbhydra2/lib not found. An update might've failed or the installation folder is corrupt
2018-07-11 21:40:40,073  CRITICAL - Error: Lib folder /usr/lib/nzbhydra2/lib not found. An update might've failed or the installation folder is corrupt
2018-07-11 22:19:14,080  INFO - No file nzbhydra.yml found. Using 128M XMX
2018-07-11 22:19:14,081  INFO - Starting NZBHydra main process with command line: java -Xmx128M -DfromWrapper -XX:TieredStopAtLevel=1 -noverify -Xloggc:/var/lib/nzbhydra2/logs/gclog-2018-07-11_22-19-14.log -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintTenuringDistribution -XX:+PrintGCCause -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=5M -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/lib/nzbhydra2/logs -Dspring.output.ansi.enabled=ALWAYS -jar /usr/lib/nzbhydra2/lib/core-1.5.1-exec.jar --nobrowser --datafolder /var/lib/nzbhydra2/ in folder /usr/lib/nzbhydra2
2018-07-11 22:19:14,088  ERROR - Unable to start process; make sure Java is installed and callable. Error message: [Errno 2] No such file or directory
2018-07-11 22:32:18,447  INFO - No file nzbhydra.yml found. Using 128M XMX
2018-07-11 22:32:18,448  INFO - Starting NZBHydra main process with command line: java -Xmx128M -DfromWrapper -XX:TieredStopAtLevel=1 -noverify -Xloggc:/var/lib/nzbhydra2/logs/gclog-2018-07-11_22-32-18.log -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintTenuringDistribution -XX:+PrintGCCause -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=5M -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/lib/nzbhydra2/logs -Dspring.output.ansi.enabled=ALWAYS -jar /usr/lib/nzbhydra2/lib/core-1.5.1-exec.jar --nobrowser --datafolder /var/lib/nzbhydra2/ in folder /usr/lib/nzbhydra2
```

I don't get why it complains about base path while still working fine or why /usr/lib/nzbhydra2/lib is not found when it does exist.

**Comment by theotherp** [comment]
That just means that the process is unable to download the zip from github
in the expected time. For some reason.

Update can also be done by just manually replacing the jar file in the lib
folder.

**Comment by DominicMe** [comment]
It must have been a different issue before as the zip file was downloaded. I tried updating again though and it worked. Not sure what the issue was before. Timeout I blame squarely on Windows update :)
