### ISSUE TITLE
checkRequiredWords NPE in search(?)

### ISSUE THREAD

**Issue by ruifung** [theotherp/nzbhydra2#232]
Somehow, using what is almost default configuration (never touched categories settings), most of my indexers errors out during search with this stack trace. I took at look at the SearchResultAcceptor and it *seems* to be trying to apply category required words but the requiredWords list is null.

[nzbhydra-debuginfos-2018-08-19-18-29.zip](https://github.com/theotherp/nzbhydra2/files/2300239/nzbhydra-debuginfos-2018-08-19-18-29.zip)

```
java.lang.NullPointerException: null
	at org.nzbhydra.searching.SearchResultAcceptor.checkRequiredWords(SearchResultAcceptor.java:267)
	at org.nzbhydra.searching.SearchResultAcceptor.acceptResults(SearchResultAcceptor.java:115)
	at org.nzbhydra.indexers.Indexer.searchInternal(Indexer.java:156)
	at org.nzbhydra.indexers.Indexer.search(Indexer.java:94)
	at org.nzbhydra.searching.Searcher.lambda$getIndexerCallable$14(Searcher.java:341)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.nzbhydra.logging.MdcThreadPoolExecutor$1.run(MdcThreadPoolExecutor.java:114)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by theotherp** [comment]
Please always post the debug infos as requested.

**Comment by ruifung** [comment]
Oh right. Done. See original post.

**Comment by theotherp** [comment]
Sorry about that.
