### ISSUE TITLE
Search returns error status 'For input string: ""'

### ISSUE THREAD

**Issue by calvinbui** [theotherp/nzbhydra2#258]
When I search nzbplanet with the term `Switch` I would get an error status saying `For input string: ""` and temporarily disable the indexer.

Searching other terms such as `Ubuntu` will return results.

```
2018-11-24 21:48:58.716  INFO --- [0.0-5076-exec-5] org.nzbhydra.searching.SearchWeb         : [Search: 871799] New search request: SearchRequest{source=INTERNAL, indexers=[nzbplanet], searchType=SEARCH, category=All, offset=0, limit=100, query=Switch, identifiers={}}
2018-11-24 21:48:58.783 DEBUG --- [0.0-5076-exec-5] o.n.searching.IndexerForSearchSelector   : [Search: 871799] Picking indexers out of 14
2018-11-24 21:48:58.784  INFO --- [0.0-5076-exec-5] o.n.searching.IndexerForSearchSelector   : [Search: 871799] Not using omgwtfnzbs because it was not selected by the user
2018-11-24 21:48:58.785  INFO --- [0.0-5076-exec-5] o.n.searching.IndexerForSearchSelector   : [Search: 871799] Not using altHUB because it was not selected by the user
2018-11-24 21:48:58.786  INFO --- [0.0-5076-exec-5] o.n.searching.IndexerForSearchSelector   : [Search: 871799] Not using NZBGeek because it was not selected by the user
2018-11-24 21:48:58.787  INFO --- [0.0-5076-exec-5] o.n.searching.IndexerForSearchSelector   : [Search: 871799] Not using NZBs.org because it was not selected by the user
2018-11-24 21:48:58.788  INFO --- [0.0-5076-exec-5] o.n.searching.IndexerForSearchSelector   : [Search: 871799] Not using Drunken Slug because it was not selected by the user
2018-11-24 21:48:58.789  INFO --- [0.0-5076-exec-5] o.n.searching.IndexerForSearchSelector   : [Search: 871799] Not using NZBCat because it was not selected by the user
2018-11-24 21:48:58.790  INFO --- [0.0-5076-exec-5] o.n.searching.IndexerForSearchSelector   : [Search: 871799] Not using anizb because it was not selected by the user
2018-11-24 21:48:58.791  INFO --- [0.0-5076-exec-5] o.n.searching.IndexerForSearchSelector   : [Search: 871799] Not using DogNZB because it was not selected by the user
2018-11-24 21:48:58.791  INFO --- [0.0-5076-exec-5] o.n.searching.IndexerForSearchSelector   : [Search: 871799] Not using SimplyNZBs because it was not selected by the user
2018-11-24 21:48:58.792  INFO --- [0.0-5076-exec-5] o.n.searching.IndexerForSearchSelector   : [Search: 871799] Not using Tabula-Rasa because it was not selected by the user
2018-11-24 21:48:58.793  INFO --- [0.0-5076-exec-5] o.n.searching.IndexerForSearchSelector   : [Search: 871799] Not using FastNZB because it was not selected by the user
2018-11-24 21:48:58.797  INFO --- [0.0-5076-exec-5] o.n.searching.IndexerForSearchSelector   : [Search: 871799] Selected 1 out of 14 indexers: nzbplanet
2018-11-24 21:48:58.811 DEBUG --- [0.0-5076-exec-5] org.nzbhydra.searching.Searcher          : [Search: 871799] Going to call 1 indexers because 0 of 100 wanted results were loaded yet
2018-11-24 21:48:58.824  INFO --- [pool-2-thread-1] org.nzbhydra.indexers.Newznab            : [Search: 871799] nzbplanet: Calling https://api.nzbplanet.net/api?apikey=<apikey>&t=search&extended=1&q=Switch&limit=100&offset=0
2018-11-24 21:49:01.158 ERROR --- [pool-2-thread-1] org.nzbhydra.indexers.Indexer            : [Search: 871799] Unexpected error while searching

java.lang.NumberFormatException: For input string: ""
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:662)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at org.nzbhydra.indexers.Newznab.lambda$parseAttributes$9(Newznab.java:429)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1492)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.nzbhydra.indexers.Newznab.parseAttributes(Newznab.java:429)
	at org.nzbhydra.indexers.Newznab.createSearchResultItem(Newznab.java:403)
	at org.nzbhydra.indexers.Newznab.getSearchResultItems(Newznab.java:337)
	at org.nzbhydra.indexers.Newznab.getSearchResultItems(Newznab.java:48)
	at org.nzbhydra.indexers.Indexer.searchInternal(Indexer.java:154)
	at org.nzbhydra.indexers.Indexer.search(Indexer.java:94)
	at org.nzbhydra.searching.Searcher.lambda$getIndexerCallable$14(Searcher.java:341)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.nzbhydra.logging.MdcThreadPoolExecutor$1.run(MdcThreadPoolExecutor.java:114)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)

2018-11-24 21:49:01.159  WARN --- [pool-2-thread-1] org.nzbhydra.indexers.Newznab            : [Search: 871799] Because an error occurred nzbplanet will be temporarily disabled until 2018-11-24T11:04:01.159553Z. This is error number 1 in a row
```

```
2018-11-24 21:49:31.092  INFO --- [0.0-5076-exec-3] org.nzbhydra.searching.SearchWeb         : [Search: 57029] New search request: SearchRequest{source=INTERNAL, indexers=[nzbplanet], searchType=SEARCH, category=All, offset=0, limit=100, query=Ubuntu, identifiers={}}
2018-11-24 21:49:31.096 DEBUG --- [0.0-5076-exec-3] o.n.searching.IndexerForSearchSelector   : [Search: 57029] Picking indexers out of 14
2018-11-24 21:49:31.096  INFO --- [0.0-5076-exec-3] o.n.searching.IndexerForSearchSelector   : [Search: 57029] Not using omgwtfnzbs because it was not selected by the user
2018-11-24 21:49:31.097  INFO --- [0.0-5076-exec-3] o.n.searching.IndexerForSearchSelector   : [Search: 57029] Not using altHUB because it was not selected by the user
2018-11-24 21:49:31.097  INFO --- [0.0-5076-exec-3] o.n.searching.IndexerForSearchSelector   : [Search: 57029] Not using NZBGeek because it was not selected by the user
2018-11-24 21:49:31.098  INFO --- [0.0-5076-exec-3] o.n.searching.IndexerForSearchSelector   : [Search: 57029] Not using NZBs.org because it was not selected by the user
2018-11-24 21:49:31.098  INFO --- [0.0-5076-exec-3] o.n.searching.IndexerForSearchSelector   : [Search: 57029] Not using Drunken Slug because it was not selected by the user
2018-11-24 21:49:31.099  INFO --- [0.0-5076-exec-3] o.n.searching.IndexerForSearchSelector   : [Search: 57029] Not using NZBCat because it was not selected by the user
2018-11-24 21:49:31.099  INFO --- [0.0-5076-exec-3] o.n.searching.IndexerForSearchSelector   : [Search: 57029] Not using anizb because it was not selected by the user
2018-11-24 21:49:31.100  INFO --- [0.0-5076-exec-3] o.n.searching.IndexerForSearchSelector   : [Search: 57029] Not using DogNZB because it was not selected by the user
2018-11-24 21:49:31.100  INFO --- [0.0-5076-exec-3] o.n.searching.IndexerForSearchSelector   : [Search: 57029] Not using SimplyNZBs because it was not selected by the user
2018-11-24 21:49:31.100  INFO --- [0.0-5076-exec-3] o.n.searching.IndexerForSearchSelector   : [Search: 57029] Not using Tabula-Rasa because it was not selected by the user
2018-11-24 21:49:31.101  INFO --- [0.0-5076-exec-3] o.n.searching.IndexerForSearchSelector   : [Search: 57029] Not using FastNZB because it was not selected by the user
2018-11-24 21:49:31.101  INFO --- [0.0-5076-exec-3] o.n.searching.IndexerForSearchSelector   : [Search: 57029] Selected 1 out of 14 indexers: nzbplanet
2018-11-24 21:49:31.102 DEBUG --- [0.0-5076-exec-3] org.nzbhydra.searching.Searcher          : [Search: 57029] Going to call 1 indexers because 0 of 100 wanted results were loaded yet
2018-11-24 21:49:31.102  INFO --- [pool-4-thread-1] org.nzbhydra.indexers.Newznab            : [Search: 57029] nzbplanet: Calling https://api.nzbplanet.net/api?apikey=<apikey>&t=search&extended=1&q=Ubuntu&limit=100&offset=0
2018-11-24 21:49:33.084  INFO --- [pool-4-thread-1] org.nzbhydra.indexers.Newznab            : [Search: 57029] nzbplanet: Successfully executed search call in 1977ms with 15 results
2018-11-24 21:49:33.136 DEBUG --- [pool-4-thread-1] org.nzbhydra.indexers.Newznab            : [Search: 57029] nzbplanet: Returning results 0-15 of 15 available (0 already rejected)
2018-11-24 21:49:33.142 DEBUG --- [0.0-5076-exec-3] org.nzbhydra.searching.Searcher          : [Search: 57029] Will load all cached results
2018-11-24 21:49:33.143  INFO --- [0.0-5076-exec-3] org.nzbhydra.searching.Searcher          : [Search: 57029] Returning results 1-15 from 15 results in cache. A total of 15 results is available from indexers of which 0 were already rejected
2018-11-24 21:49:33.154  INFO --- [0.0-5076-exec-3] org.nzbhydra.searching.SearchWeb         : [Search: 57029] Search took 2062ms
```

**Comment by theotherp** [comment]
Please post the debug infos as requested.

**Comment by calvinbui** [comment]
Can't reproduce now. The indexer may have resolved it on their end.
