### ISSUE TITLE
nzbhydra2 fails to respond to Sonarr query, gets marked as failed

### ISSUE THREAD

**Issue by Alb0t** [theotherp/nzbhydra2#269]
* What do you expect to happen? What does happen? 
When Sonarr is searching for all missing, nzbhydra2 dies. It must be re-tested in sonarr to reactivate it.

* Can the problem be reproduced? How?
100% reproducible. Search for season3 of justice league.

I do use a reverse proxy for accessing the GUI, but Sonarr bypasses it and calls http://localhost:5076/nzbhydra2 directly.

Call leading up to the exception, and the exception:
```
Dec 21 01:50:36 jim-MS-7A33 nzbhydra2[11876]: 2018-12-21 01:50:36.799  INFO --- [0.0-5076-exec-5] org.nzbhydra.api.ExternalApi             : [Search: 259944, IP: 127.0.0.1] Executing new search
Dec 21 01:50:36 jim-MS-7A33 nzbhydra2[11876]: 2018-12-21 01:50:36.800  INFO --- [0.0-5076-exec-5] o.n.searching.IndexerForSearchSelector   : [Search: 259944, IP: 127.0.0.1] Selected 2 out of 2 indexers: nzb.su, NZBGeek
Dec 21 01:50:36 jim-MS-7A33 nzbhydra2[11876]: 2018-12-21 01:50:36.801  INFO --- [ol-145-thread-2] org.nzbhydra.indexers.Newznab            : [Search: 259944, IP: 127.0.0.1] NZBGeek: Calling https://api.nzbgeek.info/api?apikey=<apikey>&t=tvsearch&extended=1&q=Chouseishin%20Series&season=1&ep=51&cat=5000,5030,5040,5045,5050,5060,5080&limit=100&offset=0
Dec 21 01:50:36 jim-MS-7A33 nzbhydra2[11876]: 2018-12-21 01:50:36.801  INFO --- [ol-145-thread-1] org.nzbhydra.indexers.Newznab            : [Search: 259944, IP: 127.0.0.1] nzb.su: Calling https://api.nzb.su/api?apikey=<apikey>&t=tvsearch&extended=1&q=Chouseishin%20Series&season=1&ep=51&cat=5000,5030,5040,5045,5050,5060,5080&limit=100&offset=0
Dec 21 01:50:37 jim-MS-7A33 nzbhydra2[11876]: 2018-12-21 01:50:37.574  INFO --- [ol-145-thread-1] org.nzbhydra.indexers.Newznab            : [Search: 259944, IP: 127.0.0.1] nzb.su: Successfully executed search call in 773ms with 0 results
Dec 21 01:50:38 jim-MS-7A33 nzbhydra2[11876]: 2018-12-21 01:50:38.350  INFO --- [ol-145-thread-2] org.nzbhydra.indexers.Newznab            : [Search: 259944, IP: 127.0.0.1] NZBGeek: Successfully executed search call in 1549ms with 0 results
Dec 21 01:50:38 jim-MS-7A33 nzbhydra2[11876]: 2018-12-21 01:50:38.352  INFO --- [0.0-5076-exec-5] org.nzbhydra.api.ExternalApi             : [Search: 259944, IP: 127.0.0.1] Search took 1552ms. Returning 0 results
Dec 21 01:50:38 jim-MS-7A33 nzbhydra2[11876]: 2018-12-21 01:50:38.798  INFO --- [0.0-5076-exec-4] org.nzbhydra.api.ExternalApi             : [Search: 375483, IP: 127.0.0.1] Received external API call: NewznabParameters{t=TVSEARCH, cat=[5080, 5050, 5060, 5045, 5040, 5030, 5000], tvRageId=4093, tvdbId=76320, tvmazeId=505, season=3, offset=0, limit=100, raw=false, o=XML, attrs=[], extended=true}
Dec 21 01:50:38 jim-MS-7A33 nzbhydra2[11876]: 2018-12-21 01:50:38.799  WARN --- [0.0-5076-exec-4] org.nzbhydra.searching.CategoryProvider  : [Search: 375483, IP: 127.0.0.1] Search supplied a general category and a subcategory: 5080,5060,5050,5045,5040,5030,5000. Will use the subcategory TV
Dec 21 01:50:38 jim-MS-7A33 nzbhydra2[11876]: 2018-12-21 01:50:38.799  INFO --- [0.0-5076-exec-4] org.nzbhydra.api.ExternalApi             : [Search: 650024, IP: 127.0.0.1] Executing new search
Dec 21 01:50:38 jim-MS-7A33 nzbhydra2[11876]: 2018-12-21 01:50:38.800 ERROR --- [0.0-5076-exec-4] org.nzbhydra.api.ExternalApi             : [Search: 650024, IP: 127.0.0.1] Unexpected error while handling API request
Dec 21 01:50:38 jim-MS-7A33 nzbhydra2[11876]: org.springframework.dao.IncorrectResultSizeDataAccessException: query did not return a unique result: 2; nested exception is javax.persistence.NonUniqueResultException: query did not return a unique result: 2
Dec 21 01:50:38 jim-MS-7A33 nzbhydra2[11876]:         at org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:378)
Dec 21 01:50:38 jim-MS-7A33 nzbhydra2[11876]:         at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:227)
Dec 21 01:50:38 jim-MS-7A33 nzbhydra2[11876]:         at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:527)
Dec 21 01:50:38 jim-MS-7A33 nzbhydra2[11876]:         at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
Dec 21 01:50:38 jim-MS-7A33 nzbhydra2[11876]:         at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242)
Dec 21 01:50:38 jim-MS-7A33 nzbhydra2[11876]:         at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:153)
Dec 21 01:50:38 jim-MS-7A33 nzbhydra2[11876]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
Dec 21 01:50:38 jim-MS-7A33 nzbhydra2[11876]:         at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:135)
Dec 21 01:50:38 jim-MS-7A33 nzbhydra2[11876]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
Dec 21 01:50:38 jim-MS-7A33 nzbhydra2[11876]:         at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
Dec 21 01:50:38 jim-MS-7A33 nzbhydra2[11876]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
Dec 21 01:50:38 jim-MS-7A33 nzbhydra2[11876]:         at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61)
Dec 21 01:50:38 jim-MS-7A33 nzbhydra2[11876]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
Dec 21 01:50:38 jim-MS-7A33 nzbhydra2[11876]:         at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
Dec 21 01:50:38 jim-MS-7A33 nzbhydra2[11876]:         at com.sun.proxy.$Proxy125.findByTvrageIdOrTvmazeIdOrTvdbId(Unknown Source)
Dec 21 01:50:38 jim-MS-7A33 nzbhydra2[11876]: Caused by: javax.persistence.NonUniqueResultException: query did not return a unique result: 2
Dec 21 01:50:38 jim-MS-7A33 nzbhydra2[11876]:         at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:123)
Dec 21 01:50:38 jim-MS-7A33 nzbhydra2[11876]:         at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:157)
Dec 21 01:50:38 jim-MS-7A33 nzbhydra2[11876]:         at org.hibernate.query.internal.AbstractProducedQuery.getSingleResult(AbstractProducedQuery.java:1471)
Dec 21 01:50:38 jim-MS-7A33 nzbhydra2[11876]:         at org.hibernate.query.criteria.internal.compile.CriteriaQueryTypeQueryAdapter.getSingleResult(CriteriaQueryTypeQueryAdapter.java:107)
Dec 21 01:50:38 jim-MS-7A33 nzbhydra2[11876]:         at sun.reflect.GeneratedMethodAccessor455.invoke(Unknown Source)
Dec 21 01:50:38 jim-MS-7A33 nzbhydra2[11876]:         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Dec 21 01:50:38 jim-MS-7A33 nzbhydra2[11876]:         at java.lang.reflect.Method.invoke(Method.java:498)
Dec 21 01:50:38 jim-MS-7A33 nzbhydra2[11876]:         at org.springframework.orm.jpa.SharedEntityManagerCreator$DeferredQueryInvocationHandler.invoke(SharedEntityManagerCreator.java:380)
Dec 21 01:50:38 jim-MS-7A33 nzbhydra2[11876]:         at com.sun.proxy.$Proxy158.getSingleResult(Unknown Source)
Dec 21 01:50:38 jim-MS-7A33 nzbhydra2[11876]:         at org.springframework.data.jpa.repository.query.JpaQueryExecution$SingleEntityExecution.doExecute(JpaQueryExecution.java:214)
Dec 21 01:50:38 jim-MS-7A33 nzbhydra2[11876]:         at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:91)
Dec 21 01:50:38 jim-MS-7A33 nzbhydra2[11876]:         at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:136)
Dec 21 01:50:38 jim-MS-7A33 nzbhydra2[11876]:         at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:125)
Dec 21 01:50:38 jim-MS-7A33 nzbhydra2[11876]:         at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:590)
Dec 21 01:50:38 jim-MS-7A33 nzbhydra2[11876]:         at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:578)
```
[nzbhydra-debuginfos-2018-12-21-01-42.zip](https://github.com/theotherp/nzbhydra2/files/2701965/nzbhydra-debuginfos-2018-12-21-01-42.zip)

**Comment by Alb0t** [comment]
I thought nzbhydra2 was crashing, but turns out it was just being marked as failed.

**Comment by Alb0t** [comment]
ok, turns out it happens when Justice League s03 gets searched.

**Comment by theotherp** [comment]
Please do the following:

1. Go to System -> Bugreport / Debug (where you got the debug infos ZIP from)
2. In the upper text area enter `select * from tvinfo` and click "Query". Upload the result from the lower text area to pastebin or something like that. The data does not contain any sensitive information (apart from what shows you like...)
3. Replace the query with `delete from tvinfo` and click "Execute".

The problem should be fixed for now and I can analyze it and hopefully fix future instances of this problem.

**Comment by Alb0t** [comment]
It looks like Sonarr freaks out when the indexer is manually added to it and the search is done too. Must be something freaky about this series.

https://pastebin.com/uYAcHSP4 (valid for 1 week)

That was a quick response, thanks. BTW I wanted to give you a shoutout for the last release, it allowed me to not have 10 different jackett indexes added to each app. I appreciate your work!

**Comment by danjames92** [comment]
also seeing this issue

https://pastebin.com/gkzms3Jf

21 rows affected

[nzbhydra-debuginfos-2018-12-27-10-20.zip](https://github.com/theotherp/nzbhydra2/files/2712169/nzbhydra-debuginfos-2018-12-27-10-20.zip)
