### ISSUE TITLE
hydra2 no longer will start after update to 2.2.5 or 2.3.0

### ISSUE THREAD

**Issue by hermy65** [theotherp/nzbhydra2#290]
This morning i noticed that hydra2 was no longer working so i restarted it and now it never actually starts. Im seeing this in the log. Hydra2 is running in a docker container on unRAID

`2019-01-27 09:39:50.146 ERROR --- [           main] org.nzbhydra.NzbHydra                    : An unexpected error occurred during startup

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.api.FlywayException: Validate failed: Detected failed migration to version 1.15 (ADD SHORT ACCESSTYPE)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1699)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:573)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:304)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1089)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:859)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:398)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:330)
	at org.nzbhydra.NzbHydra.startup(NzbHydra.java:160)
	at org.nzbhydra.NzbHydra.main(NzbHydra.java:114)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.flywaydb.core.api.FlywayException: Validate failed: Detected failed migration to version 1.15 (ADD SHORT ACCESSTYPE)
	at org.flywaydb.core.Flyway.doValidate(Flyway.java:1037)
	at org.flywaydb.core.Flyway.access$100(Flyway.java:78)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:918)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:910)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1238)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:910)
	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1758)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1695)
	... 25 common frames omitted`

**Comment by theotherp** [comment]
I'm aware and working on a solution. Sorry about that.

**Comment by hermy65** [comment]
Thanks theotherp - appreciate the quick response

**Comment by theotherp** [comment]
I just released a new version. What docker container are you running? If it's updated automatically pulling the latest version should hopefully update to the latest version which should fix this issue.

**Comment by hermy65** [comment]
im using a linuxserver container

**Comment by theotherp** [comment]
Hm, I guess that's updated automatically. You'll need to wait for 2.3.1 to appear here: https://hub.docker.com/r/linuxserver/hydra2/tags

**Comment by hermy65** [comment]
Good to go now, thanks for the quick fix!
