### ISSUE TITLE
hydra2 no longer starts after update to 2.3.1

### ISSUE THREAD

**Issue by anonvoy** [theotherp/nzbhydra2#291]
When starting nzbhydra in a terminal, I see:

```Logging wrapper output to /home/abc/.nzbhydra2/data/logs/wrapper.log
2019-01-27 17:40:49,510  INFO - Starting NZBHydra main process with command line: java -Xmx384M -DfromWrapper -XX:TieredStopAtLevel=1 -noverify -Dspring.output.ansi.enabled=ALWAYS -jar /home/abc/.nzbhydra2/lib/core-2.3.1-exec.jar --datafolder /home/abc/.nzbhydra2/data in folder /home/abc/.nzbhydra2
17:40:50.531 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Ignored because not a concrete top-level class: URL [jar:file:/home/abc/.nzbhydra2/lib/core-2.3.1-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep.class]
17:40:50.535 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/home/abc/.nzbhydra2/lib/core-2.3.1-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep003to004.class]
17:40:50.535 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/home/abc/.nzbhydra2/lib/core-2.3.1-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep004to005.class]
17:40:50.536 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/home/abc/.nzbhydra2/lib/core-2.3.1-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep005to006.class]
17:40:50.799 [main] DEBUG org.nzbhydra.config.ConfigReaderWriter - Using temporary file /home/abc/.nzbhydra2/data/nzbhydra.yml.bak
17:40:50.808 [main] DEBUG org.nzbhydra.config.ConfigReaderWriter - Copying temporary file to /home/abc/.nzbhydra2/data/nzbhydra.yml
.__   __.  ________  .______   __    __  ____    ____  _______  .______          ___          ___
|  \ |  | |       /  |   _  \ |  |  |  | \   \  /   / |       \ |   _  \        /   \        |__ \
|   \|  | `---/  /   |  |_)  ||  |__|  |  \   \/   /  |  .--.  ||  |_)  |      /  ^  \          ) |
|  . `  |    /  /    |   _  < |   __   |   \_    _/   |  |  |  ||      /      /  /_\  \        / /
|  |\   |   /  /----.|  |_)  ||  |  |  |     |  |     |  '--'  ||  |\  \----./  _____  \      / /_
|__| \__|  /________||______/ |__|  |__|     |__|     |_______/ | _| `._____/__/     \__\    |____|

2019-01-27 17:40:51.682  INFO --- [           main] org.nzbhydra.NzbHydra                    : Starting NzbHydra on Linux with PID 10503 (/home/abc/.nzbhydra2/lib/core-2.3.1-exec.jar started by abc in /home/abc/.nzbhydra2)
2019-01-27 17:40:51.691  INFO --- [           main] org.nzbhydra.NzbHydra                    : The following profiles are active: default
2019-01-27 17:40:53.315  INFO --- [           main] org.nzbhydra.config.BaseConfig           : Using data folder /home/abc/.nzbhydra2/data
2019-01-27 17:40:54.373  INFO --- [           main] o.n.a.HydraAnonymousAuthenticationFilter : Granting basic user rights to anonymous users
2019-01-27 17:40:54.374  INFO --- [           main] o.n.a.HydraAnonymousAuthenticationFilter : Granting stats rights to anonymous users
2019-01-27 17:40:54.375  INFO --- [           main] o.n.a.HydraAnonymousAuthenticationFilter : Granting admin rights to anonymous users
2019-01-27 17:40:54.538  INFO --- [           main] o.f.c.internal.license.VersionPrinter    : Flyway Community Edition 5.2.4 by Boxfuse
2019-01-27 17:40:54.541  INFO --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2019-01-27 17:40:54.729  INFO --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2019-01-27 17:40:54.733  INFO --- [           main] o.f.c.internal.database.DatabaseFactory  : Database: jdbc:h2:file:/home/abc/.nzbhydra2/data/database/nzbhydra (H2 1.4)
2019-01-27 17:40:54.838  INFO --- [           main] org.nzbhydra.database.FlywayMigration    : Found failed database migration. Attempting repair
2019-01-27 17:40:54.860  INFO --- [           main] o.f.c.i.s.JdbcTableSchemaHistory         : Repair of failed migration in Schema History table "PUBLIC"."schema_version" not necessary. No failed migration detected.
2019-01-27 17:40:54.873  INFO --- [           main] o.f.core.internal.command.DbRepair       : Successfully repaired schema history table "PUBLIC"."schema_version" (execution time 00:00.027s).
2019-01-27 17:40:54.895  WARN --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.api.FlywayException: Validate failed: Detected applied migration not resolved locally: 1.15
2019-01-27 17:40:54.896  INFO --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2019-01-27 17:41:04.901  INFO --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2019-01-27 17:41:04.937 ERROR --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.api.FlywayException: Validate failed: Detected applied migration not resolved locally: 1.15
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1745)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:576)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:307)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1083)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:853)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
Caused by: org.flywaydb.core.api.FlywayException: Validate failed: Detected applied migration not resolved locally: 1.15
        at org.flywaydb.core.Flyway.doValidate(Flyway.java:1482)
        at org.flywaydb.core.Flyway.access$100(Flyway.java:85)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:1364)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:1356)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1711)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:1356)
        at org.nzbhydra.database.FlywayMigration$1.migrate(FlywayMigration.java:44)
        at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:63)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1804)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1741)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:576)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)

2019-01-27 17:41:04.940 ERROR --- [           main] org.nzbhydra.NzbHydra                    : The existing database was created by a newer version of the program than the one you're running. Make sure to get the latest release. 
2019-01-27 17:41:18,237  ERROR - Main process shut down unexpectedly. If the wrapper was started in daemon mode you might not see the error output. Start Hydra manually with the same parameters in the same environment to see it
```

Hydra still worked after the update to 2.3.0.

**Comment by anonvoy** [comment]
Correction: The last version I used before the update to 2.3.1 was 2.2.5.

**Comment by theotherp** [comment]
So some people hat problems with 2.2.5 for which 2.3.1 provides a fix and for some people 2.2.5 worked and 2.3.1 doesn't work. What the fuck.

**Comment by theotherp** [comment]
Replace the jar in your "lib" folder with the one from this archive: https://github.com/theotherp/nzbhydra2/releases/download/v2.3.2/nzbhydra2-2.3.2-linux.zip

**Comment by theotherp** [comment]
I'll leave this open for others

**Comment by TRaSH-** [comment]
Darn i'm using a dockers(linuxserver/hydra2),
an it just got updated to this version that broke it.
it's now in a continuous loop.
Anything i can do to get it working again ?

**Comment by TRaSH-** [comment]
if you use docker compose
```  
hydra2:
    image: linuxserver/hydra2:v2.2.5-ls2
```
this worked for me

**Comment by blackhawkpr** [comment]
> Darn i'm using a dockers(linuxserver/hydra2),
> an it just got updated to this version that broke it.
> it's now in a continuous loop.
> Anything i can do to get it working again ?

Latest image (v2.3.2-ls2) is working for me.

**Comment by TRaSH-** [comment]
it got just updated,
thnx will give it a try in  a few

**Comment by DrSeussFreak** [comment]
Thanks, this solved my issue :)

**Comment by Toucan-Sam** [comment]
Just throwing my hat in the ring. Also getting this error on 2.3.2.

```2019-01-28 12:04:08.135  INFO --- [           main] org.nzbhydra.NzbHydra                    : Starting NzbHydra on media with PID 14245 (/opt/nzbhydra/lib/core-2.3.1-exec.jar started by root in /opt/nzbhydra)
2019-01-28 12:04:08.156  INFO --- [           main] org.nzbhydra.NzbHydra                    : The following profiles are active: default
2019-01-28 12:04:10.626  INFO --- [           main] org.nzbhydra.config.BaseConfig           : Using data folder /opt/nzbhydra/data
2019-01-28 12:04:10.702  INFO --- [           main] a.HydraGlobalMethodSecurityConfiguration : Enabling auth type FORM
2019-01-28 12:04:11.828  INFO --- [           main] o.f.c.internal.license.VersionPrinter    : Flyway Community Edition 5.2.4 by Boxfuse
2019-01-28 12:04:11.832  INFO --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2019-01-28 12:04:12.041  INFO --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2019-01-28 12:04:12.058  INFO --- [           main] o.f.c.internal.database.DatabaseFactory  : Database: jdbc:h2:file:/opt/nzbhydra/data/database/nzbhydra (H2 1.4)
2019-01-28 12:04:12.215  INFO --- [           main] org.nzbhydra.database.FlywayMigration    : Found failed database migration. Attempting repair
2019-01-28 12:04:12.243  INFO --- [           main] o.f.c.i.s.JdbcTableSchemaHistory         : Repair of failed migration in Schema History table "PUBLIC"."schema_version" not necessary. No failed migration detected.
2019-01-28 12:04:12.264  INFO --- [           main] o.f.core.internal.command.DbRepair       : Successfully repaired schema history table "PUBLIC"."schema_version" (execution time 00:00.037s).
2019-01-28 12:04:12.298  WARN --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.api.FlywayException: Validate failed: Detected applied migration not resolved locally: 1.15
2019-01-28 12:04:12.298  INFO --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2019-01-28 12:04:12.807  INFO --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2019-01-28 12:04:12.860 ERROR --- [           main] o.s.boot.SpringApplication               : Application run failed
ERROR --- [           main] org.nzbhydra.NzbHydra                    : The existing database was created by a newer version of the program than the one you're running. Make sure to get the latest release.```

Just loops with this message. Not urgent. Just my +1.

Thanks for all your work theotherp (deliberate no @). 😄

**Comment by theotherp** [comment]
@toucan-sam which version did you update from?

**Comment by Toucan-Sam** [comment]
@theotherp I'm not sure which version it was running before. It was auto-updating so I only noticed it wasn't working an hour or so before the above update.

```
# ./nzbhydra2 --version
19:57:12.878 [main] INFO org.nzbhydra.NzbHydra - NZBHydra 2 version: v2.3.1
```
That's what I'm running currently... which is weird because this is a download of 2.3.2 from the releases page on Github... but it appears to have not extracted the updated `core-2.3.x.jar` file. Perhaps because of the borked updates?

Either way, I've manually put the correct `core-2.3.2.jar` and it's working again. User error maybe? Thanks for your help and suggestions though!

**Comment by theotherp** [comment]
Ok, thanks. Not sure what happened but at least the latest version works.
