### ISSUE TITLE
Sonarr/Radarr/nzb360 unable to connect to nzbhydra2 suddenly

### ISSUE THREAD

**Issue by SgtBatten** [theotherp/nzbhydra2#315]
For a few days now Sonarr Radarr and NZB360 have been unable to connect to nzbhydra2.

[nzbhydra-debuginfos-2019-02-11-16-37.zip](https://github.com/theotherp/nzbhydra2/files/2849945/nzbhydra-debuginfos-2019-02-11-16-37.zip)

I have been successfully running on ubuntu 16.04 for a long time. I have manually updated to latest version (following github issue) by overwriting all the files in my /opt/nzbhydra directory.

I tried a new api key but it didn't change anything so i reverted it to avoid changing it on all my apps.

Sonarr and Radarr both throw the same 2 errors.

Invalid request Validation failed: 
 -- Unable to connect to indexer, check the log for more details

and

Unable to connect to indexer: The 'link' start tag on line 47 position 7 does not match the end tag of 'head'. Line 55, position 3.
------
System.Xml.XmlException: The 'link' start tag on line 47 position 7 does not match the end tag of 'head'. Line 55, position 3.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowTagMismatch(NodeData startTag)
   at System.Xml.XmlTextReaderImpl.ParseEndElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at NzbDrone.Core.Indexers.RssParser.LoadXmlDocument(IndexerResponse indexerResponse) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\RssParser.cs:line 112
   at NzbDrone.Core.Indexers.Newznab.NewznabRssParser.PreProcess(IndexerResponse indexerResponse) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\Newznab\NewznabRssParser.cs:line 23
   at NzbDrone.Core.Indexers.RssParser.ParseResponse(IndexerResponse indexerResponse) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\RssParser.cs:line 55
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 308
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 334

* You don't have to follow the next steps by the letter, just think about what you're trying to achieve ;-) 
* What do you expect to happen? What does happen? 
* Have you searched for this problem? You don't have to answer, just make sure.
* Can the problem be reproduced? How?
* Use a proper title. Describe the problem succinctly, don't just copy and paste the error message.
* If you use a docker container please tell me which one.

**I will close your issues if I you didn't provide proper information as described as above**

The more information you provide up front the higher the chance that I can help you.

**Comment by theotherp** [comment]
Adapt the values in this URL http://127.0.0.1:5076/api?apikey=<yourapikey>&t=tvsearch&limit=3 where needed, open it in your browser, copy the result to a text editor, remove your API key and then post it here.

**Comment by SgtBatten** [comment]
Hi mate,

[Hydra2 XML outpu.txt](https://github.com/theotherp/nzbhydra2/files/2854028/Hydra2.XML.outpu.txt)

I had to access via IP port

I tried via hydra2.domain.com but i got a 502 error. I use organizr with SSL and disabled all organizr authentication to test but it still retunred 502 with no errors in the chrome console.

**Comment by theotherp** [comment]
Looks good to me. Radarr and sonarr should accept it.

Please do the following:

- Enable trace log level in Sonarr.
- Test Hydra in Sonarr
- Send me the latest sonarr log (may be two files, one regular file, one trace file)

**Comment by SgtBatten** [comment]
Sorry to waste your time, Found an issue with my nginx conf. It was working fine earlier because hydra was running on two servers at once. when i finally shut the second one down my /api calls were being redirected to the wrong IP.

**Comment by theotherp** [comment]
Ok.
