### ISSUE TITLE
Unable to update ver 2 1.0.10 to 1.0.1.1 on linuxserver.io docker image

### ISSUE THREAD

**Issue by RXWatcher1** [theotherp/nzbhydra2#32]
full log this time:

2018-01-07 09:56:25.502 ERROR --- [0.0-5075-exec-5] org.nzbhydra.update.UpdateManager        : [IP: 173.20.227.110] Error while download or saving ZIP

java.nio.channels.ClosedByInterruptException: null
        at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
        at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:216)
        at java.nio.channels.Channels.writeFullyImpl(Channels.java:78)
        at java.nio.channels.Channels.writeFully(Channels.java:101)
        at java.nio.channels.Channels.access$000(Channels.java:61)
        at java.nio.channels.Channels$1.write(Channels.java:174)
        at java.nio.file.Files.copy(Files.java:2909)
        at java.nio.file.Files.copy(Files.java:3027)
        at org.nzbhydra.okhttp.WebAccess.downloadToFile(WebAccess.java:92)
        at org.nzbhydra.update.UpdateManager.installUpdate(UpdateManager.java:219)
        at org.nzbhydra.update.UpdatesWeb.installUpdate(UpdatesWeb.java:88)
        at org.nzbhydra.update.UpdatesWeb$$FastClassBySpringCGLIB$$ae0aa0f7.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)

09:56:25.830 [main] DEBUG org.nzbhydra.NzbHydra - Setting property server.port to value 5075
09:56:25.834 [main] DEBUG org.nzbhydra.NzbHydra - Setting property browser.disabled to value true
.__   __.  ________  .______   __    __  ____    ____  _______  .______          ___          ___
|  \ |  | |       /  |   _  \ |  |  |  | \   \  /   / |       \ |   _  \        /   \        |__ \
|   \|  | `---/  /   |  |_)  ||  |__|  |  \   \/   /  |  .--.  ||  |_)  |      /  ^  \          ) |
|  . `  |    /  /    |   _  < |   __   |   \_    _/   |  |  |  ||      /      /  /_\  \        / /
|  |\   |   /  /----.|  |_)  ||  |  |  |     |  |     |  '--'  ||  |\  \----./  _____  \      / /_
|__| \__|  /________||______/ |__|  |__|     |__|     |_______/ | _| `._____/__/     \__\    |____|

2018-01-07 09:56:26.991  INFO --- [           main] org.nzbhydra.NzbHydra                    : Starting NzbHydra on 9e5aa06f7d72 with PID 322 (/app/hydra2/lib/core-exec.jar started by abc in /app/hydra2)
2018-01-07 09:56:27.000  INFO --- [           main] org.nzbhydra.NzbHydra                    : The following profiles are active: default
2018-01-07 09:56:29.640  INFO --- [           main] org.nzbhydra.config.BaseConfig           : Using data folder /config
2018-01-07 09:56:29.759  INFO --- [           main] a.HydraGlobalMethodSecurityConfiguration : Enabling auth type FORM
2018-01-07 09:56:32.979  INFO --- [           main] o.f.core.internal.util.VersionPrinter    : Flyway 4.2.0 by Boxfuse
2018-01-07 09:56:33.102  INFO --- [           main] o.f.c.i.dbsupport.DbSupportFactory       : Database: jdbc:h2:file:/config/database/nzbhydra (H2 1.4)
2018-01-07 09:56:33.170  INFO --- [           main] o.f.core.internal.command.DbValidate     : Successfully validated 9 migrations (execution time 00:00.016s)
2018-01-07 09:56:33.180  INFO --- [           main] o.f.core.internal.command.DbMigrate      : Current version of schema "PUBLIC": 1.8
2018-01-07 09:56:33.180  INFO --- [           main] o.f.core.internal.command.DbMigrate      : Schema "PUBLIC" is up to date. No migration necessary.
2018-01-07 09:56:35.074  WARN --- [           main] org.nzbhydra.NzbHydra                    : Overwritten settings will be displayed with their original value in the config section of the GUI
2018-01-07 09:56:36.065  INFO --- [           main] o.n.searching.SearchModuleProvider       : Loading indexers
2018-01-07 09:56:36.072  INFO --- [           main] o.n.searching.SearchModuleProvider       : Initializing indexer 6box
2018-01-07 09:56:36.125  INFO --- [           main] o.n.searching.SearchModuleProvider       : Initializing indexer Binsearch
2018-01-07 09:56:36.128  INFO --- [           main] o.n.searching.SearchModuleProvider       : Initializing indexer DogNZB
2018-01-07 09:56:36.130  INFO --- [           main] o.n.searching.SearchModuleProvider       : Initializing indexer Drunken Slug
2018-01-07 09:56:36.132  INFO --- [           main] o.n.searching.SearchModuleProvider       : Initializing indexer NZB Finder
2018-01-07 09:56:36.134  INFO --- [           main] o.n.searching.SearchModuleProvider       : Initializing indexer NZBCat
2018-01-07 09:56:36.143  INFO --- [           main] o.n.searching.SearchModuleProvider       : Initializing indexer NZBGeek
2018-01-07 09:56:36.150  INFO --- [           main] o.n.searching.SearchModuleProvider       : Initializing indexer NZBIndex
2018-01-07 09:56:36.152  INFO --- [           main] o.n.searching.SearchModuleProvider       : Initializing indexer altHUB
2018-01-07 09:56:36.160  INFO --- [           main] o.n.searching.SearchModuleProvider       : Initializing indexer anizb
2018-01-07 09:56:36.162  INFO --- [           main] o.n.searching.SearchModuleProvider       : Initializing indexer nzb.su
2018-01-07 09:56:36.163  INFO --- [           main] o.n.searching.SearchModuleProvider       : Initializing indexer omgwtfnzbs
2018-01-07 09:56:36.308  INFO --- [           main] o.n.downloading.DownloaderProvider       : Loading downloaders
2018-01-07 09:56:36.308  INFO --- [           main] o.n.downloading.DownloaderProvider       : Initializing downloader NZBGet
2018-01-07 09:56:38.324  INFO --- [           main] org.nzbhydra.config.BaseConfig           : Using base host 172.18.0.19
2018-01-07 09:56:38.324  INFO --- [           main] org.nzbhydra.NzbHydra                    : You can access NZBHydra 2 in your browser via http://172.18.0.19:5075
2018-01-07 09:56:38.325  INFO --- [           main] org.nzbhydra.NzbHydra                    : Started NzbHydra in 12.359 seconds (JVM running for 12.784)
2018-01-07 09:58:15.603  WARN --- [0.0-5075-exec-1] org.nzbhydra.web.ErrorHandler            : [IP: 5.189.142.136] Unexpected error when client tried to access path /.git/config

org.springframework.security.access.AccessDeniedException: Access is denied
        at org.springframework.security.access.vote.AffirmativeBased.decide(AffirmativeBased.java:84)
        at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:233)
        at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:65)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
        at org.nzbhydra.web.MainWeb$$EnhancerBySpringCGLIB$$274e5254.index(<generated>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)

System remains on 1.0.10.

I'm not sure this is a linuxserver.io issue or a hydra2 issue.

**Comment by theotherp** [comment]
I guess (hope) theirs. I'm not at home at can't test it right now.

Am 07.01.2018 17:01 schrieb "RXWatcher" <notifications@github.com>:

**Comment by enilfodne** [comment]
Not sure if related, but i also experienced issues with the upgrade to `1.0.11`. Tried updating multiple times from the UI, but it seems the download zip was partial/corrupted and the update process cannot finish.

**Comment by theotherp** [comment]
I've updated the code to download the file for the next version. Obviously your instances will not be affected.

**Comment by fryfrog** [comment]
Generally you shouldn't update the things *inside* a docker. You should update the docker and restart, gaining you the update from the source. This is the "docker way".

**Comment by theotherp** [comment]
That means that the update could not be run via the web frontend, right? You would need to stop the container, update it and run it again?

**Comment by fryfrog** [comment]
Yeah, and as a user you can actually update the container *first* and if you ran it the right way (with `docker run --rm` you can literally just restart and it'll kick in.

No worries at all, Docker is weird and I would *totally* let others handle it. It isn't worth doing yourself and I wouldn't either, there are a bunch of people out there making good ones and they'll surely pick up nzbhyra2 like they've already got nzbhydra. :)

**Comment by RXWatcher1** [comment]
moving on. I assume this is a linux server.io issue.
