### ISSUE TITLE
Temporarily disabled by system For input string: "04/08". Unexpected error while searching

### ISSUE THREAD

**Issue by adrianhalid** [theotherp/nzbhydra2#350]
When searching for TV Episodes the code doesn't not handle parse episode information with unexpected characters.

EDIT: This issue was introduced in V2.4.0 with the feature to Group Results by Season and Episode instead of title. Shows that air daily like Vice use the format of mm/dd in the episode field.
It would be a good idea if this new feature could be configured centrally.
The only work around I currently see is to roll back to V2.3.22.

When performing search the result returns an item with the value "04/08" in the newznab:attr name="episode" node.

For example:

```
        <item>
            <title>Panorama.2019.04.08.Can.We.Trust.Huawei.1080p.HEVC.x265-MeGusta-Obfuscated</title>
            <guid isPermaLink="true">https://api.nzbgeek.info/details/85a3ea0dd3c79a344bd98c19079fea4c</guid>
            <link>https://api.nzbgeek.info/api?t=get&amp;id=85a3ea0dd3c79a344bd98c19079fea4c&amp;apikey=xxxxxxxxxxxxxxxxx</link>
            <comments>https://nzbgeek.info/geekseek.php?guid=85a3ea0dd3c79a344bd98c19079fea4c</comments>
            <pubDate>Wed, 10 Apr 2019 00:01:35 +0000</pubDate>
            <category>TV > HD</category>
            <description>Panorama.2019.04.08.Can.We.Trust.Huawei.1080p.HEVC.x265-MeGusta-Obfuscated</description>
            <enclosure url="https://api.nzbgeek.info/api?t=get&amp;id=85a3ea0dd3c79a344bd98c19079fea4c&amp;apikey=xxxxxxxxxxxxxxxxx" length="525956000" type="application/x-nzb"/>
            <newznab:attr name="category" value="5000"/>
            <newznab:attr name="category" value="5040"/>
            <newznab:attr name="size" value="525956000"/>
            <newznab:attr name="guid" value="85a3ea0dd3c79a344bd98c19079fea4c"/>
            <newznab:attr name="tvdbid" value="80748"/>
            <newznab:attr name="season" value="2019"/>
            <newznab:attr name="episode" value="04/08"/>
            <newznab:attr name="tvairdate" value="2019-02-11T00:00:00Z"/>
            <newznab:attr name="usenetdate" value="Tue, 09 Apr 2019 23:59:22 +0000"/>
        </item>
```

If you look at the stack trace you can see that line 527 is the issue.

```
java.lang.NumberFormatException: For input string: "04/08"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.valueOf(Unknown Source)
	at org.nzbhydra.indexers.Newznab.parseAttributes(Newznab.java:527)
	at org.nzbhydra.indexers.Newznab.createSearchResultItem(Newznab.java:432)
	at org.nzbhydra.indexers.Newznab.getSearchResultItems(Newznab.java:366)
	at org.nzbhydra.indexers.Newznab.getSearchResultItems(Newznab.java:48)
	at org.nzbhydra.indexers.Indexer.searchInternal(Indexer.java:154)
	at org.nzbhydra.indexers.Indexer.search(Indexer.java:94)
	at org.nzbhydra.searching.Searcher.lambda$getIndexerCallable$14(Searcher.java:341)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at org.nzbhydra.logging.MdcThreadPoolExecutor$1.run(MdcThreadPoolExecutor.java:114)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

 `searchResultItem.getAttributes().put("episode", String.valueOf(Integer.valueOf(searchResultItem.getAttributes().get("episode").replaceAll("[eE]", ""))));
        `
It is trying to convert "04/08" to an integer which then fails and falls over thus causing the indexer to be disabled.

You either want to catch and ignore such exceptions for episodes and remove them from the results.

Maybe something like this.

```
            if (searchResultItem.getAttributes().containsKey("episode")) {
                String tempEpisode = searchResultItem.getAttributes().get("episode").replaceAll("[eE]", "");
                if(tempEpisode.matches("[0-9]+")) {
                        searchResultItem.getAttributes().put("episode", String.valueOf(Integer.valueOf(tempEpisode)));
                }
            }
```

Be aware that shows that air daily may use the format of mm/dd.
So you may want to take that into consideration when making the fix.

**Comment by theotherp** [comment]
Ah yes, I forgot about dailies...

**Comment by adrianhalid** [comment]
Thanks.
That has fixed the disabling of trackers.
But now I get a popup error on the search screen

![image](https://user-images.githubusercontent.com/12272329/55850244-ebc09680-5b96-11e9-86a0-ea77545a7872.png)
