### ISSUE TITLE
Wont launch on server 2019v1809 core installation

### ISSUE THREAD

**Issue by SystemOfSilence** [theotherp/nzbhydra2#398]
java.lang.UnsatisfiedLinkError: C:\Program Files\AdoptOpenJDK\jdk-11.0.3.7-hotspot\bin\awt.dll: Can't find dependent libraries

It appears that nzbhydra2 is trying to create a tray icon even if launching the "console" version. Java can't load the class because the native assemblies don't exist in core mode.  The wrapper hangs after the java exception until issued a ctrl+c or system kill signal. A workaround is to install the windows app compatibility feature on demand. This is not ideal, is it possible to build the console version of the app with all GUI components disable/removed?

The last few lines of the log file mentioning access denied are irrelevant as far as I can tell. I have tried running with admin permissions interactively, as the system and as a standard user. 

Logging wrapper output to D:\UsenetIndex-Data\logs\wrapper.log
2019-05-19 19:14:19,836  INFO - No file nzbhydra.yml found. Using 256M XMX
2019-05-19 19:14:20,579  INFO - Determined java version as '11' from version string 'openjdk version "11.0.3" 2019-04-16'
2019-05-19 19:14:20,579  INFO - Starting NZBHydra main process with command line: java -Xmx256M -DfromWrapper -XX:TieredStopAtLevel=1 -noverify -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=D:\UsenetIndex-Data\logs -Xlog:gc*:file=..\UsenetIndex-Data\logs\gclog-2019-05-19_19-14-20.log::filecount=10,filesize=5000 -jar D:\UsenetIndex\lib\core-2.6.9-exec.jar --datafolder D:\UsenetIndex-Data in folder D:\UsenetIndex
19:14:21.156 [main] INFO org.nzbhydra.config.ConfigReaderWriter - No config file found at D:\UsenetIndex-Data\nzbhydra.yml. Initializing with base config

19:14:21.171 [main] DEBUG org.nzbhydra.config.ConfigReaderWriter - Copying YAML to D:\UsenetIndex-Data\nzbhydra.yml

19:14:21.437 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/D:/UsenetIndex/lib/core-2.6.9-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep006to007.class]

19:14:21.437 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Ignored because not a concrete top-level class: URL [jar:file:/D:/UsenetIndex/lib/core-2.6.9-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep.class]

19:14:21.437 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/D:/UsenetIndex/lib/core-2.6.9-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep007to008.class]

19:14:21.437 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/D:/UsenetIndex/lib/core-2.6.9-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep005to006.class]

19:14:21.437 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/D:/UsenetIndex/lib/core-2.6.9-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep003to004.class]

19:14:21.437 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/D:/UsenetIndex/lib/core-2.6.9-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep004to005.class]

19:14:21.453 [main] INFO org.nzbhydra.config.migration.ConfigMigration - Migrating config from version 6

19:14:21.453 [main] INFO org.nzbhydra.config.migration.ConfigMigration - Migrating config from version 7

19:14:21.656 [main] DEBUG org.nzbhydra.config.ConfigReaderWriter - Using temporary file D:\UsenetIndex-Data\nzbhydra.yml.bak

19:14:21.734 [main] DEBUG org.nzbhydra.config.ConfigReaderWriter - Copying temporary file to D:\UsenetIndex-Data\nzbhydra.yml

.__   __.  ________  .______   __    __  ____    ____  _______  .______          ___          ___

|  \ |  | |       /  |   _  \ |  |  |  | \   \  /   / |       \ |   _  \        /   \        |__ \

|   \|  | `---/  /   |  |_)  ||  |__|  |  \   \/   /  |  .--.  ||  |_)  |      /  ^  \          ) |

|  . `  |    /  /    |   _  < |   __   |   \_    _/   |  |  |  ||      /      /  /_\  \        / /

|  |\   |   /  /----.|  |_)  ||  |  |  |     |  |     |  '--'  ||  |\  \----./  _____  \      / /_

|__| \__|  /________||______/ |__|  |__|     |__|     |_______/ | _| `._____/__/     \__\    |____|

2019-05-19 19:14:22.484  INFO --- [           main] org.nzbhydra.NzbHydra                    : Starting NzbHydra on content01 with PID 1572 (D:\UsenetIndex\lib\core-2.6.9-exec.jar started by CONTENT01$ in D:\UsenetIndex)

2019-05-19 19:14:22.484  INFO --- [           main] org.nzbhydra.NzbHydra                    : The following profiles are active: default

2019-05-19 19:14:24.031  INFO --- [           main] org.nzbhydra.config.BaseConfig           : Using data folder D:\UsenetIndex-Data

2019-05-19 19:14:24.781  INFO --- [           main] o.n.a.HydraAnonymousAuthenticationFilter : Granting basic user rights to anonymous users

2019-05-19 19:14:24.781  INFO --- [           main] o.n.a.HydraAnonymousAuthenticationFilter : Granting stats rights to anonymous users

2019-05-19 19:14:24.781  INFO --- [           main] o.n.a.HydraAnonymousAuthenticationFilter : Granting admin rights to anonymous users

2019-05-19 19:14:24.937  INFO --- [           main] o.f.c.internal.license.VersionPrinter    : Flyway Community Edition 5.2.4 by Boxfuse

2019-05-19 19:14:24.937  INFO --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...

2019-05-19 19:14:25.109  INFO --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.

2019-05-19 19:14:25.109  INFO --- [           main] o.f.c.internal.database.DatabaseFactory  : Database: jdbc:h2:file:D:\UsenetIndex-Data/database/nzbhydra (H2 1.4)

2019-05-19 19:14:25.140  WARN --- [           main] o.f.c.internal.database.base.Database    : Flyway upgrade recommended: H2 1.4.199 is newer than this version of Flyway and support has not been tested.

2019-05-19 19:14:25.218  INFO --- [           main] o.f.core.internal.command.DbValidate     : Successfully validated 19 migrations (execution time 00:00.056s)

2019-05-19 19:14:25.234  INFO --- [           main] o.f.c.i.s.JdbcTableSchemaHistory         : Creating Schema History table: "PUBLIC"."schema_version"

2019-05-19 19:14:25.250  INFO --- [           main] o.f.core.internal.command.DbMigrate      : Current version of schema "PUBLIC": << Empty Schema >>

2019-05-19 19:14:25.265  INFO --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "PUBLIC" to version 1.0 - INITIAL

2019-05-19 19:14:25.296  INFO --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "PUBLIC" to version 1.1 - NZBDOWNLOAD USERAGENT

2019-05-19 19:14:25.312  INFO --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "PUBLIC" to version 1.2 - DISTINGUISH USERNAME IP

2019-05-19 19:14:25.328  INFO --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "PUBLIC" to version 1.3 - DELETE OLD SEARCHRESULTS

2019-05-19 19:14:25.343  INFO --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "PUBLIC" to version 1.4 - MAKE SEARCHRESULT INDEX NON UNIQUE

2019-05-19 19:14:25.343  INFO --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "PUBLIC" to version 1.5 - MAKE SEARCH QUERY COLUMN BIGGER

2019-05-19 19:14:25.359  INFO --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "PUBLIC" to version 1.6 - ADD SEARCH RESULT TO DOWNLOADS

2019-05-19 19:14:25.375  INFO --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "PUBLIC" to version 1.7 - ADD INDEXES FOR STATS

2019-05-19 19:14:25.390  INFO --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "PUBLIC" to version 1.8 - INCREASE QUERY AND ERROR COLUMN LENGTHs

2019-05-19 19:14:25.390  INFO --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "PUBLIC" to version 1.9 - SET DELETE CASCADES

2019-05-19 19:14:25.406  INFO --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "PUBLIC" to version 1.10 - ADD INDEX FOR DOWNLOAD STATUS UPDATE QUERIES

2019-05-19 19:14:25.406  INFO --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "PUBLIC" to version 1.11 - REMOVE INDEXERSTATUSES

2019-05-19 19:14:25.421  INFO --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "PUBLIC" to version 1.12 - ADD MEDIAINFO UNIQUE

2019-05-19 19:14:25.421  INFO --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "PUBLIC" to version 1.13 - EXTEND GENERICSTORAGE DATA LENGTH

2019-05-19 19:14:25.437  INFO --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "PUBLIC" to version 1.14 - SEARCHRESULT LINK LENGTH

2019-05-19 19:14:25.437  INFO --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "PUBLIC" to version 1.17 - SHORTACCESS AGAIN

2019-05-19 19:14:25.453  INFO --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "PUBLIC" to version 1.18 - SEARCH HISTORY INDEXES

2019-05-19 19:14:25.453  INFO --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "PUBLIC" to version 1.19 - ADD TVINFO IMDB COLUMN

2019-05-19 19:14:25.453  INFO --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "PUBLIC" to version 1.20 - EMPTY TV AND MOVIE INFO

2019-05-19 19:14:25.468  INFO --- [           main] o.f.core.internal.command.DbMigrate      : Successfully applied 19 migrations to schema "PUBLIC" (execution time 00:00.234s)

2019-05-19 19:14:27.593  INFO --- [           main] org.nzbhydra.NzbHydra                    : Adding windows system tray icon

2019-05-19 19:14:27.609  WARN --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'nzbHydra': Invocation of init method failed; nested exception is java.lang.UnsatisfiedLinkError: C:\Program Files\AdoptOpenJDK\jdk-11.0.3.7-hotspot\bin\awt.dll: Can't find dependent libraries

2019-05-19 19:14:27.609  INFO --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...

2019-05-19 19:14:27.656  INFO --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.

2019-05-19 19:14:27.687 ERROR --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'nzbHydra': Invocation of init method failed; nested exception is java.lang.UnsatisfiedLinkError: C:\Program Files\AdoptOpenJDK\jdk-11.0.3.7-hotspot\bin\awt.dll: Can't find dependent libraries

	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:139)

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:419)

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1737)

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:576)

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)

	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)

	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)

	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)

	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)

	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:846)

	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:863)

	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)

	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)

	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)

	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)

Caused by: java.lang.UnsatisfiedLinkError: C:\Program Files\AdoptOpenJDK\jdk-11.0.3.7-hotspot\bin\awt.dll: Can't find dependent libraries

	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)

	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)

	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)

	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)

	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2638)

	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:829)

	at java.base/java.lang.System.loadLibrary(System.java:1867)

	at java.desktop/java.awt.Toolkit$3.run(Toolkit.java:1395)

	at java.desktop/java.awt.Toolkit$3.run(Toolkit.java:1393)

	at java.base/java.security.AccessController.doPrivileged(Native Method)

	at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1392)

	at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1425)

	at java.desktop/java.awt.TrayIcon.<clinit>(TrayIcon.java:121)

	at org.nzbhydra.NzbHydra.addTrayIconIfApplicable(NzbHydra.java:254)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

2019-05-19 19:14:27.687 ERROR --- [           main] org.nzbhydra.NzbHydra                    : An unexpected error occurred during startup

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'nzbHydra': Invocation of init method failed; nested exception is java.lang.UnsatisfiedLinkError: C:\Program Files\AdoptOpenJDK\jdk-11.0.3.7-hotspot\bin\awt.dll: Can't find dependent libraries

	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:139)

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:419)

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1737)

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:576)

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)

	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)

	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)

	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)

	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)

	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:846)

	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:863)

	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)

	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)

	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)

	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)

Caused by: java.lang.UnsatisfiedLinkError: C:\Program Files\AdoptOpenJDK\jdk-11.0.3.7-hotspot\bin\awt.dll: Can't find dependent libraries

	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)

	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)

	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)

	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)

	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2638)

	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:829)

	at java.base/java.lang.System.loadLibrary(System.java:1867)

	at java.desktop/java.awt.Toolkit$3.run(Toolkit.java:1395)

	at java.desktop/java.awt.Toolkit$3.run(Toolkit.java:1393)

	at java.base/java.security.AccessController.doPrivileged(Native Method)

	at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1392)

	at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1425)

	at java.desktop/java.awt.TrayIcon.<clinit>(TrayIcon.java:121)

	at org.nzbhydra.NzbHydra.addTrayIconIfApplicable(NzbHydra.java:254)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

Exception in thread "main" java.lang.reflect.InvocationTargetException

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.base/java.lang.reflect.Method.invoke(Method.java:566)

	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)

	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)

	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)

	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)

Caused by: java.lang.NoClassDefFoundError: Could not initialize class java.awt.Toolkit

	at java.desktop/java.awt.Component.<clinit>(Component.java:621)

	at org.nzbhydra.NzbHydra.handleException(NzbHydra.java:219)

	at org.nzbhydra.NzbHydra.startup(NzbHydra.java:163)

	at org.nzbhydra.NzbHydra.main(NzbHydra.java:115)

	... 8 more

2019-05-19 19:19:39,512  INFO - Terminated by signal 2
2019-05-19 19:19:39,512  INFO - NZBHydra2 wrapper shutdown request. Terminating main process gracefully
2019-05-19 19:19:39,512  ERROR - Unable to start process; make sure Java is installed and callable. Error message: [Error 5] Access is denied

**Comment by theotherp** [comment]
Hopefully fixed in next version.

**Comment by SystemOfSilence** [comment]
Worked great, thank you.
