### ISSUE TITLE
Indexer keeps failing in Sonarr

### ISSUE THREAD

**Issue by hollanderrr** [theotherp/nzbhydra2#407]
Since sometime now sonarr keeps marking my NZBHydra as failed. When this happens i get the following two errors in sonarr: 

First an timed out error:

```
19-6-19 10:55:07.0|Warn|HttpClient|HTTP Error - Res: [GET] http://127.0.0.1:5075/nzbhydra/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100&tvdbid=266883&rid=34166&season=5: 500.InternalServerError
results not ready, timed out. 
```

followed by an 500 internal server error: 
```
19-6-19 10:55:07.3|Warn|Newznab|NZBHydra HTTP request failed: [500:InternalServerError] [GET] at [http://127.0.0.1:5075/nzbhydra/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100&tvdbid=266883&rid=34166&season=5]
```
Everytime this happens the following error shows in the NZBHydra log: 

```
2019-06-19 11:31:24,370 - ERROR - web - Thread-89 - results not ready, timed out.
Traceback (most recent call last):
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/libs/webargs/core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/nzbhydra/web.py", line 698, in api
    searchResult = api_search(args)
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/nzbhydra/web.py", line 772, in api_search
    result = search.search(search_request)
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/nzbhydra/search.py", line 291, in search
    indexers_to_call = pick_indexers(search_request)
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/nzbhydra/search.py", line 199, in pick_indexers
    picked, reason = checkHitOrDownloadLimit(p)
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/nzbhydra/search.py", line 127, in checkHitOrDownloadLimit
    apiHits = apiHitsQuery.count()
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/libs/peewee.py", line 3077, in count
    return self.aggregate(convert=False) or 0
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/libs/peewee.py", line 3070, in aggregate
    return self._aggregate(aggregation).scalar(convert=convert)
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/libs/peewee.py", line 2842, in scalar
    row = self._execute().fetchone()
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/libs/playhouse/sqliteq.py", line 92, in fetchone
    self._wait()
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/libs/playhouse/sqliteq.py", line 51, in _wait
    raise ResultTimeout('results not ready, timed out.')
ResultTimeout: results not ready, timed out.
```

To recreate this behaviour I just have to look for more then 1 episode at a time. 

### Second Error: 
I have configured NZBHydra to make use of port 5075. But sometimes sonarr tries (and fails) to download nzb file using port 5076 instead of port 5075, generating the following error: 

``` 
Downloading nzb for episode 'Ghost.Adventures.S19E02.St.Ignatius.Hospital.720p.HEVC.x265-MeGusta' failed (http://127.0.0.1:5076/nzbhydra/getnzb/api/-3571325777775924190?apikey=(removed): Error: ConnectFailure (Connection refused): 'http://127.0.0.1:5076/nzbhydra/getnzb/api/-3571325777775924190?apikey=PUMJHG73D56GQT72U64PUE1SHP'
```

The strange this is that this only happens sometimes and I cant find a way to reproduce it myself. 

[nzbhydra-debuginfo-2019-06-19-11-49.zip](https://github.com/theotherp/nzbhydra2/files/3305515/nzbhydra-debuginfo-2019-06-19-11-49.zip)

**Comment by theotherp** [comment]
That's a log from NZBHydra v1 which I don't support anymore, sorry. I recommend to update to v2.
