### ISSUE TITLE
 java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by tehniemer** [theotherp/nzbhydra2#421]
I'm running NZBHydra2 in Docker and am getting these errors every few days, the logs show the following 

```
java.lang.OutOfMemoryError: Java heap space

Dumping heap to /config/logs/java_pid261.hprof ...

Unable to create /config/logs/java_pid261.hprof: File exists

2019-07-22 21:22:21.794 ERROR --- [alina-utility-1] org.apache.catalina.core.ContainerBase   : Exception processing background thread


java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space

	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)

	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)

	at org.apache.catalina.core.ContainerBase.threadStart(ContainerBase.java:1274)

	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessorMonitor.run(ContainerBase.java:1320)

	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)

	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)

	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)

	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)

	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)

	at java.base/java.lang.Thread.run(Thread.java:834)

Caused by: java.lang.OutOfMemoryError: Java heap space

	at java.base/java.lang.reflect.Array.newArray(Native Method)

	at java.base/java.lang.reflect.Array.newInstance(Array.java:78)

	at java.base/java.util.Arrays.copyOf(Arrays.java:3721)

	at java.base/java.util.Arrays.copyOf(Arrays.java:3689)

	at java.base/java.util.concurrent.ConcurrentHashMap$CollectionView.toArray(ConcurrentHashMap.java:4490)

	at org.apache.catalina.session.ManagerBase.findSessions(ManagerBase.java:715)

	at org.apache.catalina.session.ManagerBase.processExpires(ManagerBase.java:567)

	at org.apache.catalina.session.ManagerBase.backgroundProcess(ManagerBase.java:558)

	at org.apache.catalina.core.StandardContext.backgroundProcess(StandardContext.java:5496)

	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1351)

	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1355)

	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1355)

	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1333)

	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)

	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
```

I have XMX set to 1024.

[nzbhydra-debuginfos-2019-07-23-14-57.zip](https://github.com/theotherp/nzbhydra2/files/3423887/nzbhydra-debuginfos-2019-07-23-14-57.zip)

**Comment by theotherp** [comment]
Sorry, a bit burnt out right now. Will take a look at some point ;-)

**Comment by theotherp** [comment]
If you can find the file /config/logs/java_pid261.hprof please upload it to a host and send me the link.

**Comment by tehniemer** [comment]
Here's a link to the file in question. https://1drv.ms/u/s!AhWy4LQhzp0exip4fn4ZvP5G-0CX

**Comment by whispy** [comment]
@theotherp, I recently experienced a similar issue. I have provided a trimmed log below, cut to right before the issue starts. I would provide a referenced `java_pid` file, but my logfile doesn't mention a specific one.

Trimmed log (indexer names censored): https://www.dropbox.com/s/wscevp1hqt9gwiz/nzbhydra2.2019-07-21.log?dl=0

My XMX is set to 300. When the error occurred, I was running v2.6.2. I believe Hydra had been running for ~63 days, if that makes a difference.

I have just updated to v2.6.11.

Full debuginfos: https://www.dropbox.com/s/rgatzxfxzcp5tr6/nzbhydra-debuginfos-2019-07-25-22-22.zip?dl=0

Please let me know if I can provide more info.

**Comment by tehniemer** [comment]
Here's another crash log 

```

2019-07-28 05:36:50.096 ERROR --- [alina-utility-1] org.apache.catalina.core.ContainerBase   : Exception processing background thread


java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space

	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)

	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)

	at org.apache.catalina.core.ContainerBase.threadStart(ContainerBase.java:1274)

	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessorMonitor.run(ContainerBase.java:1320)

	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)

	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)

	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)

	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)

	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)

	at java.base/java.lang.Thread.run(Thread.java:834)

Caused by: java.lang.OutOfMemoryError: Java heap space



Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "HydraTask2"


Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "HydraTask1"


Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "HydraTask3"


Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "HydraTask6"


Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "HydraTask5"


Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Catalina-utility-1"


Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "http-nio-0.0.0.0-5076-Acceptor-0"


Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "HikariPool-1 housekeeper"

```

**Comment by tehniemer** [comment]
@theotherp any luck on figuring out the cause of this?

**Comment by theotherp** [comment]
Sorry, I'm currently a bit... burnt out and can't really motivate me to do anything on this project besides do little quick fixes and answer some questions.

@tehniemer Unfortunately the log itself is very short and seems to have been generated after a restart (which swaps the log). What's weird is that your database file is very small and the memory should be more than enough. I guess it used to be bigger and the error occurred when Hydra shut down and tried to compact the database. You may try reducing the "Database compact time" to a smaller value, like 1000. This may mean that the database file will be bigger / not reduced as much on shutdown.

@whispy You can try this: Increase your XMX to a much higher value (like 4096 or even more) and reudce the "Store results for ... *" (searching config) to 1. Restart Hydra, go to System -> Tasks and execute the tasks "Delete old history entries" and "Delete short term storage results". Check the log for errors. If it was executed fine you can reduce XMX again but keep the "Store results" value. If the task could not be executed properly either try an even higher XMX value (if possible) or you may have to delete your database file and begin anew.

I have some ideas how to reduce the memory problem (which is most likely caused by huge database files) but I'm not there yet, sorry.

**Comment by theotherp** [comment]
@tehniemer v2.6.12 *may* reduce memory usage for you.

**Comment by tehniemer** [comment]
@theotherp thanks, I'll give all those suggestions a try and report back. 

Currently Sonarr, Radarr, Lidarr, Mylar, and LazyLibrarian make calls to Hydra.

**Comment by tehniemer** [comment]
So far so good with the changes suggested.

**Comment by tehniemer** [comment]
I started getting this error again. XMX is set to 512 and Database Compact Time is set to 1000 as suggested.
