### ISSUE TITLE
NZBHydra2 hanging on 

### ISSUE THREAD

**Issue by walgarch** [theotherp/nzbhydra2#423]
Hi, I'm trying to update nzbhydra2 on my QNAP nas and I encounter this error in the logs:

```
Exception in thread "Thread-6" java.lang.NoClassDefFoundError: Could not initialize class java.awt.Toolkit
        at java.awt.TrayIcon.<clinit>(TrayIcon.java:120)
        at org.nzbhydra.update.UpdateManager.lambda$exitWithReturnCode$3(UpdateManager.java:313)
        at java.lang.Thread.run(Thread.java:748)
```

I SSH in to restart and it comes back up without the update. Any suggestions as to how to get past this issue? I find it strange that it's trying to do anything with a tray icon since I'm on QTS 4.3.6

**Comment by theotherp** [comment]
Hm, that's weird. You can just shutdown the process and replace the current lib folder with the one from https://github.com/theotherp/nzbhydra2/releases/download/v2.6.12/nzbhydra2-2.6.12-linux.zip (it's just one file, remove the old one and put in the new one).

**Comment by walgarch** [comment]
Deleted that directory and replaced it with the one in that release you linked, but unfortunately still getting the same error :(

**Comment by theotherp** [comment]
Please post your debug infos ZIP.

**Comment by walgarch** [comment]
[nzbhydra-debuginfos-2019-08-06-22-34.zip](https://github.com/theotherp/nzbhydra2/files/3472230/nzbhydra-debuginfos-2019-08-06-22-34.zip)
Sure thing!
