### ISSUE TITLE
linuxserver/hydra2 docker container failing with corrupted nzbhydra.yml?

### ISSUE THREAD

**Issue by famewolf** [theotherp/nzbhydra2#446]
I'm not sure what happened as everything was running fine....the server got rebooted and it failed to come up..gave an error about the nzbhydra.yml so I tried copying from the .bak as instructed...still fails...I deleted the whole config to start "clean"....still fails.   Kinda at a loss here.  When started "clean" it creates a 0 byte nzbhydra.yml but still says it's "corrupted".

Log shows:

	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48),
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87),
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50),
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51),
Exception in thread "main" java.lang.reflect.InvocationTargetException,
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method),
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62),
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43),
	at java.base/java.lang.reflect.Method.invoke(Method.java:566),
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48),
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87),
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50),
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51),
Caused by: java.lang.RuntimeException: Config file /config/nzbhydra.yml corrupted. If you find a ZIP in your backup folder restore it from there. Otherwise you'll have to delete the file and start over. Please contact the developer when you have it running.,
	at org.nzbhydra.config.ConfigReaderWriter.validateExistingConfig(ConfigReaderWriter.java:180),
	at org.nzbhydra.NzbHydra.initializeAndValidateAndMigrateYamlFile(NzbHydra.java:193),
	at org.nzbhydra.NzbHydra.startup(NzbHydra.java:146),
	at org.nzbhydra.NzbHydra.main(NzbHydra.java:115),
	... 8 more,
2019-10-27 02:01:13,213  ERROR - Main process shut down unexpectedly. If the wrapper was started in daemon mode you might not see the error output. Start Hydra manually with the same parameters in the same environment to see it,
Logging wrapper output to /config/logs/wrapper.log,
2019-10-27 02:01:13,674  WARNING - Didn't find XMX in YAML file, using default of 256,
2019-10-27 02:01:13,726  INFO - Determined java version as '11' from version string 'openjdk version "11.0.4" 2019-07-16',
2019-10-27 02:01:13,726  INFO - Starting NZBHydra main process with command line: java -Xmx256M -DfromWrapper -XX:TieredStopAtLevel=1 -noverify -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/config/logs -Xlog:gc*:file=../../config/logs/gclog-2019-10-27_02-01-13.log::filecount=10,filesize=5000 -Dspring.output.ansi.enabled=ALWAYS -jar /app/hydra2/lib/core-2.7.2-exec.jar --nobrowser --datafolder /config in folder /app/hydra2,
02:01:14.146 [main] WARN org.nzbhydra.config.ConfigReaderWriter - Error while reading YAML from /config/nzbhydra.yml,
02:01:14.152 [main] DEBUG org.nzbhydra.config.ConfigReaderWriter - Using temporary file /config/nzbhydra.yml.bak,
02:01:14.152 [main] ERROR org.nzbhydra.config.ConfigReaderWriter - Config file corrupted: No content to map due to end-of-input,
 at [Source: (File); line: 1, column: 1],
02:01:14.155 [main] ERROR org.nzbhydra.NzbHydra - An unexpected error occurred during startup,
java.lang.RuntimeException: Config file /config/nzbhydra.yml corrupted. If you find a ZIP in your backup folder restore it from there. Otherwise you'll have to delete the file and start over. Please contact the developer when you have it running.,
	at org.nzbhydra.config.ConfigReaderWriter.validateExistingConfig(ConfigReaderWriter.java:180),
	at org.nzbhydra.NzbHydra.initializeAndValidateAndMigrateYamlFile(NzbHydra.java:193),
	at org.nzbhydra.NzbHydra.startup(NzbHydra.java:146),
	at org.nzbhydra.NzbHydra.main(NzbHydra.java:115),
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method),
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62),
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43),
	at java.base/java.lang.reflect.Method.invoke(Method.java:566),
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48),
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87),
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50),
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51),
Exception in thread "main" java.lang.reflect.InvocationTargetException,
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method),
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62),
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43),
	at java.base/java.lang.reflect.Method.invoke(Method.java:566),
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48),
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87),
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50),
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51),
Caused by: java.lang.RuntimeException: Config file /config/nzbhydra.yml corrupted. If you find a ZIP in your backup folder restore it from there. Otherwise you'll have to delete the file and start over. Please contact the developer when you have it running.,
	at org.nzbhydra.config.ConfigReaderWriter.validateExistingConfig(ConfigReaderWriter.java:180),
	at org.nzbhydra.NzbHydra.initializeAndValidateAndMigrateYamlFile(NzbHydra.java:193),
	at org.nzbhydra.NzbHydra.startup(NzbHydra.java:146),
	at org.nzbhydra.NzbHydra.main(NzbHydra.java:115),
	... 8 more,
2019-10-27 02:01:14,214  ERROR - Main process shut down unexpectedly. If the wrapper was started in daemon mode you might not see the error output. Start Hydra manually with the same parameters in the same environment to see it,
Logging wrapper output to /config/logs/wrapper.log,
2019-10-27 02:01:14,675  WARNING - Didn't find XMX in YAML file, using default of 256,
2019-10-27 02:01:14,726  INFO - Determined java version as '11' from version string 'openjdk version "11.0.4" 2019-07-16',
2019-10-27 02:01:14,727  INFO - Starting NZBHydra main process with command line: java -Xmx256M -DfromWrapper -XX:TieredStopAtLevel=1 -noverify -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/config/logs -Xlog:gc*:file=../../config/logs/gclog-2019-10-27_02-01-14.log::filecount=10,filesize=5000 -Dspring.output.ansi.enabled=ALWAYS -jar /app/hydra2/lib/core-2.7.2-exec.jar --nobrowser --datafolder /config in folder /app/hydra2,
02:01:15.142 [main] WARN org.nzbhydra.config.ConfigReaderWriter - Error while reading YAML from /config/nzbhydra.yml,
02:01:15.149 [main] DEBUG org.nzbhydra.config.ConfigReaderWriter - Using temporary file /config/nzbhydra.yml.bak,
02:01:15.149 [main] ERROR org.nzbhydra.config.ConfigReaderWriter - Config file corrupted: No content to map due to end-of-input,
 at [Source: (File); line: 1, column: 1],
02:01:15.152 [main] ERROR org.nzbhydra.NzbHydra - An unexpected error occurred during startup,
java.lang.RuntimeException: Config file /config/nzbhydra.yml corrupted. If you find a ZIP in your backup folder restore it from there. Otherwise you'll have to delete the file and start over. Please contact the developer when you have it running.,
	at org.nzbhydra.config.ConfigReaderWriter.validateExistingConfig(ConfigReaderWriter.java:180),
	at org.nzbhydra.NzbHydra.initializeAndValidateAndMigrateYamlFile(NzbHydra.java:193),
	at org.nzbhydra.NzbHydra.startup(NzbHydra.java:146),
	at org.nzbhydra.NzbHydra.main(NzbHydra.java:115),
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method),
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62),
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43),
	at java.base/java.lang.reflect.Method.invoke(Method.java:566),
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48),
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87),
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50),
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51),
Exception in thread "main" java.lang.reflect.InvocationTargetException,
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method),
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62),
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43),
	at java.base/java.lang.reflect.Method.invoke(Method.java:566),
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48),
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87),
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50),
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51),
Caused by: java.lang.RuntimeException: Config file /config/nzbhydra.yml corrupted. If you find a ZIP in your backup folder restore it from there. Otherwise you'll have to delete the file and start over. Please contact the developer when you have it running.,
	at org.nzbhydra.config.ConfigReaderWriter.validateExistingConfig(ConfigReaderWriter.java:180),
	at org.nzbhydra.NzbHydra.initializeAndValidateAndMigrateYamlFile(NzbHydra.java:193),
	at org.nzbhydra.NzbHydra.startup(NzbHydra.java:146),
	at org.nzbhydra.NzbHydra.main(NzbHydra.java:115),
	... 8 more,
2019-10-27 02:01:15,212  ERROR - Main process shut down unexpectedly. If the wrapper was started in daemon mode you might not see the error output. Start Hydra manually with the same parameters in the same environment to see it,
Logging wrapper output to /config/logs/wrapper.log,
2019-10-27 02:01:15,676  WARNING - Didn't find XMX in YAML file, using default of 256,
2019-10-27 02:01:15,730  INFO - Determined java version as '11' from version string 'openjdk version "11.0.4" 2019-07-16',
2019-10-27 02:01:15,731  INFO - Starting NZBHydra main process with command line: java -Xmx256M -DfromWrapper -XX:TieredStopAtLevel=1 -noverify -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/config/logs -Xlog:gc*:file=../../config/logs/gclog-2019-10-27_02-01-15.log::filecount=10,filesize=5000 -Dspring.output.ansi.enabled=ALWAYS -jar /app/hydra2/lib/core-2.7.2-exec.jar --nobrowser --datafolder /config in folder /app/hydra2,

**Comment by theotherp** [comment]
Might be an issue with rights. How do you start your container? Are you sure that the config file can be not only be created but also be written?

**Comment by famewolf** [comment]
Thank you!  My nfs acl's had gotten out of sync with my regular linux/freenas ones.  Appreciate the point in the right direction!
