### ISSUE TITLE
Unable to log in after migration

### ISSUE THREAD

**Issue by vertigo235** [theotherp/nzbhydra2#47]
So, after completing migration I restart and then my login dialog comes up.

I enter my user name and password and it says login failed. 

I verified that I am entering the correct username and password that is in the yml file.

Here is the logs, but doesn't seem very helpful. 

2018-01-09 16:17:10.143  INFO --- [0.0-5076-exec-1] o.n.migration.FromPythonMigration        : [IP: 172.17.0.1] Migration completed successfully
2018-01-09 16:20:01.796  WARN --- [0.0-5076-exec-3] org.nzbhydra.web.ErrorHandler            : [IP: 172.17.0.1] Unexpected error when client tried to access path /login and parameters password=<PASSWORD>
2018-01-09 16:21:27.406  WARN --- [0.0-5076-exec-2] org.nzbhydra.web.ErrorHandler            : [IP: 172.17.0.1] Unexpected error when client tried to access path /login and parameters _csrf=83215893-8793-4665-bd6f-eab25c8b1200, username=<USERNAME>, password=<PASSWORD>
2018-01-09 16:21:47.783  WARN --- [0.0-5076-exec-3] org.nzbhydra.web.ErrorHandler            : [IP: 172.17.0.1] Unexpected error when client tried to access path /login and parameters password=<PASSWORD>
2018-01-09 16:21:53.698  WARN --- [0.0-5076-exec-5] org.nzbhydra.web.ErrorHandler            : [IP: 172.17.0.1] Unexpected error when client tried to access path /login and parameters password=<PASSWORD>

**Comment by vertigo235** [comment]
I switched to BASIC auth in the yml file and restarted, that seems to have allowed me to log in. 

So in summary, I guess FORMS auth does not work?

**Comment by theotherp** [comment]
It should.

**Comment by weirdcrap** [comment]
Is this a Docker by chance? I experienced this with binhex's Docker of hydra2 after my migration and stopping and restarting the Docker fixed it for mem

**Comment by theotherp** [comment]
I need more info for this. Open your browser console (press F12), try to login, select the POST request to /login, copy the request and response headers, remove sensitive data, post it.

**Comment by vertigo235** [comment]
I'll see if I can troubleshoot more later, I just switched to basic auth and have used that since.

**Comment by theotherp** [comment]
I had a bug in the error message handling. The next version should contain a longer message for this case.

**Comment by theotherp** [comment]
Any news on this?

**Comment by vertigo235** [comment]
I'll give it a go in a bit

**Comment by vertigo235** [comment]
So, I switched the config file back to FORM auth and now it works.

I didn't start from scratch and do a migration though. 

So I guess we can close this, nobody else seems to have had the problem either.  Thanks for the follow up.

**Comment by theotherp** [comment]
Alright, great. Thanks for the feedback

**Comment by zxvv** [comment]
Could there be some time delay that is sufficient for the migrated password to take effect?

The reason I ask is, I saw the same "Request method 'Post' not supported" after migrating successfully from nzbhydra1.  So I hit F12 to open the console, and it showed the POST errors.  However, when I reloaded the page, login succeeded, and all subsequent login attempts succeeded.

For me it seems, after waiting a minute or so after the migration finishes, login succeeds.

**Comment by tnebrs** [comment]
Hello, just popping by to comment that I faced a similar issue right after migrating from version 1 as well with form auth enabled. Updating the password manually in the configuration file to a simple alphanumeric string bypassed the problem, after which updating the password to what it was before worked as normal. 

Nothing really helpful on the logs that I recorded I'm afraid - but let me know if you'd like me to step back through them anyway!

**Comment by darkmount** [comment]
I've just battled with this issue having updated. After update checking docker logs I can see:

```
2018-12-24 11:17:31.671  WARN --- [0.0-5076-exec-3] org.nzbhydra.web.ErrorHandler : [IP: xxx.xxx.xxx.xxx] Unexpected error when client tried to access path /login and parameters password=<password> username=<username> Error message: Request method 'POST' not supported
```

So I tried changing the password and restart container. I then got:

```
2018-12-24 11:20:00.783 ERROR --- [0.0-5076-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : [IP: xxx.xxx.xxx.xxx] Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception

java.lang.IllegalArgumentException: There is no PasswordEncoder mapped for the id "null"
	at org.springframework.security.crypto.password.DelegatingPasswordEncoder$UnmappedIdPasswordEncoder.matches(DelegatingPasswordEncoder.java:238)
	at org.springframework.security.crypto.password.DelegatingPasswordEncoder.matches(DelegatingPasswordEncoder.java:198)
	at org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter$LazyPasswordEncoder.matches(WebSecurityConfigurerAdapter.java:593)
	at org.springframework.security.authentication.dao.DaoAuthenticationProvider.additionalAuthenticationChecks(DaoAuthenticationProvider.java:86)
	at org.springframework.security.authentication.dao.AbstractUserDetailsAuthenticationProvider.authenticate(AbstractUserDetailsAuthenticationProvider.java:166)
	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:174)
	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:199)
	at org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter.attemptAuthentication(UsernamePasswordAuthenticationFilter.java:94)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:124)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
```

Eventually I got in by setting `auth:"NONE"` then commenting out the users map and setting all restrictions to false. I hope some of this info can help you nail the bug.

**Comment by bcg62** [comment]
I am also seeing 

```
There is no PasswordEncoder mapped for the id "null"
```

**Comment by dalml** [comment]
I ran into this issue after a migration myself.  My solution was to change auth to none as @darkmount suggested, and then once I was in the web interface I was able to re-enable auth and re-set the password on my account.  Worked great after that.

**Comment by pcoombe** [comment]
yep same issue here, set to NONE, and then changed it back and working ok.
running the linuxserver docker image, and file migrated from v1.

**Comment by cleverestx** [comment]
Having this issue now with the latest NZBHYDRA2 - any fix?

**Comment by eb3095** [comment]
Program info
Version: 3.17.3
Container version: v3.17.3-ls34
Container release type: Release
Container author: linuxserver.io

This issue is in fact not fixed.

```
java.lang.IllegalArgumentException: There is no PasswordEncoder mapped for the id "null"
        at org.springframework.security.crypto.password.DelegatingPasswordEncoder.matches(DelegatingPasswordEncoder.java:198)
        at org.springframework.security.authentication.dao.DaoAuthenticationProvider.additionalAuthenticationChecks(DaoAuthenticationProvider.java:90)
        at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:199)
        at org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter.attemptAuthentication(UsernamePasswordAuthenticationFilter.java:95)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116) [1 skipped]
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56) [1 skipped]
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93) [8 skipped]
```

It appears that the issue is special characters. With the $, it does not work, without it does. That error might not be related as I had removed the {noop} thinking it was part of the issue. However, for certain, the issue is special symbols in passwords.

**Comment by TrueOsiris** [comment]
Still enjoyed the same issue (and solution) when pulling the docker container today.
