### ISSUE TITLE
Out Of Memory - SSL connection closure potential issue

### ISSUE THREAD

**Issue by freender** [theotherp/nzbhydra2#479]
Prerequisites:
- nzbhydra2 version: 2.10.6
- Indexers - 4 indexers for automatic API search (clients -> sonarr, radarr)
- Environment - Running in docker
- Use proxy = SOCKS
- JVM memory = 256 MB

TC:
1. Start  nzbhydra2  for a day 
2. Check console logs
docker-compose logs -f hydra2 
*Actual Result:*
 - Out of memory
```
hydra2               |[0m [2m2019-12-30 17:58:10.703[0;39m [32m INFO[0;39m [2m---[0;39m [2m[0.0-5076-exec-5][0;39m org.nzbhydra.searching.Searcher         [0;39m [2m:[0;39m[35m [Search: 784289, Host: 172.18.0.1] [0;39m[34m[0;39mReturning results 1-100 from 100 results in cache. A total of 2785360 results is available from indexers of which 0 were already rejected and 0 were removed as duplicates
hydra2               |[0m [2m2019-12-30 17:58:10.705[0;39m [32m INFO[0;39m [2m---[0;39m [2m[0.0-5076-exec-5][0;39m org.nzbhydra.api.ExternalApi            [0;39m [2m:[0;39m[35m [Search: 784289, Host: 172.18.0.1] [0;39m[34m[0;39mSearch took 3531ms. Returning 100 results
hydra2               |[0m [2m2019-12-30 18:10:19.343[0;39m [32m INFO[0;39m [2m---[0;39m [2m[0.0-5076-exec-1][0;39m org.nzbhydra.api.ExternalApi            [0;39m [2m:[0;39m[35m [Search: 840768, Host: 172.18.0.1] [0;39m[34m[0;39mReceived external newznab API call: NewznabParameters{t=MOVIE, cat=[2000, 2010, 2020, 2030, 2035, 2040, 2045, 2050, 2060], offset=0, limit=100, raw=false, o=XML, attrs=[], extended=true}
hydra2               |[0m [2m2019-12-30 18:10:19.344[0;39m [33m WARN[0;39m [2m---[0;39m [2m[0.0-5076-exec-1][0;39m org.nzbhydra.searching.CategoryProvider [0;39m [2m:[0;39m[35m [Search: 840768, Host: 172.18.0.1] [0;39m[34m[0;39mSearch supplied a general category and a subcategory: 2060,2050,2045,2040,2035,2030,2020,2010,2000. Will use the subcategory Movies
hydra2               |[0m [2m2019-12-30 18:10:19.344[0;39m [32m INFO[0;39m [2m---[0;39m [2m[0.0-5076-exec-1][0;39m org.nzbhydra.api.ExternalApi            [0;39m [2m:[0;39m[35m [Search: 840768, Host: 172.18.0.1] [0;39m[34m[0;39mExecuting new search
hydra2               |[0m [2m2019-12-30 18:10:19.411[0;39m [32m INFO[0;39m [2m---[0;39m [2m[0.0-5076-exec-1][0;39m o.n.searching.IndexerForSearchSelector  [0;39m [2m:[0;39m[35m [Search: 840768, Host: 172.18.0.1] [0;39m[34m[0;39mNot using NNM-Club because the search source is API but the indexer is only enabled for INTERNAL searches
hydra2               |[0m [2m2019-12-30 18:10:19.411[0;39m [32m INFO[0;39m [2m---[0;39m [2m[0.0-5076-exec-1][0;39m o.n.searching.IndexerForSearchSelector  [0;39m [2m:[0;39m[35m [Search: 840768, Host: 172.18.0.1] [0;39m[34m[0;39mNot using RuTracker because the search source is API but the indexer is only enabled for INTERNAL searches
hydra2               |[0m [2m2019-12-30 18:10:19.412[0;39m [32m INFO[0;39m [2m---[0;39m [2m[0.0-5076-exec-1][0;39m o.n.searching.IndexerForSearchSelector  [0;39m [2m:[0;39m[35m [Search: 840768, Host: 172.18.0.1] [0;39m[34m[0;39mNot using Drunken Slug because all 49 allowed API hits were already made. The next API hit should be possible at 2019-12-31T00:00:19.412634
hydra2               |[0m [2m2019-12-30 18:10:19.412[0;39m [32m INFO[0;39m [2m---[0;39m [2m[0.0-5076-exec-1][0;39m o.n.searching.IndexerForSearchSelector  [0;39m [2m:[0;39m[35m [Search: 840768, Host: 172.18.0.1] [0;39m[34m[0;39mSelected 4 out of 7 indexers: omgX1Xa0, NZBGeek, LuluNZB, NZBPlanet
hydra2               |[0m [2m2019-12-30 18:10:19.413[0;39m [32m INFO[0;39m [2m---[0;39m [2m[l-1084-thread-1][0;39m org.nzbhydra.indexers.Newznab           [0;39m [2m:[0;39m[35m [Search: 840768, Host: 172.18.0.1] [0;39m[34m[0;39momgX1Xa0: Calling https://api.omgX1Xa0.me/api?apikey=<apikey>&t=movie&extended=1&cat=2000&limit=100&offset=0
hydra2               |[0m [2m2019-12-30 18:10:19.413[0;39m [32m INFO[0;39m [2m---[0;39m [2m[l-1084-thread-2][0;39m org.nzbhydra.indexers.Newznab           [0;39m [2m:[0;39m[35m [Search: 840768, Host: 172.18.0.1] [0;39m[34m[0;39mNZBGeek: Calling https://api.nzbgeek.info/api?apikey=<apikey>&t=search&extended=1&cat=2000&limit=100&offset=0
hydra2               |[0m [2m2019-12-30 18:10:19.413[0;39m [32m INFO[0;39m [2m---[0;39m [2m[l-1084-thread-3][0;39m org.nzbhydra.indexers.Newznab           [0;39m [2m:[0;39m[35m [Search: 840768, Host: 172.18.0.1] [0;39m[34m[0;39mLuluNZB: Calling https://lulunzb.com/api?apikey=<apikey>&t=search&extended=1&cat=2000&limit=100&offset=0
hydra2               |[0m [2m2019-12-30 18:10:19.413[0;39m [32m INFO[0;39m [2m---[0;39m [2m[l-1084-thread-4][0;39m org.nzbhydra.indexers.Newznab           [0;39m [2m:[0;39m[35m [Search: 840768, Host: 172.18.0.1] [0;39m[34m[0;39mNZBPlanet: Calling https://nzbplanet.net/api?apikey=<apikey>&t=movie&extended=1&cat=2000&limit=100&offset=0
hydra2               |[0m [2m2019-12-30 18:10:20.459[0;39m [32m INFO[0;39m [2m---[0;39m [2m[l-1084-thread-3][0;39m org.nzbhydra.indexers.Newznab           [0;39m [2m:[0;39m[35m [Search: 840768, Host: 172.18.0.1] [0;39m[34m[0;39mLuluNZB: Successfully executed search call in 969ms with 100 results
hydra2               |[0m [2m2019-12-30 18:10:20.755[0;39m [32m INFO[0;39m [2m---[0;39m [2m[l-1084-thread-1][0;39m org.nzbhydra.indexers.Newznab           [0;39m [2m:[0;39m[35m [Search: 840768, Host: 172.18.0.1] [0;39m[34m[0;39momgX1Xa0: Successfully executed search call in 1122ms with 100 results
hydra2               |[0m [2m2019-12-30 18:10:20.911[0;39m [32m INFO[0;39m [2m---[0;39m [2m[l-1084-thread-4][0;39m org.nzbhydra.indexers.Newznab           [0;39m [2m:[0;39m[35m [Search: 840768, Host: 172.18.0.1] [0;39m[34m[0;39mNZBPlanet: Successfully executed search call in 1421ms with 99 results
hydra2               |[0m [2m2019-12-30 18:10:21.923[0;39m [32m INFO[0;39m [2m---[0;39m [2m[l-1084-thread-2][0;39m org.nzbhydra.indexers.Newznab           [0;39m [2m:[0;39m[35m [Search: 840768, Host: 172.18.0.1] [0;39m[34m[0;39mNZBGeek: Successfully executed search call in 2504ms with 100 results
hydra2               |[0m [2m2019-12-30 18:10:22.275[0;39m [32m INFO[0;39m [2m---[0;39m [2m[0.0-5076-exec-1][0;39m org.nzbhydra.searching.Searcher         [0;39m [2m:[0;39m[35m [Search: 840768, Host: 172.18.0.1] [0;39m[34m[0;39mReturning results 1-100 from 100 results in cache. A total of 463179 results is available from indexers of which 0 were already rejected and 2 were removed as duplicates
hydra2               |[0m [2m2019-12-30 18:10:22.342[0;39m [32m INFO[0;39m [2m---[0;39m [2m[0.0-5076-exec-1][0;39m org.nzbhydra.api.ExternalApi            [0;39m [2m:[0;39m[35m [Search: 840768, Host: 172.18.0.1] [0;39m[34m[0;39mSearch took 2998ms. Returning 100 results
hydra2               |[0m [2m2019-12-30 18:12:07.456[0;39m [32m INFO[0;39m [2m---[0;39m [2m[0.0-5076-exec-3][0;39m org.nzbhydra.api.ExternalApi            [0;39m [2m:[0;39m[35m [Search: 161028, Host: 172.18.0.1] [0;39m[34m[0;39mReceived external newznab API call: NewznabParameters{t=SEARCH, cat=[3000, 3010, 3020, 3030, 3040], offset=0, limit=100, raw=false, o=XML, attrs=[], extended=true}
hydra2               |[0m [2m2019-12-30 18:12:07.457[0;39m [33m WARN[0;39m [2m---[0;39m [2m[0.0-5076-exec-3][0;39m org.nzbhydra.searching.CategoryProvider [0;39m [2m:[0;39m[35m [Search: 161028, Host: 172.18.0.1] [0;39m[34m[0;39mSearch supplied a general category and a subcategory: 3040,3030,3020,3010,3000. Will use the subcategory Audio
hydra2               |[0m [2m2019-12-30 18:12:07.457[0;39m [32m INFO[0;39m [2m---[0;39m [2m[0.0-5076-exec-3][0;39m org.nzbhydra.api.ExternalApi            [0;39m [2m:[0;39m[35m [Search: 161028, Host: 172.18.0.1] [0;39m[34m[0;39mExecuting new search
hydra2               |[0m [2m2019-12-30 18:12:07.460[0;39m [32m INFO[0;39m [2m---[0;39m [2m[0.0-5076-exec-3][0;39m o.n.searching.IndexerForSearchSelector  [0;39m [2m:[0;39m[35m [Search: 161028, Host: 172.18.0.1] [0;39m[34m[0;39mNot using NNM-Club because the search source is API but the indexer is only enabled for INTERNAL searches
hydra2               |[0m [2m2019-12-30 18:12:07.460[0;39m [32m INFO[0;39m [2m---[0;39m [2m[0.0-5076-exec-3][0;39m o.n.searching.IndexerForSearchSelector  [0;39m [2m:[0;39m[35m [Search: 161028, Host: 172.18.0.1] [0;39m[34m[0;39mNot using RuTracker because the search source is API but the indexer is only enabled for INTERNAL searches
hydra2               |[0m [2m2019-12-30 18:12:07.461[0;39m [32m INFO[0;39m [2m---[0;39m [2m[0.0-5076-exec-3][0;39m o.n.searching.IndexerForSearchSelector  [0;39m [2m:[0;39m[35m [Search: 161028, Host: 172.18.0.1] [0;39m[34m[0;39mNot using Drunken Slug because all 49 allowed API hits were already made. The next API hit should be possible at 2019-12-31T00:00:07.461479
hydra2               |[0m [2m2019-12-30 18:12:07.461[0;39m [32m INFO[0;39m [2m---[0;39m [2m[0.0-5076-exec-3][0;39m o.n.searching.IndexerForSearchSelector  [0;39m [2m:[0;39m[35m [Search: 161028, Host: 172.18.0.1] [0;39m[34m[0;39mSelected 4 out of 7 indexers: omgX1Xa0, NZBGeek, LuluNZB, NZBPlanet
hydra2               |[0m [2m2019-12-30 18:12:07.528[0;39m [32m INFO[0;39m [2m---[0;39m [2m[l-1091-thread-1][0;39m org.nzbhydra.indexers.Newznab           [0;39m [2m:[0;39m[35m [Search: 161028, Host: 172.18.0.1] [0;39m[34m[0;39momgX1Xa0: Calling https://api.omgX1Xa0.me/api?apikey=<apikey>&t=search&extended=1&cat=3000&limit=100&offset=0
hydra2               |[0m [2m2019-12-30 18:12:07.528[0;39m [32m INFO[0;39m [2m---[0;39m [2m[l-1091-thread-2][0;39m org.nzbhydra.indexers.Newznab           [0;39m [2m:[0;39m[35m [Search: 161028, Host: 172.18.0.1] [0;39m[34m[0;39mNZBGeek: Calling https://api.nzbgeek.info/api?apikey=<apikey>&t=search&extended=1&cat=3000&limit=100&offset=0
hydra2               |[0m [2m2019-12-30 18:12:07.528[0;39m [32m INFO[0;39m [2m---[0;39m [2m[l-1091-thread-4][0;39m org.nzbhydra.indexers.Newznab           [0;39m [2m:[0;39m[35m [Search: 161028, Host: 172.18.0.1] [0;39m[34m[0;39mNZBPlanet: Calling https://nzbplanet.net/api?apikey=<apikey>&t=search&extended=1&cat=3000&limit=100&offset=0
hydra2               |[0m [2m2019-12-30 18:12:07.528[0;39m [32m INFO[0;39m [2m---[0;39m [2m[l-1091-thread-3][0;39m org.nzbhydra.indexers.Newznab           [0;39m [2m:[0;39m[35m [Search: 161028, Host: 172.18.0.1] [0;39m[34m[0;39mLuluNZB: Calling https://lulunzb.com/api?apikey=<apikey>&t=search&extended=1&cat=3000&limit=100&offset=0
hydra2               |[0m [2m2019-12-30 18:12:08.412[0;39m [32m INFO[0;39m [2m---[0;39m [2m[l-1091-thread-2][0;39m org.nzbhydra.indexers.Newznab           [0;39m [2m:[0;39m[35m [Search: 161028, Host: 172.18.0.1] [0;39m[34m[0;39mNZBGeek: Successfully executed search call in 816ms with 100 results
hydra2               |[0m [2m2019-12-30 18:12:09.222[0;39m [32m INFO[0;39m [2m---[0;39m [2m[l-1091-thread-1][0;39m org.nzbhydra.indexers.Newznab           [0;39m [2m:[0;39m[35m [Search: 161028, Host: 172.18.0.1] [0;39m[34m[0;39momgX1Xa0: Successfully executed search call in 1622ms with 100 results
hydra2               |[0m [2m2019-12-30 18:12:09.223[0;39m [32m INFO[0;39m [2m---[0;39m [2m[l-1091-thread-3][0;39m org.nzbhydra.indexers.Newznab           [0;39m [2m:[0;39m[35m [Search: 161028, Host: 172.18.0.1] [0;39m[34m[0;39mLuluNZB: Successfully executed search call in 1554ms with 100 results
hydra2               |[0m [2m2019-12-30 18:12:09.357[0;39m [32m INFO[0;39m [2m---[0;39m [2m[l-1091-thread-4][0;39m org.nzbhydra.indexers.Newznab           [0;39m [2m:[0;39m[35m [Search: 161028, Host: 172.18.0.1] [0;39m[34m[0;39mNZBPlanet: Successfully executed search call in 1623ms with 100 results
hydra2               |[0m [2m2019-12-30 18:12:10.543[0;39m [32m INFO[0;39m [2m---[0;39m [2m[0.0-5076-exec-3][0;39m org.nzbhydra.searching.Searcher         [0;39m [2m:[0;39m[35m [Search: 161028, Host: 172.18.0.1] [0;39m[34m[0;39mReturning results 1-100 from 100 results in cache. A total of 548102 results is available from indexers of which 0 were already rejected and 0 were removed as duplicates
hydra2               |[0m [2m2019-12-30 18:12:10.545[0;39m [32m INFO[0;39m [2m---[0;39m [2m[0.0-5076-exec-3][0;39m org.nzbhydra.api.ExternalApi            [0;39m [2m:[0;39m[35m [Search: 161028, Host: 172.18.0.1] [0;39m[34m[0;39mSearch took 3088ms. Returning 100 results
hydra2               |[0m java.lang.OutOfMemoryError: Java heap space
hydra2               |[0m Dumping heap to /config/logs/java_pid1961.hprof ...
hydra2               |[0m Heap dump file created [485147998 bytes in 1.329 secs]
hydra2               |[0m [2m2019-12-30 18:12:12.493[0;39m [31mERROR[0;39m [2m---[0;39m [2m[0.0-5076-exec-3][0;39m org.nzbhydra.api.ExternalApi            [0;39m [2m:[0;39m[35m [Search: 161028, Host: 172.18.0.1] [0;39m[34m[0;39mUnexpected error while handling API request
hydra2               |[0m 
hydra2               |[0m org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.OutOfMemoryError: Java heap space
hydra2               |[0m 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1055)
hydra2               |[0m 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
hydra2               |[0m 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
hydra2               |[0m 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
hydra2               |[0m 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
hydra2               |[0m 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
hydra2               |[0m 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
hydra2               |[0m 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
hydra2               |[0m 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
hydra2               |[0m 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
hydra2               |[0m 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
hydra2               |[0m 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
hydra2               |[0m 	at org.nzbhydra.auth.HydraAnonymousAuthenticationFilter.doFilter(HydraAnonymousAuthenticationFilter.java:98)
hydra2               |[0m 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
hydra2               |[0m 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
hydra2               |[0m Caused by: java.lang.OutOfMemoryError: Java heap space
hydra2               |[0m 	at java.base/java.util.Arrays.copyOfRange(Arrays.java:4030)
hydra2               |[0m 	at java.base/java.lang.StringCoding.decodeUTF8(StringCoding.java:710)
hydra2               |[0m 	at java.base/java.lang.StringCoding.decode(StringCoding.java:318)
hydra2               |[0m 	at java.base/java.lang.String.<init>(String.java:592)
hydra2               |[0m 	at java.base/java.io.ByteArrayOutputStream.toString(ByteArrayOutputStream.java:241)
hydra2               |[0m 	at org.nzbhydra.web.WebConfiguration$NewznabAndTorznabResponseNamespaceFixer.write(WebConfiguration.java:182)
hydra2               |[0m 	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:298)
hydra2               |[0m 	at org.springframework.web.servlet.mvc.method.annotation.HttpEntityMethodProcessor.handleReturnValue(HttpEntityMethodProcessor.java:226)
hydra2               |[0m 	at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:82)
hydra2               |[0m 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:124)
hydra2               |[0m 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888)
hydra2               |[0m 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
hydra2               |[0m 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
hydra2               |[0m 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
hydra2               |[0m 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
hydra2               |[0m 
hydra2               |[0m Exception in thread "delayedConfigSave" java.lang.OutOfMemoryError: Java heap space
hydra2               |[0m [2m2019-12-30 18:12:30.932[0;39m [31mERROR[0;39m [2m---[0;39m [2m[alina-utility-1][0;39m o.a.coyote.http11.Http11NioProtocol     [0;39m [2m:[0;39m[35m [0;39m[34m[0;39mError processing async timeouts
hydra2               |[0m 
hydra2               |[0m java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
hydra2               |[0m 	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
hydra2               |[0m 	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
hydra2               |[0m 	at org.apache.coyote.AbstractProtocol.startAsyncTimeout(AbstractProtocol.java:609)
hydra2               |[0m 	at org.apache.coyote.AbstractProtocol$1.run(AbstractProtocol.java:592)
hydra2               |[0m 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
hydra2               |[0m 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
hydra2               |[0m 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
hydra2               |[0m 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
hydra2               |[0m 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
hydra2               |[0m 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
hydra2               |[0m 	at java.base/java.lang.Thread.run(Thread.java:834)
hydra2               |[0m Caused by: java.lang.OutOfMemoryError: Java heap space
hydra2               |[0m 	at java.base/java.util.concurrent.ConcurrentHashMap$KeySetView.iterator(ConcurrentHashMap.java:4627)
hydra2               |[0m 	at java.base/java.util.Collections$SetFromMap.iterator(Collections.java:5567)
hydra2               |[0m 	at org.apache.coyote.AbstractProtocol$2.run(AbstractProtocol.java:619)
hydra2               |[0m 	... 7 common frames omitted

```
 - There are 8 exceptions with following stack trace (might be unrelated)
```
hydra2               |[0m [2m2019-12-29 14:02:43.239[0;39m [32m INFO[0;39m [2m---[0;39m [2m[0.0-5076-exec-5][0;39m org.nzbhydra.searching.Searcher         [0;39m [2m:[0;39m[35m [Search: 989437, Host: 172.18.0.1] [0;39m[34m[0;39mReturning results 1-100 from 100 results in cache. A total of 2784282 results is available from indexers of which 0 were already rejected and 1 were removed as duplicates
hydra2               |[0m [2m2019-12-29 14:02:43.244[0;39m [32m INFO[0;39m [2m---[0;39m [2m[0.0-5076-exec-5][0;39m org.nzbhydra.api.ExternalApi            [0;39m [2m:[0;39m[35m [Search: 989437, Host: 172.18.0.1] [0;39m[34m[0;39mSearch took 1274ms. Returning 100 results
hydra2               |[0m Exception in thread "OkHttp ConnectionPool" java.lang.NullPointerException
hydra2               |[0m 	at sockslib.client.SocksSocket.isInputShutdown(SocksSocket.java:402)
hydra2               |[0m 	at java.base/sun.security.ssl.BaseSSLSocketImpl.isInputShutdown(BaseSSLSocketImpl.java:247)
hydra2               |[0m 	at java.base/sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:650)
hydra2               |[0m 	at java.base/sun.security.ssl.SSLSocketImpl.bruteForceCloseInput(SSLSocketImpl.java:606)
hydra2               |[0m 	at java.base/sun.security.ssl.SSLSocketImpl.duplexCloseOutput(SSLSocketImpl.java:566)
hydra2               |[0m 	at java.base/sun.security.ssl.SSLSocketImpl.close(SSLSocketImpl.java:479)
hydra2               |[0m 	at okhttp3.internal.Util.closeQuietly(Util.java:155)
hydra2               |[0m 	at okhttp3.ConnectionPool.cleanup(ConnectionPool.java:244)
hydra2               |[0m 	at okhttp3.ConnectionPool$1.run(ConnectionPool.java:60)
hydra2               |[0m 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
hydra2               |[0m 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
hydra2               |[0m 	at java.base/java.lang.Thread.run(Thread.java:834)
```

I also checked heap dump - 
![image](https://user-images.githubusercontent.com/40869255/71612254-2cb96a80-2b6d-11ea-8339-14dd8d550a39.png)
It seems like 62% of memory is used by SSL Sessions

604 instances of "sun.security.ssl.SSLSessionContextImpl", loaded by "<system class loader>" occupy 158,681,744 (62.04%) bytes. These instances are referenced from one instance of "java.lang.Object[]", loaded by "<system class loader>"
![image](https://user-images.githubusercontent.com/40869255/71612335-c1bc6380-2b6d-11ea-9619-a66ca7694e82.png)
*Expected Result:* Please assist in heap dump analysts. Let me know how I can share link to heap dump

[1-obfuscated.zip](https://github.com/theotherp/nzbhydra2/files/4012072/1-obfuscated.zip)

**Comment by freender** [comment]
I increased heap limit to 1000 MB and it didn't help:
![image](https://user-images.githubusercontent.com/40869255/71759988-65668600-2e84-11ea-990e-2cd4a468f102.png)

I changed log level to debug - next time it fails I will provide updated logs

**Comment by theotherp** [comment]
Thanks for the analysis. Fixed in next release.

**Comment by theotherp** [comment]
The NullPointerException will be fixed in another release. I thought I'd identified all sources but missed one.
