### ISSUE TITLE
v2.10.12 BETA fails to start

### ISSUE THREAD

**Issue by hotio** [theotherp/nzbhydra2#485]
I'm getting the following error when starting the new beta.

```

12:17:30.732 [main] ERROR org.nzbhydra.NzbHydra - An unexpected error occurred during startup | 11s
-- | --
46 | java.lang.NullPointerException: null | 11s
47 | at org.nzbhydra.config.migration.ConfigMigrationStep008to009.migrate(ConfigMigrationStep008to009.java:37) | 11s
48 | at org.nzbhydra.config.migration.ConfigMigration.migrate(ConfigMigration.java:61) | 11s
49 | at org.nzbhydra.NzbHydra.initializeAndValidateAndMigrateYamlFile(NzbHydra.java:281) | 11s
50 | at org.nzbhydra.NzbHydra.startup(NzbHydra.java:151) | 11s
51 | at org.nzbhydra.NzbHydra.main(NzbHydra.java:121) | 11s
52 | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) | 11s
53 | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) | 11s
54 | at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) | 11s
55 | at java.base/java.lang.reflect.Method.invoke(Method.java:566) | 11s
56 | at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) | 11s
57 | at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) | 11s
58 | at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) | 11s
59 | at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) | 11s
60 | Exception in thread "main" java.lang.reflect.InvocationTargetException | 11s
61 | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) | 11s
62 | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) | 11s
63 | at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) | 11s
64 | at java.base/java.lang.reflect.Method.invoke(Method.java:566) | 11s
65 | at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) | 11s
66 | at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) | 11s
67 | at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) | 11s
68 | at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) | 11s
69 | Caused by: java.lang.NullPointerException | 11s
70 | at org.nzbhydra.config.migration.ConfigMigrationStep008to009.migrate(ConfigMigrationStep008to009.java:37) | 11s
71 | at org.nzbhydra.config.migration.ConfigMigration.migrate(ConfigMigration.java:61) | 11s
72 | at org.nzbhydra.NzbHydra.initializeAndValidateAndMigrateYamlFile(NzbHydra.java:281) | 11s
73 | at org.nzbhydra.NzbHydra.startup(NzbHydra.java:151) | 11s
74 | at org.nzbhydra.NzbHydra.main(NzbHydra.java:121) | 11s
75 | ... 8 more


```
[logs_hotio_docker-nzbhydra2_3_2.log](https://github.com/theotherp/nzbhydra2/files/4049317/logs_hotio_docker-nzbhydra2_3_2.log)

**Comment by theotherp** [comment]
Stupid bot. Looks like the  prereleases were a good idea...

**Comment by hotio** [comment]
yep, 2.10.13 all good again
![screenshot](https://user-images.githubusercontent.com/26902309/72206280-fee8f580-348b-11ea-9037-45015cdc1839.png)
