### ISSUE TITLE
[2.12.6] Crash on start "Error while migrating database"

### ISSUE THREAD

**Issue by reloxx13** [theotherp/nzbhydra2#496]
Heya,

after the latest auto beta update, the app crashes with:

```
2020-01-29 10:02:02.323  WARN --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is java.lang.RuntimeException: Error while migrating database
2020-01-29 10:02:02.355 ERROR --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is java.lang.RuntimeException: Error while migrating database
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1803)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1108)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.nzbhydra.NzbHydra.startup(NzbHydra.java:164)
	at org.nzbhydra.NzbHydra.main(NzbHydra.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.lang.RuntimeException: Error while migrating database
	at org.nzbhydra.database.FlywayMigration$1.migrate(FlywayMigration.java:73)
	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:62)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1862)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1799)
	... 25 common frames omitted
Caused by: org.flywaydb.core.api.FlywayException: Validate failed: 
Migration checksum mismatch for migration version 1.11
-> Applied to database : -1156306236
-> Resolved locally    : 898390205
Migration checksum mismatch for migration version 1.17
-> Applied to database : 517011709
-> Resolved locally    : 177884391

	at org.flywaydb.core.Flyway.doValidate(Flyway.java:279)
	at org.flywaydb.core.Flyway.access$100(Flyway.java:73)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:161)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:153)
	at org.flywaydb.core.Flyway.execute(Flyway.java:521)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:153)
	at org.nzbhydra.database.FlywayMigration$1.migrate(FlywayMigration.java:41)
	... 28 common frames omitted

2020-01-29 10:02:02.359 ERROR --- [           main] org.nzbhydra.NzbHydra                    : An unexpected error occurred during startup

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is java.lang.RuntimeException: Error while migrating database
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1803)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1108)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.nzbhydra.NzbHydra.startup(NzbHydra.java:164)
	at org.nzbhydra.NzbHydra.main(NzbHydra.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.lang.RuntimeException: Error while migrating database
	at org.nzbhydra.database.FlywayMigration$1.migrate(FlywayMigration.java:73)
	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:62)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1862)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1799)
	... 25 common frames omitted
Caused by: org.flywaydb.core.api.FlywayException: Validate failed: 
Migration checksum mismatch for migration version 1.11
-> Applied to database : -1156306236
-> Resolved locally    : 898390205
Migration checksum mismatch for migration version 1.17
-> Applied to database : 517011709
-> Resolved locally    : 177884391

	at org.flywaydb.core.Flyway.doValidate(Flyway.java:279)
	at org.flywaydb.core.Flyway.access$100(Flyway.java:73)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:161)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:153)
	at org.flywaydb.core.Flyway.execute(Flyway.java:521)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:153)
	at org.nzbhydra.database.FlywayMigration$1.migrate(FlywayMigration.java:41)
	... 28 common frames omitted
```

Cannot get a debug log cause the ui is not starting.

Looking in the wrapper log it says current version is:
`S:\nzbhydra2\lib\core-2.12.6-exec.jar`

Do you need more?

**Comment by reloxx13** [comment]
[nzbhydra2.log](https://github.com/theotherp/nzbhydra2/files/4127039/nzbhydra2_log.zip)

**Comment by reloxx13** [comment]
i deleted the data dir and it started up fine, now i trued to restore from an older backup (yesterday and 2 days ago) but the restore will fail with the same error.

**Comment by theotherp** [comment]
Could you please send me the database file from your latest backup so I can reproduce it?

**Comment by reloxx13** [comment]
Wo kann ich dich per PN erreichen? Discord? E-mail?

**Comment by theotherp** [comment]
Nvm, got it. Really stupid error where the build process changed some files which then ended up with different checksums than locally.

And let's stick to english so others can understand us ;-)

Generally I prefer discord over email.

**Comment by reloxx13** [comment]
I just did not want to upload my backup in public, ill wait for the next beta and test.

**Comment by reloxx13** [comment]
[nzbhydra2_logs.zip](https://github.com/theotherp/nzbhydra2/files/4127202/nzbhydra2_logs.zip)


2.12.7 did not solve the issue, Tried a few backups, none will work and also the latest installation did not start.

**Comment by theotherp** [comment]
Send me the upload link to theotherp@gmx.de

**Comment by reloxx13** [comment]
thank you! works fine now with 2.12.8 :+1:
