### ISSUE TITLE
- missing table on startup

### ISSUE THREAD

**Issue by halkeye** [theotherp/nzbhydra2#501]
I'm running `binhex/arch-nzbhydra2:2.13.3-1-01` docker image

I can't get it to startup to generate a bug report. I'm suspecting my database is corrupted, or some migration script isn't being triggered. I'm not sure which.

ls -l /config/nzbhydra2/database/nzbhydra.mv.db
-rw-rw-rw- 1 nobody users 37023744 Feb  8 04:22 /config/nzbhydra2/database/nzbhydra.mv.db

I really don't know what other logs might be helpful, the entire startup log is as followed.

```
Created by...
___.   .__       .__
\_ |__ |__| ____ |  |__   ____ ___  ___
 | __ \|  |/    \|  |  \_/ __ \\  \/  /
 | \_\ \  |   |  \   Y  \  ___/ >    <
 |___  /__|___|  /___|  /\___  >__/\_ \
     \/        \/     \/     \/      \/
   https://hub.docker.com/u/binhex/

2020-02-08 04:15:36.361648 [info] System information Linux nzbhydra2-65df544d6f-4rxrk 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 GNU/Linux
2020-02-08 04:15:36.389503 [info] PUID defined as '1000'
2020-02-08 04:15:36.433219 [info] PGID defined as '1000'
2020-02-08 04:15:36.483935 [info] UMASK defined as '0'
2020-02-08 04:15:36.513781 [info] Permissions already set for volume mappings
2020-02-08 04:15:36.698231 [info] Deleting files in /tmp (non recursive)...
2020-02-08 04:15:36.726955 [info] Starting Supervisor...
2020-02-08 04:15:36,897 INFO Included extra file "/etc/supervisor/conf.d/nzbhydra2.conf" during parsing
2020-02-08 04:15:36,897 INFO Set uid to user 0 succeeded
2020-02-08 04:15:36,899 INFO supervisord started with pid 6
2020-02-08 04:15:37,902 INFO spawned: 'start-script' with pid 56
2020-02-08 04:15:37,903 INFO reaped unknown pid 7
2020-02-08 04:15:38,095 DEBG 'start-script' stdout output:
Logging wrapper output to /config/nzbhydra2/logs/wrapper.log
2020-02-08 04:15:38,094  INFO - Determined java version as '10' from version string 'openjdk version "10.0.2" 2018-07-17'

2020-02-08 04:15:38,095 INFO success: start-script entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2020-02-08 04:15:38,095 DEBG 'start-script' stdout output:
2020-02-08 04:15:38,095  INFO - Starting NZBHydra main process with command line: java -Xmx256M -DfromWrapper -XX:TieredStopAtLevel=1 -noverify -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/config/nzbhydra2/logs -Xlog:gc*:file=../../../config/nzbhydra2/logs/gclog-2020-02-08_04-15-38.log::filecount=10,filesize=5000 -Dspring.output.ansi.enabled=ALWAYS -jar /usr/lib/nzbhydra2/lib/core-2.13.3-exec.jar --datafolder /config/nzbhydra2 in folder /usr/lib/nzbhydra2

2020-02-08 04:15:38,909 DEBG 'start-script' stdout output:
04:15:38.906 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/usr/lib/nzbhydra2/lib/core-2.13.3-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep005to006.class]

2020-02-08 04:15:38,909 DEBG 'start-script' stdout output:
04:15:38.909 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/usr/lib/nzbhydra2/lib/core-2.13.3-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep008to009.class]

2020-02-08 04:15:38,910 DEBG 'start-script' stdout output:
04:15:38.909 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/usr/lib/nzbhydra2/lib/core-2.13.3-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep004to005.class]

2020-02-08 04:15:38,910 DEBG 'start-script' stdout output:
04:15:38.910 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/usr/lib/nzbhydra2/lib/core-2.13.3-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep003to004.class]

2020-02-08 04:15:38,910 DEBG 'start-script' stdout output:
04:15:38.910 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/usr/lib/nzbhydra2/lib/core-2.13.3-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep007to008.class]

2020-02-08 04:15:38,911 DEBG 'start-script' stdout output:
04:15:38.910 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Ignored because not a concrete top-level class: URL [jar:file:/usr/lib/nzbhydra2/lib/core-2.13.3-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep.class]

2020-02-08 04:15:38,911 DEBG 'start-script' stdout output:
04:15:38.911 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/usr/lib/nzbhydra2/lib/core-2.13.3-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep006to007.class]

2020-02-08 04:15:39,025 DEBG 'start-script' stdout output:
04:15:39.024 [main] DEBUG org.nzbhydra.config.ConfigReaderWriter - Writing to file /config/nzbhydra2/nzbhydra.yml

2020-02-08 04:15:39,070 DEBG 'start-script' stdout output:
04:15:39.070 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.host to 0.0.0.0
04:15:39.070 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.port to 5076

2020-02-08 04:15:39,071 DEBG 'start-script' stdout output:
04:15:39.070 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.urlBase to /
04:15:39.070 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.ssl to false
04:15:39.070 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.databaseCompactTime to 15000
04:15:39.070 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.logging.consolelevel to INFO
04:15:39.070 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.logging.logfilelevel to INFO
04:15:39.070 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.logging.logMaxHistory to 30

2020-02-08 04:15:39,123 DEBG 'start-script' stdout output:
04:15:39.123 [main] DEBUG org.nzbhydra.database.DatabaseRecreation - Determining if database recreation is needed

2020-02-08 04:15:39,345 DEBG 'start-script' stdout output:
04:15:39.345 [main] DEBUG org.nzbhydra.database.DatabaseRecreation - No migration scripts found to run. Skipping database recreation

2020-02-08 04:15:39,784 DEBG 'start-script' stdout output:
.__   __.  ________  .______   __    __  ____    ____  _______  .______          ___          ___
|  \ |  | |       /  |   _  \ |  |  |  | \   \  /   / |       \ |   _  \        /   \        |__ \
|   \|  | `---/  /   |  |_)  ||  |__|  |  \   \/   /  |  .--.  ||  |_)  |      /  ^  \          ) |
|  . `  |    /  /    |   _  < |   __   |   \_    _/   |  |  |  ||      /      /  /_\  \        / /
|  |\   |   /  /----.|  |_)  ||  |  |  |     |  |     |  '--'  ||  |\  \----./  _____  \      / /_
|__| \__|  /________||______/ |__|  |__|     |__|     |_______/ | _| `._____/__/     \__\    |____|


2020-02-08 04:15:39,838 DEBG 'start-script' stdout output:
2020-02-08 04:15:39.833  INFO --- [           main] org.nzbhydra.NzbHydra                    : Starting NzbHydra on nzbhydra2-65df544d6f-4rxrk with PID 73 (/usr/lib/nzbhydra2/lib/core-2.13.3-exec.jar started by nobody in /usr/lib/nzbhydra2)

2020-02-08 04:15:39,839 DEBG 'start-script' stdout output:
2020-02-08 04:15:39.839  INFO --- [           main] org.nzbhydra.NzbHydra                    : The following profiles are active: default

2020-02-08 04:15:41,309 DEBG 'start-script' stdout output:
2020-02-08 04:15:41.308  INFO --- [           main] org.nzbhydra.config.BaseConfig           : Using data folder /config/nzbhydra2

2020-02-08 04:15:41,730 DEBG 'start-script' stdout output:
2020-02-08 04:15:41.730  INFO --- [           main] o.n.a.HydraAnonymousAuthenticationFilter : Granting basic user rights to anonymous users

2020-02-08 04:15:41,731 DEBG 'start-script' stdout output:
2020-02-08 04:15:41.730  INFO --- [           main] o.n.a.HydraAnonymousAuthenticationFilter : Granting stats rights to anonymous users

2020-02-08 04:15:41,731 DEBG 'start-script' stdout output:
2020-02-08 04:15:41.731  INFO --- [           main] o.n.a.HydraAnonymousAuthenticationFilter : Granting admin rights to anonymous users

2020-02-08 04:15:41,846 DEBG 'start-script' stdout output:
2020-02-08 04:15:41.846  INFO --- [           main] o.f.c.internal.license.VersionPrinter    : Flyway Community Edition 6.2.0 by Redgate

2020-02-08 04:15:41,855 DEBG 'start-script' stdout output:
2020-02-08 04:15:41.855  INFO --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...

2020-02-08 04:15:41,877 DEBG 'start-script' stdout output:
2020-02-08 04:15:41.877  INFO --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.

2020-02-08 04:15:41,886 DEBG 'start-script' stdout output:
2020-02-08 04:15:41.886  INFO --- [           main] o.f.c.internal.database.DatabaseFactory  : Database: jdbc:h2:file:/config/nzbhydra2/database/nzbhydra (H2 1.4)

2020-02-08 04:15:41,956 DEBG 'start-script' stdout output:
2020-02-08 04:15:41.956  INFO --- [           main] o.f.core.internal.command.DbValidate     : Successfully validated 24 migrations (execution time 00:00.037s)

2020-02-08 04:15:41,972 DEBG 'start-script' stdout output:
2020-02-08 04:15:41.971  INFO --- [           main] o.f.core.internal.command.DbMigrate      : Current version of schema "PUBLIC": 1.25

2020-02-08 04:15:41,974 DEBG 'start-script' stdout output:
2020-02-08 04:15:41.973  INFO --- [           main] o.f.core.internal.command.DbMigrate      : Schema "PUBLIC" is up to date. No migration necessary.

2020-02-08 04:15:43,719 DEBG 'start-script' stdout output:
2020-02-08 04:15:43.718  WARN --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing table [indexersearch]

2020-02-08 04:15:43,719 DEBG 'start-script' stdout output:
2020-02-08 04:15:43.719  INFO --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...

2020-02-08 04:15:43,728 DEBG 'start-script' stdout output:
2020-02-08 04:15:43.728  INFO --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.

2020-02-08 04:15:43,754 DEBG 'start-script' stdout output:
2020-02-08 04:15:43.753 ERROR --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing table [indexersearch]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1803)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1108)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.nzbhydra.NzbHydra.startup(NzbHydra.java:164)
Caused by: javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing table [indexersearch]
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:403)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:378)
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1862)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1799)

2020-02-08 04:15:43,754 DEBG 'start-script' stdout output:
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1108)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
Caused by: org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing table [indexersearch]
        at org.hibernate.tool.schema.internal.AbstractSchemaValidator.validateTable(AbstractSchemaValidator.java:121)
        at org.hibernate.tool.schema.internal.GroupedSchemaValidatorImpl.validateTables(GroupedSchemaValidatorImpl.java:42)
        at org.hibernate.tool.schema.internal.AbstractSchemaValidator.performValidation(AbstractSchemaValidator.java:89)
        at org.hibernate.tool.schema.internal.AbstractSchemaValidator.doValidation(AbstractSchemaValidator.java:68)
        at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:192)
        at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:73)
        at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:320)
        at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:462)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:935)
        at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58)
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:391)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:378)
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1862)


2020-02-08 04:15:43,756 DEBG 'start-script' stdout output:
2020-02-08 04:15:43.755 ERROR --- [           main] org.nzbhydra.NzbHydra                    : An unexpected error occurred during startup

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing table [indexersearch]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1803)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)

2020-02-08 04:15:43,756 DEBG 'start-script' stdout output:
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1108)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.nzbhydra.NzbHydra.startup(NzbHydra.java:164)
Caused by: javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing table [indexersearch]
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:403)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:378)
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1862)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1799)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1108)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
Caused by: org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing table [indexersearch]
        at org.hibernate.tool.schema.internal.AbstractSchemaValidator.validateTable(AbstractSchemaValidator.java:121)
        at org.hibernate.tool.schema.internal.GroupedSchemaValidatorImpl.validateTables(GroupedSchemaValidatorImpl.java:42)
        at org.hibernate.tool.schema.internal.AbstractSchemaValidator.performValidation(AbstractSchemaValidator.java:89)
        at org.hibernate.tool.schema.internal.AbstractSchemaValidator.doValidation(AbstractSchemaValidator.java:68)
        at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:192)
        at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:73)
        at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:320)
        at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:462)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:935)
        at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58)
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:391)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:378)
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1862)


2020-02-08 04:16:02,768 WARN received SIGTERM indicating exit request
2020-02-08 04:16:02,768 DEBG killing start-script (pid 56) with signal SIGTERM
2020-02-08 04:16:02,768 INFO waiting for start-script to die

```

**Comment by halkeye** [comment]
Okay, after finding the yaml file, I guessed that the db was more about history than actual config.
I moved it out of the way, restarted, and things start up now.

I see in latest version " Fix Fixed a very rare issue where a file stored in temp directory could not be read or deleted which prevented successful database migration." might this be related?

I could provide the broken .db file if its useful, but I suspect its not and this issue can be closed.

**Comment by theotherp** [comment]
Please send me your corrupted database and the debug infos zip created from the now running instance. Also if possible the log from yesterday. Ideally upload it somewhere and send me the link to theotherp@gmx.de. Thanks.

**Comment by halkeye** [comment]
Emailed thx

**Comment by halkeye** [comment]
Gonna close this now. Its either been fixed, or not been fixed, but no longer affects me, and well past moved on.
