### ISSUE TITLE
v2.14.0 fails to start

### ISSUE THREAD

**Issue by hotio** [theotherp/nzbhydra2#509]
I'm getting the following output from my build pipeline...

```
Logging wrapper output to /config/app/logs/wrapper.log
2020-02-23 18:08:32,686  INFO - No file nzbhydra.yml found. Using 256M XMX
2020-02-23 18:08:32,729  INFO - Determined java version as '11' from version string 'openjdk version "11.0.6" 2020-01-14'
2020-02-23 18:08:32,729  INFO - Starting NZBHydra main process with command line: java -Xmx256M -DfromWrapper -XX:TieredStopAtLevel=1 -noverify -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/config/app/logs -Xlog:gc*:file=../config/app/logs/gclog-2020-02-23_18-08-32.log::filecount=10,filesize=5000 -Dspring.output.ansi.enabled=ALWAYS -jar /app/lib/core-2.14.0-exec.jar --nobrowser --datafolder /config/app in folder /app
18:08:33.120 [main] DEBUG org.nzbhydra.config.ConfigReaderWriter - Copying YAML to /config/app/nzbhydra.yml
18:08:33.312 [main] DEBUG org.nzbhydra.config.ConfigReaderWriter - Using temporary file /config/app/nzbhydra.yml.bak
 in 'reader', line 16, column 5:
        ^
 in 'reader', line 18, column 7:
          ^
 at [Source: (File); line: 17, column: 27]
java.lang.RuntimeException: Config file /config/app/nzbhydra.yml corrupted. If you find a ZIP in your backup folder restore it from there. Otherwise you'll have to delete the file and start over. Please contact the developer when you have it running.
	at org.nzbhydra.NzbHydra.initializeAndValidateAndMigrateYamlFile(NzbHydra.java:216)
	at org.nzbhydra.NzbHydra.main(NzbHydra.java:117)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
Caused by: java.lang.RuntimeException: Config file /config/app/nzbhydra.yml corrupted. If you find a ZIP in your backup folder restore it from there. Otherwise you'll have to delete the file and start over. Please contact the developer when you have it running.
	at org.nzbhydra.NzbHydra.initializeAndValidateAndMigrateYamlFile(NzbHydra.java:216)
	at org.nzbhydra.NzbHydra.main(NzbHydra.java:117)
2020-02-23 18:08:33,330  ERROR - Main process shut down unexpectedly. If the wrapper was started in daemon mode you might not see the error output. Start Hydra manually with the same parameters in the same environment to see it

```

**Comment by theotherp** [comment]
What do lines 16 to 18 look like?

**Comment by hotio** [comment]
I have no idea, it's a clean install, so you should know that better than me... :-)

**Comment by theotherp** [comment]
I can start a clean install just fine. The file is created on startup... You don't have access to the data directory in the pipeline?

**Comment by hotio** [comment]
I'll have a look....

**Comment by theotherp** [comment]
Strike that, seems to fail on linux. Probably something with line breaks. Thanks for the warning ;-)

**Comment by theotherp** [comment]
I'll have to add some kind of startup test with linux to my pipeline, this is the second time you found a bug ;-)

**Comment by hotio** [comment]
It's not that much effort for me, just wait until the color red pops up....:-)

**Comment by hotio** [comment]
![screenshot](https://user-images.githubusercontent.com/26902309/75120946-fccfa480-568f-11ea-9502-0ef68b5f8462.png)

All good again...
