### ISSUE TITLE
Hydra2 Barfing on Unicode searches and going into a restart loop until forcibly killed

### ISSUE THREAD

**Issue by alron** [theotherp/nzbhydra2#517]
It looks like hydra is having problems handling unicode. Run the following single character search `º` and hydra2 instantly bombs out and goes into a loop of stack traces. This may be the same problem as reported by others with high cpu and constant restarts. Can be triggered via internal and API searches.

Happens with linuxserver docker image and hydra versions 2.13.11 and 2.14.1 (and likely everything in-between). Ubuntu 18.04.3 is the host OS for the dockers. 

Log excerpt with the most important error messages:
```
# grep ascii wrapper.log*
wrapper.log:2020-03-07 02:59:53,500  ERROR - Unable to start process; make sure Java is installed and callable. Error message: 'ascii' codec can't decode byte 0xc2 in position 314: ordinal not in range(128)
wrapper.log.1:2020-02-19 16:12:10,749  ERROR - Unable to start process; make sure Java is installed and callable. Error message: 'ascii' codec can't decode byte 0xc2 in position 314: ordinal not in range(128)
wrapper.log.1:2020-02-19 16:13:13,348  ERROR - Unable to start process; make sure Java is installed and callable. Error message: 'ascii' codec can't decode byte 0xc2 in position 320: ordinal not in range(128)
wrapper.log.1:2020-03-07 02:52:38,421  ERROR - Unable to start process; make sure Java is installed and callable. Error message: 'ascii' codec can't decode byte 0xc2 in position 299: ordinal not in range(128)
```
These messages are followed immediately by a constant barrage of java process restarts and crazy cpu.

Example console log of the errors that immediately follow the hard crash from unicode decode error (the above errors):
```
hydra2                  | Logging wrapper output to /config/logs/wrapper.log
hydra2                  | 2020-03-07 03:18:39,392  INFO - Determined java version as '11' from version string 'openjdk version "11.0.6" 2020-01-14'
hydra2                  | 2020-03-07 03:18:39,394  INFO - Starting NZBHydra main process with command line: java -Xmx1024M -DfromWrapper -XX:TieredStopAtLevel=1 -noverify -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/config/logs -Xlog:gc*:file=../../config/logs/gclog-2020-03-07_03-18-39.log::filecount=10,filesize=5000 -Dspring.output.ansi.enabled=ALWAYS -jar /app/hydra2/lib/core-2.13.11-exec.jar --nobrowser --datafolder /config in folder /app/hydra2
hydra2                  | 03:18:40.718 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/hydra2/lib/core-2.13.11-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep008to009.class]
hydra2                  | 03:18:40.719 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/hydra2/lib/core-2.13.11-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep003to004.class]
hydra2                  | 03:18:40.719 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/hydra2/lib/core-2.13.11-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep007to008.class]
hydra2                  | 03:18:40.721 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Ignored because not a concrete top-level class: URL [jar:file:/app/hydra2/lib/core-2.13.11-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep.class]
hydra2                  | 03:18:40.939 [main] DEBUG org.nzbhydra.NzbHydra - Setting property browser.disabled to value true
hydra2                  | 03:18:40.957 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.port to 5076
hydra2                  | 03:18:40.957 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.ssl to false
hydra2                  | 03:18:40.957 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.logging.consolelevel to INFO
hydra2                  | 03:18:40.957 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.logging.logMaxHistory to 30
hydra2                  | 03:18:41.191 [main] ERROR org.nzbhydra.NzbHydra - An unexpected error occurred during startup
hydra2                  | 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
hydra2                  | 	at org.h2.message.DbException.get(DbException.java:194)
hydra2                  | 	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:182)
hydra2                  | 	at org.h2.engine.Database.getPageStore(Database.java:2659)
hydra2                  | 	at org.h2.engine.Database.openDatabase(Database.java:307)
hydra2                  | 	at org.h2.engine.Engine.openSession(Engine.java:74)
hydra2                  | 	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
hydra2                  | 	at org.h2.engine.Engine.createSession(Engine.java:29)
hydra2                  | 	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
hydra2                  | 	at org.h2.Driver.connect(Driver.java:69)
hydra2                  | 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
hydra2                  | 	at org.nzbhydra.NzbHydra.startup(NzbHydra.java:163)
hydra2                  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
hydra2                  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
hydra2                  | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
hydra2                  | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
hydra2                  | Caused by: java.lang.IllegalStateException: The file is locked: nio:/config/database/nzbhydra.mv.db [1.4.200/7]
hydra2                  | 	at org.h2.mvstore.FileStore.open(FileStore.java:172)
hydra2                  | 	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
hydra2                  | 	... 27 common frames omitted
hydra2                  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
hydra2                  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
hydra2                  | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
hydra2                  | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
hydra2                  | Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-200]
hydra2                  | 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
hydra2                  | 	at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:206)
hydra2                  | 	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
hydra2                  | 	at org.h2.engine.Database.open(Database.java:675)
hydra2                  | 	at org.h2.engine.Database.<init>(Database.java:301)
hydra2                  | 	at org.h2.engine.Engine.openSession(Engine.java:192)
hydra2                  | 	at org.h2.engine.Engine.createSession(Engine.java:166)
hydra2                  | 	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
hydra2                  | 	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
hydra2                  | 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
hydra2                  | 	at org.nzbhydra.database.DatabaseRecreation.runDatabaseScript(DatabaseRecreation.java:77)
hydra2                  | 	at org.nzbhydra.NzbHydra.main(NzbHydra.java:117)
hydra2                  | Caused by: java.lang.IllegalStateException: The file is locked: nio:/config/database/nzbhydra.mv.db [1.4.200/7]
hydra2                  | 	at org.h2.mvstore.FileStore.open(FileStore.java:172)
hydra2                  | 	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
hydra2                  | 	... 27 more
hydra2                  | 2020-03-07 03:18:41,228  ERROR - Main process shut down unexpectedly. If the wrapper was started in daemon mode you might not see the error output. Start Hydra manually with the same parameters in the same environment to see it
```
Everything past this point would be a simple loop of the same messages, ad nauseam, ad infinitum. It seems that after the unicode crash it can't gain lock on the DB until the whole container is forcibly restarted.

**Comment by theotherp** [comment]
Works fine for me. Can't reproduce. Try restoring your database file from the latest backup.

**Comment by johnny2678** [comment]
Same issue... recreating database works for a bit but then it ends up back in this state.  This just started in the last week or so:

```
16:44:34.788 [main] ERROR org.nzbhydra.NzbHydra - An unexpected error occurred during startup
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:182)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at org.nzbhydra.NzbHydra.startup(NzbHydra.java:163)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
Caused by: java.lang.IllegalStateException: The file is locked: nio:/config/database/nzbhydra.mv.db [1.4.200/7]
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	... 27 common frames omitted
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:206)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at org.nzbhydra.database.DatabaseRecreation.runDatabaseScript(DatabaseRecreation.java:77)
	at org.nzbhydra.NzbHydra.main(NzbHydra.java:117)
Caused by: java.lang.IllegalStateException: The file is locked: nio:/config/database/nzbhydra.mv.db [1.4.200/7]
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	... 27 more
2020-03-13 12:44:34,829  ERROR - Main process shut down unexpectedly. If the wrapper was started in daemon mode you might not see the error output. Start Hydra manually with the same parameters in the same environment to see it
Logging wrapper output to /config/logs/wrapper.log

```

**Comment by theotherp** [comment]
I'm not convinced that that errors have anything to do with unicode.

**Comment by alron** [comment]
@theotherp Sorry. Maybe not *unicode*, but that error is definitely UTF8 related. The very first error perfectly describes an attempt to decode 0xc2 (UTF8 hex used for non-alphabet special charaters) with an ascii decoder. `0xc2 0xba` happens to be  `º` in UTF8 (U+00BA in unicode).

**Comment by johnny2678** [comment]
increased Xmx to 256... testing

**Comment by theotherp** [comment]
Right. The issue is related to the image using the python 3 wrapper. I only tested it with the py2 wrapper. Sorry about that.

You see the database error because the java process is still running and it blocks the database. So hydra should still be reachable.

I hope to have some time tomorrow to fix this.

**Comment by alron** [comment]
@theotherp No worries at all. It wasn't a major impact for my use, especially once I figured out what was triggering it on my side. I'm just glad it was something relatively simple. 

Thanks for all your work on this project.

**Comment by johnny2678** [comment]
@theotherp I agree. thx for all you do.
