### ISSUE TITLE
[BUG] DrunkenSlug failing on 2.19.1

### ISSUE THREAD

**Issue by RemuxKid** [theotherp/nzbhydra2#538]
## How to create a bug report

**Set your log file level to debug, repeat the steps that cause the problem and post the debug infos ZIP which can be retrieved in the [System / Bugreport section](http://127.0.0.1:5076/system/bugreport). If other tools are involved post their logs as well.**
java.util.ConcurrentModificationException: null
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
	at org.nzbhydra.searching.searchrequests.InternalData.getFallbackStateByIndexer(InternalData.java:32)
	at org.nzbhydra.indexers.Newznab.buildSearchUrl(Newznab.java:132)
	at org.nzbhydra.indexers.Indexer.searchInternal(Indexer.java:171)
	at org.nzbhydra.indexers.Indexer.search(Indexer.java:119)
	at org.nzbhydra.searching.Searcher.lambda$getIndexerCallable$12(Searcher.java:411)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.nzbhydra.logging.MdcThreadPoolExecutor$1.run(MdcThreadPoolExecutor.java:114)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

* Prefix the issue title with "BUG"
* You don't have to follow the next steps by the letter, just think about what you're trying to achieve ;-) 
* What do you expect to happen? What does happen? 
Expected API to connect. Seems like this one is having an issue

* Have you searched for this problem? You don't have to answer, just make sure.
* Can the problem be reproduced? How?
* Use a proper title. Describe the problem succinctly, don't just copy and paste the error message.
* If you use a docker container please tell me which one.

**I will close your issues if I you didn't provide proper information as described as above**

The more information you provide up front the higher the chance that I can help you.

## How to request a new feature
* Prefix your issue title with "REQ".
* What do you want to happen?
* If not clear, why do you want it?
* Do you think it's something only you need or something that might be popular?
* If need be explain the use case.

**Comment by RemuxKid** [comment]
More logs:

java.util.ConcurrentModificationException: null
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
	at org.nzbhydra.searching.searchrequests.InternalData.getFallbackStateByIndexer(InternalData.java:32)
	at org.nzbhydra.indexers.Newznab.buildSearchUrl(Newznab.java:132)
	at org.nzbhydra.indexers.Indexer.searchInternal(Indexer.java:171)
	at org.nzbhydra.indexers.Indexer.search(Indexer.java:119)
	at org.nzbhydra.searching.Searcher.lambda$getIndexerCallable$12(Searcher.java:411)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.nzbhydra.logging.MdcThreadPoolExecutor$1.run(MdcThreadPoolExecutor.java:114)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by RemuxKid** [comment]
Reverting back to 2.17.6 fixes the issues

**Comment by theotherp** [comment]
Can't really reproduce it but I might know how to fix it anyway.

**Comment by theotherp** [comment]
Also, next time please format the ticket properly and attach the debug infos as requested.

**Comment by theotherp** [comment]
Try with 2.19.2
