### ISSUE TITLE
Drunken Slug: Unexpected error while searching

### ISSUE THREAD

**Issue by Commiseration** [theotherp/nzbhydra2#540]
Hello

Following today's update to v2.19.3, I can't access the Drunken Slug indexer, all other indexers are working as expected. I've pasted the log entry message and stacktrace below this message.

Check capabilities for Indexer shows the determined api limit is null and download limit is null as well.

Log Message: Drunken Slug: Unexpected error while searching

Stacktrace:

java.lang.NullPointerException: null
	at org.nzbhydra.mapping.newznab.xml.NewznabXmlApilimits.getApiOldestTime(NewznabXmlApilimits.java:73)
	at org.nzbhydra.indexers.Newznab.completeIndexerSearchResult(Newznab.java:474)
	at org.nzbhydra.indexers.Newznab.completeIndexerSearchResult(Newznab.java:73)
	at org.nzbhydra.indexers.Indexer.searchInternal(Indexer.java:194)
	at org.nzbhydra.indexers.Indexer.search(Indexer.java:119)
	at org.nzbhydra.searching.Searcher.lambda$getIndexerCallable$12(Searcher.java:411)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at org.nzbhydra.logging.MdcThreadPoolExecutor$1.run(MdcThreadPoolExecutor.java:114)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Could you please help me out.

Thanks

**Comment by theotherp** [comment]
Fix coming soon.
