### ISSUE TITLE
API error

### ISSUE THREAD

**Issue by jonfinley** [theotherp/nzbhydra2#55]
* I am trying to use nzbhydra2 with sonarr/radarr and cannot seem to get either to connect.
* Sonarr/Radarr Logs: HTTP Error - Res: [GET] http://127.0.0.1:5076/nzbhydra/api?t=movie&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100: 404.NotFound
* Sonarr/Radarr notification: Unable to connect to indexer. Page size must not be less than one!
I have tried using 127.0.0.1 and the public ip of my server.

* Bug Report:
[nzbhydra-debuginfos-2018-01-11-13-11.zip](https://github.com/theotherp/nzbhydra2/files/1623655/nzbhydra-debuginfos-2018-01-11-13-11.zip)

**Comment by theotherp** [comment]
Well you call `http://127.0.0.1:5076/nzbhydra/api?...` but you use URL base `/nzbhydra2` so you should call `http://127.0.0.1:5076/nzbhydra2/api?..`

**Comment by jonfinley** [comment]
I did not catch that! just tried again. Same Error. 
<img width="658" alt="screen shot 2018-01-11 at 1 21 20 pm" src="https://user-images.githubusercontent.com/23283167/34841653-fd241d1e-f6d6-11e7-9914-79343ca0c5ce.png">

**Comment by theotherp** [comment]
You disabled the option `useLocalUrlForApiAccess` which means that Hydra will create NZB links that refer to your external URL (which you also set). But you entered your local address (`http://127.0.0.1:5076/nzbhydra2`) into Hydra. 

Either enable that option or enter Hydra's  external URL into Radarr. Restart Hydra to clear the failed attempts by Radarr. Try it again in Radarr. See if that helps.

**Comment by jonfinley** [comment]
still getting the same error....

I'm going to try a fresh install and see if I still get the same issues.

**Comment by theotherp** [comment]
Wait. See the other issue.

**Comment by jonfinley** [comment]
okay issue good. This one I getthe same error

<img width="785" alt="screen shot 2018-01-11 at 2 35 01 pm" src="https://user-images.githubusercontent.com/23283167/34843497-aa44a248-f6dc-11e7-8828-28137db6ad3e.png">
<img width="726" alt="screen shot 2018-01-11 at 2 32 27 pm" src="https://user-images.githubusercontent.com/23283167/34843498-aa5dc6c4-f6dc-11e7-8e3c-3e8cffb1b170.png">

**Comment by theotherp** [comment]
Well at least the access works...

**Comment by jonfinley** [comment]
if this helps:
```
2018-01-11 14:32:57.482  INFO --- [0.0-5076-exec-3] org.nzbhydra.api.ExternalApi             : [IP: 127.0.0.1] Received external API call: NewznabParameters{t=MOVIE, cat=[2000, 2010, 2020, 2030, 2035, 2040, 2045, 2050, 2060], offset=0, limit=100, raw=false, extended=true}
2018-01-11 14:32:57.487  INFO --- [0.0-5076-exec-3] org.nzbhydra.api.ExternalApi             : [Search: 583044, IP: 127.0.0.1] Executing new search
2018-01-11 14:32:57.493 DEBUG --- [0.0-5076-exec-3] o.n.searching.IndexerForSearchSelector   : [Search: 583044, IP: 127.0.0.1] Picking indexers out of 9
2018-01-11 14:32:57.502 ERROR --- [0.0-5076-exec-3] org.nzbhydra.api.ExternalApi             : [Search: 583044, IP: 127.0.0.1] Unexpected error while handling API request

java.lang.IllegalArgumentException: Page size must not be less than one!
	at org.springframework.data.domain.AbstractPageRequest.<init>(AbstractPageRequest.java:47)
	at org.springframework.data.domain.PageRequest.<init>(PageRequest.java:63)
	at org.springframework.data.domain.PageRequest.<init>(PageRequest.java:40)
	at org.nzbhydra.searching.IndexerForSearchSelector$InnerInstance.checkIndexerHitLimit(IndexerForSearchSelector.java:259)
	at org.nzbhydra.searching.IndexerForSearchSelector$InnerInstance.pickIndexers(IndexerForSearchSelector.java:133)
	at org.nzbhydra.searching.IndexerForSearchSelector.pickIndexers(IndexerForSearchSelector.java:76)
	at org.nzbhydra.searching.Searcher.getSearchCacheEntry(Searcher.java:251)
	at org.nzbhydra.searching.Searcher.search(Searcher.java:100)
	at org.nzbhydra.api.ExternalApi.search(ExternalApi.java:210)
	at org.nzbhydra.api.ExternalApi.api(ExternalApi.java:114)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.nzbhydra.auth.HydraAnonymousAuthenticationFilter.doFilter(HydraAnonymousAuthenticationFilter.java:98)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:150)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:158)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by theotherp** [comment]
It does, yes....

**Comment by theotherp** [comment]
Your drunken slug  download limit is set to -9

**Comment by theotherp** [comment]
It seems I have to validate every last setting or somebody will manage to enter something wrong.

**Comment by jonfinley** [comment]
I don't mean to cause issues. I racked my brain with another user for several hours and could not figure it out

**Comment by theotherp** [comment]
Your initial bug infos did not include the error caused by Radarr's access. If they had this could've been solved in a matter of minutes.
