### ISSUE TITLE
Jackett Automation Problem

### ISSUE THREAD

**Issue by DavideCampagna** [theotherp/nzbhydra2#553]
Hi, 
First of all thank you for listening to my request to add this wonderful feature.
Now, probably I'm doing something wrong, but I can't make it work. I add all the indexers through the Jackett config (each one of them is properly working inside Jackett) the I try to search something and this happens to each indexer:

2020-04-29 00:36:29.575 ERROR --- [pool-313-thread-15] org.nzbhydra.indexers.torznab.Torznab    : [Search: 591341, Host: net-93-70-14-239.cust.vodafonedsl.it] 1337x: Unexpected error while searching
```
java.lang.NullPointerException: null
	at org.nzbhydra.indexers.Newznab.getSearchResultItems(Newznab.java:417)
	at org.nzbhydra.indexers.Newznab.getSearchResultItems(Newznab.java:71)
	at org.nzbhydra.indexers.Indexer.searchInternal(Indexer.java:184)
	at org.nzbhydra.indexers.Indexer.search(Indexer.java:119)
	at org.nzbhydra.searching.Searcher.lambda$getIndexerCallable$12(Searcher.java:411)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.nzbhydra.logging.MdcThreadPoolExecutor$1.run(MdcThreadPoolExecutor.java:114)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

2020-04-29 00:36:29.576  WARN --- [pool-313-thread-15] org.nzbhydra.indexers.torznab.Torznab    : [Search: 591341, Host: net-93-70-14-239.cust.vodafonedsl.it] Because an error occurred 1337x will be temporarily disabled until 2020-04-28T22:51:29.576132Z. This is error number 1 in a row
```

I even tried to add them again filling the username&password field that I've set in Jackett, but The problem persists

Sorry to to bother you, and thank you for your amazing job

**Comment by DavideCampagna** [comment]
Here is my bug report
[nzbhydra-debuginfos-2020-04-29-00-48.zip](https://github.com/theotherp/nzbhydra2/files/4548946/nzbhydra-debuginfos-2020-04-29-00-48.zip)

**Comment by theotherp** [comment]
Update to 2.20.1, this is already fixed.

**Comment by DavideCampagna** [comment]
Ok, thanks
Unfortunately I'm using docker and the update is not available for now, I'll update as soon as it is released 
Right now I'm using the linuxsever/nzbhydra2:dev image, maybe I can try the binhex one and see if it is up to date

**Comment by DavideCampagna** [comment]
Ok that's strange.
Out of curiosity I first tried the latest branch of the linuxserver image and actually is more updated than the dev one, now I am on 2.20.1 and everything seems to work just fine
Thank you for you support and sorry to bother you

**Comment by theotherp** [comment]
Ohhh... perhaps because that tag may get the latest release that is or was tagged as beta. I'll ask them.

**Comment by theotherp** [comment]
See https://github.com/linuxserver/docker-nzbhydra2/issues/4

**Comment by DavideCampagna** [comment]
Thanks
