### ISSUE TITLE
Torznab searches no longer working

### ISSUE THREAD

**Issue by Noiprox6** [theotherp/nzbhydra2#573]
[nzbhydra-debuginfos-2020-05-25-01-16.zip](https://github.com/theotherp/nzbhydra2/files/4675331/nzbhydra-debuginfos-2020-05-25-01-16.zip)

I have 3 torznab indexers setup (two existing and one new added for testing this issue.
I had them setup to search from Sonarr and Radarr before and they were working fine though I don't know when the stopped as I also use NZBs now for most things.
I have the torznab indexers setup in Jacket and I can search them fine there with lots of results for the same search query I try in NZBHydra but in Hydra it says there is an unexpected error while searching.

I'm sorry I couldn't figure out how to set the log file level to debug.  I have attached the requested log files and the relevant section is also pasted below.

Thank you.

2020-05-25 00:07:17.549  INFO --- [ pool-573-thread-1] org.nzbhydra.indexers.torznab.Torznab    : [ID: 47390, Host: 127.0.0.1] EZTV: Calling http://127.0.0.1:9117/api/v2.0/indexers/eztv/results/torznab/api?apikey=<apikey>&t=tvsearch&extended=1&password=1&cat=5000
2020-05-25 00:07:18.564 ERROR --- [ pool-573-thread-1] org.nzbhydra.indexers.torznab.Torznab    : [ID: 47390, Host: 127.0.0.1] EZTV: Unexpected error while searching

java.lang.NullPointerException: null
	at org.nzbhydra.indexers.Newznab.completeIndexerSearchResult(Newznab.java:466)
	at org.nzbhydra.indexers.torznab.Torznab.completeIndexerSearchResult(Torznab.java:122)
	at org.nzbhydra.indexers.torznab.Torznab.completeIndexerSearchResult(Torznab.java:52)
	at org.nzbhydra.indexers.Indexer.searchInternal(Indexer.java:194)
	at org.nzbhydra.indexers.Indexer.search(Indexer.java:119)
	at org.nzbhydra.searching.Searcher.lambda$getIndexerCallable$12(Searcher.java:412)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at org.nzbhydra.logging.MdcThreadPoolExecutor$1.run(MdcThreadPoolExecutor.java:114)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by vxr** [comment]
Seems to be caused by this patch: https://github.com/theotherp/nzbhydra2/commit/a7f59b23597906e2d7a524f982b1f7e182fbf183

**Comment by Minituff** [comment]
I am also having the same issues.

**Comment by theotherp** [comment]
I should get my tests running again...
