### ISSUE TITLE
Problem with Hydra URL added to SABnzbd

### ISSUE THREAD

**Issue by anonvoy** [theotherp/nzbhydra2#59]
I have nzbhydra2 (just updated to 1.0.18) running on a linux machine. Hydra2 "lives" in my browser at http://127.0.0.1:5076/ or at http://localhost:5076/ (both work).

Recently (three days or so)? a problem cropped up with NZBs that Hydra2 added to SABnzbd. The adding itself works, only the URL is problematic: Hydra adds URLs of the type

http://linux-q1zt:5076/getnzb/api/1234567890123456789?apikey=<APIKEY>

to SABnzbd, and SABnzbd duly tries to fetch the NZB from that URL. linux-q1zt is the name of my machine as it shows up in the command prompt.

But Hydra cannot be reached at http://linux-q1zt:5076/, not in the browser (just an error message), and apparently not by SABnzbd either, because fetching the NZB does not work. So at the moment, I have to go the "black hole" route to add NZBs.

I'm pretty sure this worked before and only cropped up recently after an update. I hope it's possible to have Hydra add URLs that work like http://127.0.0.1:5076/ or http://localhost:5076/?

**Comment by theotherp** [comment]
In your main config set the host to 127.0.0.1

I'm trying to make the code work for everybody but every time I change something to fix one issue I cause another....

**Comment by anonvoy** [comment]
The host in my main config already was set to 127.0.0.1. So no, that didn't help.

**Comment by theotherp** [comment]
Please post the debug infos.

I'll do some tests tomorrow.

**Comment by anonvoy** [comment]
Hydra log:

```
2018-01-13 21:49:54.810  INFO --- [0.1-5076-exec-5] o.nzbhydra.downloading.sabnzbd.Sabnzbd   : [Search: 740850, IP: <IP>] Successfully added link http://linux-q1zt:5076/getnzb/api/6183612717769042815?apikey=<APIKEY> for NZB "openSUSE-Leap-42.2-DVD-x86 64.nzb" to sabnzbd queue with ID SABnzbd_nzo_uGO6Jj
2018-01-13 21:50:08.542  INFO --- [0.1-5076-exec-2] o.n.debuginfos.DebugInfosProvider        : [Search: 646105, IP: <IP>] Creating debug infos
2018-01-13 21:50:08.542  INFO --- [0.1-5076-exec-2] o.n.debuginfos.DebugInfosProvider        : [Search: 646105, IP: <IP>] NZBHydra2 version: null
2018-01-13 21:50:08.542  INFO --- [0.1-5076-exec-2] o.n.debuginfos.DebugInfosProvider        : [Search: 646105, IP: <IP>] Java command line: <BASEPATH>/lib/core-1.0.18-exec.jar --datafolder <BASEPATH>/data restarted
2018-01-13 21:50:08.542  INFO --- [0.1-5076-exec-2] o.n.debuginfos.DebugInfosProvider        : [Search: 646105, IP: <IP>] Java runtime name: Java(TM) SE Runtime Environment
2018-01-13 21:50:08.543  INFO --- [0.1-5076-exec-2] o.n.debuginfos.DebugInfosProvider        : [Search: 646105, IP: <IP>] Java runtime version: 1.8.0_121-b13
2018-01-13 21:50:08.543  INFO --- [0.1-5076-exec-2] o.n.debuginfos.DebugInfosProvider        : [Search: 646105, IP: <IP>] OS name: Linux
2018-01-13 21:50:08.543  INFO --- [0.1-5076-exec-2] o.n.debuginfos.DebugInfosProvider        : [Search: 646105, IP: <IP>] OS architecture: amd64
2018-01-13 21:50:08.543  INFO --- [0.1-5076-exec-2] o.n.debuginfos.DebugInfosProvider        : [Search: 646105, IP: <IP>] User country: DE
2018-01-13 21:50:08.543  INFO --- [0.1-5076-exec-2] o.n.debuginfos.DebugInfosProvider        : [Search: 646105, IP: <IP>] File encoding: UTF-8
```

SABnzbd log:

```
2018-01-13 21:49:54,810::INFO::[urlgrabber:124] Grabbing URL http://linux-q1zt:5076/getnzb/api/6183612717769042815?apikey=<APIKEY>
2018-01-13 21:49:54,816::INFO::[urlgrabber:203] Retry URL http://linux-q1zt:5076/getnzb/api/6183612717769042815?apikey=<APIKEY>
2018-01-13 21:50:54,894::INFO::[urlgrabber:124] Grabbing URL http://linux-q1zt:5076/getnzb/api/6183612717769042815?apikey=<APIKEY>
2018-01-13 21:50:54,926::INFO::[urlgrabber:203] Retry URL http://linux-q1zt:5076/getnzb/api/6183612717769042815?apikey=<APIKEY>
```

I'll send two additional log files by mail.

**Comment by anonvoy** [comment]
SABnzbd log:
```
2018-01-13 21:49:54,808::INFO::[__init__:550] Fetching http://linux-q1zt:5076/getnzb/api/6183612717769042815?apikey=<APIKEY>
2018-01-13 21:49:54,809::INFO::[nzbqueue:277] Saving queue
2018-01-13 21:49:54,810::INFO::[urlgrabber:124] Grabbing URL http://linux-q1zt:5076/getnzb/api/6183612717769042815?apikey=<APIKEY>
2018-01-13 21:49:54,816::INFO::[urlgrabber:203] Retry URL http://linux-q1zt:5076/getnzb/api/6183612717769042815?apikey=<APIKEY>
2018-01-13 21:50:54,894::INFO::[urlgrabber:124] Grabbing URL http://linux-q1zt:5076/getnzb/api/6183612717769042815?apikey=<APIKEY>
2018-01-13 21:50:54,926::INFO::[urlgrabber:203] Retry URL http://linux-q1zt:5076/getnzb/api/6183612717769042815?apikey=<APIKEY>
2018-01-13 21:52:55,203::INFO::[urlgrabber:124] Grabbing URL http://linux-q1zt:5076/getnzb/api/6183612717769042815?apikey=<APIKEY>
2018-01-13 21:52:55,243::INFO::[urlgrabber:203] Retry URL http://linux-q1zt:5076/getnzb/api/6183612717769042815?apikey=<APIKEY>
2018-01-13 21:55:55,535::INFO::[urlgrabber:124] Grabbing URL http://linux-q1zt:5076/getnzb/api/6183612717769042815?apikey=<APIKEY>
2018-01-13 21:55:55,540::INFO::[urlgrabber:203] Retry URL http://linux-q1zt:5076/getnzb/api/6183612717769042815?apikey=<APIKEY>
2018-01-13 21:59:55,952::INFO::[urlgrabber:124] Grabbing URL http://linux-q1zt:5076/getnzb/api/6183612717769042815?apikey=<APIKEY>
2018-01-13 21:59:55,959::INFO::[urlgrabber:203] Retry URL http://linux-q1zt:5076/getnzb/api/6183612717769042815?apikey=<APIKEY>
2018-01-13 22:04:56,271::INFO::[urlgrabber:124] Grabbing URL http://linux-q1zt:5076/getnzb/api/6183612717769042815?apikey=<APIKEY>
2018-01-13 22:04:56,281::INFO::[urlgrabber:203] Retry URL http://linux-q1zt:5076/getnzb/api/6183612717769042815?apikey=<APIKEY>
```

**Comment by theotherp** [comment]
No, the complete debug infos. See https://github.com/theotherp/nzbhydra2/blob/master/ISSUE_TEMPLATE.md

**Comment by theotherp** [comment]
I will probably remove the option to send links to downloaders in one of the coming versions. Just select to upload NZBs to your downloader instead of sending a link.

**Comment by anonvoy** [comment]
I just tried that and set Hydra2 to upload NZBs to SABnzbd. What I get is this:

```
An error occurred:
500: Internal Server Error

Path: /internalapi/downloader/addNzbs

Message: No message available
```

Hydra log:

```
2018-01-14 14:03:13.505  INFO --- [0.1-5076-exec-2] org.nzbhydra.downloading.NzbHandler      : [Search: 957767, IP: <IP>] NZB download request for openSUSE-Leap-42.2-DVD-x86 64 from indexer NZB.su
2018-01-14 14:03:13.506 ERROR --- [0.1-5076-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : [Search: 957767, IP: <IP>] Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause

java.lang.NullPointerException: null
	at okhttp3.RequestBody.create(RequestBody.java:56)
	at org.nzbhydra.downloading.sabnzbd.Sabnzbd.addNzb(Sabnzbd.java:123)
	at org.nzbhydra.downloading.Downloader.addBySearchResultIds(Downloader.java:71)
	at org.nzbhydra.downloading.Downloader$$FastClassBySpringCGLIB$$cf015001.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
	at org.nzbhydra.downloading.sabnzbd.Sabnzbd$$EnhancerBySpringCGLIB$$575f8e0c.addBySearchResultIds(<generated>)
	at org.nzbhydra.downloading.DownloaderWeb.addNzb(DownloaderWeb.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPut(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:664)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.nzbhydra.auth.HydraAnonymousAuthenticationFilter.doFilter(HydraAnonymousAuthenticationFilter.java:98)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:124)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

Changing the "NZB adding type" to "Upload NZB" for SABnzbd was the only thing I changed in the config.

**Comment by theotherp** [comment]
Yeah that doesn't look too good. Another thing for me to look at ;-)

**Comment by theotherp** [comment]
That means that the NZB was not successfully downloaded / was empty. Without full log I can't even guess why.

**Comment by anonvoy** [comment]
I sent you the log zip file by mail. Downloading said NZB to disk works without a problem, and SABnzbd imports it without any problem too.

**Comment by anonvoy** [comment]
By "Downloading said nzb to disk"  I mean letting hydra save it to disk. (Sorry, for some reason I can't edit my earlier github posts anymore? Preview doesn't work either.)

**Comment by theotherp** [comment]
Yeah that's what I meant too.

**Comment by theotherp** [comment]
I'm seeing multiple interesting things in the log. Unfortunately nothing that indicates why sending the NZBs to sabnzbd doesn't work...

* Your searches seem to take so long (50 seconds and more) that the calling tool gives up (or the browser or you closed the page). Apparently you're aware of set because you set a global timeout of 50 seconds. I'll try to handle that more gracefully.

* You seem to have a really obscure taste in movies. There are a lot of messages that TMDB doesn't know a movie with a given IMDB id. But that's not a problem per se... :-)

I still can't explain the original behavior bit hope that the next version fixes it...

**Comment by theotherp** [comment]
If you want you can try a pre-release of the next version. It would help me know if it works "out in the wild" and it might solve your issue. You can download it here: https://ufile.io/1jq2z

Shutdown Hydra. Make a backup of your nzbhydra.yml, go into the hydra lib folder, move the existing JAR somewhere else (don't just rename it), put the JAR from the link in there, start Hydra again.

Note: This will not work if you run Hydra in docker.

**Comment by anonvoy** [comment]
OK, I've downloaded the pre-release and installed it as described. Adding NZBs to SABnzbd by "send link" now works (thanks!) because Hydra adds a link of the http://127.0.0.1:5076 variety to SABnzbd. Adding NZBs to SABnzbd by "upload NZB" still doesn't work however, symptoms as before. I'll send you logs by mail.

**Comment by theotherp** [comment]
Alright, I found the issue with the error when uploading.

Hopefully the next version also fixes the original issue. 

So there'll be at least one way to get what you want ;-)

**Comment by theotherp** [comment]
Any news?

**Comment by anonvoy** [comment]
I'm still on 1.0.19-snapshot because 1.1.0 apparently didn't work with Sickrage, and that's what I use. Tried Sonarr once, didn't like it. I'll try 1.1.1 and let you know.

**Comment by anonvoy** [comment]
I've tried 1.1.1 now, and both methods of adding NZBs to SABnzbd (adding link / uploading the NZB) now work. Thanks again :-)

**Comment by theotherp** [comment]
Great!
