### ISSUE TITLE
BUG - Radarr initiated download failed

### ISSUE THREAD

**Issue by Hunter4vr** [theotherp/nzbhydra2#648]
Hi there, 

Radarr/Sonarr say that indexers are working until i initiate a download. Searches fine until i pick a download. Following that i get a message from Radarr or Sonarr saying "Indexers unavailable due to failures: NZBHydra2".

Below are the logs.

Around 2 weeks ago i have imported a backup / config file from another computer that i migrated from. It was working fine for about a week and now the above issue is happening. Should i perhaps do a clean reinstall?

Thanks

2020-12-09 18:43:42.182  INFO --- [http-nio-192.168.1] org.nzbhydra.downloading.FileHandler     : [ID: 96016, Host: Media-Server] NZB download request for "Holidate.2020.1080p.WEBRip.x264-RARBG" from indexer nzbplanet
2020-12-09 18:43:44.475  INFO --- [http-nio-192.168.1] org.nzbhydra.downloading.FileHandler     : [ID: 96016, Host: Media-Server] NZB download from indexer successfully completed in 2291ms
2020-12-09 18:43:47.527  WARN --- [http-nio-192.168.1] o.h.engine.jdbc.spi.SqlExceptionHelper   : [ID: 96016, Host: Media-Server] SQL Error: 50000, SQLState: HY000
2020-12-09 18:43:47.527 ERROR --- [http-nio-192.168.1] o.h.engine.jdbc.spi.SqlExceptionHelper   : [ID: 96016, Host: Media-Server] General error: "java.lang.IllegalStateException: Unable to read the page at position 143929370886335270 [1.4.200/6]"; SQL statement:
select searchresu0_.id as id1_13_, searchresu0_.details as details2_13_, searchresu0_.download_type as download3_13_, searchresu0_.first_found as first_fo4_13_, searchresu0_.indexer_id as indexer_9_13_, searchresu0_.indexerguid as indexerg5_13_, searchresu0_.indexersearchentity as indexer10_13_, searchresu0_.link as link6_13_, searchresu0_.pub_date as pub_date7_13_, searchresu0_.title as title8_13_ from searchresult searchresu0_ where upper(searchresu0_.title) like upper(?) escape ? [50000-200]
2020-12-09 18:43:47.528 ERROR --- [http-nio-192.168.1] o.n.d.IndexerUniquenessScoreSaver        : [ID: 96016, Host: Media-Server] Error while saving data for uniqueness scores

org.springframework.orm.jpa.JpaSystemException: could not extract ResultSet; nested exception is org.hibernate.exception.GenericJDBCException: could not extract ResultSet
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:353)
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:255)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:528)
	at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
	at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:153)
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:149) [1 skipped]
	at com.sun.proxy.$Proxy204.findAllByTitleLikeIgnoreCase(Unknown Source) [4 skipped]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at com.sun.proxy.$Proxy120.findAllByTitleLikeIgnoreCase(Unknown Source) [3 skipped]
	at org.nzbhydra.downloading.IndexerUniquenessScoreSaver.getIndexersFoundSameResult(IndexerUniquenessScoreSaver.java:123)
	at org.nzbhydra.downloading.IndexerUniquenessScoreSaver.handleDownloadEvent(IndexerUniquenessScoreSaver.java:82)
	at org.nzbhydra.downloading.IndexerUniquenessScoreSaver.onNzbDownloadEvent(IndexerUniquenessScoreSaver.java:66)
	at org.nzbhydra.downloading.IndexerUniquenessScoreSaver$$FastClassBySpringCGLIB$$75c773e.invoke(<generated>)
	at org.nzbhydra.downloading.IndexerUniquenessScoreSaver$$EnhancerBySpringCGLIB$$eb538b31.onNzbDownloadEvent(<generated>) [2 skipped]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:305) [1 skipped]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:190)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:153)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:404)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:374)
	at org.nzbhydra.downloading.FileHandler.publishEvents(FileHandler.java:178)
	at org.nzbhydra.downloading.FileHandler.handleContentDownload(FileHandler.java:159)
	at org.nzbhydra.downloading.FileHandler.getFileByResult(FileHandler.java:98)
	at org.nzbhydra.downloading.FileHandler.getFileByGuid(FileHandler.java:89)
	at org.nzbhydra.downloading.FileHandler$$FastClassBySpringCGLIB$$f3d132e2.invoke(<generated>)
	at org.springframework.transaction.interceptor.TransactionInterceptor$$Lambda$894/0x00000000a78e6fe0.proceedWithInvocation(Unknown Source) [4 skipped]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.nzbhydra.downloading.FileHandler$$EnhancerBySpringCGLIB$$45a2249d.getFileByGuid(<generated>) [3 skipped]
	at org.nzbhydra.downloading.nzbs.NzbHandlingWeb.downloadNzbWithApikey(NzbHandlingWeb.java:133)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.nzbhydra.auth.HydraAnonymousAuthenticationFilter.doFilter(HydraAnonymousAuthenticationFilter.java:101) [19 skipped]
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) [11 skipped]
	at org.nzbhydra.auth.HeaderAuthenticationFilter.doFilterInternal(HeaderAuthenticationFilter.java:55) [1 skipped]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116) [2 skipped]
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105) [8 skipped]
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56) [1 skipped]
	at org.nzbhydra.auth.ForwardedForRecognizingFilter.doFilterInternal(ForwardedForRecognizingFilter.java:52) [4 skipped]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93) [8 skipped]
	at org.nzbhydra.auth.HydraEmbeddedServletContainer$1.invoke(HydraEmbeddedServletContainer.java:89) [13 skipped]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) [4 skipped]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [2 skipped]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:845) [1 skipped]
Caused by: org.hibernate.exception.GenericJDBCException: could not extract ResultSet
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:67)
	at org.hibernate.loader.Loader.getResultSet(Loader.java:2285)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2038)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2000)
	at org.hibernate.loader.Loader.doQuery(Loader.java:951)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:352)
	at org.hibernate.loader.Loader.doList(Loader.java:2831)
	at org.hibernate.loader.Loader.doList(Loader.java:2813)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2645)
	at org.hibernate.loader.Loader.list(Loader.java:2640)
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:506)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:400)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:219)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1412)
	at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1565)
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1533)
	at org.hibernate.query.Query.getResultList(Query.java:165)
	at org.hibernate.query.criteria.internal.compile.CriteriaQueryTypeQueryAdapter.getResultList(CriteriaQueryTypeQueryAdapter.java:76)
	at org.springframework.data.jpa.repository.query.JpaQueryExecution$CollectionExecution.doExecute(JpaQueryExecution.java:126)
	at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:88)
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:154)
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:142)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor$QueryMethodInvoker.invoke(QueryExecutorMethodInterceptor.java:195)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:152)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:130)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:80) [1 skipped]
	at org.springframework.transaction.interceptor.TransactionInterceptor$$Lambda$894/0x00000000a78e6fe0.proceedWithInvocation(Unknown Source) [1 skipped]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139) [1 skipped]
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:149) [1 skipped]
	at com.sun.proxy.$Proxy204.findAllByTitleLikeIgnoreCase(Unknown Source) [4 skipped]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	... 142 common frames omitted
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: Unable to read the page at position 143929370886335270 [1.4.200/6]"; SQL statement:
select searchresu0_.id as id1_13_, searchresu0_.details as details2_13_, searchresu0_.download_type as download3_13_, searchresu0_.first_found as first_fo4_13_, searchresu0_.indexer_id as indexer_9_13_, searchresu0_.indexerguid as indexerg5_13_, searchresu0_.indexersearchentity as indexer10_13_, searchresu0_.link as link6_13_, searchresu0_.pub_date as pub_date7_13_, searchresu0_.title as title8_13_ from searchresult searchresu0_ where upper(searchresu0_.title) like upper(?) escape ? [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.command.Command.executeQuery(Command.java:212)
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:114)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:57)
	... 174 common frames omitted
Caused by: java.lang.IllegalStateException: Unable to read the page at position 143929370886335270 [1.4.200/6]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.MVStore.readPage(MVStore.java:2213)
	at org.h2.mvstore.MVMap.readPage(MVMap.java:672)
	at org.h2.mvstore.Page$NonLeaf.getChildPage(Page.java:1043)
	at org.h2.mvstore.Cursor.hasNext(Cursor.java:53)
	at org.h2.mvstore.tx.TransactionMap$CommittedIterator.fetchNext(TransactionMap.java:779)
	at org.h2.mvstore.tx.TransactionMap$TMIterator.next(TransactionMap.java:952)
	at org.h2.mvstore.db.MVPrimaryIndex$MVStoreCursor.next(MVPrimaryIndex.java:469)
	at org.h2.index.IndexCursor.next(IndexCursor.java:291)
	at org.h2.table.TableFilter.next(TableFilter.java:529)
	at org.h2.command.dml.Select$LazyResultQueryFlat.fetchNextRow(Select.java:1843)
	at org.h2.result.LazyResult.hasNext(LazyResult.java:101)
	at org.h2.result.LazyResult.next(LazyResult.java:60)
	at org.h2.command.dml.Select.queryFlat(Select.java:737)
	at org.h2.command.dml.Select.queryWithoutCache(Select.java:844)
	at org.h2.command.dml.Query.queryWithoutCacheLazyCheck(Query.java:201)
	at org.h2.command.dml.Query.query(Query.java:489)
	at org.h2.command.dml.Query.query(Query.java:451)
	at org.h2.command.CommandContainer.query(CommandContainer.java:285)
	at org.h2.command.Command.executeQuery(Command.java:195)
	... 178 common frames omitted
Caused by: java.lang.IllegalArgumentException: dateValue out of range 4398047545734
	at org.h2.value.ValueTimestamp.<init>(ValueTimestamp.java:59)
	at org.h2.value.ValueTimestamp.fromDateValueAndNanos(ValueTimestamp.java:77)
	at org.h2.mvstore.db.ValueDataType.readValue(ValueDataType.java:629)
	at org.h2.mvstore.db.ValueDataType.readValue(ValueDataType.java:707)
	at org.h2.mvstore.db.ValueDataType.read(ValueDataType.java:225)
	at org.h2.mvstore.tx.VersionedValueType.read(VersionedValueType.java:79)
	at org.h2.mvstore.tx.VersionedValueType.read(VersionedValueType.java:70)
	at org.h2.mvstore.Page$Leaf.readPayLoad(Page.java:1511)
	at org.h2.mvstore.Page.read(Page.java:607)
	at org.h2.mvstore.Page.read(Page.java:239)
	at org.h2.mvstore.MVStore.readPage(MVStore.java:2211)
	... 196 common frames omitted

2020-12-09 18:43:47.532 ERROR --- [http-nio-192.168.1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : [ID: 96016, Host: Media-Server] Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.orm.jpa.JpaSystemException: Unable to rollback against JDBC Connection; nested exception is org.hibernate.TransactionException: Unable to rollback against JDBC Connection] with root cause

java.lang.IllegalArgumentException: dateValue out of range 4398047545584
	at org.h2.value.ValueTimestamp.<init>(ValueTimestamp.java:59)
	at org.h2.value.ValueTimestamp.fromDateValueAndNanos(ValueTimestamp.java:77)
	at org.h2.mvstore.db.ValueDataType.readValue(ValueDataType.java:629)
	at org.h2.mvstore.db.ValueDataType.readValue(ValueDataType.java:707)
	at org.h2.mvstore.db.ValueDataType.read(ValueDataType.java:225)
	at org.h2.mvstore.tx.VersionedValueType.read(VersionedValueType.java:65)
	at org.h2.mvstore.Page$Leaf.readPayLoad(Page.java:1511)
	at org.h2.mvstore.Page.read(Page.java:607)
	at org.h2.mvstore.Page.read(Page.java:239)
	at org.h2.mvstore.MVStore.readPage(MVStore.java:2211)
	at org.h2.mvstore.MVMap.readPage(MVMap.java:672)
	at org.h2.mvstore.Page$NonLeaf.getChildPage(Page.java:1043)
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:748)
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:748)
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:748)
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:710)
	at org.h2.mvstore.MVStore.compactRewrite(MVStore.java:2137)
	at org.h2.mvstore.MVStore.rewriteChunks(MVStore.java:2026)
	at org.h2.mvstore.MVStore.doMaintenance(MVStore.java:2844)
	at org.h2.mvstore.MVStore.writeInBackground(MVStore.java:2788)
	at org.h2.mvstore.MVStore$BackgroundWriterThread.run(MVStore.java:3290)

**Comment by theotherp** [comment]
Please post your debug infos.

Sorry for the late response.

**Comment by sankermike4** [comment]
Since Hunter4vr hasn't responded please see my debug information below. I running into a similar issue with Radarr and NzbHydrav2. I'm currently using v3.8.1 and running NzbHydrav2 in linuxserver.io  v3.8.1-ls5 docker container. I've been running into this issue for a few weeks.

[nzbhydra-debuginfos-2020-12-30-18-50.zip](https://github.com/theotherp/nzbhydra2/files/5756130/nzbhydra-debuginfos-2020-12-30-18-50.zip)

**Comment by theotherp** [comment]
@sankermike4 There's a problem with the database which I can't explain, showing an error I've never seen and don't even find any google results about... You can try restoring from an older update or just shutdown hydra and delete the .db file. You'll lose history and stats but the config will be preserved.

**Comment by sankermike4** [comment]
Ok thanks for looking into it. I deleted the database and its working again. One thing to note is that using NzbHydra2 for torrrents worked fine.
