### ISSUE TITLE
Unable to update nzbhydra due to 500 error and java error seemingly caused by failing backup

### ISSUE THREAD

**Issue by dshokouhi** [theotherp/nzbhydra2#655]
**Set your log file level to debug, repeat the steps that cause the problem and post the debug infos ZIP which can be retrieved in the [System / Bugreport section](http://127.0.0.1:5076/system/bugreport). If other tools are involved post their logs as well.**

You don't have to follow the next steps by the letter, just think about what you're trying to achieve ;-) 

* What do you expect to happen? What does happen? 

I expect Hydra can be updated as it always has been

* Have you searched for this problem? You don't have to answer, just make sure.

Yes I don't see the exact java error in the issues tab

* Can the problem be reproduced? How?

Yes I can reproduce this issue by simply attempting to update via the UI.  I can also reproduce it by attempting to create a backup in the System page

* Use a proper title. Describe the problem succinctly, don't just copy and paste the error message.

When I attempt to update hydra I get the below java traceback in the logs

* If you use a docker container please tell me which one.
 
 I am running it on Windows via source I think

* If there's a bug with the GUI post at least your current version, OS, resolution and browser and post a screenshot if necessary.

I am using Windows 10 in chrome

**I will close your issues if I you didn't provide proper information as described as above**

The more information you provide up front the higher the chance that I can help you.
```
javax.persistence.PersistenceException: org.hibernate.exception.DataException: could not execute statement
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
	at org.hibernate.query.internal.AbstractProducedQuery.executeUpdate(AbstractProducedQuery.java:1621)
	at org.nzbhydra.backup.BackupAndRestore.backupDatabase(BackupAndRestore.java:166)
	at org.nzbhydra.backup.BackupAndRestore.backup(BackupAndRestore.java:92)
	at org.nzbhydra.backup.BackupAndRestore$$FastClassBySpringCGLIB$$bd5e894d.invoke()
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at org.nzbhydra.backup.BackupAndRestore$$EnhancerBySpringCGLIB$$290dd3ec.backup()
	at org.nzbhydra.backup.BackupWeb.backupOnly(BackupWeb.java:55)
	at org.nzbhydra.backup.BackupWeb$$FastClassBySpringCGLIB$$42929f7e.invoke()
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at org.nzbhydra.backup.BackupWeb$$EnhancerBySpringCGLIB$$85aa9065.backupOnly()
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.nzbhydra.auth.HydraAnonymousAuthenticationFilter.doFilter(HydraAnonymousAuthenticationFilter.java:101)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:158)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.nzbhydra.auth.HeaderAuthenticationFilter.doFilterInternal(HeaderAuthenticationFilter.java:55)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:204)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:117)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.nzbhydra.auth.ForwardedForRecognizingFilter.doFilterInternal(ForwardedForRecognizingFilter.java:52)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.ForwardedHeaderFilter.doFilterInternal(ForwardedHeaderFilter.java:158)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.nzbhydra.auth.HydraEmbeddedServletContainer$1.invoke(HydraEmbeddedServletContainer.java:89)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.hibernate.exception.DataException: could not execute statement
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:52)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:200)
	at org.hibernate.engine.query.spi.NativeSQLQueryPlan.performExecuteUpdate(NativeSQLQueryPlan.java:107)
	at org.hibernate.internal.SessionImpl.executeNativeUpdate(SessionImpl.java:1507)
	at org.hibernate.query.internal.NativeQueryImpl.doExecuteUpdate(NativeQueryImpl.java:295)
	at org.hibernate.query.internal.AbstractProducedQuery.executeUpdate(AbstractProducedQuery.java:1612)
	... 129 common frames omitted
Caused by: org.h2.jdbc.JdbcSQLDataException: Cannot parse "TIMESTAMP" constant "198960"; SQL statement:
BACKUP TO 'C:/nzbhydra2-1.5.2-windows/data/backup/nzbhydra-2020-12-17 10-33-23.zip'; [22007-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:457)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.value.ValueTimestamp.parse(ValueTimestamp.java:136)
	at org.h2.value.Value.convertToTimestamp(Value.java:1169)
	at org.h2.value.Value.convertTo(Value.java:822)
	at org.h2.value.Value.convertTo(Value.java:758)
	at org.h2.value.Value.compareTo(Value.java:1550)
	at org.h2.mvstore.db.ValueDataType.compareValues(ValueDataType.java:189)
	at org.h2.mvstore.db.ValueDataType.compare(ValueDataType.java:165)
	at org.h2.mvstore.MVMap.compare(MVMap.java:640)
	at org.h2.mvstore.Page.binarySearch(Page.java:391)
	at org.h2.mvstore.CursorPos.traverseDown(CursorPos.java:53)
	at org.h2.mvstore.MVMap.operate(MVMap.java:1804)
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:614)
	at org.h2.mvstore.MVMap.rewritePage(MVMap.java:775)
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:734)
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:748)
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:748)
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:748)
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:710)
	at org.h2.mvstore.MVStore.compactRewrite(MVStore.java:2137)
	at org.h2.mvstore.MVStore.rewriteChunks(MVStore.java:2026)
	at org.h2.mvstore.MVStore.compact(MVStore.java:2007)
	at org.h2.mvstore.db.MVTableEngine$Store.flush(MVTableEngine.java:275)
	at org.h2.command.dml.BackupCommand.backupTo(BackupCommand.java:63)
	at org.h2.command.dml.BackupCommand.update(BackupCommand.java:51)
	at org.h2.command.CommandContainer.update(CommandContainer.java:198)
	at org.h2.command.Command.executeUpdate(Command.java:251)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:191)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:152)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197)
	... 133 common frames omitted
Caused by: java.lang.IllegalArgumentException: 198960
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:166)
	at org.h2.util.DateTimeUtils.parseTimestamp(DateTimeUtils.java:316)
	at org.h2.value.ValueTimestamp.parse(ValueTimestamp.java:134)
	... 163 common frames omitted
```

![image](https://user-images.githubusercontent.com/1634145/102529704-26115500-4055-11eb-8720-781254a819a0.png)

![image](https://user-images.githubusercontent.com/1634145/102529749-388b8e80-4055-11eb-9c6f-8b86b1388f08.png)

**Comment by dshokouhi** [comment]
I restarted my host OS today after doing some updates and the error has changed actually.  Seems something got corrupted? Whats strange is that its still working 

```
2020-12-20 16:16:35.264 ERROR --- [http-nio-0.0.0.0-5] o.h.engine.jdbc.spi.SqlExceptionHelper   : [ID: 77579, Host: 192.168.1.1, User: boogie] General error: "java.lang.IllegalStateException: Unable to read the page at position 18831335706449488 [1.4.200/6]"; SQL statement:
BACKUP TO 'C:/nzbhydra2-1.5.2-windows/data/backup/nzbhydra-2020-12-20 16-16-34.zip'; [50000-200]
2020-12-20 16:16:35.272 ERROR --- [http-nio-0.0.0.0-5] org.nzbhydra.backup.BackupWeb            : [ID: 77579, Host: 192.168.1.1, User: boogie] Error while creating backup

javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: could not execute statement
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
	at org.hibernate.query.internal.AbstractProducedQuery.executeUpdate(AbstractProducedQuery.java:1621)
	at org.nzbhydra.backup.BackupAndRestore.backupDatabase(BackupAndRestore.java:166)
	at org.nzbhydra.backup.BackupAndRestore.backup(BackupAndRestore.java:92)
	at org.nzbhydra.backup.BackupAndRestore$$FastClassBySpringCGLIB$$bd5e894d.invoke(<generated>)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367) [4 skipped]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.nzbhydra.backup.BackupAndRestore$$EnhancerBySpringCGLIB$$967c2367.backup(<generated>) [3 skipped]
	at org.nzbhydra.backup.BackupWeb.backupAndDownload(BackupWeb.java:36)
	at org.nzbhydra.backup.BackupWeb$$FastClassBySpringCGLIB$$42929f7e.invoke(<generated>)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367) [4 skipped]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69) [2 skipped]
	at org.nzbhydra.backup.BackupWeb$$EnhancerBySpringCGLIB$$e22d6b5b.backupAndDownload(<generated>) [3 skipped]
	at org.nzbhydra.auth.HydraAnonymousAuthenticationFilter.doFilter(HydraAnonymousAuthenticationFilter.java:101) [22 skipped]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126) [3 skipped]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:158) [7 skipped]
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) [3 skipped]
	at org.nzbhydra.auth.HeaderAuthenticationFilter.doFilterInternal(HeaderAuthenticationFilter.java:55) [1 skipped]
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:204) [2 skipped]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116) [2 skipped]
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105) [8 skipped]
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56) [1 skipped]
	at org.nzbhydra.auth.ForwardedForRecognizingFilter.doFilterInternal(ForwardedForRecognizingFilter.java:52) [4 skipped]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93) [8 skipped]
	at org.nzbhydra.auth.HydraEmbeddedServletContainer$1.invoke(HydraEmbeddedServletContainer.java:89) [14 skipped]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) [4 skipped]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [2 skipped]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source) [1 skipped]
Caused by: org.hibernate.exception.GenericJDBCException: could not execute statement
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:200)
	at org.hibernate.engine.query.spi.NativeSQLQueryPlan.performExecuteUpdate(NativeSQLQueryPlan.java:107)
	at org.hibernate.internal.SessionImpl.executeNativeUpdate(SessionImpl.java:1507)
	at org.hibernate.query.internal.NativeQueryImpl.doExecuteUpdate(NativeQueryImpl.java:295)
	at org.hibernate.query.internal.AbstractProducedQuery.executeUpdate(AbstractProducedQuery.java:1612)
	... 129 common frames omitted
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: Unable to read the page at position 18831335706449488 [1.4.200/6]"; SQL statement:
BACKUP TO 'C:/nzbhydra2-1.5.2-windows/data/backup/nzbhydra-2020-12-20 16-16-34.zip'; [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.command.Command.executeUpdate(Command.java:259)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:191)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:152)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197)
	... 133 common frames omitted
Caused by: java.lang.IllegalStateException: Unable to read the page at position 18831335706449488 [1.4.200/6]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.MVStore.readPage(MVStore.java:2213)
	at org.h2.mvstore.MVMap.readPage(MVMap.java:672)
	at org.h2.mvstore.Page$NonLeaf.getChildPage(Page.java:1043)
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:748)
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:748)
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:748)
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:710)
	at org.h2.mvstore.MVStore.compactRewrite(MVStore.java:2137)
	at org.h2.mvstore.MVStore.rewriteChunks(MVStore.java:2026)
	at org.h2.mvstore.MVStore.compact(MVStore.java:2007)
	at org.h2.mvstore.db.MVTableEngine$Store.flush(MVTableEngine.java:275)
	at org.h2.command.dml.BackupCommand.backupTo(BackupCommand.java:63)
	at org.h2.command.dml.BackupCommand.update(BackupCommand.java:51)
	at org.h2.command.CommandContainer.update(CommandContainer.java:198)
	at org.h2.command.Command.executeUpdate(Command.java:251)
	... 138 common frames omitted
Caused by: org.h2.message.DbException: File corrupted while reading record: "type: 235". Possible solution: use the recovery tool [90030-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.mvstore.db.ValueDataType.readValue(ValueDataType.java:766)
	at org.h2.mvstore.db.ValueDataType.read(ValueDataType.java:225)
	at org.h2.mvstore.tx.VersionedValueType.read(VersionedValueType.java:65)
	at org.h2.mvstore.Page$Leaf.readPayLoad(Page.java:1511)
	at org.h2.mvstore.Page.read(Page.java:607)
	at org.h2.mvstore.Page.read(Page.java:239)
	at org.h2.mvstore.MVStore.readPage(MVStore.java:2211)
	... 152 common frames omitted
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: File corrupted while reading record: "type: 235". Possible solution: use the recovery tool [90030-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 161 common frames omitted

2020-12-20 16:16:35.288 ERROR --- [http-nio-0.0.0.0-5] o.a.c.c.C.[.[.[.[dispatcherServlet]      : [ID: 77579, Host: 192.168.1.1, User: boogie] Servlet.service() for servlet [dispatcherServlet] in context with path [/nzbhydra] threw exception [Request processing failed; nested exception is org.springframework.orm.jpa.JpaSystemException: Unable to rollback against JDBC Connection; nested exception is org.hibernate.TransactionException: Unable to rollback against JDBC Connection] with root cause

java.lang.IllegalArgumentException: 198960
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:166)
	at org.h2.util.DateTimeUtils.parseTimestamp(DateTimeUtils.java:316)
	at org.h2.value.ValueTimestamp.parse(ValueTimestamp.java:134)
	at org.h2.value.Value.convertToTimestamp(Value.java:1169)
	at org.h2.value.Value.convertTo(Value.java:822)
	at org.h2.value.Value.convertTo(Value.java:758)
	at org.h2.value.Value.compareTo(Value.java:1550)
	at org.h2.mvstore.db.ValueDataType.compareValues(ValueDataType.java:189)
	at org.h2.mvstore.db.ValueDataType.compare(ValueDataType.java:165)
	at org.h2.mvstore.MVMap.compare(MVMap.java:640)
	at org.h2.mvstore.Page.binarySearch(Page.java:391)
	at org.h2.mvstore.CursorPos.traverseDown(CursorPos.java:53)
	at org.h2.mvstore.MVMap.operate(MVMap.java:1804)
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:614)
	at org.h2.mvstore.MVMap.rewritePage(MVMap.java:775)
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:734)
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:748)
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:748)
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:748)
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:710)
	at org.h2.mvstore.MVStore.compactRewrite(MVStore.java:2137)
	at org.h2.mvstore.MVStore.rewriteChunks(MVStore.java:2026)
	at org.h2.mvstore.MVStore.writeInBackground(MVStore.java:2802)
	at org.h2.mvstore.MVStore$BackgroundWriterThread.run(MVStore.java:3290)
```

**Comment by theotherp** [comment]
The database is corrupted. You can try repairing the db by starting the wrapper with the `--repairdb` command. Otherwise restore from an older backup or just delete it.
