### ISSUE TITLE
Since update 3.10.1 (websocket) multiple issue

### ISSUE THREAD

**Issue by sooslaca** [theotherp/nzbhydra2#683]
Hi, looks like websocket implementation since v3.10.1 has some issues (still in 3.11.1 which is the newest as of today).

Some logs from browser dev tools:
```
Firefox can’t establish a connection to the server at wss://nzbhydra.home/nzbhydra/websocket/568/4mznh22p/websocket. sockjs.js:1687
Firefox can’t establish a connection to the server at https://nzbhydra.home/nzbhydra/websocket/568/fso1v0lh/eventsource. 2 sockjs.js:2251
Firefox can’t establish a connection to the server at wss://nzbhydra.home/nzbhydra/websocket/612/d0qzevs4/websocket. sockjs.js:1687
Firefox can’t establish a connection to the server at https://nzbhydra.home/nzbhydra/websocket/612/ilurdmiz/eventsource. 2 sockjs.js:2251
Uncaught Error: Incompatibile SockJS! Main site uses: "1.5.0", the iframe: "1.0.0".
    s https://cdn.jsdelivr.net/sockjs/1.0.0/sockjs.min.js:2
    attachEvent https://cdn.jsdelivr.net/sockjs/1.0.0/sockjs.min.js:3
    bootstrap_iframe https://cdn.jsdelivr.net/sockjs/1.0.0/sockjs.min.js:2
    _sockjs_onload https://nzbhydra.home/nzbhydra/websocket/iframe.html#hspqbqmk:8
sockjs.min.js:2:4344
GEThttps://nzbhydra.home/nzbhydra/websocket/568/umajgbl2/jsonp?c=_jp.ascsjor
[HTTP/2 404 Not Found 12ms]

GEThttps://nzbhydra.home/nzbhydra/websocket/612/1obyvpb4/jsonp?c=_jp.abkvecq
[HTTP/2 404 Not Found 11ms]

The resource from “https://nzbhydra.home/nzbhydra/websocket/568/umajgbl2/jsonp?c=_jp.ascsjor” was blocked due to MIME type (“”) mismatch (X-Content-Type-Options: nosniff).
nzbhydra
Loading failed for the <script> with source “https://nzbhydra.home/nzbhydra/websocket/568/umajgbl2/jsonp?c=_jp.ascsjor”. nzbhydra:1:1
The resource from “https://nzbhydra.home/nzbhydra/websocket/612/1obyvpb4/jsonp?c=_jp.abkvecq” was blocked due to MIME type (“”) mismatch (X-Content-Type-Options: nosniff).
nzbhydra
Loading failed for the <script> with source “https://nzbhydra.home/nzbhydra/websocket/612/1obyvpb4/jsonp?c=_jp.abkvecq”. nzbhydra:1:1
```

Some logs from server side:
```
2021-01-31 20:13:49.192 ERROR --- [http-nio-0.0.0.0-5] o.a.c.c.C.[.[.[.[dispatcherServlet]      : [Host: 192.168.x.x] Servlet.service() for servlet [dispatcherServlet] in context with path [/nzbhydra] threw exception [Request processing failed; nested exception is org.springframework.web.socket.sockjs.SockJsException: Uncaught failure in SockJS request, uri=https://nzbhydra.home/nzbhydra/websocket/612/ws5gnvbj/xhr?t=1612120329317; nested exception is org.springframework.web.socket.sockjs.SockJsTransportFailureException: Failed to open session; nested exception is java.lang.IllegalArgumentException: Async support must be enabled on a servlet and for all filters involved in async request processing. This is done in Java code using the Servlet API or by adding "<async-supported>true</async-supported>" to servlet and filter declarations in web.xml. Also you must use a Servlet 3.0+ container] with root cause
java.lang.IllegalArgumentException: Async support must be enabled on a servlet and for all filters involved in async request processing. This is done in Java code using the Servlet API or by adding "<async-supported>true</async-supported>" to servlet and filter declarations in web.xml. Also you must use a Servlet 3.0+ container
        at org.springframework.http.server.ServletServerHttpAsyncRequestControl.<init>(ServletServerHttpAsyncRequestControl.java:61)
        at org.springframework.web.socket.sockjs.transport.session.AbstractHttpSockJsSession.handleInitialRequest(AbstractHttpSockJsSession.java:225)
        at org.springframework.web.socket.sockjs.transport.handler.AbstractHttpSendingTransportHandler.handleRequest(AbstractHttpSendingTransportHandler.java:66)
        at org.springframework.web.socket.sockjs.support.AbstractSockJsService.handleRequest(AbstractSockJsService.java:439)
        at org.nzbhydra.auth.HydraAnonymousAuthenticationFilter.doFilter(HydraAnonymousAuthenticationFilter.java:101) [13 skipped]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
        at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:158) [1 skipped]

2021-01-31 20:13:49.504  WARN --- [http-nio-0.0.0.0-5] o.s.w.s.s.t.h.DefaultSockJsService       : [Host: 192.168.x.x] Origin check enabled but transport 'jsonp' does not support it.
```

I'm using https://hub.docker.com/layers/linuxserver/nzbhydra2/version-v3.11.1/images/sha256-d64ec3ae58c1030408690996a6930d24339606515884f309cb279f82470705bb?context=explore

**Comment by theotherp** [comment]
I'd expect at least to see the debug infos, additionally which browser you're using.

**Comment by theotherp** [comment]
Nvm, I can reproduce this.

**Comment by theotherp** [comment]
Add this to your nginx location:

```
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
```

**Comment by theotherp** [comment]
Interesting that it took 3 days until this was reported...

**Comment by sooslaca** [comment]
Awesome I'm not on nginx but the two rows helped me to solve the same on my environment.
If anyone needs the traefik version of the above:
```
      - "traefik.http.routers.nzbhydra.middlewares=sslheader"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
```

**Comment by nemchik** [comment]
Anyone using lsio swag (formerly named letsencrypt) please see this comment if you have issues getting websockets working with the included proxy samples https://github.com/linuxserver/reverse-proxy-confs/issues/198#issuecomment-690733011

**Comment by EricHupp** [comment]
Does this apply to caddy as well? 

I keep getting random lockouts with sonarr but nothing else. 
I tried putting it in my code block but it kept making caddy fail, so I would assume I'm putting it in wrong. 


`hydra.plexapp.org {


handle /* {

reverse_proxy 192.168.1.99:5076

}

}`

**Comment by hamiltont** [comment]
Note: per the advice [here](https://www.nginx.com/blog/websocket-nginx), the correct config is a just a small bit more fancy. Specifically, nginx advises informing the proxied server that they will close every single connection unless there is specifically a header present that requests to upgrade the connection

> We’re adding the map block so that the Connection header is correctly set to close when the Upgrade header in the request is set to ''

**Comment by nemchik** [comment]
> Note: per the advice [here](https://www.nginx.com/blog/websocket-nginx), the correct config is a just a small bit more fancy. Specifically, nginx advises informing the proxied server that they will close every single connection unless there is specifically a header present that requests to upgrade the connection
> 
> > We’re adding the map block so that the Connection header is correctly set to close when the Upgrade header in the request is set to ''

P.s. this is correctly handled in the lsio swag configs.
