### ISSUE TITLE
nzbhydrawrapper doesn't convert javaversion argument to int

### ISSUE THREAD

**Issue by ghost** [theotherp/nzbhydra2#724]
Running `/usr/bin/python3 /opt/nzbhydra/nzbhydra2wrapperPy3.py --nobrowser --javaversion` results in the following error:

```
Aug 26 23:55:59 cadoth python3[2288907]: Logging wrapper output to /opt/nzbhydra/data/logs/wrapper.log                                                            Aug 26 23:55:59 cadoth python3[2288907]: Traceback (most recent call last):                                                                                       
Aug 26 23:55:59 cadoth python3[2288907]:   File "/opt/nzbhydra/nzbhydra2wrapperPy3.py", line 587, in <module>                                                     Aug 26 23:55:59 cadoth python3[2288907]:     process = startup()                                                                                                  
Aug 26 23:55:59 cadoth python3[2288907]:   File "/opt/nzbhydra/nzbhydra2wrapperPy3.py", line 377, in startup                                                      Aug 26 23:55:59 cadoth python3[2288907]:     if javaVersion < 9:                                                                                                  
Aug 26 23:55:59 cadoth python3[2288907]: TypeError: '<' not supported between instances of 'str' and 'int' 
```

Using `--java /usr/lib/jvm/java-11-openjdk-amd64/bin/java` instead worked.

* OS: Debian 11
* NZBHydra 3.15.1

**Comment by theotherp** [comment]
That likely just means that whatever java version returns an output that the parser cannot read.
Please run `java -version` and post the output.
