### ISSUE TITLE
adding my own spotweb instance

### ISSUE THREAD

**Issue by digrouz** [theotherp/nzbhydra2#747]
Hello,

I'm having some troubles adding my own spotweb instance. when I try to add it, I get error message:
2021-12-14 09:12:26.187  INFO --- [http-nio-0.0.0.0-5] o.n.indexers.capscheck.IndexerChecker    : [ID: 25286, Host: <hidden ip>] Will check capabilities of indexer tatooine-spotweb using 2 concurrent connections and a delay of 1000ms
2021-12-14 09:12:30.532 ERROR --- [http-nio-0.0.0.0-5] o.n.indexers.capscheck.IndexerChecker    : [ID: 25286, Host: <hidden ip>] Error while communicating with indexer: org.nzbhydra.indexers.exceptions.IndexerAccessException: Unable to parse indexer output
2021-12-14 09:12:30.532 ERROR --- [http-nio-0.0.0.0-5] o.n.indexers.capscheck.IndexerChecker    : [ID: 25286, Host: <hidden ip>] Error while communicating with indexer: org.nzbhydra.indexers.exceptions.IndexerAccessException: Unable to parse indexer output
2021-12-14 09:12:30.533 ERROR --- [http-nio-0.0.0.0-5] o.n.indexers.capscheck.IndexerChecker    : [ID: 25286, Host: <hidden ip>] Error while communicating with indexer: org.nzbhydra.indexers.exceptions.IndexerAccessException: Unable to parse indexer output
2021-12-14 09:12:30.533 ERROR --- [http-nio-0.0.0.0-5] o.n.indexers.capscheck.IndexerChecker    : [ID: 25286, Host: <hidden ip>] Error while communicating with indexer: org.nzbhydra.indexers.exceptions.IndexerAccessException: Unable to parse indexer output
2021-12-14 09:12:30.533 ERROR --- [http-nio-0.0.0.0-5] o.n.indexers.capscheck.IndexerChecker    : [ID: 25286, Host: <hidden ip>] Error while communicating with indexer: org.nzbhydra.indexers.exceptions.IndexerAccessException: Unable to parse indexer output
2021-12-14 09:12:30.533 ERROR --- [http-nio-0.0.0.0-5] o.n.indexers.capscheck.IndexerChecker    : [ID: 25286, Host: <hidden ip>] Error while communicating with indexer: org.nzbhydra.indexers.exceptions.IndexerAccessException: Unable to parse indexer output
2021-12-14 09:12:30.533 ERROR --- [http-nio-0.0.0.0-5] o.n.indexers.capscheck.IndexerChecker    : [ID: 25286, Host: <hidden ip>] Error while communicating with indexer: org.nzbhydra.indexers.exceptions.IndexerAccessException: Unable to parse indexer output
2021-12-14 09:12:30.533  INFO --- [http-nio-0.0.0.0-5] o.n.indexers.capscheck.IndexerChecker    : [ID: 25286, Host: <hidden ip>] Indexer own-spotweb does not support searching by any IDs
2021-12-14 09:12:30.555 ERROR --- [http-nio-0.0.0.0-5] o.n.indexers.capscheck.IndexerChecker    : [ID: 25286, Host: <hidden ip>] Error while accessing indexer: Unable to parse indexer output
2021-12-14 09:12:30.555  INFO --- [http-nio-0.0.0.0-5] o.n.indexers.capscheck.IndexerChecker    : [ID: 25286, Host: <hidden ip>] Indexer own-spotweb didn't provide a backend type. Will use newznab.

From nginx point of view, i get only 200 return codes:
10.42.0.1 - digrouz [14/Dec/2021:09:12:27 +0000] "GET /index.php?page=newznabapi?apikey=<hidden key>&t=tvsearch&rid=24493 HTTP/1.1" 200 1541 "-" "NZBHydra2" "0.006" "0.004" "2.33"
10.42.0.1 - digrouz [14/Dec/2021:09:12:27 +0000] "GET /index.php?page=newznabapi?apikey=<hidden key>&t=tvsearch&tvdbid=121361 HTTP/1.1" 200 1543 "-" "NZBHydra2" "0.010" "0.012" "2.33"
10.42.0.1 - digrouz [14/Dec/2021:09:12:28 +0000] "GET /index.php?page=newznabapi?apikey=<hidden key>&t=tvsearch&tvmazeid=82 HTTP/1.1" 200 1541 "-" "NZBHydra2" "0.010" "0.012" "2.33"
10.42.0.1 - digrouz [14/Dec/2021:09:12:28 +0000] "GET /index.php?page=newznabapi?apikey=<hidden key>&t=tvsearch&traktid=1390 HTTP/1.1" 200 1541 "-" "NZBHydra2" "0.003" "0.004" "2.34"
10.42.0.1 - digrouz [14/Dec/2021:09:12:29 +0000] "GET /index.php?page=newznabapi?apikey=<hidden key>&t=tvsearch&imdbid=0944947 HTTP/1.1" 200 1544 "-" "NZBHydra2" "0.004" "0.004" "2.33"
10.42.0.1 - digrouz [14/Dec/2021:09:12:29 +0000] "GET /index.php?page=newznabapi?apikey=<hidden key>&t=movie&tmdbid=24428 HTTP/1.1" 200 1539 "-" "NZBHydra2" "0.004" "0.000" "2.34"
10.42.0.1 - digrouz [14/Dec/2021:09:12:30 +0000] "GET /index.php?page=newznabapi?apikey=<hidden key>&t=movie&imdbid=0848228 HTTP/1.1" 200 1542 "-" "NZBHydra2" "0.005" "0.004" "2.33"
10.42.0.1 - digrouz [14/Dec/2021:09:12:30 +0000] "GET /index.php?page=newznabapi?apikey=<hidden key>&t=caps HTTP/1.1" 200 1529 "-" "NZBHydra2" "0.004" "0.004" "2.34"

so I don't really understand why it does not work. I'm using last version of both products: nzbhydra 3.18.4 and spotweb 1.5.1. How can I debug further?

**Comment by theotherp** [comment]
Your spotweb instance doesn't return newznab compatible results under that
path.

**Comment by digrouz** [comment]
Is there any specific to use ?

**Comment by theotherp** [comment]
I don't know spotweb. It's whatever URL you would enter in sonarr or radarr or whatever.

**Comment by digrouz** [comment]
this url seems to work properly within sickchill

**Comment by theotherp** [comment]
Post your debug infos zip.

**Comment by henroFall** [comment]
Hello, necro-thread. This is still an issue, there is chatter online about changing the setting under NZB Handling to "Merge NZB Files" and not "compress NZB files to 1-zip file," but my preference was already set that way. My spotweb instance works fine if I type in manual queries, but when NZBHydra tries to query, it logs a time out. I can check the abilities of the server just fine, that step does not error out.

```
org.nzbhydra.indexers.exceptions.IndexerUnreachableException: Error while communicating with indexer spotweb.local. Server returned: timeout. Code: 0
	at org.nzbhydra.indexers.IndexerWebAccess.get(IndexerWebAccess.java:111)
	at org.nzbhydra.indexers.Indexer.callInderWebAccess(Indexer.java:400)
	at org.nzbhydra.indexers.Indexer.getAndStoreResultToDatabase(Indexer.java:391)
	at org.nzbhydra.indexers.Newznab.getAndStoreResultToDatabase(Newznab.java:331)
	at org.nzbhydra.indexers.Newznab.getAndStoreResultToDatabase(Newznab.java:74)
	at org.nzbhydra.indexers.Indexer.buildSearchUrlAndCall(Indexer.java:212)
	at org.nzbhydra.indexers.Indexer.search(Indexer.java:146)
	at org.nzbhydra.searching.Searcher.lambda$getIndexerCallable$12(Searcher.java:437)
	at java.base@22.0.1/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at org.nzbhydra.logging.MdcThreadPoolExecutor$1.run(MdcThreadPoolExecutor.java:111)
	at java.base@22.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base@22.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base@22.0.1/java.lang.Thread.runWith(Thread.java:1583)
	at java.base@22.0.1/java.lang.Thread.run(Thread.java:1570)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:853)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:829)
Caused by: org.nzbhydra.webaccess.WebAccessException: timeout. Code: 0
	at org.nzbhydra.webaccess.WebAccess.callUrl(WebAccess.java:115)
	at org.nzbhydra.webaccess.WebAccess.callUrl(WebAccess.java:53)
	at org.nzbhydra.indexers.IndexerWebAccess.lambda$get$0(IndexerWebAccess.java:83)
	... 8 common frames omitted
Caused by: java.net.SocketTimeoutException: timeout
	at okio.SocketAsyncTimeout.newTimeoutException(JvmOkio.kt:147)
	at okio.AsyncTimeout.access$newTimeoutException(AsyncTimeout.kt:158)
	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:337)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:427)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:320)
	at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:180)
	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:110)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at org.nzbhydra.webaccess.WebAccess.callUrl(WebAccess.java:91)
	... 10 common frames omitted
	Suppressed: java.io.IOException: unexpected end of stream on http://192.168.200.138/...
		at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:210)
		... 24 common frames omitted
	Caused by: java.io.EOFException: \n not found: limit=0 content=…
		at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:332)
		at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
		at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:180)
		... 24 common frames omitted
Caused by: java.net.SocketException: Socket closed
	at java.base@22.0.1/sun.nio.ch.NioSocketImpl.endRead(NioSocketImpl.java:243)
	at java.base@22.0.1/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
	at java.base@22.0.1/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)
	at java.base@22.0.1/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)
	at java.base@22.0.1/java.net.Socket$SocketInputStream.implRead(Socket.java:1108)
	at java.base@22.0.1/java.net.Socket$SocketInputStream.read(Socket.java:1095)
	at okio.InputStreamSource.read(JvmOkio.kt:94)
	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:125)
	... 28 common frames omitted

2025-03-31 18:19:00.638  WARN --- [  pool-16-thread-4] org.nzbhydra.indexers.Newznab            : [ID: 91065, Host: 192.168.200.131] Because an error occurred spotweb.local will be temporarily disabled until 2025-03-31T18:24:00.638600Z. This is error number 1 in a row
```
