### ISSUE TITLE
Can't start the program

### ISSUE THREAD

**Issue by ZePequeno2** [theotherp/nzbhydra2#755]
ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'dogNZB': Unsatisfied dependency expressed through field 'unmarshaller'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'marshaller' defined in class path resource [org/nzbhydra/web/WebConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[])" because "com.sun.xml.bind.v2.runtime.reflect.opt.Injector.defineClass" is null

**Comment by theotherp** [comment]
Please post a full log and tell me the Java version which you're running.

**Comment by ZePequeno2** [comment]
Installed OpenJDK ver 17.0.2

2022-01-29 17:17:04,615  INFO - Starting NZBHydra main process with command line: java -Xmx256M -DfromWrapper -XX:TieredStopAtLevel=1 -noverify -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=C:\Users\USER\Desktop\misc\nzbhydra2\data\logs -jar C:\Users\USER\Desktop\misc\nzbhydra2\lib\core-3.17.3-exec.jar --datafolder C:\Users\USER\Desktop\misc\nzbhydra2\data in folder C:\Users\USER\Desktop\misc\nzbhydra2
JVMJ9VM193W Como o Java 13 -Xverify:none e -noverify foram descontinuados para remoção, eles podem não ser opções aceitas no futuro.
17:17:08.047 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/C:/Users/USER/Desktop/misc/nzbhydra2/lib/core-3.17.3-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep006to007.class]
17:17:08.060 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/C:/Users/USER/Desktop/misc/nzbhydra2/lib/core-3.17.3-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep004to005.class]
17:17:08.061 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/C:/Users/USER/Desktop/misc/nzbhydra2/lib/core-3.17.3-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep005to006.class]
17:17:08.063 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Ignored because not a concrete top-level class: URL [jar:file:/C:/Users/USER/Desktop/misc/nzbhydra2/lib/core-3.17.3-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep.class]
17:17:08.064 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/C:/Users/USER/Desktop/misc/nzbhydra2/lib/core-3.17.3-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep003to004.class]
17:17:08.065 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/C:/Users/USER/Desktop/misc/nzbhydra2/lib/core-3.17.3-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep007to008.class]
17:17:08.066 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/C:/Users/USER/Desktop/misc/nzbhydra2/lib/core-3.17.3-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep011to012.class]
17:17:08.067 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/C:/Users/USER/Desktop/misc/nzbhydra2/lib/core-3.17.3-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep009to010.class]
17:17:08.068 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/C:/Users/USER/Desktop/misc/nzbhydra2/lib/core-3.17.3-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep008to009.class]
17:17:08.069 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/C:/Users/USER/Desktop/misc/nzbhydra2/lib/core-3.17.3-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep010to011.class]
17:17:08.070 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/C:/Users/USER/Desktop/misc/nzbhydra2/lib/core-3.17.3-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep014to015.class]
17:17:08.071 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/C:/Users/USER/Desktop/misc/nzbhydra2/lib/core-3.17.3-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep013to014.class]
17:17:08.072 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/C:/Users/USER/Desktop/misc/nzbhydra2/lib/core-3.17.3-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep012to013.class]
17:17:08.073 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/C:/Users/USER/Desktop/misc/nzbhydra2/lib/core-3.17.3-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep017to018.class]
17:17:08.074 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/C:/Users/USER/Desktop/misc/nzbhydra2/lib/core-3.17.3-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep015to016.class]
17:17:08.075 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/C:/Users/USER/Desktop/misc/nzbhydra2/lib/core-3.17.3-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep016to017.class]
17:17:08.078 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/C:/Users/USER/Desktop/misc/nzbhydra2/lib/core-3.17.3-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep018to019.class]
17:17:08.329 [main] DEBUG org.nzbhydra.config.ConfigReaderWriter - Writing to file C:\Users\USER\Desktop\misc\nzbhydra2\data\nzbhydra.yml
17:17:08.371 [main] DEBUG org.nzbhydra.config.ConfigReaderWriter - Writing config took 214ms
17:17:08.389 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.host to 0.0.0.0
17:17:08.389 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.port to 5076
17:17:08.390 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.urlBase to /
17:17:08.390 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.ssl to false
17:17:08.390 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.databaseCompactTime to 15000
17:17:08.390 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.databaseRetentionTime to 1000
17:17:08.390 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.databaseWriteDelay to 5000
17:17:08.391 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.logging.consolelevel to INFO
17:17:08.391 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.logging.logfilelevel to INFO
17:17:08.391 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.logging.logMaxHistory to 30
17:17:08.600 [main] DEBUG org.nzbhydra.database.DatabaseRecreation - Determining if database recreation is needed
17:17:09.378 [main] DEBUG org.nzbhydra.database.DatabaseRecreation - No migration scripts found to run. Skipping database recreation
.__   __.  ________  .______   __    __  ____    ____  _______  .______          ___          ___
|  \ |  | |       /  |   _  \ |  |  |  | \   \  /   / |       \ |   _  \        /   \        |__ \
|   \|  | `---/  /   |  |_)  ||  |__|  |  \   \/   /  |  .--.  ||  |_)  |      /  ^  \          ) |
|  . `  |    /  /    |   _  < |   __   |   \_    _/   |  |  |  ||      /      /  /_\  \        / /
|  |\   |   /  /----.|  |_)  ||  |  |  |     |  |     |  '--'  ||  |\  \----./  _____  \      / /_
|__| \__|  /________||______/ |__|  |__|     |__|     |_______/ | _| `._____/__/     \__\    |____|

2022-01-29 17:17:11.369  INFO --- [              main] org.nzbhydra.NzbHydra                    : Starting NzbHydra on DESKTOP-69QQM1D with PID 8896 (C:\Users\USER\Desktop\misc\nzbhydra2\lib\core-3.17.3-exec.jar started by USER in C:\Users\USER\Desktop\misc\nzbhydra2)
2022-01-29 17:17:11.403  INFO --- [              main] org.nzbhydra.NzbHydra                    : The following profiles are active: default
2022-01-29 17:17:18.647  INFO --- [              main] org.nzbhydra.config.BaseConfig           : Using data folder C:\Users\USER\Desktop\misc\nzbhydra2\data
2022-01-29 17:17:20.103  INFO --- [              main] o.n.a.HydraAnonymousAuthenticationFilter : Granting basic user rights to anonymous users
2022-01-29 17:17:20.105  INFO --- [              main] o.n.a.HydraAnonymousAuthenticationFilter : Granting stats rights to anonymous users
2022-01-29 17:17:20.108  INFO --- [              main] o.n.a.HydraAnonymousAuthenticationFilter : Granting admin rights to anonymous users
2022-01-29 17:17:20.476  INFO --- [              main] o.f.c.internal.license.VersionPrinter    : Flyway Community Edition 6.2.0 by Redgate
2022-01-29 17:17:20.543  INFO --- [              main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2022-01-29 17:17:20.609  INFO --- [              main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2022-01-29 17:17:20.652  INFO --- [              main] o.f.c.internal.database.DatabaseFactory  : Database: jdbc:h2:file:C:\Users\USER\Desktop\misc\nzbhydra2\data/database/nzbhydra (H2 1.4)
2022-01-29 17:17:20.862  INFO --- [              main] o.f.core.internal.command.DbValidate     : Successfully validated 28 migrations (execution time 00:00.105s)
2022-01-29 17:17:20.904  INFO --- [              main] o.f.core.internal.command.DbMigrate      : Current version of schema "PUBLIC": 5
2022-01-29 17:17:20.911  INFO --- [              main] o.f.core.internal.command.DbMigrate      : Schema "PUBLIC" is up to date. No migration necessary.
2022-01-29 17:17:21.210  INFO --- [              main] org.nzbhydra.NzbHydra                    : Adding windows system tray icon
2022-01-29 17:17:21.730  INFO --- [              main] o.n.d.downloaders.DownloaderProvider     : Loading downloaders
2022-01-29 17:17:21.732  INFO --- [              main] o.n.d.downloaders.DownloaderProvider     : Finished initializing active downloaders
2022-01-29 17:17:21.734  INFO --- [              main] o.n.d.downloaders.DownloaderProvider     : No downloaders configured
2022-01-29 17:17:23.607 ERROR --- [              main] c.s.x.b.v2.runtime.reflect.opt.Injector  : null

java.security.PrivilegedActionException: null
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:743)
        at com.sun.xml.bind.v2.runtime.reflect.opt.Injector.<clinit>(Injector.java:197)
        at com.sun.xml.bind.v2.runtime.reflect.opt.AccessorInjector.prepare(AccessorInjector.java:81)
        at com.sun.xml.bind.v2.runtime.reflect.opt.OptimizedAccessorFactory.get(OptimizedAccessorFactory.java:125)
        at com.sun.xml.bind.v2.runtime.reflect.Accessor$GetterSetterReflection.optimize(Accessor.java:402)
        at com.sun.xml.bind.v2.runtime.property.SingleElementLeafProperty.<init>(SingleElementLeafProperty.java:92)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at com.sun.xml.bind.v2.runtime.property.PropertyFactory.create(PropertyFactory.java:128)
        at com.sun.xml.bind.v2.runtime.ClassBeanInfoImpl.<init>(ClassBeanInfoImpl.java:181)
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getOrCreate(JAXBContextImpl.java:514)
        at com.sun.xml.bind.v2.runtime.ClassBeanInfoImpl.<init>(ClassBeanInfoImpl.java:168)
Caused by: java.lang.NoSuchMethodException: sun.misc.Unsafe.defineClass(java.lang.String, [B, int, int, java.lang.ClassLoader, java.security.ProtectionDomain)
        at java.base/java.lang.Class.newNoSuchMethodException(Class.java:658)
        at java.base/java.lang.Class.throwExceptionOrReturnNull(Class.java:1456)
        at java.base/java.lang.Class.getMethodHelper(Class.java:1542)
        at java.base/java.lang.Class.getMethod(Class.java:1448)
        at com.sun.xml.bind.v2.runtime.reflect.opt.Injector$3.run(Injector.java:201)
        at com.sun.xml.bind.v2.runtime.reflect.opt.Injector$3.run(Injector.java:197)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:739)
        at com.sun.xml.bind.v2.runtime.reflect.opt.Injector.<clinit>(Injector.java:197)
        at com.sun.xml.bind.v2.runtime.reflect.opt.AccessorInjector.prepare(AccessorInjector.java:81)
        at com.sun.xml.bind.v2.runtime.reflect.opt.OptimizedAccessorFactory.get(OptimizedAccessorFactory.java:125)
        at com.sun.xml.bind.v2.runtime.reflect.Accessor$GetterSetterReflection.optimize(Accessor.java:402)
        at com.sun.xml.bind.v2.runtime.property.SingleElementLeafProperty.<init>(SingleElementLeafProperty.java:92)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

2022-01-29 17:17:23.645  WARN --- [              main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'dogNzb': Unsatisfied dependency expressed through field 'unmarshaller'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'marshaller' defined in class path resource [org/nzbhydra/web/WebConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[])" because "com.sun.xml.bind.v2.runtime.reflect.opt.Injector.defineClass" is null
2022-01-29 17:17:23.647  INFO --- [              main] org.nzbhydra.WindowsTrayIcon             : Removing tray icon
2022-01-29 17:17:23.694  WARN --- [              main] .s.c.a.CommonAnnotationBeanPostProcessor : Destroy method on bean with name 'nzbHydra' threw an exception: org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'delegatingApplicationListener': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
2022-01-29 17:17:25.402 ERROR --- [        HydraTask1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task

org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'delegatingApplicationListener': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:212)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:207)
        at org.springframework.context.event.AbstractApplicationEventMulticaster.retrieveApplicationListeners(AbstractApplicationEventMulticaster.java:245)
        at org.springframework.context.event.AbstractApplicationEventMulticaster.getApplicationListeners(AbstractApplicationEventMulticaster.java:197)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:134)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:404)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:361)
        at org.springframework.boot.autoconfigure.orm.jpa.DataSourceInitializedPublisher.publishEventIfRequired(DataSourceInitializedPublisher.java:99)
        at org.springframework.boot.autoconfigure.orm.jpa.DataSourceInitializedPublisher.access$100(DataSourceInitializedPublisher.java:50)
        at org.springframework.boot.autoconfigure.orm.jpa.DataSourceInitializedPublisher$DataSourceSchemaCreatedPublisher.lambda$postProcessEntityManagerFactory$0(DataSourceInitializedPublisher.java:200)
        at org.springframework.boot.autoconfigure.orm.jpa.DataSourceInitializedPublisher$DataSourceSchemaCreatedPublisher$$Lambda$892/0x000000005a829c18.run(Unknown Source)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

2022-01-29 17:17:25.417  INFO --- [              main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2022-01-29 17:17:25.451  INFO --- [              main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2022-01-29 17:17:25.531 ERROR --- [              main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'dogNzb': Unsatisfied dependency expressed through field 'unmarshaller'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'marshaller' defined in class path resource [org/nzbhydra/web/WebConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[])" because "com.sun.xml.bind.v2.runtime.reflect.opt.Injector.defineClass" is null
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:643)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:130)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1422)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
        at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$272/0x00000000585a9900.getObject(Unknown Source)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:893)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'marshaller' defined in class path resource [org/nzbhydra/web/WebConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[])" because "com.sun.xml.bind.v2.runtime.reflect.opt.Injector.defineClass" is null
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
        at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$272/0x00000000585a9900.getObject(Unknown Source)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1304)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1224)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:130)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1422)
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[])" because "com.sun.xml.bind.v2.runtime.reflect.opt.Injector.defineClass" is null
        at com.sun.xml.bind.v2.runtime.reflect.opt.Injector.inject(Injector.java:311)
        at com.sun.xml.bind.v2.runtime.reflect.opt.Injector.inject(Injector.java:97)
        at com.sun.xml.bind.v2.runtime.reflect.opt.AccessorInjector.prepare(AccessorInjector.java:87)
        at com.sun.xml.bind.v2.runtime.reflect.opt.OptimizedAccessorFactory.get(OptimizedAccessorFactory.java:125)
        at com.sun.xml.bind.v2.runtime.reflect.Accessor$GetterSetterReflection.optimize(Accessor.java:402)
        at com.sun.xml.bind.v2.runtime.property.SingleElementLeafProperty.<init>(SingleElementLeafProperty.java:92)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at com.sun.xml.bind.v2.runtime.property.PropertyFactory.create(PropertyFactory.java:128)
        at com.sun.xml.bind.v2.runtime.ClassBeanInfoImpl.<init>(ClassBeanInfoImpl.java:181)
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getOrCreate(JAXBContextImpl.java:514)
        at com.sun.xml.bind.v2.runtime.ClassBeanInfoImpl.<init>(ClassBeanInfoImpl.java:168)

2022-01-29 17:17:25.543 ERROR --- [              main] org.nzbhydra.NzbHydra                    : An unexpected error occurred during startup

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'dogNzb': Unsatisfied dependency expressed through field 'unmarshaller'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'marshaller' defined in class path resource [org/nzbhydra/web/WebConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[])" because "com.sun.xml.bind.v2.runtime.reflect.opt.Injector.defineClass" is null
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:643)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:130)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1422)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
        at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$272/0x00000000585a9900.getObject(Unknown Source)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:893)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'marshaller' defined in class path resource [org/nzbhydra/web/WebConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[])" because "com.sun.xml.bind.v2.runtime.reflect.opt.Injector.defineClass" is null
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
        at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$272/0x00000000585a9900.getObject(Unknown Source)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1304)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1224)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:130)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1422)
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[])" because "com.sun.xml.bind.v2.runtime.reflect.opt.Injector.defineClass" is null
        at com.sun.xml.bind.v2.runtime.reflect.opt.Injector.inject(Injector.java:311)
        at com.sun.xml.bind.v2.runtime.reflect.opt.Injector.inject(Injector.java:97)
        at com.sun.xml.bind.v2.runtime.reflect.opt.AccessorInjector.prepare(AccessorInjector.java:87)
        at com.sun.xml.bind.v2.runtime.reflect.opt.OptimizedAccessorFactory.get(OptimizedAccessorFactory.java:125)
        at com.sun.xml.bind.v2.runtime.reflect.Accessor$GetterSetterReflection.optimize(Accessor.java:402)
        at com.sun.xml.bind.v2.runtime.property.SingleElementLeafProperty.<init>(SingleElementLeafProperty.java:92)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at com.sun.xml.bind.v2.runtime.property.PropertyFactory.create(PropertyFactory.java:128)
        at com.sun.xml.bind.v2.runtime.ClassBeanInfoImpl.<init>(ClassBeanInfoImpl.java:181)
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getOrCreate(JAXBContextImpl.java:514)
        at com.sun.xml.bind.v2.runtime.ClassBeanInfoImpl.<init>(ClassBeanInfoImpl.java:168)

**Comment by theotherp** [comment]
Sorry for the late response. Can you please try an older java version? Java 17 is supported but perhaps there are still problems with it.
