### ISSUE TITLE
Testers needed - Migrate to new database library

### ISSUE THREAD

**Issue by theotherp** [theotherp/nzbhydra2#764]
Please comment here if you're interested in testing an alpha/beta with a new database library. This new version may hopefully be a bit more performant, *may* result in smaller database files (for those suffering from very larg ones) and / or give me options to fine tune how data is compacted (for those where a lot of IO is produced).

Notes:

- You need to be running NZBHydra as a binary (i.e. not in docker) because you have to manually update the jar file. If you know how to do that in a container that's fine as well.
- This is for a short test only. You will need make a copy of your data, run the new version, check if the database is migrated properly and ideally keep it running for few days. You may need to return to the older version and thus lose all the history that has been written during that time.

**Comment by joaoptc** [comment]
Hello !
Just send the link and I will test it.
I have to delete my DB once in a while so ... starting from scratch is not a big deal for me ....

**Comment by pilonull** [comment]
I can give it a shot. I'm running nzbhydra as a binary and I could care less about my db getting wiped.

**Comment by theotherp** [comment]
Thanks! I'll comment when I have a (hopefully) proper version.

**Comment by jjaomni** [comment]
i'm game if you got any more slots open...

**Comment by theotherp** [comment]
Hi all. Thanks (again) for commenting. I'm kinda busy at the moment and
wouldn't want you to test stuff without me being able to properly respond
or help out. I'll let you know when I have time to do this.

**Comment by dovzamir** [comment]
Be happy to join the testers when you find the time to get back on the horse.

**Comment by Viper780** [comment]
I could also test it. nzbhydra2 is running on FreeBSD here.
But a testsetup under Windows or Linux should also ich be viable

**Comment by Viper780** [comment]
Hi @theotherp 

Startup under FreeBSD went without a hitch. But as soon as a application trys the API it throws an error.
See the attached debug log
[nzbhydra-debuginfos-2022-11-01-20-55.zip](https://github.com/theotherp/nzbhydra2/files/9913614/nzbhydra-debuginfos-2022-11-01-20-55.zip)

**Comment by theotherp** [comment]
@Viper780 Thanks for the fast test! I'll look into it. Everybody else: This may be a bigger problem, please leave the testing until this is fixed.

**Comment by Viper780** [comment]
Sorry for the late reply
Had a few minutes today an nzbhydra2 is running for a few hours now. Looks very promising. I'll let it run over the weekend.

Would there be a option to use a "real database" in the future ?

**Comment by Viper780** [comment]
@theotherp 
Some of the stats are empty (NZB downloads per age (in 100 day steps, all downloads), Indexer API accesses and Avg. response times (in ms) )

**Comment by Viper780** [comment]
The (automatic) Update from today brakes nzbhydra2

`root@NZB:/usr/local/share/nzbhydra2 # /usr/local/openjdk8/bin/java -Xmx1000M -DfromWrapper -XX:TieredStopAtLevel=1 -noverify -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/usr/local/nzbhydra2/logs -Dspring.output.ansi.enabled=ALWAYS -jar /usr/local/share/nzbhydra2/lib/core-4.7.2-exec.jar --nobrowser --datafolder /usr/local/nzbhydra2 in folder /usr/local/share/nzbhydra2
21:14:26.749 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/usr/local/share/nzbhydra2/lib/core-4.7.2-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep005to006.class]
21:14:26.751 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/usr/local/share/nzbhydra2/lib/core-4.7.2-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep012to013.class]
21:14:26.751 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/usr/local/share/nzbhydra2/lib/core-4.7.2-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep009to010.class]
21:14:26.752 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/usr/local/share/nzbhydra2/lib/core-4.7.2-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep003to004.class]
21:14:26.752 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/usr/local/share/nzbhydra2/lib/core-4.7.2-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep004to005.class]
21:14:26.752 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/usr/local/share/nzbhydra2/lib/core-4.7.2-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep007to008.class]
21:14:26.752 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Ignored because not a concrete top-level class: URL [jar:file:/usr/local/share/nzbhydra2/lib/core-4.7.2-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep.class]
21:14:26.752 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/usr/local/share/nzbhydra2/lib/core-4.7.2-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep006to007.class]
21:14:26.752 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/usr/local/share/nzbhydra2/lib/core-4.7.2-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep008to009.class]
21:14:26.752 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/usr/local/share/nzbhydra2/lib/core-4.7.2-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep010to011.class]
21:14:26.753 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/usr/local/share/nzbhydra2/lib/core-4.7.2-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep011to012.class]
21:14:26.753 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/usr/local/share/nzbhydra2/lib/core-4.7.2-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep013to014.class]
21:14:26.753 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/usr/local/share/nzbhydra2/lib/core-4.7.2-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep014to015.class]
21:14:26.753 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/usr/local/share/nzbhydra2/lib/core-4.7.2-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep015to016.class]
21:14:26.753 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/usr/local/share/nzbhydra2/lib/core-4.7.2-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep018to019.class]
21:14:26.753 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/usr/local/share/nzbhydra2/lib/core-4.7.2-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep017to018.class]
21:14:26.753 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/usr/local/share/nzbhydra2/lib/core-4.7.2-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep016to017.class]
21:14:26.854 [main] DEBUG org.nzbhydra.config.ConfigReaderWriter - Writing to file /usr/local/nzbhydra2/nzbhydra.yml
21:14:26.874 [main] DEBUG org.nzbhydra.config.ConfigReaderWriter - Writing config took 97ms
21:14:26.874 [main] DEBUG org.nzbhydra.NzbHydra - Setting property browser.disabled to value true
21:14:26.889 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.host to 0.0.0.0
21:14:26.889 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.port to 5076
21:14:26.889 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.urlBase to /
21:14:26.889 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.ssl to true
21:14:26.889 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.sslKeyStore to /usr/local/nzbhydra2/keystore.p12
21:14:26.889 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.sslKeyStorePassword to geheim220
21:14:26.889 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.databaseCompactTime to 30000
21:14:26.889 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.databaseRetentionTime to 1000
21:14:26.889 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.databaseWriteDelay to 5000
21:14:26.890 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.logging.consolelevel to INFO
21:14:26.890 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.logging.logfilelevel to WARN
21:14:26.890 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.logging.logMaxHistory to 30
21:14:26.938 [main] DEBUG org.nzbhydra.database.DatabaseRecreation - Determining if database recreation is needed
21:14:26.998 [main] ERROR org.nzbhydra.NzbHydra - An unexpected error occurred during startup
org.h2.jdbc.JdbcSQLNonTransientConnectionException: File corrupted while reading record: null. Possible solution: use the recovery tool [90030-200]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
        at org.h2.message.DbException.get(DbException.java:194)
        at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:222)
        at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:182)
        at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
        at org.h2.engine.Database.getPageStore(Database.java:2659)
        at org.h2.engine.Database.open(Database.java:675)
        at org.h2.engine.Database.openDatabase(Database.java:307)
        at org.h2.engine.Database.<init>(Database.java:301)
        at org.h2.engine.Engine.openSession(Engine.java:74)
        at org.h2.engine.Engine.openSession(Engine.java:192)
        at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
        at org.h2.engine.Engine.createSession(Engine.java:166)
        at org.h2.engine.Engine.createSession(Engine.java:29)
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
        at org.h2.Driver.connect(Driver.java:69)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:247)
        at org.nzbhydra.database.DatabaseRecreation.isDatabaseRecreationNotNeeded(DatabaseRecreation.java:91)
        at org.nzbhydra.database.DatabaseRecreation.runDatabaseScript(DatabaseRecreation.java:75)
        at org.nzbhydra.NzbHydra.startup(NzbHydra.java:192)
        at org.nzbhydra.NzbHydra.main(NzbHydra.java:119)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.lang.IllegalStateException: The write format 2 is larger than the supported format 1, and the file was not opened in read-only mode [1.4.200/5]
        at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
        at org.h2.mvstore.MVStore.readStoreHeader(MVStore.java:741)
        at org.h2.mvstore.MVStore.<init>(MVStore.java:396)
        at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
        at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
        ... 28 common frames omitted
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: File corrupted while reading record: null. Possible solution: use the recovery tool [90030-200]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
        at org.h2.message.DbException.get(DbException.java:194)
        at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:222)
        at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:182)
        at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
        at org.h2.engine.Database.getPageStore(Database.java:2659)
        at org.h2.engine.Database.open(Database.java:675)
        at org.h2.engine.Database.openDatabase(Database.java:307)
        at org.h2.engine.Database.<init>(Database.java:301)
        at org.h2.engine.Engine.openSession(Engine.java:74)
        at org.h2.engine.Engine.openSession(Engine.java:192)
        at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
        at org.h2.engine.Engine.createSession(Engine.java:166)
        at org.h2.engine.Engine.createSession(Engine.java:29)
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
        at org.h2.Driver.connect(Driver.java:69)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:247)
        at org.nzbhydra.database.DatabaseRecreation.isDatabaseRecreationNotNeeded(DatabaseRecreation.java:91)
        at org.nzbhydra.database.DatabaseRecreation.runDatabaseScript(DatabaseRecreation.java:75)
        at org.nzbhydra.NzbHydra.startup(NzbHydra.java:192)
        at org.nzbhydra.NzbHydra.main(NzbHydra.java:119)
        ... 8 more
Caused by: java.lang.IllegalStateException: The write format 2 is larger than the supported format 1, and the file was not opened in read-only mode [1.4.200/5]
        at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
        at org.h2.mvstore.MVStore.readStoreHeader(MVStore.java:741)
        at org.h2.mvstore.MVStore.<init>(MVStore.java:396)
        at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
        at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
        ... 28 more`

**Comment by theotherp** [comment]
Thanks for the info. That was to be expected. Sorry if that wasn't clear.
You should upgrade to the latest version (delete your database file first
or restore from the last backup before using the test version).

Hopefully I'll find some time to develop this further next year.

**Comment by Viper780** [comment]
For me it was a bit unexpected because I thought i did deactivate the autoupdate. obviously not.

Your backup before updates worked like a charm and the data isn't needed. So there was no harm.
If you need any further testing with the new DB lib just ask again,

**Comment by theotherp** [comment]
New DB is live. Thanks all.
