### ISSUE TITLE
Search broken after java 8 update 333 (win x64)

### ISSUE THREAD

**Issue by wally-nl** [theotherp/nzbhydra2#773]
After installing latest java update (java 8 update 333, x64 on windows 10 in this case) indexer gets disabled after every search (so could be java issue, will try to reinstall previous version)

java.lang.NoClassDefFoundError: Could not initialize class okhttp3.internal.platform.Platform
	at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:263)
	at okhttp3.OkHttpClient.(OkHttpClient.java:229)
	at okhttp3.OkHttpClient.(OkHttpClient.java:202)
	at org.nzbhydra.webaccess.HydraOkHttp3ClientHttpRequestFactory.getBaseBuilder(HydraOkHttp3ClientHttpRequestFactory.java:187)
	at org.nzbhydra.webaccess.HydraOkHttp3ClientHttpRequestFactory.getOkHttpClientBuilder(HydraOkHttp3ClientHttpRequestFactory.java:137)
	at org.nzbhydra.webaccess.WebAccess.callUrl(WebAccess.java:87)
	at org.nzbhydra.webaccess.WebAccess.callUrl(WebAccess.java:53)
	at org.nzbhydra.indexers.IndexerWebAccess.lambda$get$0(IndexerWebAccess.java:71)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at org.nzbhydra.logging.MdcThreadPoolExecutor$1.run(MdcThreadPoolExecutor.java:114)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by wally-nl** [comment]
issue gone after downgrade to java 8 update 331
