### ISSUE TITLE
BUG - Crashing on startup

### ISSUE THREAD

**Issue by scottismyname** [theotherp/nzbhydra2#788]
I am running on a Synology in a docker container (hotio/nzbhydra2:latest).  My synology got updated, and when my system restarted, the program would not start.  I was able to get it to start by moving the database files out of the way.  I then tried restoring both backups that I had, and they would fail with the same issues.  Would really like to try to preserve my database as I'm a nerd and love stats :)

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-env-file-init: executing...
[cont-init.d] 00-env-file-init: exited 0.
[cont-init.d] 00-start-container: executing...

----------------------------------------------------------------------
ENVIRONMENT
----------------------------------------------------------------------
PUID=1026
PGID=100
UMASK=022
TZ=America/Los_Angeles
----------------------------------------------------------------------

Executing usermod...
usermod: no changes
Applying permissions to /config
[cont-init.d] 00-start-container: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Logging wrapper output to /config/logs/wrapper.log
2022-08-11 08:44:55,706  INFO - Determined java version as '11' from version string 'openjdk version "11.0.15" 2022-04-19'
2022-08-11 08:44:55,706  INFO - Starting NZBHydra main process with command line: java -Xmx256M -DfromWrapper -XX:TieredStopAtLevel=1 -noverify -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/config/logs -Dspring.output.ansi.enabled=ALWAYS -jar /app/bin/lib/core-4.4.0-exec.jar --nobrowser --datafolder /config in folder /app/bin
08:44:56.810 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/bin/lib/core-4.4.0-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep014to015.class]
08:44:56.811 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/bin/lib/core-4.4.0-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep003to004.class]
08:44:56.812 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/bin/lib/core-4.4.0-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep006to007.class]
08:44:56.812 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/bin/lib/core-4.4.0-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep008to009.class]
08:44:56.813 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/bin/lib/core-4.4.0-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep011to012.class]
08:44:56.813 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/bin/lib/core-4.4.0-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep015to016.class]
08:44:56.813 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/bin/lib/core-4.4.0-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep018to019.class]
08:44:56.814 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/bin/lib/core-4.4.0-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep017to018.class]
08:44:57.024 [main] DEBUG org.nzbhydra.config.ConfigReaderWriter - Writing to file /config/nzbhydra.yml
08:44:57.051 [main] DEBUG org.nzbhydra.NzbHydra - Setting property browser.disabled to value true
08:44:57.081 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.port to 5076
08:44:57.081 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.ssl to false
08:44:57.081 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.databaseRetentionTime to 1000
08:44:57.081 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.logging.consolelevel to DEBUG
08:44:57.081 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.logging.logMaxHistory to 30
08:44:57.547 [main] ERROR org.nzbhydra.NzbHydra - An unexpected error occurred during startup
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
        at org.h2.message.DbException.get(DbException.java:194)
        at org.h2.message.DbException.toSQLException(DbException.java:319)
        at org.h2.jdbc.JdbcConnection.close(JdbcConnection.java:461)
        at org.nzbhydra.database.DatabaseRecreation.runDatabaseScript(DatabaseRecreation.java:75)
        at org.nzbhydra.NzbHydra.main(NzbHydra.java:119)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
        at org.h2.mvstore.Page.getKey(Page.java:270)
        at org.h2.mvstore.MVMap.rewrite(MVMap.java:734)
        at org.h2.mvstore.MVStore.compactRewrite(MVStore.java:2137)
        at org.h2.mvstore.MVStore.compact(MVStore.java:2007)
        at org.h2.mvstore.MVStore.closeStore(MVStore.java:1170)
        at org.h2.mvstore.db.MVTableEngine$Store.close(MVTableEngine.java:404)
        at org.h2.engine.Database.closeImpl(Database.java:1454)
        at org.h2.engine.Database.removeSession(Database.java:1307)
        at org.h2.jdbc.JdbcConnection.close(JdbcConnection.java:453)
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
        at org.h2.message.DbException.get(DbException.java:194)
        at org.h2.message.DbException.toSQLException(DbException.java:319)
        at org.h2.jdbc.JdbcConnection.close(JdbcConnection.java:461)
        at org.nzbhydra.database.DatabaseRecreation.runDatabaseScript(DatabaseRecreation.java:75)
        at org.nzbhydra.NzbHydra.main(NzbHydra.java:119)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at org.h2.mvstore.MVMap.rewritePage(MVMap.java:773)
        at org.h2.mvstore.MVMap.rewrite(MVMap.java:710)
        at org.h2.mvstore.MVStore.rewriteChunks(MVStore.java:2026)
        at org.h2.mvstore.MVStore.compactFile(MVStore.java:1968)
        at org.h2.mvstore.MVStore.close(MVStore.java:1133)
        at org.h2.engine.Database.closeOpenFilesAndUnlock(Database.java:1545)
        at org.h2.engine.Database.close(Database.java:1373)
        at org.h2.engine.Session.close(Session.java:963)
        ... 12 more
2022-08-11 08:44:57,576  ERROR - Main process shut down unexpectedly. If the wrapper was started in daemon mode you might not see the error output. Start Hydra manually with the same parameters in the same environment to see it
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Comment by theotherp** [comment]
The database file is corrupted. Try restoring it from the latest backup or
delete it (you'll lose stats and history but no config).

**Comment by scottismyname** [comment]
I actually did for both backups I have and I get the same problem

**Comment by scottismyname** [comment]
@theotherp is there any way for me to try to open the db file locally? It doesn't appear to be a sqllite file.

**Comment by theotherp** [comment]
No there isn't. Unfortunately I can't really help right now as I'm on
vacation. If neither restoring nor deleting the file help I'm not sure what
will.
You can try installing hydra on another machine (perhaps using the same
database file) and if it works you can transfer the file back.

**Comment by scottismyname** [comment]
No worries! Hope you enjoy your vacation!

I was able to open all of my saved databases using RazorSQL and opening the h2 database.  Querying works fine on all databases and I can see the tables.

Not sure why hydra is crapping out on it though.

I tried copying the database file to a windows machine and using that file and it errors out with the same problem as my docker container on the synology.

The good news is that the database seems to be in tact, the bad news is that hydra doesn't like it for some reason!  Maybe when you return from vacation you can help me debug :)

**Comment by scottismyname** [comment]
@theotherp Wondering if you might have time now to help me dig into this? If not, no worries, it's more for my curiosity than anything else.

**Comment by theotherp** [comment]
Sorry, kinda forgot about that. 

With the new version the database has been upgraded. 

The problem with the database is that it may be corrupted and you'd never know if you don't access the section that's corrupted. That's why the old code would make backups of the already corrupted database, resulting in a false sense of security. The new version checks the integrity of the database before making a backup. If a backup fails you get notified and at least can restore from the latest (valid) backup.

**Comment by theotherp** [comment]
Please reopen if you're still affected.
