### ISSUE TITLE
Unable to send test notification to Apprise API

### ISSUE THREAD

**Issue by armanatz** [theotherp/nzbhydra2#806]
### Some info in case needed:
**NZBHydra2 version:** `4.6.1`
**Running in Docker:** `Yes`
**Docker image:** `binhex/arch-nzbhydra2`
**System:** `Unraid 6.9.2`

---

I am trying to hook up NZBHydra2 to an Apprise API Docker container that I have set up but whenever I try to send a test notification to see if it is working, I get an Error 500 as per the screenshot below:

![image](https://user-images.githubusercontent.com/3622268/196511710-17efd060-e18f-4202-a3da-85de396e29e2.png)

I searched my logs and found this entry that seems to point to a runtime error occurring whenever a test notification is sent:

```
2022-10-19 01:43:43.665 ERROR --- [http-nio-0.0.0.0-5] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : [ID: 24503, Host: 10.20.0.20] Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java
.lang.RuntimeException: Unable to create test notification for event type VIP_RENEWAL_REQUIRED] with root cause

java.lang.RuntimeException: Unable to create test notification for event type VIP_RENEWAL_REQUIRED
        at org.nzbhydra.notifications.NotificationsWeb.testNotification(NotificationsWeb.java:105)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.nzbhydra.auth.HydraAnonymousAuthenticationFilter.doFilter(HydraAnonymousAuthenticationFilter.java:101) [22 skipped]
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) [16 skipped]
        at org.nzbhydra.auth.AsyncSupportFilter.doFilterInternal(AsyncSupportFilter.java:35) [1 skipped]
        at org.nzbhydra.auth.HeaderAuthenticationFilter.doFilterInternal(HeaderAuthenticationFilter.java:55) [2 skipped]
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103) [2 skipped]
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110) [8 skipped]
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80)
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55) [1 skipped]
        at org.nzbhydra.auth.ForwardedForRecognizingFilter.doFilterInternal(ForwardedForRecognizingFilter.java:37) [4 skipped]
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96) [8 skipped]
        at org.nzbhydra.auth.HydraEmbeddedServletContainer$1.invoke(HydraEmbeddedServletContainer.java:89) [10 skipped]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382) [4 skipped]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895)
        at java.base/java.lang.Thread.run(Thread.java:829) [5 skipped]
```

**Comment by silv3r23** [comment]
Same issue here, v4.6.1 with dockerized binhex/arch-nzbhydra2

**Comment by theotherp** [comment]
Do you mean https://hub.docker.com/r/caronc/apprise ?

**Comment by siggijarl** [comment]
Same issue.
but I have both nzhydra and apprise installed locally in Windows.

> An error occurred:
> 500: Internal Server Error
> 
> Path: /internalapi/notifications/test/UPDATE_INSTALLED
> 
> Message: undefined

Apprise works fine if I use it from the cmd line.

Log:
```
2022-11-30 16:18:27.609 ERROR --- [http-nio-redacted] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : [Host: redacted] Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: Unable to create test notification for event type UPDATE_INSTALLED] with root cause

java.lang.RuntimeException: Unable to create test notification for event type UPDATE_INSTALLED
	at org.nzbhydra.notifications.NotificationsWeb.testNotification(NotificationsWeb.java:105)
	at org.nzbhydra.notifications.NotificationsWeb$$FastClassBySpringCGLIB$$9341de4a.invoke(<generated>)
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:61) [4 skipped]
	at org.nzbhydra.notifications.NotificationsWeb$$EnhancerBySpringCGLIB$$9cc3f878.testNotification(<generated>) [3 skipped]
	at org.nzbhydra.auth.HydraAnonymousAuthenticationFilter.doFilter(HydraAnonymousAuthenticationFilter.java:101) [22 skipped]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115) [9 skipped]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:102) [9 skipped]
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:93)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) [3 skipped]
	at org.nzbhydra.auth.AsyncSupportFilter.doFilterInternal(AsyncSupportFilter.java:35) [1 skipped]
	at org.nzbhydra.auth.HeaderAuthenticationFilter.doFilterInternal(HeaderAuthenticationFilter.java:55) [2 skipped]
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:219) [2 skipped]
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:213)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103) [1 skipped]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110) [8 skipped]
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55) [1 skipped]
	at org.nzbhydra.auth.ForwardedForRecognizingFilter.doFilterInternal(ForwardedForRecognizingFilter.java:37) [4 skipped]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96) [8 skipped]
	at org.nzbhydra.auth.HydraEmbeddedServletContainer$1.invoke(HydraEmbeddedServletContainer.java:89) [10 skipped]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382) [4 skipped]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895)
	at java.lang.Thread.run(Unknown Source) [5 skipped]

```

**Comment by theotherp** [comment]
Sorry for the late response. This seems to be caused by the container but so far I have been unable to determine why.

**Comment by siggijarl** [comment]
I just got the 4.7.2 update and it's fixed for me!

![image](https://user-images.githubusercontent.com/81829230/204906467-e504a655-b2a1-4450-bc00-dc4f465d22df.png)
