### ISSUE TITLE
Binsearch Parser Throws Error on 0 Results

### ISSUE THREAD

**Issue by Alamei** [theotherp/nzbhydra2#81]
Minor bug: If you run a search with Binsearch targeted as an indexer and said search returns 0 results, the parser throws a hard exception looking for the first element of an empty array:
```
java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at org.nzbhydra.indexers.Binsearch.completeIndexerSearchResult(Binsearch.java:60)
	at org.nzbhydra.indexers.Binsearch.completeIndexerSearchResult(Binsearch.java:40)
	at org.nzbhydra.indexers.Indexer.searchInternal(Indexer.java:176)
	at org.nzbhydra.indexers.Indexer.search(Indexer.java:106)
	at org.nzbhydra.searching.Searcher.lambda$getIndexerCallable$14(Searcher.java:348)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at org.nzbhydra.logging.MdcThreadPoolExecutor$1.run(MdcThreadPoolExecutor.java:114)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by theotherp** [comment]
Thanks.
