### ISSUE TITLE
org.hibernate.LazyInitializationException: could not initialize proxy [org.nzbhydra.indexers.IndexerSearchEntity#7284433] - no Session

### ISSUE THREAD

**Issue by brianjmurrell** [theotherp/nzbhydra2#815]
I'm randomly getting the following in my logs along with an error reported to the client:

```
2023-01-08 04:12:39.019  INFO --- [http-nio-0.0.0.0-5] org.nzbhydra.downloading.FileHandler     : [ID: 33364, Host: localhost] REDIRECT download request for "[redacted]" from indexer [redacted]
2023-01-08 04:12:39.169 ERROR --- [http-nio-0.0.0.0-5] o.n.d.IndexerUniquenessScoreSaver        : [ID: 33364, Host: localhost] Error while saving data for uniqueness scores

org.hibernate.LazyInitializationException: could not initialize proxy [org.nzbhydra.indexers.IndexerSearchEntity#7284433] - no Session
        at org.hibernate.proxy.AbstractLazyInitializer.initialize(AbstractLazyInitializer.java:176)
        at org.hibernate.proxy.AbstractLazyInitializer.getImplementation(AbstractLazyInitializer.java:322)
        at org.hibernate.proxy.pojo.bytebuddy.ByteBuddyInterceptor.intercept(ByteBuddyInterceptor.java:45)
        at org.hibernate.proxy.ProxyConfiguration$InterceptorDispatcher.intercept(ProxyConfiguration.java:95)
        at org.nzbhydra.indexers.IndexerSearchEntity$HibernateProxy$ykFzq1Ee.getSuccessful(Unknown Source)
        at org.nzbhydra.downloading.IndexerUniquenessScoreSaver.getIndexersFoundSameResult(IndexerUniquenessScoreSaver.java:129)
        at org.nzbhydra.downloading.IndexerUniquenessScoreSaver.handleDownloadEvent(IndexerUniquenessScoreSaver.java:82)
        at org.nzbhydra.downloading.IndexerUniquenessScoreSaver.onNzbDownloadEvent(IndexerUniquenessScoreSaver.java:66)
        at org.nzbhydra.downloading.IndexerUniquenessScoreSaver$$FastClassBySpringCGLIB$$75c773e.invoke(<generated>)
        at org.nzbhydra.downloading.IndexerUniquenessScoreSaver$$EnhancerBySpringCGLIB$$94deffad.onNzbDownloadEvent(<generated>) [2 skipped]
        at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:344) [4 skipped]
        at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:229)
        at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:166)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:391)
        at org.nzbhydra.downloading.FileHandler.publishEvents(FileHandler.java:206)
        at org.nzbhydra.downloading.FileHandler.handleRedirect(FileHandler.java:199)
        at org.nzbhydra.downloading.FileHandler.getFileByResult(FileHandler.java:122)
        at org.nzbhydra.downloading.FileHandler.getFileByResult(FileHandler.java:116)
        at org.nzbhydra.downloading.FileHandler.getFileByGuid(FileHandler.java:90)
        at org.nzbhydra.downloading.FileHandler$$FastClassBySpringCGLIB$$f3d132e2.invoke(<generated>)
        at org.nzbhydra.downloading.FileHandler$$EnhancerBySpringCGLIB$$ef2d9919.getFileByGuid(<generated>) [2 skipped]
        at org.nzbhydra.downloading.nzbs.NzbHandlingWeb.downloadNzbWithApikey(NzbHandlingWeb.java:139)
        at org.nzbhydra.downloading.nzbs.NzbHandlingWeb$$FastClassBySpringCGLIB$$fbb32e1e.invoke(<generated>)
        at org.nzbhydra.downloading.nzbs.NzbHandlingWeb$$EnhancerBySpringCGLIB$$4579976c.downloadNzbWithApikey(<generated>) [2 skipped]
        at org.nzbhydra.auth.HydraAnonymousAuthenticationFilter.doFilter(HydraAnonymousAuthenticationFilter.java:101) [22 skipped]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115) [9 skipped]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81)
        at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:136) [9 skipped]
        at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:93)
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) [3 skipped]
        at org.nzbhydra.auth.AsyncSupportFilter.doFilterInternal(AsyncSupportFilter.java:35) [1 skipped]
        at org.nzbhydra.auth.HeaderAuthenticationFilter.doFilterInternal(HeaderAuthenticationFilter.java:55) [2 skipped]
        at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:150) [2 skipped]
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103) [2 skipped]
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110) [8 skipped]
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80)
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55) [1 skipped]
        at org.nzbhydra.auth.ForwardedForRecognizingFilter.doFilterInternal(ForwardedForRecognizingFilter.java:37) [4 skipped]
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96) [8 skipped]
        at org.nzbhydra.auth.HydraEmbeddedServletContainer$1.invoke(HydraEmbeddedServletContainer.java:89) [10 skipped]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382) [4 skipped]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895)
        at java.lang.Thread.run(Thread.java:750) [5 skipped]
```

I don't really know what's causing it or how to reproduce so being able to set logs to debug and causing it is not straightforward.

I'm using version 4.7.6 on AlmaLinux 8.7.

**Comment by theotherp** [comment]
Should be fixed in the next major release.

**Comment by brianjmurrell** [comment]
Ah, excellent.  Any thoughts on when that will be released?

**Comment by theotherp** [comment]
Two weeks.
