### ISSUE TITLE
v5 Application Run Failed: org.springframework.beans.factory.UnsatisfiedDependencyException

### ISSUE THREAD

**Issue by thehaven** [theotherp/nzbhydra2#820]
After bumping to the latest version v5.0.0 tag via linuxserver/nzbhydra2 docker image the application fails to run with org.springframework.beans.factory.UnsatisfiedDependencyException

I cannot supply a full debug zip as the application will not start but happy to supply more log output as required.
```
2023-01-20 17:16:48.057 ERROR --- [              main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'externalApi': Unsatisfied dependency expressed through field 'fileHandler': Error creating bean with name 'fileHandler': Unsatisfied dependency expressed through field 'searchModuleProvider': Error creating bean with name 'searchModuleProvider': Unsatisfied dependency expressed through field 'indexerInstantiator': Error creating bean with name 'indexerInstantiator': Unsatisfied dependency expressed through field 'titleMapping': Error creating bean with name 'customQueryAndTitleMappingHandler': Unexpected AOP exception
        at org.springframework.beans.factory.aot.AutowiredFieldValueResolver.resolveValue(AutowiredFieldValueResolver.java:195)
        at org.springframework.beans.factory.aot.AutowiredFieldValueResolver.resolveObject(AutowiredFieldValueResolver.java:154)
        at org.springframework.beans.factory.aot.AutowiredFieldValueResolver.resolve(AutowiredFieldValueResolver.java:143)
        at org.nzbhydra.api.ExternalApi__Autowiring.apply(ExternalApi__Autowiring.java:17)
        at org.springframework.beans.factory.support.InstanceSupplier$1.get(InstanceSupplier.java:82)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainInstanceFromSupplier(AbstractAutowireCapableBeanFactory.java:1225)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1210)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1157)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:561)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:961)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'fileHandler': Unsatisfied dependency expressed through field 'searchModuleProvider': Error creating bean with name 'searchModuleProvider': Unsatisfied dependency expressed through field 'indexerInstantiator': Error creating bean with name 'indexerInstantiator': Unsatisfied dependency expressed through field 'titleMapping': Error creating bean with name 'customQueryAndTitleMappingHandler': Unexpected AOP exception
```

**Comment by theotherp** [comment]
Yeah I'm getting reports of this but I don't understand why, it runs fine for me with that image.

**Comment by theotherp** [comment]
Alright, it's caused by the auth settings. Setting it to NONE should fix it but I understand that's not a fix. I'll try to get it fixed as soon as possible.

**Comment by thehaven** [comment]
For now I've reverted to my backup (zfs) snapshot and happily running 4.7.6 - happy to try again once the fix lands and provide some feedback then.

**Comment by theotherp** [comment]
Please try 5.0.1 it should hopefully work

**Comment by claylevering** [comment]
Hi there!  Would this have impacted `latest` for 4.7.6 as well?  Seeing the same issues from a recent docker pull

**Comment by theotherp** [comment]
Depends on the docker image, lsio for example has not updated yet

**Comment by uicnren** [comment]
getting this same error on macOS Ventura 13.1 using the generic 5.0.2 hydra2

reverted back to previous version for the mean time.

**Comment by claylevering** [comment]
@theotherp how can we help with getting pieces of this resolved or getting testable builds?  I'm definitely using the the lsio build and I'm seeing no updates on `latest` so I would love to help you (selfishly, obv.)

**Comment by theotherp** [comment]
@uicnren Can you please post the full content of the logs folder?

@claylevering The build should (hopefully) be stable enough now for lsio to build a new image. Running the linux release (or windows release) directly using the data folder you would use for the docker container should be close enough to find any errors.

@uicnren's error is somewhat unexpected (more so than the others) because the generic release is basically the one I use during development.

**Comment by uicnren** [comment]
@theotherp my apologies, I had deleted the setup when I reverted, so I did not save the logs.

however I will report that on v5.0.6 it now runs and works. I do get one error on startup, but it does not seem to have affected anything. I will grab the logs as well.
```
2023-01-21 19:33:28.051 ERROR --- [              main] o.n.debuginfos.DebugInfosProvider        : Error initializing performance metrics reading

java.lang.NullPointerException: Cannot invoke "org.springframework.boot.actuate.metrics.MetricsEndpoint$MetricDescriptor.getMeasurements()" because the return value of "org.springframework.boot.actuate.metrics.MetricsEndpoint.metric(String, java.util.List)" is null
	at org.nzbhydra.debuginfos.DebugInfosProvider.logMetrics(DebugInfosProvider.java:130)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:424) [1 skipped]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:368)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:192)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:420)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1743)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
```

**Comment by theotherp** [comment]
@uicnren That happens because you have the performance logging marker enabled. Just remove it. I'll try to get it fixed but for now it's not high priority.

**Comment by thehaven** [comment]
Thanks @theotherp for all your work on this - I just bumped to 5.07 from 4.7.6 and everything is working well with no sign of the original issue.
