### ISSUE TITLE
BUG: lsio hydra2 docker container with auto update enabled fills disk

### ISSUE THREAD

**Issue by JC1869** [theotherp/nzbhydra2#824]
Regrettably I didn't get the dumps for you on this. Here's what I believe was happening:
1) I had turned on auto-update in the hydra2 settings
2) my /tmp was full of files that looked like "nzbhydraxxxxxxxxzip"
3) Restarting container doesn't clear /tmp
4) restarting hydra via webui doesn't clear /tmp

snip from the logs. This was repeating about every 2 minutes:
2023-01-22 00:46:48.629  INFO --- [              main] o.s.m.s.b.SimpleBrokerMessageHandler     : Starting...
2023-01-22 00:46:48.629  INFO --- [              main] o.s.m.s.b.SimpleBrokerMessageHandler     : BrokerAvailabilityEvent[available=true, SimpleBrokerMessageHandler [org.springframework.messaging.simp.broker.DefaultSubscriptionRegistry@291c0025]]
2023-01-22 00:46:48.629  INFO --- [              main] o.s.m.s.b.SimpleBrokerMessageHandler     : Started.
2023-01-22 00:46:48.629  INFO --- [              main] org.nzbhydra.NzbHydra                    : Started NzbHydra in 1.436 seconds (process running for 1.571)
2023-01-22 00:46:48.658  INFO --- [              main] org.nzbhydra.NzbHydra                    : Version: 5.0.4
2023-01-22 00:46:48.658  INFO --- [              main] org.nzbhydra.NzbHydra                    : Build timestamp: 2023-01-21 09:43
2023-01-22 00:46:48.659  INFO --- [              main] org.nzbhydra.NzbHydra                    : You seem to be running NZBHydra 2 in docker. You can access Hydra using your local address and the IP you provided
2023-01-22 00:46:50.870  INFO --- [HT-Check for and i] org.nzbhydra.update.AutomaticUpdater     : Automatic updater found update
2023-01-22 00:46:50.871  INFO --- [HT-Check for and i] org.nzbhydra.update.UpdateManager        : Starting process to update to v5.0.7
2023-01-22 00:46:58.203  INFO --- [HT-Check for and i] org.nzbhydra.update.UpdateManager        : Creating backup before shutting down
2023-01-22 00:46:58.204  INFO --- [HT-Check for and i] org.nzbhydra.backup.BackupAndRestore     : Deleting old backups if any exist
2023-01-22 00:46:58.208  INFO --- [HT-Check for and i] org.nzbhydra.backup.BackupAndRestore     : Creating backup
2023-01-22 00:46:58.208  INFO --- [HT-Check for and i] org.nzbhydra.backup.BackupAndRestore     : Backing up database to /config/backup/nzbhydra-2023-01-22 00-46-58.zip
2023-01-22 00:47:48.493  INFO --- [   MessageBroker-1] o.s.w.s.c.WebSocketMessageBrokerStats    : WebSocketSession[0 current WS(0)-HttpStream(0)-HttpPoll(0), 0 total, 0 closed abnormally (0 connect failure, 0 send limit, 0 transport error)], stompSubProtocol[processed CONNECT(0)-CONNECTED(0)-DISCONNECT(0)], stompBrokerRelay[null], inboundChannel[pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0], outboundChannel[pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0], sockJsScheduler[pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 0]
2023-01-22 00:49:28.011  INFO --- [HT-Check for and i] org.nzbhydra.backup.BackupAndRestore     : Successfully wrote backup to file /config/backup/nzbhydra-2023-01-22 00-46-58.zip
2023-01-22 00:49:28.240  INFO --- [HT-Check for and i] org.nzbhydra.update.UpdateManager        : Shutting down to let wrapper execute the update
2023-01-22 00:49:28.542  INFO --- [          Thread-3] o.s.m.s.b.SimpleBrokerMessageHandler     : Stopping...
2023-01-22 00:49:28.550  INFO --- [          Thread-3] o.s.m.s.b.SimpleBrokerMessageHandler     : BrokerAvailabilityEvent[available=false, SimpleBrokerMessageHandler [org.springframework.messaging.simp.broker.DefaultSubscriptionRegistry@291c0025]]
2023-01-22 00:49:28.591  INFO --- [          Thread-3] o.s.m.s.b.SimpleBrokerMessageHandler     : Stopped.
2023-01-22 00:49:28.591  INFO --- [          Thread-3] o.s.b.w.e.tomcat.GracefulShutdown        : Commencing graceful shutdown. Waiting for active requests to complete
2023-01-22 00:49:28.592  INFO --- [   tomcat-shutdown] o.s.b.w.e.tomcat.GracefulShutdown        : Graceful shutdown complete
2023-01-22 00:49:28.592  INFO --- [          Thread-3] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2023-01-22 00:49:28.595  INFO --- [          Thread-3] org.nzbhydra.NzbHydra                    : Shutting down and using up to 15000ms to compact database
2023-01-22 00:49:28.596  INFO --- [          Thread-3] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2023-01-22 00:49:28.596  INFO --- [          Thread-3] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2023-01-22 00:49:28.597  INFO --- [          Thread-3] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2023-01-22 00:49:28.597 ERROR --- [HT-Delete old sear] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task

org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:467)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.startTransaction(AbstractPlatformTransactionManager.java:400)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:595)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:382)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.nzbhydra.searching.cleanup.OldResultsCleanupTask$$SpringCGLIB$$0.deleteOldResults(<generated>) [3 skipped]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) [1 skipped]
	at org.nzbhydra.tasks.HydraTaskScheduler.lambda$scheduleTask$1(HydraTaskScheduler.java:95)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base@17.0.5/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base@17.0.5/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@17.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
Caused by: java.lang.IllegalStateException: EntityManagerFactory is closed
	at org.hibernate.internal.SessionFactoryImpl.validateNotClosed(SessionFactoryImpl.java:553)
	at org.hibernate.internal.SessionFactoryImpl.createEntityManager(SessionFactoryImpl.java:613)
	at org.hibernate.internal.SessionFactoryImpl.createEntityManager(SessionFactoryImpl.java:155)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.createNativeEntityManager(AbstractEntityManagerFactoryBean.java:584)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.invokeProxyMethod(AbstractEntityManagerFactoryBean.java:487) [1 skipped]
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean$ManagedEntityManagerFactoryInvocationHandler.invoke(AbstractEntityManagerFactoryBean.java:733)
	at jdk.proxy4/jdk.proxy4.$Proxy78.createNativeEntityManager(Unknown Source)
	at org.springframework.orm.jpa.JpaTransactionManager.createEntityManagerForTransaction(JpaTransactionManager.java:485)
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:410)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.startTransaction(AbstractPlatformTransactionManager.java:400)
	... 21 common frames omitted

2023-01-22 00:49:55.348  INFO --- [              main] org.nzbhydra.NzbHydra                    : Starting AOT-processed NzbHydra using Java 17.0.5 with PID 27303 (/app/nzbhydra2/core started by abc in /app/nzbhydra2)
2023-01-22 00:49:55.348  INFO --- [              main] org.nzbhydra.NzbHydra                    : The following 1 profile is active: "default"

my backup folder also filled up with backups:
'nzbhydra-2023-01-22 03-52-16.zip'
'nzbhydra-2023-01-22 03-54-32.zip'
'nzbhydra-2023-01-22 03-56-56.zip'
'nzbhydra-2023-01-22 03-59-48.zip'
'nzbhydra-2023-01-22 04-02-20.zip'
'nzbhydra-2023-01-22 04-04-06.zip'
'nzbhydra-2023-01-22 04-05-21.zip'
'nzbhydra-2023-01-22 04-06-37.zip'
'nzbhydra-2023-01-22 04-07-48.zip'
'nzbhydra-2023-01-22 04-09-02.zip'
'nzbhydra-2023-01-22 04-10-17.zip'
'nzbhydra-2023-01-22 04-11-28.zip'
'nzbhydra-2023-01-22 04-12-39.zip'
'nzbhydra-2023-01-22 04-13-48.zip'
'nzbhydra-2023-01-22 04-14-57.zip'
'nzbhydra-2023-01-22 04-16-07.zip'
'nzbhydra-2023-01-22 04-17-16.zip'
'nzbhydra-2023-01-22 04-18-29.zip'
'nzbhydra-2023-01-22 04-19-36.zip'
'nzbhydra-2023-01-22 04-20-47.zip'
'nzbhydra-2023-01-22 04-22-00.zip'
'nzbhydra-2023-01-22 04-23-08.zip'
'nzbhydra-2023-01-22 04-24-17.zip'
'nzbhydra-2023-01-22 04-25-28.zip'
'nzbhydra-2023-01-22 07-12-13.zip'

The obvious answer is not to enable automatic updates in the container, but I wanted to post this just in case something else should be done.

**Comment by theotherp** [comment]
Already noticed this on my own machine. Thanks. Fix is on the way. Not sure why this never happened before.

**Comment by theotherp** [comment]
Btw, thanks for the exemplary bug report :-)

**Comment by JC1869** [comment]
You're welcome. Been using hydra since the very beginning and you do great work XD

**Comment by theotherp** [comment]
Should be fixed
