### ISSUE TITLE
4.7.6 to latest Upgrade Failure

### ISSUE THREAD

**Issue by andrew-from-toronto** [theotherp/nzbhydra2#825]
Logs:
```
2023-01-22 11:55:48.793  INFO --- [              main] org.nzbhydra.NzbHydra                    : Starting AOT-processed NzbHydra using Java 17.0.5 with PID 145 (/app/nzbhydra2/core started by abc in /app/nzbhydra2)
2023-01-22 11:55:48.794 DEBUG --- [              main] org.nzbhydra.NzbHydra                    : Running with Spring Boot v3.0.2, Spring v6.0.4
2023-01-22 11:55:48.794  INFO --- [              main] org.nzbhydra.NzbHydra                    : The following 1 profile is active: "default"
2023-01-22 11:55:48.825  INFO --- [              main] trationDelegate$BeanPostProcessorChecker : Bean 'hydraTaskConfiguration' of type [org.nzbhydra.tasks.HydraTaskConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2023-01-22 11:55:48.832  INFO --- [              main] trationDelegate$BeanPostProcessorChecker : Bean 'baseConfig' of type [org.nzbhydra.config.BaseConfig] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2023-01-22 11:55:48.832  INFO --- [              main] trationDelegate$BeanPostProcessorChecker : Bean 'categoriesConfigValidator' of type [org.nzbhydra.config.validation.CategoriesConfigValidator] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2023-01-22 11:55:48.833  INFO --- [              main] trationDelegate$BeanPostProcessorChecker : Bean 'downloaderConfigValidator' of type [org.nzbhydra.config.validation.DownloaderConfigValidator] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2023-01-22 11:55:48.833  INFO --- [              main] trationDelegate$BeanPostProcessorChecker : Bean 'downloadingConfigValidator' of type [org.nzbhydra.config.validation.DownloadingConfigValidator] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2023-01-22 11:55:48.834  INFO --- [              main] trationDelegate$BeanPostProcessorChecker : Bean 'searchingConfigValidator' of type [org.nzbhydra.config.validation.SearchingConfigValidator] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2023-01-22 11:55:48.835  INFO --- [              main] trationDelegate$BeanPostProcessorChecker : Bean 'loggingConfigValidator' of type [org.nzbhydra.config.validation.LoggingConfigValidator] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2023-01-22 11:55:48.835  INFO --- [              main] trationDelegate$BeanPostProcessorChecker : Bean 'mainConfigValidator' of type [org.nzbhydra.config.validation.MainConfigValidator] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2023-01-22 11:55:48.835  INFO --- [              main] trationDelegate$BeanPostProcessorChecker : Bean 'userAuthConfigValidator' of type [org.nzbhydra.config.validation.UserAuthConfigValidator] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2023-01-22 11:55:48.836  INFO --- [              main] trationDelegate$BeanPostProcessorChecker : Bean 'authConfigValidator' of type [org.nzbhydra.config.validation.AuthConfigValidator] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2023-01-22 11:55:48.836  INFO --- [              main] trationDelegate$BeanPostProcessorChecker : Bean 'indexerConfigValidator' of type [org.nzbhydra.config.validation.IndexerConfigValidator] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2023-01-22 11:55:48.837  INFO --- [              main] trationDelegate$BeanPostProcessorChecker : Bean 'notificationConfigValidator' of type [org.nzbhydra.config.validation.NotificationConfigValidator] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2023-01-22 11:55:48.837  INFO --- [              main] trationDelegate$BeanPostProcessorChecker : Bean 'baseConfigValidator' of type [org.nzbhydra.config.validation.BaseConfigValidator] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2023-01-22 11:55:48.837  INFO --- [              main] org.nzbhydra.config.BaseConfigHandler    : Using data folder /config
2023-01-22 11:55:48.846 DEBUG --- [              main] org.nzbhydra.config.ConfigReaderWriter   : CONFIG_READ_WRITE: Writing to file /config/nzbhydra.yml
2023-01-22 11:55:48.853  INFO --- [              main] trationDelegate$BeanPostProcessorChecker : Bean 'baseConfigHandler' of type [org.nzbhydra.config.BaseConfigHandler] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2023-01-22 11:55:48.854  INFO --- [              main] trationDelegate$BeanPostProcessorChecker : Bean 'configProvider' of type [org.nzbhydra.config.ConfigProvider] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2023-01-22 11:55:48.854  INFO --- [              main] trationDelegate$BeanPostProcessorChecker : Bean 'hydraGlobalMethodSecurityConfiguration' of type [org.nzbhydra.auth.HydraGlobalMethodSecurityConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2023-01-22 11:55:48.855  INFO --- [              main] a.HydraGlobalMethodSecurityConfiguration : Enabling auth type FORM
2023-01-22 11:55:48.855  INFO --- [              main] trationDelegate$BeanPostProcessorChecker : Bean 'methodSecurityMetadataSource' of type [org.springframework.security.access.method.DelegatingMethodSecurityMetadataSource] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2023-01-22 11:55:48.856  INFO --- [              main] trationDelegate$BeanPostProcessorChecker : Bean 'taskExecutor' of type [org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2023-01-22 11:55:48.893  INFO --- [              main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 5076 (http)
2023-01-22 11:55:48.895  INFO --- [              main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 75 ms
2023-01-22 11:55:48.940  INFO --- [              main] o.s.boot.web.servlet.RegistrationBean    : Filter characterEncodingFilter was not registered (possibly already registered?)
2023-01-22 11:55:48.940 DEBUG --- [              main] o.n.a.HydraAnonymousAuthenticationFilter : Filter 'hydraAnonymousAuthenticationFilter' configured for use
2023-01-22 11:55:48.940 DEBUG --- [              main] org.nzbhydra.auth.AsyncSupportFilter     : Filter 'asyncSupportFilter' configured for use
2023-01-22 11:55:48.946  INFO --- [              main] o.nzbhydra.database.DatabaseRecreation   : Determined existing database to be version 1.4. Migration needed.
2023-01-22 11:55:48.946 DEBUG --- [              main] o.nzbhydra.database.DatabaseRecreation   : Java executable not found. Trying just java and hope it's in path
2023-01-22 11:55:49.013 DEBUG --- [              main] o.nzbhydra.database.DatabaseRecreation   : Downloaded file from https://repo1.maven.org/maven2/com/h2database/h2/1.4.200/h2-1.4.200.jar to /tmp/nzbhydra17125131872551405285.jar. Will be deleted on exit
2023-01-22 11:55:49.084 DEBUG --- [              main] o.nzbhydra.database.DatabaseRecreation   : Downloaded file from https://repo1.maven.org/maven2/com/h2database/h2/2.1.214/h2-2.1.214.jar to /tmp/nzbhydra11792620026402825325.jar. Will be deleted on exit
2023-01-22 11:55:49.141  INFO --- [              main] o.nzbhydra.database.DatabaseRecreation   : Running database migration from 1.4 to 2
2023-01-22 11:55:49.141  INFO --- [              main] o.nzbhydra.database.DatabaseRecreation   : Copying old database file /config/database/nzbhydra.mv.db to backup /config/database/nzbhydra.mv.db.old.bak.1674406549141 which will be automatically deleted after 14 days
2023-01-22 11:55:50.278  INFO --- [              main] o.nzbhydra.database.DatabaseRecreation   : Running command: java -cp /tmp/nzbhydra17125131872551405285.jar org.h2.tools.Shell -url jdbc:h2:file:/config/database/nzbhydra -user sa -sql alter user sa set password 'sa'
2023-01-22 11:55:53.186  INFO --- [              main] o.nzbhydra.database.DatabaseRecreation   : Running command: java -cp /tmp/nzbhydra17125131872551405285.jar org.h2.tools.Script -url jdbc:h2:file:/config/database/nzbhydra -user sa -password sa -script /tmp/nzbhydra21361759170287670.sql
2023-01-22 11:56:04.149  INFO --- [              main] o.nzbhydra.database.DatabaseRecreation   : Running command: java -cp /tmp/nzbhydra11792620026402825325.jar org.h2.tools.RunScript -url jdbc:h2:file:/config/database/nzbhydra -user sa -password sa -script /tmp/nzbhydra21361759170287670.sql -options FROM_1X
2023-01-22 11:56:09.004 ERROR --- [              main] o.nzbhydra.database.DatabaseRecreation   : Error while trying to migrate database to 2.0
2023-01-22 11:56:09.050  INFO --- [              main] o.nzbhydra.database.DatabaseRecreation   : Restoring database file /config/database/nzbhydra.mv.db from backup /config/database/nzbhydra.mv.db.old.bak.1674406549141
2023-01-22 11:56:09.065  WARN --- [              main] w.s.c.ServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'getDatabaseRecreationBean': java.lang.RuntimeException: Database import failed.. Code: 1
2023-01-22 11:56:09.067 ERROR --- [              main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'getDatabaseRecreationBean': java.lang.RuntimeException: Database import failed.. Code: 1
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1751)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:313)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1130)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:905)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:584)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:432)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.nzbhydra.NzbHydra.startup(NzbHydra.java:186)
	at org.nzbhydra.NzbHydra.main(NzbHydra.java:135)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Database import failed.. Code: 1
	at org.nzbhydra.database.DatabaseRecreation.migrateToH2v2IfNeeded(DatabaseRecreation.java:174)
	at org.nzbhydra.database.DatabaseRecreation.runDatabaseScript(DatabaseRecreation.java:65)
	at org.nzbhydra.database.DatabaseRecreationBean.afterPropertiesSet(DatabaseRecreationBean.java:26)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1797)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1747)
	... 17 common frames omitted
Caused by: java.lang.RuntimeException: Database import failed.. Code: 1
	at org.nzbhydra.database.DatabaseRecreation.runH2Command(DatabaseRecreation.java:195)
	at org.nzbhydra.database.DatabaseRecreation.migrateToH2v2IfNeeded(DatabaseRecreation.java:160)
	... 21 common frames omitted

2023-01-22 11:56:09.068 ERROR --- [              main] org.nzbhydra.NzbHydra                    : An unexpected error occurred during startup

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'getDatabaseRecreationBean': java.lang.RuntimeException: Database import failed.. Code: 1
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1751)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:313)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1130)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:905)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:584)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:432)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.nzbhydra.NzbHydra.startup(NzbHydra.java:186)
	at org.nzbhydra.NzbHydra.main(NzbHydra.java:135)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Database import failed.. Code: 1
	at org.nzbhydra.database.DatabaseRecreation.migrateToH2v2IfNeeded(DatabaseRecreation.java:174)
	at org.nzbhydra.database.DatabaseRecreation.runDatabaseScript(DatabaseRecreation.java:65)
	at org.nzbhydra.database.DatabaseRecreationBean.afterPropertiesSet(DatabaseRecreationBean.java:26)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1797)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1747)
	... 17 common frames omitted
Caused by: java.lang.RuntimeException: Database import failed.. Code: 1
	at org.nzbhydra.database.DatabaseRecreation.runH2Command(DatabaseRecreation.java:195)
	at org.nzbhydra.database.DatabaseRecreation.migrateToH2v2IfNeeded(DatabaseRecreation.java:160)
	... 21 common frames omitted

2023-01-22 11:56:09.069 ERROR --- [              main] org.nzbhydra.NzbHydra                    : FATAL: An unexpected error occurred during startup:
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'getDatabaseRecreationBean': java.lang.RuntimeException: Database import failed.. Code: 1

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'getDatabaseRecreationBean': java.lang.RuntimeException: Database import failed.. Code: 1
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1751)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:313)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1130)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:905)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:584)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:432)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.nzbhydra.NzbHydra.startup(NzbHydra.java:186)
	at org.nzbhydra.NzbHydra.main(NzbHydra.java:135)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Database import failed.. Code: 1
	at org.nzbhydra.database.DatabaseRecreation.migrateToH2v2IfNeeded(DatabaseRecreation.java:174)
	at org.nzbhydra.database.DatabaseRecreation.runDatabaseScript(DatabaseRecreation.java:65)
	at org.nzbhydra.database.DatabaseRecreationBean.afterPropertiesSet(DatabaseRecreationBean.java:26)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1797)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1747)
	... 17 common frames omitted
Caused by: java.lang.RuntimeException: Database import failed.. Code: 1
	at org.nzbhydra.database.DatabaseRecreation.runH2Command(DatabaseRecreation.java:195)
	at org.nzbhydra.database.DatabaseRecreation.migrateToH2v2IfNeeded(DatabaseRecreation.java:160)
	... 21 common frames omitted
```

I restored my database from a backup just to ensure no data corruption and can confirm running it off 4.7.6 continues to work fine. Looks like an issue with the db migration to me. Let me know if I can gather any more info, the exception doesn't really seem to give enough info, even with debug logging on.

**Comment by theotherp** [comment]
Yeah, not much to work on. It would be easiest for me if you could just zip the database and send it to me. It will contain the history and also API keys but I don't care about that and will delete it afterwards. You can send it to theotherp@posteo.net

Or you can try running the commands mentioned in the log:

```
2023-01-22 11:55:49.013 DEBUG --- [              main] o.nzbhydra.database.DatabaseRecreation   : Downloaded file from https://repo1.maven.org/maven2/com/h2database/h2/1.4.200/h2-1.4.200.jar to /tmp/nzbhydra17125131872551405285.jar. Will be deleted on exit
2023-01-22 11:55:49.084 DEBUG --- [              main] o.nzbhydra.database.DatabaseRecreation   : Downloaded file from https://repo1.maven.org/maven2/com/h2database/h2/2.1.214/h2-2.1.214.jar to /tmp/nzbhydra11792620026402825325.jar. Will be deleted on exit
2023-01-22 11:55:49.141  INFO --- [              main] o.nzbhydra.database.DatabaseRecreation   : Running database migration from 1.4 to 2
2023-01-22 11:55:49.141  INFO --- [              main] o.nzbhydra.database.DatabaseRecreation   : Copying old database file /config/database/nzbhydra.mv.db to backup /config/database/nzbhydra.mv.db.old.bak.1674406549141 which will be automatically deleted after 14 days
2023-01-22 11:55:50.278  INFO --- [              main] o.nzbhydra.database.DatabaseRecreation   : Running command: java -cp /tmp/nzbhydra17125131872551405285.jar org.h2.tools.Shell -url jdbc:h2:file:/config/database/nzbhydra -user sa -sql alter user sa set password 'sa'
2023-01-22 11:55:53.186  INFO --- [              main] o.nzbhydra.database.DatabaseRecreation   : Running command: java -cp /tmp/nzbhydra17125131872551405285.jar org.h2.tools.Script -url jdbc:h2:file:/config/database/nzbhydra -user sa -password sa -script /tmp/nzbhydra21361759170287670.sql
2023-01-22 11:56:04.149  INFO --- [              main] o.nzbhydra.database.DatabaseRecreation   : Running command: java -cp /tmp/nzbhydra11792620026402825325.jar org.h2.tools.RunScript -url jdbc:h2:file:/config/database/nzbhydra -user sa -password sa -script /tmp/nzbhydra21361759170287670.sql -options FROM_1X
```

**Comment by andrew-from-toronto** [comment]
I managed to get more info by monitoring the console log output vs the log file...

```
2023-01-22 12:37:42.295  INFO --- [              main] o.nzbhydra.database.DatabaseRecreation   : Running command: java -cp /tmp/nzbhydra10116209287778160356.jar org.h2.tools.RunScript -url jdbc:h2:file:/config/database/nzbhydra -user sa -password sa -script /tmp/nzbhydra5113391055335939469.sql -options FROM_1X
Exception in thread "main" org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PRIMARY KEY ON PUBLIC.INDEXERAPIACCESS(ID) ( /* key:3298778 */ 3298778, 'SEARCH', NULL, CAST(1454 AS BIGINT), 'SUCCESSFUL', TIMESTAMP '2021-03-27 09:01:36.741', 10)"; SQL statement:
INSERT INTO "PUBLIC"."INDEXERAPIACCESS" VALUES
(3298709, 'SEARCH', NULL, 270, 'SUCCESSFUL', TIMESTAMP '2021-04-15 08:57:38.056', 10),
(3298711, 'SEARCH', NULL, 409, 'SUCCESSFUL', TIMESTAMP '2021-04-15 08:57:38.196', 12),
(3298713, 'SEARCH', NULL, NULL, 'API_ERROR', TIMESTAMP '2021-04-15 08:57:38.197', 12),
(3298715, 'SEARCH', NULL, 1091, 'SUCCESSFUL', TIMESTAMP '2021-04-15 08:57:38.877', 11),
(3298717, 'SEARCH', NULL, 2220, 'SUCCESSFUL', TIMESTAMP '2021-04-15 08:57:40.007', 13),
(3298719, 'SEARCH', NULL, 3760, 'SUCCESSFUL', TIMESTAMP '2021-04-15 08:57:41.547', 7),
(3298728, 'SEARCH', NULL, 258, 'SUCCESSFUL', TIMESTAMP '2021-04-15 09:06:39.293', 9),
(3298730, 'SEARCH', NULL, 480, 'SUCCESSFUL', TIMESTAMP '2021-04-15 09:06:39.515', 12),
(3298732, 'SEARCH', NULL, NULL, 'API_ERROR', TIMESTAMP '2021-04-15 09:06:39.516', 12),
(3298734, 'SEARCH', NULL, 543, 'SUCCESSFUL', TIMESTAMP '2021-04-15 09:06:39.579', 13),
(3298736, 'SEARCH', NULL, 984, 'SUCCESSFUL', TIMESTAMP '2021-04-15 09:06:40.019', 11),
(3298738, 'SEARCH', NULL, 1166, 'SUCCESSFUL', TIMESTAMP '2021-04-15 09:06:40.202', 10),
(3298740, 'SEARCH', NULL, 2197, 'SUCCESSFUL', TIMESTAMP '2021-04-15 09:06:41.232', 7),
(3298749, 'SEARCH', NULL, 154, 'SUCCESSFUL', TIMESTAMP '2021-04-15 09:09:26.65', 9),
(3298750, 'SEARCH', NULL, 155, 'SUCCESSFUL', TIMESTAMP '2021-04-15 09:09:26.651', 13),
(3298753, 'SEARCH', NULL, 399, 'SUCCESSFUL', TIMESTAMP '2021-04-15 09:09:26.895', 12),
(3298755, 'SEARCH', NULL, NULL, 'API_ERROR', TIMESTAMP '2021-04-15 09:09:26.897', 12),
(3298757, 'SEARCH', NULL, 712, 'SUCCESSFUL', TIMESTAMP '2021-04-15 09:09:27.208', 7),
(3298759, 'SEARCH', NULL, 1432, 'SUCCESSFUL', TIMESTAMP '2021-04-15 09:09:27.928', 10),
(3298761, 'SEARCH', NULL, 1685, 'SUCCESSFUL', TIMESTAMP '2021-04-15 09:09:28.181', 11),
(3298769, 'SEARCH', NULL, 768, 'SUCCESSFUL', TIMESTAMP '2021-04-15 09:09:29.316', 10),
(3298772, 'SEARCH', NULL, 153, 'SUCCESSFUL', TIMESTAMP '2021-04-15 09:13:08.225', 9),
(3298774, 'SEARCH', NULL, 392, 'SUCCESSFUL', TIMESTAMP '2021-04-15 09:13:08.464', 12),
(3298776, 'SEARCH', NULL, NULL, 'API_ERROR', TIMESTAMP '2021-04-15 09:13:08.465', 12),
(3298778, 'SEARCH', NULL, 535, 'SUCCESSFUL', TIMESTAMP '2021-04-15 09:13:08.607', 13),
(3298780, 'SEARCH', NULL, 1015, 'SUCCESSFUL', TIMESTAMP '2021-04-15 09:13:09.086', 11),
(3298782, 'SEARCH', NULL, 1481, 'SUCCESSFUL', TIMESTAMP '2021-04-15 09:13:09.553', 10),
(3298784, 'SEARCH', NULL, 3771, 'SUCCESSFUL', TIMESTAMP '2021-04-15 09:13:11.843', 7),
(3298793, 'SEARCH', NULL, 227, 'SUCCESSFUL', TIMESTAMP '2021-04-15 09:22:09.483', 9),
(3298795, 'SEARCH', NULL, 495, 'SUCCESSFUL', TIMESTAMP '2021-04-15 09:22:09.75', 12),
(3298797, 'SEARCH', NULL, NULL, 'API_ERROR', TIMESTAMP '2021-04-15 09:22:09.752', 12),
(3298799, 'SEARCH', NULL, 567, 'SUCCESSFUL', TIMESTAMP '2021-04-15 09:22:09.823', 13),
(3298801, 'SEARCH', NULL, 626, 'SUCCESSFUL', TIMESTAMP '2021-04-15 09:22:09.881', 10),
(3298803, 'SEARCH', NULL, 700, 'SUCCESSFUL', TIMESTAMP '2021-04-15 09:22:09.956', 7),
(3298805, 'SEARCH', NULL, 1158, 'SUCCESSFUL', TIMESTAMP '2021-04-15 09:22:10.414', 11),
(3298814, 'SEARCH', NULL, 153, 'SUCCESSFUL', TIMESTAMP '2021-04-15 09:24:56.84', 9),
(3298816, 'SEARCH', NULL, 172, 'SUCCESSFUL', TIMESTAMP '2021-04-15 09:24:56.86', 13),
(3298818, 'SEARCH', NULL, 409, 'SUCCESSFUL', TIMESTAMP '2021-04-15 09:24:57.097', 12),
(3298820, 'SEARCH', NULL, NULL, 'API_ERROR', TIMESTAMP '2021-04-15 09:24:57.098', 12),
(3298822, 'SEARCH', NULL, 849, 'SUCCESSFUL', TIMESTAMP '2021-04-15 09:24:57.537', 10),
(3298824, 'SEARCH', NULL, 1750, 'SUCCESSFUL', TIMESTAMP '2021-04-15 09:24:58.438', 11),
(3298826, 'SEARCH', NULL, 2358, 'SUCCESSFUL', TIMESTAMP '2021-04-15 09:24:59.046', 7),
(3298835, 'SEARCH', NULL, 235, 'SUCCESSFUL', TIMESTAMP '2021-04-15 09:28:38.504', 9),
(3298837, 'SEARCH', NULL, 383, 'SUCCESSFUL', TIMESTAMP '2021-04-15 09:28:38.651', 12),
(3298839, 'SEARCH', NULL, NULL, 'API_ERROR', TIMESTAMP '2021-04-15 09:28:38.653', 12),
(3298841, 'SEARCH', NULL, 554, 'SUCCESSFUL', TIMESTAMP '2021-04-15 09:28:38.822', 13),
(3298843, 'SEARCH', NULL, 1092, 'SUCCESSFUL', TIMESTAMP '2021-04-15 09:28:39.36', 11) [23505-214]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:508)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
        at org.h2.message.DbException.get(DbException.java:223)
        at org.h2.message.DbException.get(DbException.java:199)
        at org.h2.mvstore.db.MVPrimaryIndex.add(MVPrimaryIndex.java:120)
        at org.h2.mvstore.db.MVTable.addRow(MVTable.java:519)
        at org.h2.command.dml.Insert.insertRows(Insert.java:174)
        at org.h2.command.dml.Insert.update(Insert.java:135)
        at org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:74)
        at org.h2.command.CommandContainer.update(CommandContainer.java:169)
        at org.h2.command.Command.executeUpdate(Command.java:252)
        at org.h2.command.dml.RunScriptCommand.execute(RunScriptCommand.java:108)
        at org.h2.command.dml.RunScriptCommand.update(RunScriptCommand.java:70)
        at org.h2.command.CommandContainer.update(CommandContainer.java:169)
        at org.h2.command.Command.executeUpdate(Command.java:252)
        at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:252)
        at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:223)
        at org.h2.tools.RunScript.processRunscript(RunScript.java:273)
        at org.h2.tools.RunScript.runTool(RunScript.java:137)
        at org.h2.tools.RunScript.main(RunScript.java:66)
2023-01-22 12:37:47.109 ERROR --- [              main] o.nzbhydra.database.DatabaseRecreation   : Error while trying to migrate database to 2.0
```

**Comment by theotherp** [comment]
Ok, cool (kinda).

There's multiple ways to tackle this:

- The easiest: delete the database. You will lose history and stats but it's quickly done.
- Remove data from that table. It's only for stats. This will require running a certain script to open the database file and execute a command.
- Remove specific data from the table. That would get so complicated I'd rather not do it.

**Comment by andrew-from-toronto** [comment]
Option 1 is fine for me - Just tried and can confirm v5 is running. Thanks for the help 👍🏻
