### ISSUE TITLE
org.nzbhydra.indexers.exceptions.IndexerUnreachableException after upgrade to 5.1.1 with openjdk17

### ISSUE THREAD

**Issue by hubert3** [theotherp/nzbhydra2#831]
Probably a JRE issue but nzbhydra2 5.1.1 can't connect to any indexers using SSL with the following error in the log

Running SunOS 5.11 illumos (Jan 2023)

Will post a comment if I find a solution

org.nzbhydra.indexers.exceptions.IndexerUnreachableException: Error while communicating with indexer xxx. Server returned: javax.net.ssl.SSLException: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_GENERAL_ERROR
	at org.nzbhydra.indexers.IndexerWebAccess.get(IndexerWebAccess.java:106)
	at org.nzbhydra.indexers.Indexer.callInderWebAccess(Indexer.java:414)
	at org.nzbhydra.indexers.Indexer.getAndStoreResultToDatabase(Indexer.java:405)
	at org.nzbhydra.indexers.Newznab.getAndStoreResultToDatabase(Newznab.java:393)
	at org.nzbhydra.indexers.Newznab.getAndStoreResultToDatabase(Newznab.java:84)
	at org.nzbhydra.indexers.Indexer.searchInternal(Indexer.java:210)
	at org.nzbhydra.indexers.Indexer.search(Indexer.java:144)
	at org.nzbhydra.searching.Searcher.lambda$getIndexerCallable$12(Searcher.java:415)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.nzbhydra.logging.MdcThreadPoolExecutor$1.run(MdcThreadPoolExecutor.java:111)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: javax.net.ssl.SSLException: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_GENERAL_ERROR
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:371)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:314)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:309)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:123)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1505)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1420)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at org.nzbhydra.webaccess.WebAccess.callUrl(WebAccess.java:90)
	at org.nzbhydra.webaccess.WebAccess.callUrl(WebAccess.java:52)
	at org.nzbhydra.indexers.IndexerWebAccess.lambda$get$0(IndexerWebAccess.java:72)
	... 5 common frames omitted
Caused by: javax.crypto.AEADBadTagException: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_GENERAL_ERROR
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11AEADCipher.handleException(P11AEADCipher.java:827)
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11AEADCipher.implDoFinal(P11AEADCipher.java:800)
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11AEADCipher.engineDoFinal(P11AEADCipher.java:624)
	at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2500)
	at java.base/sun.security.ssl.SSLCipher$T13GcmReadCipherGenerator$GcmReadCipher.decrypt(SSLCipher.java:1933)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(SSLSocketInputRecord.java:260)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:181)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
	... 29 common frames omitted
Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_GENERAL_ERROR
	at jdk.crypto.cryptoki/sun.security.pkcs11.wrapper.PKCS11.C_Decrypt(Native Method)
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11AEADCipher.implDoFinal(P11AEADCipher.java:785)
	... 35 common frames omitted

**Comment by hubert3** [comment]
Fix was to add

```    java_arguments.append("-Dsun.security.pkcs11.enable-solaris=false")```

before the line if releaseType == ReleaseType.NATIVE:

in nzbhydra2wrapperPy3.py

nzbhydra2 now complains that my wrapper file is outdated but I can live with that

**Comment by theotherp** [comment]
Thanks for the hint. I'll add it to the wrapper.
