### ISSUE TITLE
Unable to add NZBs directly to SABnzbd following 4-to-5 migration

### ISSUE THREAD

**Issue by JinglingB** [theotherp/nzbhydra2#833]
OS: Windows 10
NZBHydra 5.1.1

Following the migration (I went from 4.7.6 to 5.1.1 directly), I have been unable to add NZBs directly to SAB from NZBHydra2. Downloading NZBs to my browser with NZBHydra works fine. NZBHydra shows SAB's queue at the bottom.

Both NZBHydra and SABnzbd are running on the same system, no Docker, both using unsecured HTTP access. Removing SABnzbd from NZBHydra's downloaders and re-adding it hasn't helped any.

In short, I am unable to add *any* NZB to SAB. The web interface shows me this message (reproduced in its entirety):

```
An error occurred:
undefined: undefined

Message: undefined
```

After enabling debugging output to the console, I see the following when clicking the SAB button on an NZB listing:

```
2023-01-27 21:39:50.066  INFO --- [http-nio-127.0.0.1] org.nzbhydra.downloading.FileHandler     : PROXY download request for "[REDACTED]" from indexer [REDACTED]
2023-01-27 21:39:53.275  INFO --- [http-nio-127.0.0.1] org.nzbhydra.downloading.FileHandler     : NZB download from indexer successfully completed in 3203ms
2023-01-27 21:39:53.275 ERROR --- [http-nio-127.0.0.1] o.n.d.IndexerUniquenessScoreSaver        : Error while saving data for uniqueness scores

org.springframework.orm.jpa.JpaObjectRetrievalFailureException: Unable to find org.nzbhydra.indexers.IndexerSearchEntity with id -64771067
        at org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:376)
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:235)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:550)
        at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
        at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:152)
        at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:163) [1 skipped]
        at jdk.proxy4/jdk.proxy4.$Proxy58.getReferenceById(Unknown Source) [4 skipped]
        at org.nzbhydra.downloading.IndexerUniquenessScoreSaver.handleDownloadEvent(IndexerUniquenessScoreSaver.java:93)
        at org.nzbhydra.downloading.IndexerUniquenessScoreSaver$1.doInTransactionWithoutResult(IndexerUniquenessScoreSaver.java:78)
        at org.springframework.transaction.support.TransactionCallbackWithoutResult.doInTransaction(TransactionCallbackWithoutResult.java:36)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
        at org.nzbhydra.downloading.IndexerUniquenessScoreSaver.onNzbDownloadEvent(IndexerUniquenessScoreSaver.java:75)
        at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:343) [1 skipped]
        at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:228)
Caused by: jakarta.persistence.EntityNotFoundException: Unable to find org.nzbhydra.indexers.IndexerSearchEntity with id -64771067
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$JpaEntityNotFoundDelegate.handleEntityNotFound(EntityManagerFactoryBuilderImpl.java:182)
        at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:231)
        at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:363)
        at org.hibernate.event.internal.DefaultLoadEventListener.doOnLoad(DefaultLoadEventListener.java:113)
        at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:75)
        at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:118)
        at org.hibernate.internal.SessionImpl.fireLoadNoChecks(SessionImpl.java:1244)
        at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1232)
        at org.hibernate.loader.access.IdentifierLoadAccessImpl.doGetReference(IdentifierLoadAccessImpl.java:147)
        at org.hibernate.loader.access.IdentifierLoadAccessImpl.lambda$getReference$0(IdentifierLoadAccessImpl.java:82)
        at org.hibernate.loader.access.IdentifierLoadAccessImpl.perform(IdentifierLoadAccessImpl.java:108)
        at org.hibernate.loader.access.IdentifierLoadAccessImpl.getReference(IdentifierLoadAccessImpl.java:82)
        at org.hibernate.internal.SessionImpl.getReference(SessionImpl.java:2434)
        at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:307) [1 skipped]
        at jdk.proxy4/jdk.proxy4.$Proxy78.getReference(Unknown Source)

2023-01-27 21:39:53.275 ERROR --- [http-nio-127.0.0.1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.springframework.transaction.UnexpectedRollbackException: Transaction silently rolled back because it has been marked as rollback-only] with root cause

org.springframework.transaction.UnexpectedRollbackException: Transaction silently rolled back because it has been marked as rollback-only
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:752)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:711)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:654)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:407)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.nzbhydra.downloading.FileHandler$$SpringCGLIB$$0.getFileByResult(<generated>) [3 skipped]
        at org.nzbhydra.downloading.downloaders.Downloader.addBySearchResultIds(Downloader.java:145)
        at org.nzbhydra.downloading.downloaders.DownloaderWeb.addNzb(DownloaderWeb.java:65)
        at org.nzbhydra.auth.HydraAnonymousAuthenticationFilter.doFilter(HydraAnonymousAuthenticationFilter.java:101) [19 skipped]
        at org.nzbhydra.auth.AsyncSupportFilter.doFilterInternal(AsyncSupportFilter.java:35) [2 skipped]
        at org.springframework.security.web.access.intercept.AuthorizationFilter.doFilter(AuthorizationFilter.java:100) [8 skipped]
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:107) [20 skipped]
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:93)
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:62) [14 skipped]
        at org.nzbhydra.auth.ForwardedForRecognizingFilter.doFilterInternal(ForwardedForRecognizingFilter.java:37) [8 skipped]

2023-01-27 21:40:04.505  INFO --- [   MessageBroker-5] o.s.w.s.c.WebSocketMessageBrokerStats    : WebSocketSession[2 current WS(2)-HttpStream(0)-HttpPoll(0), 2 total, 0 closed abnormally (0 connect failure, 0 send limit, 0 transport error)], stompSubProtocol[processed CONNECT(2)-CONNECTED(2)-DISCONNECT(0)], stompBrokerRelay[null], inboundChannel[pool size = 2, active threads = 0, queued tasks = 0, completed tasks = 12], outboundChannel[pool size = 2, active threads = 0, queued tasks = 0, completed tasks = 35], sockJsScheduler[pool size = 6, active threads = 1, queued tasks = 3, completed tasks = 14]
```

Thank you and I hope you have a nice weekend.

**Comment by theotherp** [comment]
Sorry for the troubles. Please create and attach a debug infos zip.

**Comment by theotherp** [comment]
Can you please try searching for something that's definitely not in your history, i.e. which you never searched before, and see if that fails as well?

**Comment by qwerty12** [comment]
I searched for something I've definitely not searched for before and downloaded an NZB from NZB Finder of something I've never downloaded before and NZBHydra was able to successfully directly add the NZB to SABnzbd

**Comment by theotherp** [comment]
So I guess this means that some of the data for results that were previously already found are lost. While hydra has kept the results it is missing some other data in the database. I don't think there's a good way to fix this. If you don't care about the history / stats you can delete the database file while hydra is down.
