### ISSUE TITLE
Crashing during startup

### ISSUE THREAD

**Issue by chris-sanders** [theotherp/nzbhydra2#834]
Starting 3 days ago after an automatic upgrade to `ghcr.io/linuxserver/nzbhydra2:latest@sha256:38b3e04aeafd4d3b7a40a7da48f475ff7c52d3d357c4b1608290d4a55a1766f5`

I'm getting crash looping on boot. These is the logs before it crashes and eventually K8s restries.

```
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.cgroupv1.CgroupV1Subsystem.getLongValue(CgroupV1Subsystem.java:269)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.cgroupv1.CgroupV1Subsystem.getHierarchical(CgroupV1Subsystem.java:215)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.cgroupv1.CgroupV1Subsystem.setSubSystemControllerPath(CgroupV1Subsystem.java:203)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.cgroupv1.CgroupV1Subsystem.initSubSystem(CgroupV1Subsystem.java:111)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.cgroupv1.CgroupV1Subsystem.<clinit>(CgroupV1Subsystem.java:47)
	... 18 more
2023-01-27 22:40:10,887  ERROR - Main process shut down unexpectedly. If the wrapper was started in daemon mode you might not see the error output. Start Hydra manually with the same parameters in the same environment to see it
Logging wrapper output to /config/logs/wrapper.log
2023-01-27 22:40:10,944  INFO - Determined release type: native
2023-01-27 22:40:10,945  INFO - Starting NZBHydra main process with command line: ./core -Xmx256M -DfromWrapper=true -DinternalApiKey=kvnmnptcilgqjgscphhy -Dspring.output.ansi.enabled=ALWAYS --nobrowser --datafolder /config in folder /app/nzbhydra2
22:40:11.974 [main] INFO org.nzbhydra.NzbHydra - Version: 5.1.1
22:40:11.974 [main] INFO org.nzbhydra.NzbHydra - Build timestamp: 2023-01-24 18:15
Exception in thread "main" java.lang.InternalError: java.lang.reflect.InvocationTargetException
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.Metrics.systemMetrics(Metrics.java:67)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.Container.metrics(Container.java:44)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.ContainerInfo.<init>(ContainerInfo.java:34)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.Containers.activeProcessorCount(Containers.java:125)
	at java.base@17.0.5/java.lang.Runtime.availableProcessors(Runtime.java:247)
	at com.fasterxml.jackson.databind.util.internal.PrivateMaxEntriesMap.<clinit>(PrivateMaxEntriesMap.java:136)
	at com.fasterxml.jackson.databind.util.internal.PrivateMaxEntriesMap$Builder.initialCapacity(PrivateMaxEntriesMap.java:1465)
	at com.fasterxml.jackson.databind.util.LRUMap.<init>(LRUMap.java:37)
	at com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector.<init>(JacksonAnnotationIntrospector.java:82)
	at com.fasterxml.jackson.databind.ObjectMapper.<clinit>(ObjectMapper.java:375)
	at org.nzbhydra.Jackson.<clinit>(Jackson.java:35)
	at org.nzbhydra.config.ConfigReaderWriter.validateExistingConfig(ConfigReaderWriter.java:166)
	at org.nzbhydra.NzbHydra.initializeAndValidateAndMigrateYamlFile(NzbHydra.java:245)
	at org.nzbhydra.NzbHydra.startup(NzbHydra.java:173)
	at org.nzbhydra.NzbHydra.main(NzbHydra.java:135)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base@17.0.5/java.lang.reflect.Method.invoke(Method.java:568)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.Metrics.systemMetrics(Metrics.java:63)
	... 14 more
Caused by: java.lang.ExceptionInInitializerError
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.CgroupSubsystemFactory.create(CgroupSubsystemFactory.java:78)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.CgroupMetrics.getInstance(CgroupMetrics.java:164)
	... 16 more
Caused by: java.lang.NullPointerException
	at java.base@17.0.5/java.util.Objects.requireNonNull(Objects.java:208)
	at java.base@17.0.5/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:263)
	at java.base@17.0.5/java.nio.file.Path.of(Path.java:147)
	at java.base@17.0.5/java.nio.file.Paths.get(Paths.java:69)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.CgroupUtil.lambda$readStringValue$0(CgroupUtil.java:57)
	at java.base@17.0.5/java.security.AccessController.executePrivileged(AccessController.java:144)
	at java.base@17.0.5/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.CgroupUtil.readStringValue(CgroupUtil.java:59)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.CgroupSubsystemController.getStringValue(CgroupSubsystemController.java:66)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.CgroupSubsystemController.getLongValue(CgroupSubsystemController.java:125)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.cgroupv1.CgroupV1Subsystem.getLongValue(CgroupV1Subsystem.java:269)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.cgroupv1.CgroupV1Subsystem.getHierarchical(CgroupV1Subsystem.java:215)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.cgroupv1.CgroupV1Subsystem.setSubSystemControllerPath(CgroupV1Subsystem.java:203)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.cgroupv1.CgroupV1Subsystem.initSubSystem(CgroupV1Subsystem.java:111)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.cgroupv1.CgroupV1Subsystem.<clinit>(CgroupV1Subsystem.java:47)
	... 18 more
2023-01-27 22:40:11,990  ERROR - Main process shut down unexpectedly. If the wrapper was started in daemon mode you might not see the error output. Start Hydra manually with the same parameters in the same environment to see it
Logging wrapper output to /config/logs/wrapper.log
2023-01-27 22:40:12,046  INFO - Determined release type: native
2023-01-27 22:40:12,047  INFO - Starting NZBHydra main process with command line: ./core -Xmx256M -DfromWrapper=true -DinternalApiKey=lakvxsafrukawetjdyit -Dspring.output.ansi.enabled=ALWAYS --nobrowser --datafolder /config in folder /app/nzbhydra2
22:40:13.113 [main] INFO org.nzbhydra.NzbHydra - Version: 5.1.1
22:40:13.113 [main] INFO org.nzbhydra.NzbHydra - Build timestamp: 2023-01-24 18:15
Exception in thread "main" java.lang.InternalError: java.lang.reflect.InvocationTargetException
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.Metrics.systemMetrics(Metrics.java:67)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.Container.metrics(Container.java:44)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.ContainerInfo.<init>(ContainerInfo.java:34)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.Containers.activeProcessorCount(Containers.java:125)
	at java.base@17.0.5/java.lang.Runtime.availableProcessors(Runtime.java:247)
	at com.fasterxml.jackson.databind.util.internal.PrivateMaxEntriesMap.<clinit>(PrivateMaxEntriesMap.java:136)
	at com.fasterxml.jackson.databind.util.internal.PrivateMaxEntriesMap$Builder.initialCapacity(PrivateMaxEntriesMap.java:1465)
	at com.fasterxml.jackson.databind.util.LRUMap.<init>(LRUMap.java:37)
	at com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector.<init>(JacksonAnnotationIntrospector.java:82)
	at com.fasterxml.jackson.databind.ObjectMapper.<clinit>(ObjectMapper.java:375)
	at org.nzbhydra.Jackson.<clinit>(Jackson.java:35)
	at org.nzbhydra.config.ConfigReaderWriter.validateExistingConfig(ConfigReaderWriter.java:166)
	at org.nzbhydra.NzbHydra.initializeAndValidateAndMigrateYamlFile(NzbHydra.java:245)
	at org.nzbhydra.NzbHydra.startup(NzbHydra.java:173)
	at org.nzbhydra.NzbHydra.main(NzbHydra.java:135)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base@17.0.5/java.lang.reflect.Method.invoke(Method.java:568)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.Metrics.systemMetrics(Metrics.java:63)
	... 14 more
Caused by: java.lang.ExceptionInInitializerError
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.CgroupSubsystemFactory.create(CgroupSubsystemFactory.java:78)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.CgroupMetrics.getInstance(CgroupMetrics.java:164)
	... 16 more
Caused by: java.lang.NullPointerException
	at java.base@17.0.5/java.util.Objects.requireNonNull(Objects.java:208)
	at java.base@17.0.5/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:263)
	at java.base@17.0.5/java.nio.file.Path.of(Path.java:147)
	at java.base@17.0.5/java.nio.file.Paths.get(Paths.java:69)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.CgroupUtil.lambda$readStringValue$0(CgroupUtil.java:57)
	at java.base@17.0.5/java.security.AccessController.executePrivileged(AccessController.java:144)
	at java.base@17.0.5/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.CgroupUtil.readStringValue(CgroupUtil.java:59)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.CgroupSubsystemController.getStringValue(CgroupSubsystemController.java:66)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.CgroupSubsystemController.getLongValue(CgroupSubsystemController.java:125)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.cgroupv1.CgroupV1Subsystem.getLongValue(CgroupV1Subsystem.java:269)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.cgroupv1.CgroupV1Subsystem.getHierarchical(CgroupV1Subsystem.java:215)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.cgroupv1.CgroupV1Subsystem.setSubSystemControllerPath(CgroupV1Subsystem.java:203)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.cgroupv1.CgroupV1Subsystem.initSubSystem(CgroupV1Subsystem.java:111)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.cgroupv1.CgroupV1Subsystem.<clinit>(CgroupV1Subsystem.java:47)
	... 18 more
```

I tried reverting to `latest@sha256:6669eac9d45688c3377157ab7708775a94ff46c88da72350096a2f02b3b5dd78` which is what I was running before the restart 3 days ago. Unfortunately, it still crash looped. I suspect that means it wasn't a recent update, and was hoping you might have a better idea what is happening at this point when it crashes so I can dig in more on the root cause.

Thanks for any insights you have.

**Comment by chris-sanders** [comment]
Switching to `4.7.6` it's running again. Maybe LinuxServer.io has only recently switched to v5? I'm not sure why reverting to the previous SHA didn't help, but explicitly going to 4.7.6 has.

**Comment by theotherp** [comment]
You seem to have run into a somewhat obscure java / JDKB bug on which I can barely find any infos. Not sure how much that will tell you but here it is: https://bugs.openjdk.org/browse/JDK-8272124

During the startup a library is trying to determine the number of available processors which in turn tries to ask the JDK thatthen has to read cgroups which "is a Linux kernel feature that limits, accounts for, and isolates the resource usage (CPU, memory, disk I/O, network, etc.) of a collection of processes." as wikipedia states. 

It reads a cgroup file and tries to parse it, splitting it into values separated by `:`. If the third entry (whatever that is) contains a colon itself the string cannot be parsed and returns the error.

As you're running on docker I don't really understand why that could happen on your machine and not on all the others. Also the linked bug is supposed to be fixed in the JDK I use to build the image. So, I'm lost. I'll ask the lsio people if they have an idea.

**Comment by theotherp** [comment]
You don't run hydra on kubernetes, do you? Is there anything else that is different or "weird" about your docker host environment?

I'm afraid there's not much I can do here.

**Comment by chris-sanders** [comment]
I do run on kubernetes, it's containerd not docker if that matters. The version of containerd is a bit long in the tooth because Canonical has let the version fall out of date https://bugs.launchpad.net/ubuntu/focal/+source/containerd/+bug/1996534

Thanks for the detailed explanation, I'll follow up on this containerd version now that I understand why cgroups was listed on the trace! 

You're welcome to close this case or when I get a confirmed root cause I can post back. Looks like this is very likely an Ubuntu issue and not hydra.

**Comment by theotherp** [comment]
Good luck :-)
