### ISSUE TITLE
Disabled indexers are searched via API

### ISSUE THREAD

**Issue by jkhsjdhjs** [theotherp/nzbhydra2#843]
When searching via the NZBHydra API, disabled indexers are searched as well. This is not the case when searching via the web UI.
In this case Indexer 5 is disabled, but as you can see, it is still searched.

```
2023-02-05 22:09:41.017  INFO --- [http-nio-127.0.0.1] org.nzbhydra.api.ExternalApi             : [ID: 78700] Received external newznab API call: NewznabParameters{t=TVSEARCH, cat=[5030, 5040, 5070], offset=0, limit=100, raw=false, o=XML, attrs=[], extended=true, indexers=[]}
2023-02-05 22:09:41.018  INFO --- [http-nio-127.0.0.1] org.nzbhydra.api.ExternalApi             : [ID: 78700] Updating search because cache time is exceeded
2023-02-05 22:09:41.018  INFO --- [http-nio-127.0.0.1] org.nzbhydra.api.ExternalApi             : [ID: 78700] Executing new search
2023-02-05 22:09:41.019  INFO --- [http-nio-127.0.0.1] o.n.searching.IndexerForSearchSelector   : [ID: 78700] Not using Indexer 6 because it's disabled for category TV
2023-02-05 22:09:41.022  INFO --- [http-nio-127.0.0.1] o.n.searching.IndexerForSearchSelector   : [ID: 78700] Selected 5 out of 6 indexers: Indexer 3, Indexer 4, Indexer 5, Indexer 2, Indexer 1
2023-02-05 22:09:41.023  INFO --- [  pool-45-thread-1] org.nzbhydra.indexers.Newznab            : [ID: 78700] Indexer 3: Calling *URL*
2023-02-05 22:09:41.023  INFO --- [  pool-45-thread-3] org.nzbhydra.indexers.Newznab            : [ID: 78700] Indexer 5: Calling *URL*
2023-02-05 22:09:41.023  INFO --- [  pool-45-thread-4] org.nzbhydra.indexers.Newznab            : [ID: 78700] Indexer 2: Calling *URL*
2023-02-05 22:09:41.023  INFO --- [  pool-45-thread-2] org.nzbhydra.indexers.Newznab            : [ID: 78700] Indexer 4: Calling *URL*
2023-02-05 22:09:41.023  INFO --- [  pool-45-thread-5] org.nzbhydra.indexers.Newznab            : [ID: 78700] Indexer 1: Calling *URL*
2023-02-05 22:09:41.326  INFO --- [  pool-45-thread-2] org.nzbhydra.indexers.Newznab            : [ID: 78700] Indexer 4: Successfully executed search call in 292ms with 10000 total results
2023-02-05 22:09:41.339 ERROR --- [  pool-45-thread-3] org.nzbhydra.indexers.Newznab            : [ID: 78700] Indexer 5: Remote host terminated the handshake

org.nzbhydra.indexers.exceptions.IndexerUnreachableException: Error while communicating with indexer Indexer 5. Server returned: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
	at org.nzbhydra.indexers.IndexerWebAccess.get(IndexerWebAccess.java:106)
	at org.nzbhydra.indexers.Indexer.callInderWebAccess(Indexer.java:417)
	at org.nzbhydra.indexers.Indexer.getAndStoreResultToDatabase(Indexer.java:408)
	at org.nzbhydra.indexers.Newznab.getAndStoreResultToDatabase(Newznab.java:385)
	at org.nzbhydra.indexers.Newznab.getAndStoreResultToDatabase(Newznab.java:84)
	at org.nzbhydra.indexers.Indexer.searchInternal(Indexer.java:210)
	at org.nzbhydra.indexers.Indexer.search(Indexer.java:144)
	at org.nzbhydra.searching.Searcher.lambda$getIndexerCallable$12(Searcher.java:415)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.nzbhydra.logging.MdcThreadPoolExecutor$1.run(MdcThreadPoolExecutor.java:111)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
	at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1719)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1518)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1425)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at org.nzbhydra.webaccess.WebAccess.callUrl(WebAccess.java:90)
	at org.nzbhydra.webaccess.WebAccess.callUrl(WebAccess.java:52)
	at org.nzbhydra.indexers.IndexerWebAccess.lambda$get$0(IndexerWebAccess.java:72)
	... 5 common frames omitted
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:489)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:478)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1510)
	... 28 common frames omitted

2023-02-05 22:09:41.340  WARN --- [  pool-45-thread-3] org.nzbhydra.indexers.Newznab            : [ID: 78700] Because an error occurred Indexer 5 will be temporarily disabled until 2023-02-05T22:14:41.340232499Z. This is error number 1 in a row
2023-02-05 22:09:41.714  INFO --- [  pool-45-thread-4] org.nzbhydra.indexers.Newznab            : [ID: 78700] Indexer 2: Successfully executed search call in 678ms with 148341 total results
2023-02-05 22:09:41.966  WARN --- [  pool-45-thread-1] org.nzbhydra.indexers.Newznab            : [ID: 78700] Indexer 3: Indexer's response indicates a total of 500000 results but actually only 65 were returned
2023-02-05 22:09:41.967  INFO --- [  pool-45-thread-1] org.nzbhydra.indexers.Newznab            : [ID: 78700] Indexer 3: Successfully executed search call in 936ms with 65 total results
2023-02-05 22:09:42.276  INFO --- [  pool-45-thread-5] org.nzbhydra.indexers.Newznab            : [ID: 78700] Indexer 1: Successfully executed search call in 1238ms with 125000 total results
2023-02-05 22:09:42.280  INFO --- [http-nio-127.0.0.1] org.nzbhydra.searching.Searcher          : [ID: 78700] Returning results 1-100 from 167 results in cache. A total of 283406 results is available from indexers of which 0 were already rejected and 0 were removed as duplicates
2023-02-05 22:09:42.284  INFO --- [http-nio-127.0.0.1] org.nzbhydra.api.ExternalApi             : [ID: 78700] Search took 1266ms. Returning 100 results
2023-02-05 22:09:42.284  INFO --- [http-nio-127.0.0.1] org.nzbhydra.api.ExternalApi             : [ID: 78700] Putting search result into cache
```

**Comment by theotherp** [comment]
Please post the debug infos zip.

**Comment by jkhsjdhjs** [comment]
The issue occured when sonarr performed its RSS sync every 15 minutes. One of my indexers was down, so it couldn't be searched and was disabled for 15 minutes by nzbhydra. Since this caused a notification every 15 minutes, I disabled the indexer manually, while it was already disabled temporarily.

What I initially thought might've been going on is that the indexer was re-enabled after 15 minutes anyways (even though I disabled it manually), then the sonarr RSS sync came in, which caused the error again. What kinda contradicts this theory is that the indexer was still permanently disabled after the next error, so it did remember that I disabled the indexer manually.

However, I don't seem to be able to reproduce this issue anymore. I tried reproducing it by changing the URL of one indexer to something non-existant, so connecting would fail. It was initially disabled temporarily when attempting a search, but wasn't searched again after disabling it permanently. So I don't know what was going on there.

**Comment by jkhsjdhjs** [comment]
Just experienced the same issue with the same indexer again, but today disabling the indexer permanently worked fine. Not sure what was going on yesterday.

**Comment by jkhsjdhjs** [comment]
Closing this, maybe I'll re-open should I ever be able to reproduce this issue.

**Comment by jkhsjdhjs** [comment]
@theotherp I have a similar issue again, which is probably related. This time an enabled indexer is not searched, so the exact opposite. I sent you the debug info zip via mail.

**Comment by theotherp** [comment]
@jkhsjdhjs Please tell me what search (when) and which indexer was not searched.

**Comment by theotherp** [comment]
The only reason why an indexer would not be even part of the select is if it was disabled be the user. But five minutes later you were able to select it in the UI. So unless you didn't reenable it during that time I have really no idea why it would be skipped.

I'll extend the logging in this area.
