### ISSUE TITLE
BUG NZBhydra2 keeps updating to v5.1.5

### ISSUE THREAD

**Issue by pven** [theotherp/nzbhydra2#849]
NZBhydra2 is not starting anymore, it is constantly trying to update and I don't see why.

Generating anonymous logs is not possible (I think). How can I see what is wrong?

Until the 'crash' it was trying to update every few minutes, the backup was filling up my diskspace.

I am running on CentOS 7.9

How can I fix this?

**Comment by pven** [comment]
This is what I found in the log:
```
2023-02-12 11:56:55.465  WARN --- [HT-Delete old sear] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 50000, SQLState: HY000
2023-02-12 11:56:55.467 ERROR --- [HT-Delete old sear] o.h.engine.jdbc.spi.SqlExceptionHelper   : General error: "org.h2.mvstore.MVStoreException: Reading fro
m file sun.nio.ch.FileChannelImpl@3cb589da failed at 69377487 (length -1), read 0, remaining 384 [2.1.214/1]"; SQL statement:
delete from SEARCHRESULT where FIRST_FOUND  < DATEADD('SECOND', 1675940215, DATE '1970-01-01') AND ID not in (select SEARCH_RESULT_ID from INDEXERNZBDOWNLOAD
where SEARCH_RESULT_ID is not null) [50000-214]
```


My storage was full, maybe this has to do with it? I restarted mysql (no idea if nzbhydra2 is using that) and I delete (stupid maybe) all nzbhydra2-backups.

**Comment by theotherp** [comment]
The database was corrupted when the disk was full. As you deleted all
backups you'll have to delete the database folder. You'll lose history and
stats but keep all settings.

**Comment by pven** [comment]
I removed the database-folder, it recreated itself but it is still constantly updating. I can not find any error in the recent log.

**Comment by pven** [comment]
I found this line in the wrapper.log
```
2023-02-12 13:04:19,609  INFO - Removing update ZIP /var/nzbhydra2/data/update/nzbhydra2-5.1.5-amd64-linux.zip
```

I thought I was using the genric-version.

**Comment by pven** [comment]
Hmm, I unzipped the new generic-version to the nzbhydra2-directory, started it, and now it works. :-)

**Comment by pven** [comment]
Sorry, still got one error:
```
delete from SEARCHRESULT where FIRST_FOUND  < DATEADD('SECOND', 1675951887, DATE '1970-01-01') AND ID not in (select SEARCH_RESULT_ID from INDEXERNZBDOWNLOAD where SEARCH_RESULT_ID is not null) [50200-214]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:560)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
        at org.h2.message.DbException.get(DbException.java:212)
        at org.h2.command.Command.filterConcurrentUpdate(Command.java:324)
        at org.h2.command.Command.executeUpdate(Command.java:258)
        at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
        at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
        at org.hibernate.sql.exec.internal.StandardJdbcMutationExecutor.execute(StandardJdbcMutationExecutor.java:84)
        ... 33 common frames omitted
Caused by: org.h2.message.DbException: Row "-6345253750046790398" not found in primary index "PUBLIC.SEARCHRESULT_DATA" [90143-214]
        at org.h2.message.DbException.get(DbException.java:223)
        at org.h2.mvstore.db.MVPrimaryIndex.getRow(MVPrimaryIndex.java:265)
        at org.h2.mvstore.db.MVTable.getRow(MVTable.java:331)
        at org.h2.mvstore.db.MVSecondaryIndex$MVStoreCursor.get(MVSecondaryIndex.java:421)
        at org.h2.index.IndexCursor.get(IndexCursor.java:270)
        at org.h2.table.TableFilter.getValue(TableFilter.java:1032)
        at org.h2.expression.ExpressionColumn.getValue(ExpressionColumn.java:286)
        at org.h2.expression.condition.Comparison.getValue(Comparison.java:217)
        at org.h2.expression.condition.ConditionAndOr.getValue(ConditionAndOr.java:106)
        at org.h2.expression.Expression.getBooleanValue(Expression.java:332)
        at org.h2.command.dml.FilteredDataChangeStatement.nextRow(FilteredDataChangeStatement.java:73)
        at org.h2.command.dml.Delete.update(Delete.java:58)
        at org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:74)
        at org.h2.command.CommandContainer.update(CommandContainer.java:169)
        at org.h2.command.Command.executeUpdate(Command.java:252)
        ... 38 common frames omitted
```

Can I fix this, or is starting with a new database preferable?

**Comment by theotherp** [comment]
Nope. You might've been able if you still had your backups.

**Comment by pven** [comment]
Clear. Thanks for the answers!
