### ISSUE TITLE
Calling /api/stats/indexers give a 500 error

### ISSUE THREAD

**Issue by RomRider** [theotherp/nzbhydra2#882]
Whenever I call `/api/stats/indexers?apikey=XXXX` to get the status of the indexers remotely, I get a 500 error.

This is what shows up in the logs while doing the call:
```
ava.lang.IllegalStateException: No primary or single unique constructor found for class org.nzbhydra.api.stats.ApiHistoryRequest
	at org.springframework.beans.BeanUtils.getResolvableConstructor(BeanUtils.java:267)
	at org.nzbhydra.auth.HydraAnonymousAuthenticationFilter.doFilter(HydraAnonymousAuthenticationFilter.java:101) [22 skipped]
	at org.springframework.security.web.access.intercept.AuthorizationFilter.doFilter(AuthorizationFilter.java:100) [10 skipped]
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:110) [12 skipped]
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:101)
	at org.nzbhydra.auth.AsyncSupportFilter.doFilterInternal(AsyncSupportFilter.java:35) [11 skipped]
	at org.nzbhydra.auth.HeaderAuthenticationFilter.doFilterInternal(HeaderAuthenticationFilter.java:80) [4 skipped]
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:227) [4 skipped]
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:221)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:107) [3 skipped]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:93)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:62) [14 skipped]
	at org.nzbhydra.auth.ForwardedForRecognizingFilter.doFilterInternal(ForwardedForRecognizingFilter.java:37) [9 skipped]
	at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42) [4 skipped]
	at org.nzbhydra.auth.HydraEmbeddedServletContainer$1.invoke(HydraEmbeddedServletContainer.java:88) [22 skipped]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:400) [4 skipped]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:859)
	at java.base@17.0.5/java.lang.Thread.run(Thread.java:833) [5 skipped]
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
```

It used to work, but I can't tell in which version it stopped unfortunately...

**Comment by Wamy-Dev** [comment]
This is still an issue for me unfortunately.
