### ISSUE TITLE
Nzbgeek SSL handshake

### ISSUE THREAD

**Issue by Ninjouz** [theotherp/nzbhydra2#91]
Hey !

I have an issue with nzbgeek that prevents nzbhydra to call the API.
`
The connection to the indexer failed: Error while communicating with indexer NZBGeek. Server returned: javax.net.ssl.SSLProtocolException: handshake alert: unrecognized_name
`

I called the api from my browser (Chrome) and it works without any certficate alert.

How can i help you debug ?

**Comment by theotherp** [comment]
Post your debug infos.

**Comment by Ninjouz** [comment]
Here u go

`org.nzbhydra.indexers.exceptions.IndexerUnreachableException: Error while communicating with indexer NZBGeek. Server returned: javax.net.ssl.SSLProtocolException: handshake alert:  unrecognized_name
	at org.nzbhydra.indexers.IndexerWebAccess.get(IndexerWebAccess.java:76)
	at org.nzbhydra.indexers.IndexerWebAccess.get(IndexerWebAccess.java:43)
	at org.nzbhydra.indexers.capscheck.NewznabChecker.setSupportedSearchTypesAndIndexerCategoryMapping(NewznabChecker.java:253)
	at org.nzbhydra.indexers.capscheck.NewznabChecker.checkCaps(NewznabChecker.java:186)
	at org.nzbhydra.indexers.capscheck.NewznabChecker.checkCaps(NewznabChecker.java:112)
	at org.nzbhydra.indexers.capscheck.IndexerWeb.checkCaps(IndexerWeb.java:52)
	at org.nzbhydra.indexers.capscheck.IndexerWeb$$FastClassBySpringCGLIB$$4c12f63e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
	at org.nzbhydra.indexers.capscheck.IndexerWeb$$EnhancerBySpringCGLIB$$fb6f4e9f.checkCaps(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.nzbhydra.auth.HydraAnonymousAuthenticationFilter.doFilter(HydraAnonymousAuthenticationFilter.java:98)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.nzbhydra.auth.HydraAnonymousAuthenticationFilter.doFilter(HydraAnonymousAuthenticationFilter.java:98)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:158)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:124)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.nzbhydra.auth.HydraEmbeddedServletContainer$1.invoke(HydraEmbeddedServletContainer.java:90)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLProtocolException: handshake alert:  unrecognized_name
	at sun.security.ssl.ClientHandshaker.handshakeAlert(ClientHandshaker.java:1446)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2026)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1135)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:281)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:251)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:151)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:195)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall.execute(RealCall.java:69)
	at org.nzbhydra.okhttp.WebAccess.callUrl(WebAccess.java:65)
	at org.nzbhydra.indexers.IndexerWebAccess.lambda$get$0(IndexerWebAccess.java:60)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 common frames omitted
`

**Comment by theotherp** [comment]
No. Post the zip that you get from the debug section in hydra. You
should've read and followed the instructions when you created this issue.

Am 25.01.2018 20:16 schrieb "Ninjouz" <notifications@github.com>:

Here u go

org.nzbhydra.indexers.exceptions.IndexerUnreachableException: Error while
communicating with indexer NZBGeek. Server returned:
javax.net.ssl.SSLProtocolException:
handshake alert: unrecognized_name at org.nzbhydra.indexers.
IndexerWebAccess.get(IndexerWebAccess.java:76) at org.nzbhydra.indexers.
IndexerWebAccess.get(IndexerWebAccess.java:43) at org.nzbhydra.indexers.
capscheck.NewznabChecker.setSupportedSearchTypesAndIndexerCategoryMapping(NewznabChecker.java:253)
at org.nzbhydra.indexers.capscheck.NewznabChecker.
checkCaps(NewznabChecker.java:186) at org.nzbhydra.indexers.
capscheck.NewznabChecker.checkCaps(NewznabChecker.java:112) at
org.nzbhydra.indexers.capscheck.IndexerWeb.checkCaps(IndexerWeb.java:52) at
org.nzbhydra.indexers.capscheck.IndexerWeb$$FastClassBySpringCGLIB$$4c12f63e.invoke(<generated>)
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.
invokeJoinpoint(CglibAopProxy.java:738) at org.springframework.aop.
framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
at org.springframework.security.access.intercept.aopalliance.
MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69) at
org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(
ReflectiveMethodInvocation.java:179) at org.springframework.aop.
framework.CglibAopProxy$DynamicAdvisedInterceptor.
intercept(CglibAopProxy.java:673) at org.nzbhydra.indexers.
capscheck.IndexerWeb$$EnhancerBySpringCGLIB$$fb6f4e9f.checkCaps(<generated>)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(
DelegatingMethodAccessorImpl.java:43) at
java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(
InvocableHandlerMethod.java:205) at org.springframework.web.method.support.
InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) at
org.springframework.web.servlet.mvc.method.annotation.
ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
at org.springframework.web.servlet.mvc.method.annotation.
RequestMappingHandlerAdapter.invokeHandlerMethod(
RequestMappingHandlerAdapter.java:827) at org.springframework.web.
servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(
RequestMappingHandlerAdapter.java:738) at org.springframework.web.
servlet.mvc.method.AbstractHandlerMethodAdapter.handle(
AbstractHandlerMethodAdapter.java:85) at org.springframework.web.
servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967) at
org.springframework.web.servlet.DispatcherServlet.
doService(DispatcherServlet.java:901) at org.springframework.web.
servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) at
org.springframework.web.servlet.FrameworkServlet.
doPost(FrameworkServlet.java:872) at
javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
at org.springframework.web.servlet.FrameworkServlet.
service(FrameworkServlet.java:846) at javax.servlet.http.
HttpServlet.service(HttpServlet.java:742) at org.apache.catalina.core.
ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) at
org.apache.catalina.core.ApplicationFilterChain.doFilter(
ApplicationFilterChain.java:166) at org.nzbhydra.auth.
HydraAnonymousAuthenticationFilter.doFilter(HydraAnonymousAuthenticationFilter.java:98)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(
ApplicationFilterChain.java:193) at org.apache.catalina.core.
ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at
org.springframework.security.web.FilterChainProxy$
VirtualFilterChain.doFilter(FilterChainProxy.java:317) at
org.springframework.security.web.access.intercept.FilterSecurityInterceptor.
invoke(FilterSecurityInterceptor.java:127) at org.springframework.security.
web.access.intercept.FilterSecurityInterceptor.doFilter(
FilterSecurityInterceptor.java:91) at org.springframework.security.
web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
at org.springframework.security.web.access.ExceptionTranslationFilter.
doFilter(ExceptionTranslationFilter.java:114) at
org.springframework.security.web.FilterChainProxy$
VirtualFilterChain.doFilter(FilterChainProxy.java:331) at
org.springframework.security.web.session.SessionManagementFilter.doFilter(
SessionManagementFilter.java:137) at org.springframework.security.
web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
at org.nzbhydra.auth.HydraAnonymousAuthenticationFilter.doFilter(
HydraAnonymousAuthenticationFilter.java:98) at org.springframework.security.
web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
at org.springframework.security.web.authentication.rememberme.
RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:158)
at org.springframework.security.web.FilterChainProxy$
VirtualFilterChain.doFilter(FilterChainProxy.java:331) at
org.springframework.security.web.servletapi.SecurityContextHolderAwareRequ
estFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170) at
org.springframework.security.web.FilterChainProxy$
VirtualFilterChain.doFilter(FilterChainProxy.java:331) at
org.springframework.security.web.savedrequest.RequestCacheAwareFilter.
doFilter(RequestCacheAwareFilter.java:63) at org.springframework.security.
web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
at org.springframework.security.web.authentication.
AbstractAuthenticationProcessingFilter.doFilter(
AbstractAuthenticationProcessingFilter.java:200) at
org.springframework.security.web.FilterChainProxy$
VirtualFilterChain.doFilter(FilterChainProxy.java:331) at
org.springframework.security.web.authentication.logout.
LogoutFilter.doFilter(LogoutFilter.java:116) at
org.springframework.security.web.FilterChainProxy$
VirtualFilterChain.doFilter(FilterChainProxy.java:331) at
org.springframework.security.web.csrf.CsrfFilter.
doFilterInternal(CsrfFilter.java:124) at org.springframework.web.
filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) at
org.springframework.security.web.FilterChainProxy$
VirtualFilterChain.doFilter(FilterChainProxy.java:331) at
org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64)
at org.springframework.web.filter.OncePerRequestFilter.
doFilter(OncePerRequestFilter.java:107) at org.springframework.security.
web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
at org.springframework.security.web.context.SecurityContextPersistenceFilt
er.doFilter(SecurityContextPersistenceFilter.java:105) at
org.springframework.security.web.FilterChainProxy$
VirtualFilterChain.doFilter(FilterChainProxy.java:331) at
org.springframework.security.web.context.request.async.
WebAsyncManagerIntegrationFilter.doFilterInternal(
WebAsyncManagerIntegrationFilter.java:56) at org.springframework.web.
filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) at
org.springframework.security.web.FilterChainProxy$
VirtualFilterChain.doFilter(FilterChainProxy.java:331) at
org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(
DelegatingFilterProxy.java:346) at org.springframework.web.
filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262) at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(
ApplicationFilterChain.java:193) at org.apache.catalina.core.
ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at
org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(
CharacterEncodingFilter.java:197) at org.springframework.web.
filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(
ApplicationFilterChain.java:193) at org.apache.catalina.core.
ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
at org.nzbhydra.auth.HydraEmbeddedServletContainer$1.invoke(
HydraEmbeddedServletContainer.java:90) at org.apache.catalina.core.
StandardHostValve.invoke(StandardHostValve.java:140) at
org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
at org.apache.coyote.AbstractProcessorLight.process(
AbstractProcessorLight.java:66) at org.apache.coyote.AbstractProtocol$
ConnectionHandler.process(AbstractProtocol.java:868) at
org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:748) Caused by:
javax.net.ssl.SSLProtocolException:
handshake alert: unrecognized_name at sun.security.ssl.ClientHandshaker.
handshakeAlert(ClientHandshaker.java:1446) at sun.security.ssl.
SSLSocketImpl.recvAlert(SSLSocketImpl.java:2026) at sun.security.ssl.
SSLSocketImpl.readRecord(SSLSocketImpl.java:1135) at sun.security.ssl.
SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385) at
sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413) at
sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397) at
okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:281)
at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:251)
at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:151)
at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:195)
at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(
RetryAndFollowUpInterceptor.java:120) at okhttp3.internal.http.
RealInterceptorChain.proceed(RealInterceptorChain.java:92) at
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185) at
okhttp3.RealCall.execute(RealCall.java:69) at
org.nzbhydra.okhttp.WebAccess.callUrl(WebAccess.java:65)
at org.nzbhydra.indexers.IndexerWebAccess.lambda$get$0(IndexerWebAccess.java:60)
at java.util.concurrent.FutureTask.run(FutureTask.java:266) at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
... 1 common frames omitted

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/theotherp/nzbhydra2/issues/91#issuecomment-360570247>,
or mute the thread

**Comment by Ninjouz** [comment]
Added the  hostanme exception in the config. Still dont understand why the handshake does not work as their certificate is OK. 
It works now. Then update the DB directly via SQL commands as there is no way to do it on the UI.

**Comment by theotherp** [comment]
Did you manually remove the exception from the config? What did you need to
change in the database?

Am 25.01.2018 11:31 nachm. schrieb "Ninjouz" <notifications@github.com>:

**Comment by Ninjouz** [comment]
Well to be precise, the first and real issue was that after the migration I found out that NZBGEEK was permanently disabled.
I tried everything to get it enabled back as their API was working (even deleting / adding it back or even resetting the config thus removing the exception surely).

Thought i found the root cause with the SSL exception but it was not it as I saw on your wiki page the SNI exception feature.
Then I watched directly on the DB (table INDEXERSTATUS IIRC), the PERMANENTLY_DISABLED boolean was set to TRUE for nzbgeek. UPDATE table, restart nzbhydra2 to reread the value from the DB and that's it.

But I dont know why it got permanently disabled

**Comment by theotherp** [comment]
You should be able to enable any indexer from the "Indexer statuses" section in the History & stats tab. I might add the same function to the config because that's where you'd naturally look.

An indexer is permanently disabled if during searching an error occurs that will probably not be solved by itself (e.g. wrong API key, SSL errors, etc.). To enable it again you either enable it by clicking the check mark in the indexer statuses section of by repeating the connection /caps check in the config. I cannot think of a scenario where what you describe might happen. I'll take a closer look at the code.

In any case the exception in the config should've been there by default. Because you didn't send me the debug infos with the anonymized config I'll never know. The next time you raise an issue please follow the instructions, they're there for a reason.

**Comment by Ninjouz** [comment]
Ok my bad, I never thought that the check sign in the indexer status was actually clickable. Man, that's not intuitive at all. Why not using a check box like everywhere else ?

Thanks for the info though, I'll know in the future.

**Comment by theotherp** [comment]
I'll try to think of something more self explaining.

Am 26.01.2018 19:35 schrieb "Ninjouz" <notifications@github.com>:

**Comment by DrakeJones** [comment]
This issue is happening again...
