### ISSUE TITLE
Error while testing connection to hydra with Sonarr

### ISSUE THREAD

**Issue by RotasOpera** [theotherp/nzbhydra2#93]
Im running hydraV2 in a Docker environment with a migrated db from v1. That all worked well.
I changed the port in Sonarr from <ip>:5075 to <ip>:5076, but Sonarr throws this error when testing the connection: Unable to connect to indexer. Page size must not be less than one!

Hydra2 log
`java.lang.IllegalArgumentException: Page size must not be less than one!
	at org.springframework.data.domain.AbstractPageRequest.(AbstractPageRequest.java:47)
	at org.springframework.data.domain.PageRequest.(PageRequest.java:63)
	at org.springframework.data.domain.PageRequest.(PageRequest.java:40)
	at org.nzbhydra.searching.IndexerForSearchSelector$InnerInstance.checkIndexerHitLimit(IndexerForSearchSelector.java:250)
	at org.nzbhydra.searching.IndexerForSearchSelector$InnerInstance.pickIndexers(IndexerForSearchSelector.java:124)
	at org.nzbhydra.searching.IndexerForSearchSelector.pickIndexers(IndexerForSearchSelector.java:67)
	at org.nzbhydra.searching.Searcher.getSearchCacheEntry(Searcher.java:261)
	at org.nzbhydra.searching.Searcher.search(Searcher.java:100)
	at org.nzbhydra.api.ExternalApi.search(ExternalApi.java:262)
	at org.nzbhydra.api.ExternalApi.api(ExternalApi.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.nzbhydra.auth.HydraAnonymousAuthenticationFilter.doFilter(HydraAnonymousAuthenticationFilter.java:98)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.nzbhydra.auth.HydraEmbeddedServletContainer$1.invoke(HydraEmbeddedServletContainer.java:90)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
 Close
`

Sonarr log of the error:
`NzbDrone.Core.Indexers.Newznab.NewznabException: Page size must not be less than one!
  at NzbDrone.Core.Indexers.Newznab.NewznabRssParser.PreProcess (NzbDrone.Core.Indexers.IndexerResponse indexerResponse) [0x000d4] in M:\BuildAgent\work\3a352f0853732683\src\NzbDrone.Core\Indexers\Newznab\NewznabRssParser.cs:47 
  at NzbDrone.Core.Indexers.RssParser.ParseResponse (NzbDrone.Core.Indexers.IndexerResponse indexerResponse) [0x0000d] in M:\BuildAgent\work\3a352f0853732683\src\NzbDrone.Core\Indexers\RssParser.cs:55 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].FetchPage (NzbDrone.Core.Indexers.IndexerRequest request, NzbDrone.Core.Indexers.IParseIndexerResponse parser) [0x00008] in M:\BuildAgent\work\3a352f0853732683\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:290 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].TestConnection () [0x0000e] in M:\BuildAgent\work\3a352f0853732683\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:316 `

I already restarted both Sonarr and hydra. Connection with hydraV1 still seems to work fine.

Btw. I really like the new stats overview! Keep up the great work!

**Comment by theotherp** [comment]
In the future please post the full debug infos (the zip) . It really helps
me with analyzing what might be wrong.

Luckily for you I already know what's going on. One of your indexers has a
download or hit limit that's lower than one. Check the config.


Am 26.01.2018 22:24 schrieb "RotasOpera" <notifications@github.com>:

Im running hydraV2 in a Docker environment with a migrated db from v1. That
all worked well.
I changed the port in Sonarr from :5075 to :5076, but Sonarr throws this
error when testing the connection: Unable to connect to indexer. Page size
must not be less than one!

Hydra2 log
java.lang.IllegalArgumentException: Page size must not be less than one! at
org.springframework.data.domain.AbstractPageRequest.(AbstractPageRequest.java:47)
at org.springframework.data.domain.PageRequest.(PageRequest.java:63) at
org.springframework.data.domain.PageRequest.(PageRequest.java:40) at
org.nzbhydra.searching.IndexerForSearchSelector$InnerInstanc
e.checkIndexerHitLimit(IndexerForSearchSelector.java:250) at
org.nzbhydra.searching.IndexerForSearchSelector$InnerInstanc
e.pickIndexers(IndexerForSearchSelector.java:124) at
org.nzbhydra.searching.IndexerForSearchSelector.pickIndexers
(IndexerForSearchSelector.java:67) at org.nzbhydra.searching.Searche
r.getSearchCacheEntry(Searcher.java:261) at
org.nzbhydra.searching.Searcher.search(Searcher.java:100)
at org.nzbhydra.api.ExternalApi.search(ExternalApi.java:262) at
org.nzbhydra.api.ExternalApi.api(ExternalApi.java:96) at
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498) at
org.springframework.web.method.support.InvocableHandlerMetho
d.doInvoke(InvocableHandlerMethod.java:205) at
org.springframework.web.method.support.InvocableHandlerMetho
d.invokeForRequest(InvocableHandlerMethod.java:133) at
org.springframework.web.servlet.mvc.method.annotation.Servle
tInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
at org.springframework.web.servlet.mvc.method.annotation.Reques
tMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
at org.springframework.web.servlet.mvc.method.annotation.Reques
tMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
at org.springframework.web.servlet.mvc.method.AbstractHandlerMe
thodAdapter.handle(AbstractHandlerMethodAdapter.java:85) at
org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) at
org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) at
org.apache.catalina.core.ApplicationFilterChain.internalDoFi
lter(ApplicationFilterChain.java:231) at org.apache.catalina.core.Appli
cationFilterChain.doFilter(ApplicationFilterChain.java:166) at
org.nzbhydra.auth.HydraAnonymousAuthenticationFilter.
doFilter(HydraAnonymousAuthenticationFilter.java:98) at
org.apache.catalina.core.ApplicationFilterChain.internalDoFi
lter(ApplicationFilterChain.java:193) at org.apache.catalina.core.Appli
cationFilterChain.doFilter(ApplicationFilterChain.java:166) at
org.springframework.security.web.FilterChainProxy$VirtualFil
terChain.doFilter(FilterChainProxy.java:317) at
org.springframework.security.web.access.ExceptionTranslation
Filter.doFilter(ExceptionTranslationFilter.java:114) at
org.springframework.security.web.FilterChainProxy$VirtualFil
terChain.doFilter(FilterChainProxy.java:331) at
org.springframework.security.web.session.SessionManagementFi
lter.doFilter(SessionManagementFilter.java:137) at
org.springframework.security.web.FilterChainProxy$VirtualFil
terChain.doFilter(FilterChainProxy.java:331) at
org.springframework.security.web.authentication.AnonymousAut
henticationFilter.doFilter(AnonymousAuthenticationFilter.java:111) at
org.springframework.security.web.FilterChainProxy$VirtualFil
terChain.doFilter(FilterChainProxy.java:331) at
org.springframework.security.web.servletapi.SecurityContextH
olderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
at org.springframework.security.web.FilterChainProxy$VirtualFil
terChain.doFilter(FilterChainProxy.java:331) at
org.springframework.security.web.savedrequest.RequestCacheAw
areFilter.doFilter(RequestCacheAwareFilter.java:63) at
org.springframework.security.web.FilterChainProxy$VirtualFil
terChain.doFilter(FilterChainProxy.java:331) at
org.springframework.security.web.authentication.logout.Logou
tFilter.doFilter(LogoutFilter.java:116) at org.springframework.security.w
eb.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:100)
at org.springframework.web.filter.OncePerRequestFilter.doFilter
(OncePerRequestFilter.java:107) at org.springframework.security.w
eb.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
at org.springframework.security.web.header.HeaderWriterFilter.d
oFilterInternal(HeaderWriterFilter.java:64) at
org.springframework.web.filter.OncePerRequestFilter.doFilter
(OncePerRequestFilter.java:107) at org.springframework.security.w
eb.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
at org.springframework.security.web.context.SecurityContextPers
istenceFilter.doFilter(SecurityContextPersistenceFilter.java:105) at
org.springframework.security.web.FilterChainProxy$VirtualFil
terChain.doFilter(FilterChainProxy.java:331) at
org.springframework.security.web.context.request.async.WebAs
yncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
at org.springframework.web.filter.OncePerRequestFilter.doFilter
(OncePerRequestFilter.java:107) at org.springframework.security.w
eb.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
at org.springframework.security.web.FilterChainProxy.doFilterIn
ternal(FilterChainProxy.java:214) at org.springframework.security.w
eb.FilterChainProxy.doFilter(FilterChainProxy.java:177) at
org.springframework.web.filter.DelegatingFilterProxy.invokeD
elegate(DelegatingFilterProxy.java:346) at org.springframework.web.filter
.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262) at
org.apache.catalina.core.ApplicationFilterChain.internalDoFi
lter(ApplicationFilterChain.java:193) at org.apache.catalina.core.Appli
cationFilterChain.doFilter(ApplicationFilterChain.java:166) at
org.springframework.web.filter.CharacterEncodingFilter.doFil
terInternal(CharacterEncodingFilter.java:197) at
org.springframework.web.filter.OncePerRequestFilter.doFilter
(OncePerRequestFilter.java:107) at org.apache.catalina.core.Appli
cationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
at org.nzbhydra.auth.HydraEmbeddedServletContainer$1.invoke(Hyd
raEmbeddedServletContainer.java:90) at org.apache.catalina.core.Stand
ardHostValve.invoke(StandardHostValve.java:140) at
org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
at org.apache.coyote.AbstractProtocol$ConnectionHandler.
process(AbstractProtocol.java:868) at org.apache.tomcat.util.net.Nio
Endpoint$SocketProcessor.doRun(NioEndpoint.java:1457) at
org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:748) Close

Sonarr log of the error:
NzbDrone.Core.Indexers.Newznab.NewznabException: Page size must not be less
than one! at NzbDrone.Core.Indexers.Newznab.NewznabRssParser.PreProcess
(NzbDrone.Core.Indexers.IndexerResponse indexerResponse) [0x000d4] in
M:\BuildAgent\work\3a352f0853732683\src\NzbDrone.Core\
Indexers\Newznab\NewznabRssParser.cs:47 at
NzbDrone.Core.Indexers.RssParser.ParseResponse
(NzbDrone.Core.Indexers.IndexerResponse indexerResponse) [0x0000d] in
M:\BuildAgent\work\3a352f0853732683\src\NzbDrone.Core\Indexers\RssParser.cs:55
at NzbDrone.Core.Indexers.HttpIndexerBase1[TSettings].FetchPage
(NzbDrone.Core.Indexers.IndexerRequest request,
NzbDrone.Core.Indexers.IParseIndexerResponse parser) [0x00008] in
M:\BuildAgent\work\3a352f0853732683\src\NzbDrone.Core\
Indexers\HttpIndexerBase.cs:290
at NzbDrone.Core.Indexers.HttpIndexerBase1[TSettings].TestConnection ()
[0x0000e] in M:\BuildAgent\work\3a352f0853732683\src\NzbDrone.Core\
Indexers\HttpIndexerBase.cs:316

I already restarted both Sonarr and hydra. Connection with hydraV1 still
seems to work fine.

Btw. I really like the new stats overview! Keep up the great work!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/theotherp/nzbhydra2/issues/93>, or mute the thread

**Comment by theotherp** [comment]
I've added a check that should prevent this from being migrated. Config validation should prevent it from being saved.

**Comment by RotasOpera** [comment]
Thank you for the quick response. You were right, everything works now. 
But I noticed that the connection fails if you enter a 0 as api/Download limit. The tooltip to the right should say that these fields must not be empty if this is the case.

**Comment by theotherp** [comment]
Just don't enter anything. It's empty by default and you're not required to enter anything.
