### ISSUE TITLE
can't send to Sabnzb after updating to 5.3.11

### ISSUE THREAD

**Issue by daywalker90** [theotherp/nzbhydra2#934]
When trying to send a nzb to Sabnzb i get an undefined error and this in the logs:
```
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]: 2024-03-25 16:15:04.313 ERROR --- [http-nio-0.0.0.0-5] o.n.d.IndexerUniquenessScoreSaver        : Error while saving data for uniqueness scores
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]: org.springframework.orm.jpa.JpaObjectRetrievalFailureException: Unable to find org.nzbhydra.indexers.IndexerSearchEntity with id -64324304
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]:         at org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:376)
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]:         at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:234)
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]:         at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:550)
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]:         at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]:         at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:243)
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]:         at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:152)
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]:         at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:164) [1 skipped]
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]:         at jdk.proxy4/jdk.proxy4.$Proxy73.getReferenceById(Unknown Source) [4 skipped]
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]:         at org.nzbhydra.downloading.IndexerUniquenessScoreSaver.handleDownloadEvent(IndexerUniquenessScoreSaver.java:93)
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]:         at org.nzbhydra.downloading.IndexerUniquenessScoreSaver$1.doInTransactionWithoutResult(IndexerUniquenessScoreSaver.java:78)
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]:         at org.springframework.transaction.support.TransactionCallbackWithoutResult.doInTransaction(TransactionCallbackWithoutResult.java:36)
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]:         at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]:         at org.nzbhydra.downloading.IndexerUniquenessScoreSaver.onNzbDownloadEvent(IndexerUniquenessScoreSaver.java:75)
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]:         at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:348) [1 skipped]
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]:         at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:233)
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]: Caused by: jakarta.persistence.EntityNotFoundException: Unable to find org.nzbhydra.indexers.IndexerSearchEntity with id -64324304
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]:         at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$JpaEntityNotFoundDelegate.handleEntityNotFound(EntityManagerFactoryBuilderImpl.java:186)
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]:         at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:207)
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]:         at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:241)
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]:         at org.hibernate.event.internal.DefaultLoadEventListener.doOnLoad(DefaultLoadEventListener.java:106)
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]:         at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:78)
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]:         at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:138)
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]:         at org.hibernate.internal.SessionImpl.fireLoadNoChecks(SessionImpl.java:1231)
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]:         at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1219)
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]:         at org.hibernate.loader.internal.IdentifierLoadAccessImpl.doGetReference(IdentifierLoadAccessImpl.java:146)
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]:         at org.hibernate.loader.internal.IdentifierLoadAccessImpl.lambda$getReference$0(IdentifierLoadAccessImpl.java:81)
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]:         at org.hibernate.loader.internal.IdentifierLoadAccessImpl.perform(IdentifierLoadAccessImpl.java:107)
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]:         at org.hibernate.loader.internal.IdentifierLoadAccessImpl.getReference(IdentifierLoadAccessImpl.java:81)
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]:         at org.hibernate.internal.SessionImpl.getReference(SessionImpl.java:2512)
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]:         at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:311) [1 skipped]
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]:         at jdk.proxy4/jdk.proxy4.$Proxy65.getReference(Unknown Source)
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]: 2024-03-25 16:15:04.317 ERROR --- [http-nio-0.0.0.0-5] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.springframework.transaction.UnexpectedRollbackException: Transaction silently rolled back because it has been marked as rollback-only] with root cause
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]: org.springframework.transaction.UnexpectedRollbackException: Transaction silently rolled back because it has been marked as rollback-only
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]:         at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:752)
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]:         at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:711)
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]:         at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:660)
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]:         at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:410)
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]:         at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]:         at org.nzbhydra.downloading.FileHandler$$SpringCGLIB$$0.getFileByResult(<generated>) [3 skipped]
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]:         at org.nzbhydra.downloading.downloaders.Downloader.addBySearchResultIds(Downloader.java:145)
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]:         at org.nzbhydra.downloading.downloaders.DownloaderWeb.addNzb(DownloaderWeb.java:65)
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]:         at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:67) [5 skipped]
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]:         at org.nzbhydra.downloading.downloaders.DownloaderWeb$$SpringCGLIB$$0.addNzb(<generated>) [3 skipped]
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]:         at org.nzbhydra.auth.HydraAnonymousAuthenticationFilter.doFilter(HydraAnonymousAuthenticationFilter.java:101) [19 skipped]
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]:         at org.springframework.security.web.access.intercept.AuthorizationFilter.doFilter(AuthorizationFilter.java:100) [14 skipped]
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]:         at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:110) [12 skipped]
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]:         at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:101)
Mar 25 16:15:04  nzbhydra2wrapperPy3.py[3100]:         at org.nzbhydra.auth.AsyncSupportFilter.doFilterInternal(AsyncSupportFilter.java:35) [11 skipped]
```

**Comment by theotherp** [comment]
This particular nzb or all of the them?

The result can't be found in the database for some reason.

**Comment by daywalker90** [comment]
tried different nzbs from different indexers. Same problem.

**Comment by theotherp** [comment]
Please post debug infos

**Comment by daywalker90** [comment]
If you mean the zip from the report a bug page, that leaks too much sorry. I fixed it by deleting the database. Now it works again.
